Repository ansible/ansible, pull requests merged in 2022-04, with the labels that each got.

#77408 get_url: remove deprecated sha256sum module param
  changelogs/fragments/get_url-remove-deprecated-sha256sum.yml
  lib/ansible/modules/get_url.py
  test/sanity/ignore.txt
Labels: test, module, core_review, support:core, feature, affects_2.14

#77409 apt_key: remove deprecated key module param
  changelogs/fragments/apt_key-remove-deprecated-key.yml
  lib/ansible/modules/apt_key.py
  test/sanity/ignore.txt
Labels: test, module, core_review, support:core, feature, affects_2.14

#77369 INI: values with spaces can be single or double quoted
  docs/docsite/rst/user_guide/intro_inventory.rst
Labels: core_review, support:core, new_contributor, docs, docs_only, affects_2.13

#77446 Add test to assert that missing libyaml doesn't result in an error
  test/integration/targets/pyyaml/aliases
  test/integration/targets/pyyaml/runme.sh
Labels: community_review, needs_triage, support:community, affects_2.14

#77454 [docs] community_steering_committee.rst: add chairperson
  docs/docsite/rst/community/steering/community_steering_committee.rst
  docs/docsite/rst/community/steering/steering_committee_membership.rst
Labels: core_review, support:core, docs, small_patch, docsite, docs_only, affects_2.14

#74859 make collection warning message clearer
  lib/ansible/cli/galaxy.py
Labels: core_review, support:core, new_contributor, bug, affects_2.12

#77455 Remove deprecated UnsafeProxy
  changelogs/fragments/unsafeproxy-deprecated.yml
  lib/ansible/utils/unsafe_proxy.py
Labels: needs_triage, core_review, support:core, feature, affects_2.14

#77391 Document how to release a collection
  docs/docsite/rst/community/collection_contributors/collection_integration_about.rst
  docs/docsite/rst/community/collection_contributors/collection_integration_add.rst
  docs/docsite/rst/community/collection_contributors/collection_release_with_branches.rst
  docs/docsite/rst/community/collection_contributors/collection_release_without_branches.rst
  docs/docsite/rst/community/collection_contributors/collection_releasing.rst
  docs/docsite/rst/community/collection_development_process.rst
  docs/docsite/rst/community/contributions_collections.rst
  docs/docsite/rst/community/maintainers.rst
  docs/docsite/rst/community/maintainers_guidelines.rst
  docs/docsite/rst/community/maintainers_workflow.rst
  docs/docsite/sphinx_conf/core_conf.py
Labels: core_review, support:core, docs, docsite, docs_only, affects_2.14

#77459 [stable-2.13] Catch ImportError when pyyaml doesn't have libyaml extension (#77434)
  lib/ansible/module_utils/common/yaml.py
  test/integration/targets/pyyaml/aliases
  test/integration/targets/pyyaml/runme.sh
Labels: backport, needs_triage, core_review, support:community, support:core, small_patch, affects_2.13

#77404 winrm - ensure callers PATH for kinit is set (#77401) - 2.13
  changelogs/fragments/winrm-kinit-path.yml
  lib/ansible/plugins/connection/__init__.py
  lib/ansible/plugins/connection/winrm.py
  test/units/plugins/connection/test_winrm.py
Labels: windows, backport, needs_triage, core_review, support:core, bug, affects_2.13

#77438 [docs][backport][2.13] Backportapalooza 3-31
  docs/docsite/rst/community/communication.rst
  docs/docsite/rst/community/reporting_bugs_and_features.rst
  docs/docsite/rst/dev_guide/developing_collections_structure.rst
  docs/docsite/rst/user_guide/cheatsheet.rst
  docs/docsite/rst/user_guide/index.rst
  docs/docsite/rst/user_guide/playbooks_reuse_roles.rst
Labels: backport, shipit, needs_triage, support:core, docs, docsite, docs_only, affects_2.13

#77466 docs: Update porting guide for ansible 5.6.0
  docs/docsite/rst/porting_guides/porting_guide_5.rst
Labels: core_review, support:core, docs, docs_only, affects_2.14

#77465 compile sanity test: fix crash
  changelogs/fragments/77465-ansible-test-compile-crash.yml
  test/lib/ansible_test/_util/target/sanity/compile/compile.py
Labels: test, core_review, support:core, bug, affects_2.14

#65499 Hide "[WARNING]: No inventory was parsed" message
  changelogs/fragments/65499-no_inventory_parsed.yml
  lib/ansible/config/base.yml
  lib/ansible/inventory/manager.py
Labels: core_review, inventory, support:core, feature, affects_2.10

#77312 honor use_proxy parameter
  changelogs/fragments/58632-uri-include_use_proxy.yaml
  lib/ansible/module_utils/urls.py
  lib/ansible/modules/uri.py
  test/integration/targets/uri/tasks/main.yml
Labels: module, core_review, support:core, new_contributor, bug, affects_2.13

#77478 Fix ini section for INVENTORY_UNPARSED_WARNING
  lib/ansible/config/base.yml
Labels: needs_triage, core_review, support:core, bug, small_patch, affects_2.14

#77472 ansible-test - Don't fail if network cannot be disconnected
  changelogs/fragments/77472-ansible-test-network-disconnect-warning.yml
  test/lib/ansible_test/_internal/delegation.py
Labels: test, core_review, support:core, bug, affects_2.14

#77485 Ensure correct environment_class is set on Template
  changelogs/fragments/templar-correct-environment_class-template.yml
  lib/ansible/template/__init__.py
Labels: needs_triage, core_review, support:core, bug, affects_2.14

#77488 2.13: Ensure correct environment_class is set on Template (#77485)
  changelogs/fragments/templar-correct-environment_class-template.yml
  lib/ansible/template/__init__.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.13

#77467 Trivial
  docs/docsite/rst/community/collection_development_process.rst
  docs/docsite/rst/community/development_process.rst
Labels: core_review, support:core, docs, docsite, docs_only, affects_2.14

#77439 Update installing_collections_file.rst
  docs/docsite/rst/shared_snippets/installing_collections_file.rst
Labels: core_review, support:core, new_contributor, docs, small_patch, has_issue, docs_only, affects_2.14

#77436 avoid recursion in example
  docs/docsite/rst/user_guide/complex_data_manipulation.rst
Labels: core_review, support:core, docs, docs_only, affects_2.14

#77372 Clarifying how handlers are handled
  docs/docsite/rst/user_guide/playbooks_handlers.rst
Labels: core_review, support:core, docs, docs_only, affects_2.13

#77497 Update developing_collections_shared.rst
  docs/docsite/rst/dev_guide/developing_collections_shared.rst
Labels: core_review, support:core, docs, small_patch, docsite, docs_only, affects_2.14

#77493 Get git executable for collections in git repos
  changelogs/fragments/77493-ansible-galaxy-find-git-executable-before-using.yaml
  lib/ansible/galaxy/collection/concrete_artifact_manager.py
  test/units/galaxy/test_collection_install.py
Labels: needs_triage, core_review, support:core, bug, affects_2.14

#77490 [docs][backport] 0407 weekly docs backports
  docs/docsite/rst/community/collection_contributors/collection_integration_about.rst
  docs/docsite/rst/community/collection_contributors/collection_integration_add.rst
  docs/docsite/rst/community/collection_contributors/collection_release_with_branches.rst
  docs/docsite/rst/community/collection_contributors/collection_release_without_branches.rst
  docs/docsite/rst/community/collection_contributors/collection_releasing.rst
  docs/docsite/rst/community/collection_development_process.rst
  docs/docsite/rst/community/contributions_collections.rst
  docs/docsite/rst/community/development_process.rst
  docs/docsite/rst/community/maintainers.rst
  docs/docsite/rst/community/maintainers_guidelines.rst
  docs/docsite/rst/community/maintainers_workflow.rst
  docs/docsite/rst/community/steering/community_steering_committee.rst
  docs/docsite/rst/community/steering/steering_committee_membership.rst
  docs/docsite/rst/porting_guides/porting_guide_5.rst
  docs/docsite/rst/shared_snippets/installing_collections_file.rst
  docs/docsite/rst/user_guide/complex_data_manipulation.rst
  docs/docsite/rst/user_guide/intro_inventory.rst
  docs/docsite/rst/user_guide/playbooks_handlers.rst
  docs/docsite/sphinx_conf/core_conf.py
  lib/ansible/modules/template.py
Labels: backport, module, needs_triage, core_review, support:core, docs, docsite, docs_only, affects_2.13

#77444 PlayIterator - remove deprecated states
  changelogs/fragments/play_iterator-remove_deprecations.yml
  lib/ansible/executor/play_iterator.py
  test/units/executor/test_play_iterator.py
Labels: core_review, support:core, feature, affects_2.14

#77495 template override colon bugfixes
  changelogs/fragments/template_override.yml
  lib/ansible/template/__init__.py
  test/integration/targets/template/files/override_colon_value.expected
  test/integration/targets/template/tasks/main.yml
  test/integration/targets/template/templates/override_colon_value.j2
  test/integration/targets/template/templates/override_separator.j2
Labels: needs_triage, core_review, support:core, new_contributor, bug, traceback, affects_2.14

#77508 Update Ansible release version to v2.13.0b0.post0.
  lib/ansible/release.py
Labels: backport, core_review, support:core, small_patch, affects_2.13

#77496 Update developing_collections_structure.rst
  docs/docsite/rst/dev_guide/developing_collections_structure.rst
Labels: core_review, support:core, docs, small_patch, docsite, docs_only, affects_2.14

#76114 Make "~/.ansible" path configurable
  hacking/env-setup
  lib/ansible/cli/__init__.py
  lib/ansible/cli/arguments/option_helpers.py
  lib/ansible/cli/pull.py
  lib/ansible/config/base.yml
  lib/ansible/galaxy/api.py
  lib/ansible/plugins/loader.py
  test/units/galaxy/test_api.py
Labels: core_review, support:core, new_contributor, feature, affects_2.13

#77513 Remove scheduled CI runs.
  .azure-pipelines/azure-pipelines.yml
Labels: backport, core_review, support:core, affects_2.10

#77476 [stable-2.12] Fix sanity test crash.
  changelogs/fragments/77465-ansible-test-compile-crash.yml
  test/lib/ansible_test/_util/target/sanity/compile/compile.py
Labels: backport, test, core_review, support:core, bug, affects_2.12

#77387 2.14 Roadmap
  docs/docsite/rst/roadmap/ROADMAP_2_14.rst
  docs/docsite/rst/roadmap/ansible_core_roadmap_index.rst
Labels: WIP, support:core, docs, docs_only, affects_2.14

#77518 Update reporting_bugs_and_features.rst
  docs/docsite/rst/community/reporting_bugs_and_features.rst
Labels: core_review, support:core, new_contributor, docs, docsite, docs_only, affects_2.14

#77526 docs: Add porting guide for Ansible 6.0.0a1
  docs/docsite/rst/porting_guides/porting_guide_6.rst
  docs/docsite/rst/porting_guides/porting_guides.rst
Labels: core_review, support:core, docs, docs_only, affects_2.14

#77522 Exclude Python 2.6 from interpreter discovery.
  changelogs/fragments/python-2.6-discovery.yml
  lib/ansible/config/base.yml
Labels: core_review, support:core, bug, affects_2.14

#77529 Steering Committee: add new member
  docs/docsite/rst/community/steering/community_steering_committee.rst
Labels: needs_triage, core_review, support:core, docs, small_patch, docsite, docs_only, affects_2.14

#77501 [2.12] Get git executable for collections in git repos (#77493)
  changelogs/fragments/77493-ansible-galaxy-find-git-executable-before-using.yaml
  lib/ansible/galaxy/collection/concrete_artifact_manager.py
  test/units/galaxy/test_collection_install.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.12

#77365 [bp-2.12] hostname - fix TypeError in FileStrategy
  changelogs/fragments/77074-hostname-fix-typeerror-in-filestrategy.yml
  lib/ansible/modules/hostname.py
Labels: backport, module, needs_triage, core_review, support:core, bug, has_issue, affects_2.12

#77528 [stable-2.13] Exclude Python 2.6 from interpreter discovery.
  changelogs/fragments/python-2.6-discovery.yml
  lib/ansible/config/base.yml
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.13

#77402 winrm - ensure callers PATH for kinit is set (#77401) - 2.11
  changelogs/fragments/winrm-kinit-path.yml
  lib/ansible/plugins/connection/winrm.py
  test/units/plugins/connection/test_winrm.py
Labels: windows, backport, needs_triage, core_review, support:core, bug, affects_2.11

#77389 [2.12] fix shell/command/script tasks skipping in check mode (#76353)
  changelogs/fragments/76353-fix-check-mode-skipping.yaml
  lib/ansible/modules/command.py
  lib/ansible/plugins/action/script.py
  test/integration/targets/command_shell/tasks/main.yml
Labels: backport, module, needs_triage, core_review, support:community, support:core, bug, has_issue, affects_2.12

#77348 SID - Use literal UPN value when attempting a user to SID lookup (#77334) - 2.12
  changelogs/fragments/ModuleUtils.SID-long-username.yml
  lib/ansible/module_utils/powershell/Ansible.ModuleUtils.SID.psm1
Labels: windows, backport, needs_triage, core_review, support:core, bug, affects_2.12

#77347 SID - Use literal UPN value when attempting a user to SID lookup (#77334) - 2.11
  changelogs/fragments/ModuleUtils.SID-long-username.yml
  lib/ansible/module_utils/powershell/Ansible.ModuleUtils.SID.psm1
Labels: windows, backport, needs_triage, core_review, support:core, bug, has_issue, affects_2.11

#77498 Move to display as single source of verbosity
  changelogs/fragments/display_verbosity.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/plugins/action/__init__.py
  lib/ansible/plugins/connection/psrp.py
  lib/ansible/plugins/connection/ssh.py
  test/units/plugins/action/test_action.py
Labels: windows, networking, needs_triage, core_review, support:core, bug, affects_2.14

#77509 ansible-connection verboistery
  changelogs/fragments/ansible_connection_verbosity.yml
  lib/ansible/cli/scripts/ansible_connection_cli_stub.py
  lib/ansible/executor/task_executor.py
Labels: networking, needs_triage, core_review, support:core, feature, affects_2.14

#70351 Allow strftime to display time in UTC
  changelogs/fragments/strftime-in-utc.yml
  docs/docsite/rst/user_guide/playbooks_filters.rst
  lib/ansible/plugins/filter/core.py
Labels: core_review, support:core, docs, feature, affects_2.11

#77483 Config, ensure templating happens at functions
  changelogs/fragments/ensure_config_always_templated.yml
  lib/ansible/cli/config.py
  lib/ansible/config/manager.py
  lib/ansible/constants.py
Labels: core_review, support:core, bug, has_issue, affects_2.14

#77517 CLI now issues clearer error when 0 hosts selected
  changelogs/fragments/better_nohosts_error.yml
  lib/ansible/cli/__init__.py
Labels: needs_triage, core_review, support:core, bug, affects_2.14

#77511 Better info sourcing
  changelogs/fragments/better_info_sources.yml
  lib/ansible/plugins/action/__init__.py
  test/units/plugins/action/test_action.py
Labels: needs_triage, core_review, support:core, bug, affects_2.14

#56116 Allow for lazy evaluation of Jinja2 expressions
  changelogs/fragments/56017-allow-lazy-eval-on-jinja2-expr.yml
  docs/docsite/rst/porting_guides/porting_guide_core_2.14.rst
  lib/ansible/template/vars.py
  test/integration/targets/template/lazy_eval.yml
  test/integration/targets/template/runme.sh
  test/units/playbook/test_conditional.py
Labels: core_review, support:core, docs, feature, has_issue, affects_2.10

#77539 Pin antsibull to 0.42.0
  docs/docsite/known_good_reqs.txt
Labels: backport, core_review, support:core, docs, affects_2.12, docs_only

#77540 Pin antsibull to 0.42.0 (#77539)
  docs/docsite/known_good_reqs.txt
Labels: backport, core_review, support:core, docs, small_patch, affects_2.11, docs_only

#77499 update python devel docs
  docs/docsite/rst/dev_guide/developing_python_3.rst
Labels: needs_triage, core_review, support:core, docs, docsite, docs_only, affects_2.14

#77515 Update pip example with standard lowercase http[s]_proxy env vars
  lib/ansible/modules/pip.py
Labels: module, core_review, support:core, docs, small_patch, docs_only, affects_2.14

#77516 Clean up integration tests
  test/integration/targets/ansible-galaxy-collection/tasks/install.yml
  test/integration/targets/ansible-galaxy-collection/tasks/verify.yml
  test/integration/targets/module_defaults/test_action_group_metadata.yml
Labels: community_review, support:community, affects_2.14

#77532 setup: remove 'any' as seemingly valid option
  lib/ansible/modules/setup.py
Labels: module, needs_triage, core_review, support:core, docs, small_patch, docs_only, affects_2.14

#77533 Update docs to recommend the TTY for prompts over stderr
  docs/docsite/rst/user_guide/vault.rst
Labels: core_review, support:core, docs, small_patch, docs_only, affects_2.14

#77546 Revert "Config, ensure templating happens at functions (#77483)"
  changelogs/fragments/ensure_config_always_templated.yml
  lib/ansible/cli/config.py
  lib/ansible/config/manager.py
  lib/ansible/constants.py
Labels: core_review, support:core, bug, traceback, affects_2.14

#77531 Fix a broken link and grammatical issues in the DSC doc
  docs/docsite/rst/user_guide/windows_dsc.rst
Labels: windows, core_review, support:core, new_contributor, docs, docsite, docs_only, affects_2.14

#77494 Add contributor path page
  docs/docsite/rst/community/contributor_path.rst
  docs/docsite/rst/community/how_can_I_help.rst
  docs/docsite/rst/community/index.rst
  docs/docsite/rst/community/maintainers_guidelines.rst
Labels: core_review, support:core, docs, docsite, docs_only, affects_2.14

#77555 ansible-test - Remove more Python 2.7 support.
  changelogs/fragments/ansible-test-less-python-2.7.yml
  test/lib/ansible_test/_data/completion/docker.txt
  test/lib/ansible_test/_data/completion/remote.txt
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: test, core_review, support:core, feature, affects_2.14

#77543 New release v2.12.5rc1
  changelogs/CHANGELOG-v2.12.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.12.5rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, core_review, support:core, affects_2.12

#77542 New release v2.11.11rc1
  changelogs/CHANGELOG-v2.11.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.11.11rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, core_review, support:core, affects_2.11

#77554 Yolo
  changelogs/fragments/config_manager_changes.yml
  changelogs/fragments/ensure_config_always_templated.yml
  lib/ansible/cli/config.py
  lib/ansible/config/data.py
  lib/ansible/config/manager.py
  lib/ansible/constants.py
  test/units/config/test_data.py
  test/units/config/test_manager.py
Labels: needs_triage, core_review, support:core, bug, affects_2.14

#77558 Update Ansible release version to v2.11.11rc1.post0.
  lib/ansible/release.py
Labels: backport, core_review, support:core, small_patch, affects_2.11

#77559 Update Ansible release version to v2.12.5rc1.post0.
  lib/ansible/release.py
Labels: backport, core_review, support:core, small_patch, affects_2.12

#77544 Fix error message for non-str hosts in yaml inventory
  lib/ansible/plugins/inventory/yaml.py
Labels: needs_triage, core_review, support:core, bug, has_issue, affects_2.14

#77573 ansible-test - Fix rstcheck compatibility issues.
  changelogs/fragments/ansible-test-rstcheck-pin.yml
  test/lib/ansible_test/_data/requirements/constraints.txt
  test/sanity/code-smell/package-data.requirements.txt
  test/sanity/code-smell/rstcheck-cli.py
  test/sanity/code-smell/rstcheck.py
  test/sanity/code-smell/rstcheck.requirements.txt
Labels: backport, test, core_review, support:core, bug, affects_2.11

#77569 Add a test and changelog for non-string host names in yaml inv
  changelogs/fragments/77544-fix-error-yaml-inventory-int-hostnames.yml
  test/integration/targets/inventory_yaml/runme.sh
  test/integration/targets/inventory_yaml/test_int_hostname.yml
Labels: needs_triage, core_review, support:community, support:core, affects_2.14

#77561 ensure dependencies are a dict
  changelogs/fragments/77561-ansible-galaxy-coll-install-null-dependencies.yml
  lib/ansible/galaxy/collection/concrete_artifact_manager.py
  test/units/galaxy/test_collection_install.py
Labels: core_review, support:core, bug, traceback, has_issue, affects_2.14

#77578 ansible-test - Support multiple coverage versions.
  changelogs/fragments/ansible-test-coverage.yml
  test/lib/ansible_test/_internal/commands/coverage/__init__.py
  test/lib/ansible_test/_internal/commands/coverage/combine.py
  test/lib/ansible_test/_internal/coverage_util.py
  test/lib/ansible_test/_internal/python_requirements.py
  test/lib/ansible_test/_internal/util.py
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: test, core_review, support:core, feature, affects_2.14

#77584 ansible-test - Pin rstcheck version.
  changelogs/fragments/ansible-test-rstcheck-pin.yml
  test/lib/ansible_test/_data/requirements/constraints.txt
  test/lib/ansible_test/_data/sanity/rstcheck/rstcheck-cli.py
  test/lib/ansible_test/_internal/sanity/rstcheck.py
Labels: backport, test, core_review, support:core, bug, affects_2.10

#77587 [stable-2.9] ansible-test - Pin rstcheck version. (#77584)
  changelogs/fragments/ansible-test-rstcheck-pin.yml
  test/lib/ansible_test/_data/requirements/constraints.txt
  test/lib/ansible_test/_data/sanity/rstcheck/rstcheck-cli.py
  test/lib/ansible_test/_internal/sanity/rstcheck.py
Labels: backport, test, core_review, support:core, bug, affects_2.9

#77589 [DOCS] community_steering_committee.rst: add new member
  docs/docsite/rst/community/steering/community_steering_committee.rst
Labels: needs_triage, core_review, support:core, docs, small_patch, docsite, docs_only, affects_2.14

#77570 varaiblemanager, more efficienet vars file reads
  changelogs/fragments/vm_more_efficient.yml
  lib/ansible/vars/manager.py
Labels: needs_triage, core_review, support:core, bug, affects_2.14

#77507 Deprecate PlayContext.verbosity
  changelogs/fragments/77507-deprecate-pc-verbosity.yml
  lib/ansible/playbook/play_context.py
Labels: core_review, support:core, bug, affects_2.14

#77567 add select distro installs to docs
  docs/docsite/rst/installation_guide/index.rst
  docs/docsite/rst/installation_guide/installation_distros.rst
Labels: core_review, support:core, docs, has_issue, docs_only, affects_2.14

#77576 arg_spec - Return aliases in validation result and update aliases
  changelogs/fragments/77576-arg_spec-no_log-aliases.yml
  lib/ansible/module_utils/basic.py
  lib/ansible/module_utils/common/arg_spec.py
  test/units/module_utils/basic/test_argument_spec.py
  test/units/module_utils/common/arg_spec/test_aliases.py
Labels: core_review, support:core, bug, affects_2.14

#77588 git fix docs and wrapper script
  changelogs/fragments/git_fixes.yml
  lib/ansible/modules/git.py
Labels: module, core_review, support:core, bug, affects_2.14

#77596 varaiblemanager, more efficienet vars file reads (#77570)
  changelogs/fragments/vm_more_efficient.yml
  lib/ansible/vars/manager.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.13

#77603 git fix docs and wrapper script (#77588)
  changelogs/fragments/git_fixes.yml
  lib/ansible/modules/git.py
Labels: backport, module, needs_triage, core_review, support:core, bug, affects_2.13

#77601 [stable-2.13] arg_spec - Return aliases in validation result and update aliases (#77576)
  changelogs/fragments/77576-arg_spec-no_log-aliases.yml
  lib/ansible/module_utils/basic.py
  lib/ansible/module_utils/common/arg_spec.py
  test/units/module_utils/basic/test_argument_spec.py
  test/units/module_utils/common/arg_spec/test_aliases.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.13

#77557 [docs][backport] Docs backports week 4-18-22
  docs/docsite/rst/community/contributor_path.rst
  docs/docsite/rst/community/how_can_I_help.rst
  docs/docsite/rst/community/index.rst
  docs/docsite/rst/community/maintainers_guidelines.rst
  docs/docsite/rst/community/reporting_bugs_and_features.rst
  docs/docsite/rst/community/steering/community_steering_committee.rst
  docs/docsite/rst/dev_guide/developing_collections_shared.rst
  docs/docsite/rst/dev_guide/developing_collections_structure.rst
  docs/docsite/rst/dev_guide/developing_python_3.rst
  docs/docsite/rst/porting_guides/porting_guide_6.rst
  docs/docsite/rst/porting_guides/porting_guides.rst
  docs/docsite/rst/user_guide/vault.rst
  docs/docsite/rst/user_guide/windows_dsc.rst
  lib/ansible/modules/pip.py
  lib/ansible/modules/setup.py
Labels: windows, backport, module, needs_triage, core_review, support:core, docs, docsite, docs_only, affects_2.13

#77504 Replace antsibull with antsibull-docs
  docs/docsite/known_good_reqs.txt
  docs/docsite/requirements.txt
  hacking/build_library/build_ansible/command_plugins/collection_meta.py
  hacking/build_library/build_ansible/command_plugins/docs_build.py
  test/sanity/code-smell/docs-build.requirements.in
  test/sanity/code-smell/docs-build.requirements.txt
Labels: test, core_review, support:core, docs, affects_2.14

#77611 [stable-2.13] Replace antsibull with antsibull-docs (#77504)
  docs/docsite/known_good_reqs.txt
  docs/docsite/requirements.txt
  hacking/build_library/build_ansible/command_plugins/collection_meta.py
  hacking/build_library/build_ansible/command_plugins/docs_build.py
  test/sanity/code-smell/docs-build.requirements.in
  test/sanity/code-smell/docs-build.requirements.txt
Labels: backport, test, core_review, support:core, docs, affects_2.13

#77613 ansible-test - Update default containers to 5.9.0.
  changelogs/fragments/ansible-test-default-container-update-5.9.0.yaml
  test/lib/ansible_test/_data/completion/docker.txt
Labels: backport, test, core_review, support:core, feature, affects_2.13

#77627 New release v2.11.11
  changelogs/CHANGELOG-v2.11.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.11.11_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, core_review, support:core, affects_2.11

#77628 New release v2.12.5
  changelogs/CHANGELOG-v2.12.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.12.5_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, core_review, support:core, affects_2.12

#77629 New release v2.13.0b1
  changelogs/CHANGELOG-v2.13.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.13.0b1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, core_review, support:core, affects_2.13

#77599 add link to deprecation warning
  changelogs/fragments/77599-add-url-include-deprecation.yml
  lib/ansible/playbook/helpers.py
Labels: needs_triage, core_review, support:core, bug, affects_2.14

#77632 Update Ansible release version to v2.11.11.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, core_review, support:core, small_patch, affects_2.11

#77633 Update Ansible release version to v2.12.5.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, core_review, support:core, small_patch, affects_2.12

#77634 Update Ansible release version to v2.13.0b1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, core_review, support:core, small_patch, affects_2.13

#77637 Fix use of deprecated antsibull-docs option.
  hacking/build_library/build_ansible/command_plugins/docs_build.py
Labels: core_review, support:core, docs, small_patch, affects_2.14

#77638 ansible-test - Fix subprocess management.
  changelogs/fragments/ansible-test-subprocess-isolation.yml
  test/integration/targets/ansible-test-no-tty/aliases
  test/integration/targets/ansible-test-no-tty/runme.py
  test/integration/targets/ansible-test-no-tty/runme.sh
  test/lib/ansible_test/_internal/ansible_util.py
  test/lib/ansible_test/_internal/commands/coverage/__init__.py
  test/lib/ansible_test/_internal/commands/coverage/combine.py
  test/lib/ansible_test/_internal/commands/integration/cloud/cs.py
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_internal/commands/sanity/pylint.py
  test/lib/ansible_test/_internal/commands/sanity/validate_modules.py
  test/lib/ansible_test/_internal/commands/shell/__init__.py
  test/lib/ansible_test/_internal/config.py
  test/lib/ansible_test/_internal/connections.py
  test/lib/ansible_test/_internal/core_ci.py
  test/lib/ansible_test/_internal/delegation.py
  test/lib/ansible_test/_internal/docker_util.py
  test/lib/ansible_test/_internal/host_profiles.py
  test/lib/ansible_test/_internal/util.py
  test/lib/ansible_test/_internal/util_common.py
  test/lib/ansible_test/_internal/venv.py
  test/lib/ansible_test/_util/controller/sanity/code-smell/changelog.py
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/module_args.py
  test/lib/ansible_test/_util/target/cli/ansible_test_cli_stub.py
  test/sanity/code-smell/docs-build.py
  test/sanity/code-smell/package-data.py
  test/units/test_no_tty.py
Labels: test, core_review, support:community, support:core, bug, affects_2.14

#77636 Reduce CI test matrix.
  .azure-pipelines/azure-pipelines.yml
  test/integration/targets/ansible-galaxy-collection/aliases
  test/lib/ansible_test/_internal/sanity/integration_aliases.py
  test/utils/shippable/galaxy.sh
Labels: backport, test, core_review, support:community, support:core, affects_2.9

#77639 Require blocking IO for ansible CLI.
  changelogs/fragments/ansible-require-blocking-io.yml
  lib/ansible/cli/__init__.py
Labels: core_review, support:core, feature, affects_2.14

#77609 Prevent losing unsafe from lookups
  changelogs/fragments/77535-prevent-losing-unsafe-lookups.yml
  lib/ansible/template/__init__.py
  test/integration/targets/template/unsafe.yml
  test/units/template/test_templar.py
Labels: core_review, support:core, bug, affects_2.14

#77631 Add python path to version output
  changelogs/fragments/python_version_path.yml
  lib/ansible/cli/arguments/option_helpers.py
Labels: needs_triage, core_review, support:core, feature, affects_2.14

#77645 Pin antsibull so 2.10 docs build works again
  docs/docsite/known_good_reqs.txt
Labels: backport, core_review, support:core, docs, affects_2.10, docs_only

#77646 docs: Update porting guide for ansible 5.7.0
  docs/docsite/rst/porting_guides/porting_guide_5.rst
Labels: core_review, support:core, docs, docs_only, affects_2.14

#77597 remove import_play examples from include module
  lib/ansible/modules/_include.py
Labels: module, core_review, deprecated, support:core, docs, affects_2.14

#77612 trim down to use sanity test docs requirements file
  docs/docsite/known_good_reqs.txt
  docs/docsite/rst/community/documentation_contributions.rst
Labels: core_review, support:core, docs, docsite, has_issue, docs_only, affects_2.14

#77648 Typo fix
  docs/docsite/rst/community/contributor_path.rst
Labels: core_review, support:core, new_contributor, docs, small_patch, docsite, docs_only, affects_2.14

#77665 Update guide_vultr.rst
  docs/docsite/rst/scenario_guides/guide_vultr.rst
Labels: core_review, support:core, docs, docs_only, affects_2.14

#77641 ansible-test - Fix subprocess management.
  changelogs/fragments/ansible-test-subprocess-isolation.yml
  test/integration/targets/ansible-test-no-tty/aliases
  test/integration/targets/ansible-test-no-tty/runme.py
  test/integration/targets/ansible-test-no-tty/runme.sh
  test/lib/ansible_test/_internal/ansible_util.py
  test/lib/ansible_test/_internal/commands/coverage/__init__.py
  test/lib/ansible_test/_internal/commands/coverage/combine.py
  test/lib/ansible_test/_internal/commands/integration/__init__.py
  test/lib/ansible_test/_internal/commands/integration/cloud/cs.py
  test/lib/ansible_test/_internal/commands/integration/coverage.py
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_internal/commands/sanity/pylint.py
  test/lib/ansible_test/_internal/commands/sanity/validate_modules.py
  test/lib/ansible_test/_internal/commands/shell/__init__.py
  test/lib/ansible_test/_internal/commands/units/__init__.py
  test/lib/ansible_test/_internal/config.py
  test/lib/ansible_test/_internal/connections.py
  test/lib/ansible_test/_internal/containers.py
  test/lib/ansible_test/_internal/core_ci.py
  test/lib/ansible_test/_internal/coverage_util.py
  test/lib/ansible_test/_internal/delegation.py
  test/lib/ansible_test/_internal/docker_util.py
  test/lib/ansible_test/_internal/host_profiles.py
  test/lib/ansible_test/_internal/pypi_proxy.py
  test/lib/ansible_test/_internal/python_requirements.py
  test/lib/ansible_test/_internal/util.py
  test/lib/ansible_test/_internal/util_common.py
  test/lib/ansible_test/_internal/venv.py
  test/lib/ansible_test/_util/controller/sanity/code-smell/changelog.py
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/module_args.py
  test/lib/ansible_test/_util/target/cli/ansible_test_cli_stub.py
  test/sanity/code-smell/docs-build.py
  test/sanity/code-smell/package-data.py
  test/units/test_no_tty.py
Labels: test, core_review, support:community, support:core, bug, affects_2.14

#77663 Reduce output from ansible-doc integration test.
  test/integration/targets/ansible-doc/runme.sh
Labels: community_review, support:community, affects_2.14

#77668 Require blocking IO for ansible CLI.
  changelogs/fragments/ansible-require-blocking-io.yml
  lib/ansible/cli/__init__.py
Labels: needs_revision, support:core, feature, affects_2.14

#77577 clarify latest release
  docs/docsite/.templates/banner.html
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: core_review, support:core, docs, docs_only, affects_2.14

#77672 typo in doc
  docs/docsite/rst/community/collection_contributors/collection_integration_add.rst
Labels: core_review, support:core, docs, small_patch, docsite, docs_only, affects_2.14

#77682 ansible-doc stay 3.8 python compatible
  lib/ansible/cli/doc.py
  test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol/plugins/filter/grouped.py
  test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol/plugins/filter/ultimatequestion.yml
  test/integration/targets/ansible-doc/runme.sh
Labels: new_plugin, core_review, support:community, support:core, bug, small_patch, affects_2.14

#77654 Fix lazy eval version in integration tests
  test/integration/targets/template/lazy_eval.yml
Labels: core_review, support:core, affects_2.14

#77655 Remove deprecated loading cache plugins directly without cache_loader
  changelogs/fragments/remove-import-cache-plugin-directly.yml
  lib/ansible/plugins/cache/__init__.py
  test/sanity/ignore.txt
  test/units/plugins/cache/test_cache.py
Labels: test, core_review, support:core, feature, affects_2.14

#77657 document base64 filters
  lib/ansible/plugins/filter/b64decode.yml
  lib/ansible/plugins/filter/b64encode.yml
Labels: new_plugin, core_review, support:core, docs, affects_2.14

#77659 dont rely on path to set config defs for plugins
  changelogs/fragments/config_load_by_name.yml
  lib/ansible/plugins/loader.py
  test/integration/targets/plugin_loader/runme.sh
  test/integration/targets/plugin_loader/use_coll_name.yml
Labels: core_review, support:community, support:core, bug, has_issue, affects_2.14

#77650 2.13: Prevent losing unsafe from lookups (#77609)
  changelogs/fragments/77535-prevent-losing-unsafe-lookups.yml
  lib/ansible/template/__init__.py
  test/integration/targets/template/unsafe.yml
  test/units/template/test_templar.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.13

#77447 ansible-config added json/yaml output to list/dump
  changelogs/fragments/config_formats.yml
  lib/ansible/cli/config.py
  lib/ansible/cli/doc.py
  lib/ansible/module_utils/common/json.py
Labels: core_review, support:core, feature, affects_2.14

#77677 Remove deprecated subclassing DefaultCallback without doc_fragment
  changelogs/fragments/remove-deprecated-default-callback-without-doc.yml
  lib/ansible/plugins/callback/default.py
  test/sanity/ignore.txt
Labels: test, core_review, support:core, feature, affects_2.14

#77702 Trim message in split integration test.
  test/integration/targets/split/tasks/main.yml
Labels: community_review, support:community, affects_2.14

#77701 ansible-test - Add support for remote Ubuntu VMs.
  changelogs/fragments/ansible-test-ubuntu-remote.yml
  test/lib/ansible_test/_data/completion/remote.txt
  test/lib/ansible_test/_internal/host_profiles.py
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: test, core_review, support:core, feature, affects_2.14

#77704 fix SELinux facts tests
  test/integration/targets/module_utils_facts.system.selinux/aliases
  test/integration/targets/module_utils_facts.system.selinux/tasks/main.yml
Labels: community_review, support:community, affects_2.14

#77706 ansible-test - Fix remote completion validation.
  changelogs/fragments/ansible-test-remote-completion-validation.yml
  test/lib/ansible_test/_internal/completion.py
Labels: test, core_review, support:core, bug, affects_2.14

#77703 Install acl on Ubuntu for copy integration test.
  test/integration/targets/copy/tasks/acls.yml
Labels: core_review, support:core, affects_2.14

#77705 ansible-test - Remove obsolete code.
  test/lib/ansible_test/_internal/constants.py
Labels: test, core_review, support:core, bug, affects_2.14

#77711 ansible-test - Add multi-arch remote support.
  changelogs/fragments/ansible-test-multi-arch-remotes.yml
  test/lib/ansible_test/_data/completion/network.txt
  test/lib/ansible_test/_data/completion/remote.txt
  test/lib/ansible_test/_data/completion/windows.txt
  test/lib/ansible_test/_internal/cli/compat.py
  test/lib/ansible_test/_internal/cli/environments.py
  test/lib/ansible_test/_internal/cli/parsers/key_value_parsers.py
  test/lib/ansible_test/_internal/commands/integration/cloud/aws.py
  test/lib/ansible_test/_internal/commands/integration/cloud/azure.py
  test/lib/ansible_test/_internal/commands/integration/cloud/hcloud.py
  test/lib/ansible_test/_internal/commands/integration/filters.py
  test/lib/ansible_test/_internal/completion.py
  test/lib/ansible_test/_internal/config.py
  test/lib/ansible_test/_internal/core_ci.py
  test/lib/ansible_test/_internal/host_configs.py
  test/lib/ansible_test/_internal/host_profiles.py
  test/lib/ansible_test/_internal/util.py
Labels: test, core_review, support:core, feature, affects_2.14
