Repository ansible/ansible, pull requests merged in 2022-03, with the labels that each got.

#77162 Release 2.11.9 publish
  lib/ansible/release.py
Labels: backport, needs_triage, core_review, support:core, small_patch, affects_2.11

#77161 Update Ansible release version to v2.12.3.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, support:core, small_patch, affects_2.12

#77148 ansible-test - Correct a typo in the name key
  test/integration/targets/git/handlers/cleanup-freebsd.yml
Labels: core_review, support:core, new_contributor, affects_2.13

#77173 Data tagging and sidecar docs are delayed, and will be retargeted for 2.14
  docs/docsite/rst/roadmap/ROADMAP_2_13.rst
Labels: needs_triage, core_review, support:core, docs, docs_only, affects_2.13

#77176 Disable ansible-runner test on RHEL 7.9.
  test/integration/targets/ansible-runner/aliases
Labels: backport, community_review, support:community, affects_2.10

#77177 Disable ansible-runner test on RHEL 7.9.
  test/integration/targets/ansible-runner/aliases
Labels: backport, community_review, support:community, affects_2.9

#77170 Fixes for type hinting issues.
  lib/ansible/executor/module_common.py
  lib/ansible/executor/process/worker.py
  lib/ansible/galaxy/api.py
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/module_utils/basic.py
  lib/ansible/module_utils/facts/collector.py
  lib/ansible/module_utils/facts/packages.py
  lib/ansible/modules/apt.py
  lib/ansible/modules/apt_repository.py
  lib/ansible/modules/group.py
  lib/ansible/modules/hostname.py
  lib/ansible/modules/unarchive.py
  lib/ansible/modules/user.py
  lib/ansible/parsing/yaml/loader.py
  lib/ansible/playbook/role_include.py
  lib/ansible/plugins/become/__init__.py
  lib/ansible/plugins/connection/__init__.py
  lib/ansible/utils/_junit_xml.py
  lib/ansible/utils/collection_loader/_collection_finder.py
Labels: module, core_review, support:core, bug, affects_2.13

#77183 Fix module exception handlers.
  lib/ansible/modules/apt_repository.py
  lib/ansible/modules/async_wrapper.py
Labels: module, core_review, support:core, bug, affects_2.13

#77184 Fix type hints and variable usage in modules.
  lib/ansible/modules/hostname.py
  lib/ansible/modules/pip.py
  lib/ansible/modules/user.py
  lib/ansible/modules/wait_for.py
  lib/ansible/modules/yum.py
Labels: module, core_review, support:core, bug, affects_2.13

#77185 hostname - Use base class on UnimplementedStrategy
  lib/ansible/modules/hostname.py
Labels: module, core_review, support:core, bug, affects_2.13

#77187 module_utils - Fix type hinting issues.
  lib/ansible/module_utils/common/parameters.py
  lib/ansible/module_utils/common/yaml.py
  lib/ansible/module_utils/compat/importlib.py
  lib/ansible/module_utils/compat/selectors.py
  lib/ansible/module_utils/facts/default_collectors.py
  lib/ansible/module_utils/facts/packages.py
  lib/ansible/module_utils/pycompat24.py
  lib/ansible/module_utils/urls.py
  lib/ansible/module_utils/yumdnf.py
Labels: core_review, support:core, bug, affects_2.13

#77141 first_found: allow spaces in names
  changelogs/fragments/77136-first_found-spaces-in-names.yml
  lib/ansible/plugins/lookup/first_found.py
  test/integration/targets/lookup_first_found/files/vars file spaces.yml
  test/integration/targets/lookup_first_found/tasks/main.yml
Labels: core_review, support:community, support:core, bug, affects_2.13

#77188 Additional type hinting cleanup.
  lib/ansible/module_utils/common/yaml.py
  lib/ansible/module_utils/compat/paramiko.py
  lib/ansible/module_utils/compat/selectors.py
  lib/ansible/module_utils/facts/default_collectors.py
  lib/ansible/module_utils/urls.py
  lib/ansible/modules/hostname.py
  lib/ansible/modules/pip.py
  test/sanity/ignore.txt
Labels: test, module, core_review, support:core, bug, affects_2.13

#77197 Add typing to module_utils.compat.
  changelogs/fragments/compat-typing.yml
  lib/ansible/module_utils/common/yaml.py
  lib/ansible/module_utils/compat/typing.py
  lib/ansible/module_utils/facts/default_collectors.py
  lib/ansible/modules/hostname.py
Labels: module, core_review, support:core, feature, collection, collection:pfsensible.core, affects_2.13

#77191 Update example in with_first_found documentation to work
  lib/ansible/plugins/lookup/first_found.py
Labels: core_review, support:core, docs, docs_only, affects_2.13

#77198 More type hint fixes for module_utils.
  lib/ansible/module_utils/compat/version.py
  lib/ansible/module_utils/facts/ansible_collector.py
  lib/ansible/module_utils/facts/collector.py
  lib/ansible/module_utils/facts/hardware/base.py
  lib/ansible/module_utils/facts/network/base.py
  lib/ansible/module_utils/facts/network/fc_wwn.py
  lib/ansible/module_utils/facts/network/iscsi.py
  lib/ansible/module_utils/facts/network/nvme.py
  lib/ansible/module_utils/facts/other/facter.py
  lib/ansible/module_utils/facts/other/ohai.py
  lib/ansible/module_utils/facts/system/apparmor.py
  lib/ansible/module_utils/facts/system/caps.py
  lib/ansible/module_utils/facts/system/chroot.py
  lib/ansible/module_utils/facts/system/cmdline.py
  lib/ansible/module_utils/facts/system/date_time.py
  lib/ansible/module_utils/facts/system/distribution.py
  lib/ansible/module_utils/facts/system/dns.py
  lib/ansible/module_utils/facts/system/env.py
  lib/ansible/module_utils/facts/system/fips.py
  lib/ansible/module_utils/facts/system/local.py
  lib/ansible/module_utils/facts/system/lsb.py
  lib/ansible/module_utils/facts/system/pkg_mgr.py
  lib/ansible/module_utils/facts/system/platform.py
  lib/ansible/module_utils/facts/system/python.py
  lib/ansible/module_utils/facts/system/selinux.py
  lib/ansible/module_utils/facts/system/service_mgr.py
  lib/ansible/module_utils/facts/system/ssh_pub_keys.py
  lib/ansible/module_utils/facts/system/user.py
  lib/ansible/module_utils/facts/virtual/base.py
  lib/ansible/module_utils/urls.py
Labels: core_review, support:core, bug, affects_2.13

#77201 Simplify existing type hints.
  lib/ansible/galaxy/api.py
  lib/ansible/playbook/role_include.py
  lib/ansible/utils/_junit_xml.py
Labels: core_review, support:core, feature, affects_2.13

#77182 Fix ansible console to respect ANSIBLE_STDOUT_CALLBACK
  changelogs/fragments/ansible-console-callback.yaml
  lib/ansible/cli/console.py
Labels: core_review, support:core, new_contributor, feature, affects_2.13

#77202 ansible-test - Simplify type hints.
  test/lib/ansible_test/_internal/commands/coverage/analyze/targets/__init__.py
  test/lib/ansible_test/_internal/commands/coverage/analyze/targets/combine.py
  test/lib/ansible_test/_internal/commands/coverage/analyze/targets/filter.py
  test/lib/ansible_test/_internal/commands/coverage/analyze/targets/generate.py
  test/lib/ansible_test/_internal/commands/coverage/analyze/targets/missing.py
Labels: test, core_review, support:core, feature, affects_2.13

#77200 Point to AH docs
  docs/docsite/rst/shared_snippets/galaxy_server_list.txt
  docs/docsite/rst/user_guide/collections_using.rst
Labels: core_review, support:core, docs, docs_only, affects_2.13

#71734 Extend validate-modules to also validate plugins
  changelogs/fragments/71734-validate-plugins.yml
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_internal/commands/sanity/ansible_doc.py
  test/lib/ansible_test/_internal/commands/sanity/validate_modules.py
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/__init__.py
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/schema.py
Labels: test, core_review, support:core, docs, feature, docsite, has_issue, affects_2.11

#77203 galaxy - Clean up type hints and imports.
  lib/ansible/galaxy/api.py
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/collection/concrete_artifact_manager.py
  lib/ansible/galaxy/collection/galaxy_api_proxy.py
  lib/ansible/galaxy/collection/gpg.py
  lib/ansible/galaxy/dependency_resolution/__init__.py
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  lib/ansible/galaxy/dependency_resolution/providers.py
  lib/ansible/galaxy/dependency_resolution/versioning.py
Labels: shipit, support:core, bug, affects_2.13

#77180 Honor --quiet parameter properly in fish shell
  changelogs/fragments/77180-fix-fish-env-setup-script.yml
  hacking/env-setup.fish
Labels: core_review, support:core, bug, affects_2.13

#77211 Type hint fixes.
  lib/ansible/cli/console.py
  lib/ansible/config/manager.py
  lib/ansible/galaxy/api.py
  lib/ansible/galaxy/collection/galaxy_api_proxy.py
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  lib/ansible/galaxy/dependency_resolution/providers.py
  lib/ansible/module_utils/common/_collections_compat.py
  lib/ansible/parsing/ajson.py
  lib/ansible/playbook/base.py
  lib/ansible/plugins/action/__init__.py
  lib/ansible/plugins/action/reboot.py
  lib/ansible/plugins/become/__init__.py
  lib/ansible/plugins/inventory/toml.py
  lib/ansible/plugins/shell/cmd.py
  lib/ansible/plugins/shell/powershell.py
  lib/ansible/plugins/terminal/__init__.py
  lib/ansible/plugins/vars/host_group_vars.py
  lib/ansible/utils/_junit_xml.py
  lib/ansible/utils/collection_loader/_collection_finder.py
  lib/ansible/utils/collection_loader/_collection_meta.py
  lib/ansible/utils/jsonrpc.py
  lib/ansible/utils/ssh_functions.py
Labels: windows, networking, core_review, support:core, support:network, bug, affects_2.13

#77212 Remove obsolete Python 2.x compat code.
  lib/ansible/executor/module_common.py
  lib/ansible/plugins/loader.py
  lib/ansible/utils/hashing.py
  lib/ansible/utils/multiprocessing.py
Labels: core_review, support:core, feature, affects_2.13

#77224 Type hint fixes.
  lib/ansible/executor/action_write_locks.py
  lib/ansible/executor/module_common.py
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/collection/galaxy_api_proxy.py
  lib/ansible/parsing/yaml/loader.py
  lib/ansible/plugins/__init__.py
  lib/ansible/plugins/connection/paramiko_ssh.py
  lib/ansible/plugins/inventory/toml.py
  lib/ansible/plugins/loader.py
Labels: core_review, support:core, bug, affects_2.13

#77225 Make ansible_index.rst more readable
  docs/docsite/rst/ansible_index.rst
Labels: core_review, support:core, new_contributor, docs, docs_only, affects_2.13

#77210 Handle collection redirects for filters/tests
  changelogs/fragments/77210-fix-collection-filter-test-redirects.yml
  lib/ansible/template/__init__.py
  test/integration/targets/collections/collection_root_user/ansible_collections/testns/testredirect/meta/runtime.yml
  test/integration/targets/collections/runme.sh
  test/integration/targets/collections/test_collection_meta.yml
Labels: needs_triage, core_review, support:community, support:core, bug, affects_2.13

#77226 Code cleanup for type hinting issues.
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/collection/concrete_artifact_manager.py
  lib/ansible/utils/collection_loader/_collection_finder.py
Labels: core_review, support:core, bug, affects_2.13

#77229 Update include role to match the base class.
  lib/ansible/playbook/role_include.py
Labels: core_review, support:core, bug, affects_2.13

#77230 Add inline type hint ignores.
  lib/ansible/plugins/inventory/yaml.py
  lib/ansible/utils/collection_loader/_collection_finder.py
Labels: core_review, support:core, bug, affects_2.13

#77238 ansible-test - Update default containers to 5.7.0.
  changelogs/fragments/ansible-test-default-container-update-5.7.0.yaml
  test/lib/ansible_test/_data/completion/docker.txt
Labels: test, core_review, support:core, feature, affects_2.13

#77237 Fix yaml loader and compat.
  changelogs/fragments/module_utils-yaml-fix.yml
  lib/ansible/module_utils/common/yaml.py
  lib/ansible/parsing/yaml/loader.py
  test/sanity/ignore.txt
Labels: test, core_review, support:core, bug, affects_2.13

#77239 Remove collections compat from controller code.
  lib/ansible/cli/config.py
  lib/ansible/cli/doc.py
  lib/ansible/config/manager.py
  lib/ansible/context.py
  lib/ansible/errors/__init__.py
  lib/ansible/executor/stats.py
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  lib/ansible/inventory/group.py
  lib/ansible/inventory/host.py
  lib/ansible/parsing/yaml/objects.py
  lib/ansible/playbook/role/__init__.py
  lib/ansible/plugins/action/__init__.py
  lib/ansible/plugins/action/add_host.py
  lib/ansible/plugins/cache/__init__.py
  lib/ansible/plugins/callback/__init__.py
  lib/ansible/plugins/filter/core.py
  lib/ansible/plugins/filter/mathstuff.py
  lib/ansible/plugins/inventory/__init__.py
  lib/ansible/plugins/inventory/script.py
  lib/ansible/plugins/inventory/toml.py
  lib/ansible/plugins/inventory/yaml.py
  lib/ansible/plugins/lookup/csvfile.py
  lib/ansible/plugins/lookup/dict.py
  lib/ansible/plugins/lookup/first_found.py
  lib/ansible/plugins/lookup/ini.py
  lib/ansible/plugins/lookup/list.py
  lib/ansible/plugins/test/core.py
  lib/ansible/template/__init__.py
  lib/ansible/template/vars.py
  lib/ansible/utils/context_objects.py
  lib/ansible/utils/listify.py
  lib/ansible/utils/plugin_docs.py
  lib/ansible/utils/py3compat.py
  lib/ansible/utils/unsafe_proxy.py
  lib/ansible/utils/vars.py
  lib/ansible/vars/clean.py
  lib/ansible/vars/fact_cache.py
  lib/ansible/vars/hostvars.py
  lib/ansible/vars/manager.py
  test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol/plugins/lookup/noop.py
  test/integration/targets/rel_plugin_loading/subdir/inventory_plugins/notyaml.py
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py
  test/support/integration/plugins/inventory/foreman.py
  test/support/network-integration/collections/ansible_collections/ansible/netcommon/plugins/filter/network.py
  test/support/network-integration/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py
  test/support/network-integration/collections/ansible_collections/vyos/vyos/plugins/cliconf/vyos.py
  test/units/parsing/test_ajson.py
  test/units/parsing/yaml/test_loader.py
  test/units/playbook/role/test_role.py
Labels: test, core_review, inventory, support:community, support:core, feature, affects_2.13

#77240 Remove obsolete Python 2.x controller code.
  lib/ansible/executor/process/worker.py
  lib/ansible/executor/task_queue_manager.py
  lib/ansible/plugins/callback/__init__.py
  lib/ansible/utils/display.py
Labels: core_review, support:core, feature, affects_2.13

#77245 ansible-test - Fix PS coverage `--all` generation.
  changelogs/fragments/ansible-test-powershell-coverage-all.yaml
  test/lib/ansible_test/_internal/commands/coverage/combine.py
Labels: test, core_review, support:core, bug, affects_2.13

#73925 Update developing_modules_general_aci.rst
  docs/docsite/rst/dev_guide/developing_modules_general_aci.rst
Labels: core_review, support:core, docs, docsite, affects_2.11, docs_only

#75753 Support podman-remote in ansible-test
  changelogs/fragments/ansible-test-podman-remote.yaml
  test/lib/ansible_test/_internal/containers.py
  test/lib/ansible_test/_internal/docker_util.py
  test/lib/ansible_test/_internal/util.py
Labels: test, core_review, support:core, feature, affects_2.12

#77254 Add ansible devtools working group in community communication
  docs/docsite/rst/community/communication.rst
Labels: core_review, support:core, docs, small_patch, docsite, docs_only, affects_2.13

#77247 get_url fix word emphasis on documentation
  lib/ansible/modules/get_url.py
Labels: module, core_review, support:core, docs, docs_only, affects_2.13

#77220 Include links to the modern homes of the windows modules
  docs/docsite/rst/user_guide/windows_faq.rst
Labels: windows, core_review, support:core, docs, docsite, docs_only, affects_2.13

#77255 ansible-test - Fix delegation inventory path.
  changelogs/fragments/ansible-test-delegation-inventory.yaml
  test/lib/ansible_test/_internal/commands/integration/__init__.py
  test/lib/ansible_test/_internal/commands/integration/network.py
  test/lib/ansible_test/_internal/commands/integration/windows.py
Labels: test, core_review, support:core, bug, affects_2.13

#77256 [stable-2.12] ansible-test - Fix delegation inventory path.
  changelogs/fragments/ansible-test-delegation-inventory.yaml
  test/lib/ansible_test/_internal/commands/integration/__init__.py
  test/lib/ansible_test/_internal/commands/integration/network.py
  test/lib/ansible_test/_internal/commands/integration/windows.py
Labels: backport, test, core_review, support:core, bug, affects_2.12

#77216 After 2.10 Collections can use vars plugins
  docs/docsite/rst/dev_guide/developing_collections_structure.rst
Labels: core_review, support:core, docs, docsite, docs_only, affects_2.13

#77214 Address Docs: How to report bugs #53520
  docs/docsite/rst/community/reporting_bugs_and_features.rst
Labels: core_review, support:core, new_contributor, docs, docsite, docs_only, affects_2.13

#77261 ansible-test - Fix cloud plugin traceback.
  changelogs/fragments/ansible-test-remote-cloud-skip-traceback.yml
  test/lib/ansible_test/_internal/cloud/__init__.py
Labels: backport, test, core_review, support:core, bug, affects_2.11

#77263 [stable-2.10] ansible-test - Fix cloud plugin traceback.
  changelogs/fragments/ansible-test-remote-cloud-skip-traceback.yml
  test/lib/ansible_test/_internal/cloud/__init__.py
Labels: backport, test, core_review, support:core, bug, affects_2.10

#77264 [stable-2.9] ansible-test - Fix cloud plugin traceback.
  changelogs/fragments/ansible-test-remote-cloud-skip-traceback.yml
  test/lib/ansible_test/_internal/cloud/__init__.py
Labels: backport, test, core_review, support:core, bug, affects_2.9

#77281 stub out ipaddr page and point to new home
  docs/docsite/rst/user_guide/playbooks_filters_ipaddr.rst
Labels: needs_triage, core_review, support:core, docs, docs_only, affects_2.13

#77125 [stable-2.12] Use full python package for ansiballz cache filenames (#77090)
  changelogs/fragments/fqn-module-cache.yml
  lib/ansible/executor/module_common.py
  test/integration/targets/collections/ansiballz_dupe/collections/ansible_collections/duplicate/name/plugins/modules/ping.py
  test/integration/targets/collections/ansiballz_dupe/test_ansiballz_cache_dupe_shortname.yml
  test/integration/targets/collections/runme.sh
Labels: needs_info, backport, needs_triage, needs_template, stale_ci, support:community, support:core, affects_2.12

#77128 [2.12] ansible-galaxy collection verify - display new files/dirs as modified content
  changelogs/fragments/76690-fix-ansible-galaxy-collection-verify-modified-content.yaml
  lib/ansible/galaxy/collection/__init__.py
  test/integration/targets/ansible-galaxy-collection/tasks/verify.yml
Labels: backport, needs_triage, core_review, support:community, support:core, bug, affects_2.12

#77179 [stable-2.12] Mention ansible-core RPM package in Ansible Core Installation Guide (backport #76801)
  docs/docsite/rst/installation_guide/intro_installation.rst
Labels: backport, needs_triage, core_review, stale_ci, support:core, new_contributor, docs, small_patch, affects_2.12, docs_only

#77207 2.12: first_found: allow spaces in names (#77141)
  changelogs/fragments/77136-first_found-spaces-in-names.yml
  lib/ansible/plugins/lookup/first_found.py
  test/integration/targets/lookup_first_found/files/vars file spaces.yml
  test/integration/targets/lookup_first_found/tasks/main.yml
Labels: backport, needs_triage, core_review, stale_ci, support:community, support:core, bug, affects_2.12

#77126 [stable-2.11] Use full python package for ansiballz cache filenames (#77090)
  changelogs/fragments/fqn-module-cache.yml
  lib/ansible/executor/module_common.py
  test/integration/targets/collections/ansiballz_dupe/collections/ansible_collections/duplicate/name/plugins/modules/ping.py
  test/integration/targets/collections/ansiballz_dupe/test_ansiballz_cache_dupe_shortname.yml
  test/integration/targets/collections/runme.sh
Labels: needs_info, backport, needs_triage, needs_template, stale_ci, support:community, support:core, affects_2.11

#77129 [2.11] ansible-galaxy collection verify - display new files/dirs as modified content
  changelogs/fragments/76690-fix-ansible-galaxy-collection-verify-modified-content.yaml
  lib/ansible/galaxy/collection/__init__.py
  test/integration/targets/ansible-galaxy-collection/tasks/verify.yml
Labels: backport, needs_triage, core_review, stale_ci, support:community, support:core, bug, affects_2.11

#77142 [2.12 backport] use same timeout for galaxy api interactions (backport of #77088)
  changelogs/fragments/ansible_galaxy_timeout.yml
  lib/ansible/galaxy/api.py
  lib/ansible/galaxy/collection/concrete_artifact_manager.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.12

#77143 [2.11 backport] use same timeout for galaxy api interactions (#77088)
  changelogs/fragments/ansible_galaxy_timeout.yml
  lib/ansible/galaxy/api.py
  lib/ansible/galaxy/collection/concrete_artifact_manager.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.11

#77282 Add a YAML representer for NativeJinjaText
  changelogs/fragments/nativejinjatext-yaml-representer.yml
  lib/ansible/parsing/yaml/dumper.py
Labels: core_review, support:core, bug, affects_2.13

#77300 Update intro_patterns.rst
  docs/docsite/rst/user_guide/intro_patterns.rst
Labels: core_review, support:core, new_contributor, docs, small_patch, docs_only, affects_2.13

#77271 unarchive: fix io_buffer_size option, remove ignore.txt entry
  changelogs/fragments/77271-unarchive.yml
  lib/ansible/modules/unarchive.py
  test/sanity/ignore.txt
  test/units/modules/test_unarchive.py
Labels: test, module, core_review, support:core, bug, has_issue, affects_2.13

#77275 ansible_distribution: Add support for Uos/Deepin
  changelogs/fragments/77275-add-support-for-deepin-distro-info-detection.yaml
  lib/ansible/module_utils/facts/system/distribution.py
  lib/ansible/modules/hostname.py
  test/units/module_utils/facts/system/distribution/fixtures/deepin_20.4.json
  test/units/module_utils/facts/system/distribution/fixtures/uos_20.json
Labels: module, core_review, support:core, new_contributor, bug, affects_2.13

#77235 Update ansible extension information
  docs/docsite/rst/community/other_tools_and_programs.rst
Labels: core_review, support:core, docs, docsite, docs_only, affects_2.13

#77299 2.12: Add YAML representers for NativeJinjaUnsafeText and NativeJinjaText
  changelogs/fragments/nativejinjatext-yaml-representer.yml
  changelogs/fragments/nativejinjaunsafetext-yaml-representer.yml
  lib/ansible/parsing/yaml/dumper.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.12

#77311 [stable-2.12] unarchive: fix io_buffer_size option, remove ignore.txt entry
  changelogs/fragments/77271-unarchive.yml
  lib/ansible/modules/unarchive.py
  test/sanity/ignore.txt
  test/units/modules/test_unarchive.py
Labels: backport, test, module, needs_triage, core_review, support:core, bug, affects_2.12

#77243 Update systemd strategy to not confuse NetworkManager
  changelogs/fragments/76958-hostname-systemd-nm.yaml
  lib/ansible/modules/hostname.py
  test/integration/targets/hostname/tasks/test_normal.yml
Labels: module, core_review, support:core, bug, affects_2.13

#77329 New release v2.12.4rc1
  changelogs/CHANGELOG-v2.12.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.12.4rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, core_review, support:core, affects_2.12

#77331 Update Ansible release version to v2.11.10rc1.post0.
  lib/ansible/release.py
Labels: backport, core_review, support:core, small_patch, affects_2.11

#77332 Update Ansible release version to v2.12.4rc1.post0.
  lib/ansible/release.py
Labels: backport, core_review, support:core, small_patch, affects_2.12

#77327 typo variable reference
  docs/docsite/rst/user_guide/playbooks_environment.rst
Labels: core_review, support:core, new_contributor, docs, small_patch, docs_only, affects_2.13

#77193 linux networking facts: Provide IPv4 prefix
  changelogs/fragments/77193-linux-networking-facts-Provide-IPv4-prefix.yml
  lib/ansible/module_utils/facts/network/linux.py
Labels: core_review, stale_ci, support:core, feature, affects_2.13

#73818 Simplify documentation for search paths
  docs/docsite/rst/user_guide/playbook_pathing.rst
Labels: core_review, support:core, docs, affects_2.11, docs_only

#77178 Reduce intro install to just pip
  docs/docsite/rst/installation_guide/intro_installation.rst
Labels: core_review, support:core, docs, docs_only, affects_2.13

#77290 Add quickstart testing docs for collections
  docs/docsite/rst/community/collection_contributors/collection_integration_about.rst
  docs/docsite/rst/community/collection_contributors/collection_integration_add.rst
  docs/docsite/rst/community/collection_contributors/collection_integration_running.rst
  docs/docsite/rst/community/collection_contributors/collection_integration_tests.rst
  docs/docsite/rst/community/collection_contributors/collection_integration_updating.rst
  docs/docsite/rst/community/collection_contributors/collection_test_pr_locally.rst
  docs/docsite/rst/community/collection_contributors/collection_unit_tests.rst
  docs/docsite/rst/community/collection_contributors/test_index.rst
  docs/docsite/rst/community/contributions_collections.rst
  docs/docsite/rst/community/create_pr_quick_start.rst
  docs/docsite/rst/dev_guide/developing_collections_testing.rst
  docs/docsite/sphinx_conf/core_conf.py
Labels: needs_revision, support:core, docs, docsite, docs_only, affects_2.13

#77026 ansible-galaxy - add configuration options for more flexible collection signature verification
  changelogs/fragments/76681-ansible-galaxy-add-gpg-signature-verification.yaml
  docs/docsite/rst/shared_snippets/installing_collections.txt
  docs/docsite/rst/shared_snippets/installing_multiple_collections.txt
  lib/ansible/cli/galaxy.py
  lib/ansible/config/base.yml
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/collection/concrete_artifact_manager.py
  test/integration/targets/ansible-galaxy-collection/tasks/install.yml
  test/integration/targets/ansible-galaxy-collection/tasks/verify.yml
  test/units/galaxy/test_collection.py
  test/units/galaxy/test_collection_install.py
Labels: core_review, support:community, support:core, docs, feature, has_issue, affects_2.13

#76427 Add find_spec and exec_module to RestrictedModuleLoader
  test/lib/ansible_test/_internal/commands/sanity/mypy.py
  test/lib/ansible_test/_util/controller/sanity/mypy/ansible-test.ini
  test/lib/ansible_test/_util/target/sanity/import/importer.py
  test/sanity/ignore.txt
Labels: needs_revision, test, support:core, feature, small_patch, has_issue, affects_2.13

#67616 Support ignoring of certificates for ansible-galaxy during SCM cloning
  changelogs/fragments/67616-galaxy-scm-cloning-ignore-certs.yml
  lib/ansible/utils/galaxy.py
  test/integration/targets/ansible-galaxy/cleanup-default.yml
  test/integration/targets/ansible-galaxy/cleanup-freebsd.yml
  test/integration/targets/ansible-galaxy/cleanup.yml
  test/integration/targets/ansible-galaxy/files/testserver.py
  test/integration/targets/ansible-galaxy/runme.sh
  test/integration/targets/ansible-galaxy/setup.yml
Labels: needs_revision, support:community, support:core, bug, P3, has_issue, affects_2.10

#77346 Fix quotes
  docs/docsite/rst/reference_appendices/test_strategies.rst
Labels: core_review, support:core, new_contributor, docs, small_patch, docs_only, affects_2.13

#77342 Incorrect parent role paths var description
  docs/docsite/rst/reference_appendices/special_variables.rst
Labels: core_review, support:core, docs, small_patch, docs_only, affects_2.13

#77341 Improve documentation to fix outdated file paths
  hacking/README.md
  hacking/test-module.py
Labels: core_review, support:core, new_contributor, docs, affects_2.13

#77269 Revision: "Address Docs: How to report bugs" #53520
  docs/docsite/rst/community/reporting_bugs_and_features.rst
Labels: core_review, support:core, docs, docsite, has_issue, docs_only, affects_2.13

#77323 Add what to look for in PyYAML documentation
  docs/docsite/rst/user_guide/playbooks_filters.rst
Labels: core_review, support:core, docs, small_patch, docs_only, affects_2.13

#77330 Creat steering committee docs
  docs/docsite/rst/community/contributions_collections.rst
  docs/docsite/rst/community/steering/community_steering_committee.rst
  docs/docsite/rst/community/steering/steering_committee_membership.rst
  docs/docsite/rst/community/steering/steering_committee_past_members.rst
  docs/docsite/rst/community/steering/steering_index.rst
  docs/docsite/sphinx_conf/core_conf.py
Labels: core_review, support:core, docs, docsite, docs_only, affects_2.13

#77319 log results for get_best_parsable_locale
  changelogs/fragments/log_locale_selection_results.yml
  lib/ansible/module_utils/common/locale.py
Labels: core_review, support:core, feature, has_issue, affects_2.13

#77013 Action Plugin argspec validation
  changelogs/fragments/action-plugin-arg-spec.yml
  lib/ansible/plugins/action/__init__.py
  lib/ansible/plugins/action/async_status.py
  lib/ansible/plugins/action/pause.py
  test/integration/targets/pause/test-pause.yml
Labels: core_review, support:core, feature, affects_2.13

#77358 ansible-test - Remove RHEL 9.0b support.
  changelogs/fragments/ansible-test-rhel9.yaml
  test/lib/ansible_test/_data/completion/remote.txt
Labels: test, core_review, support:core, feature, affects_2.13

#77035 Handle errors during ansible-doc --metadata-dump more gracefully
  changelogs/fragments/77035-ansible-doc-metadata-dump-errors.yml
  lib/ansible/cli/doc.py
  test/integration/targets/ansible-doc/broken-docs/collections/ansible_collections/testns/testcol/MANIFEST.json
  test/integration/targets/ansible-doc/broken-docs/collections/ansible_collections/testns/testcol/plugins/cache/notjsonfile.py
  test/integration/targets/ansible-doc/broken-docs/collections/ansible_collections/testns/testcol/plugins/inventory/statichost.py
  test/integration/targets/ansible-doc/broken-docs/collections/ansible_collections/testns/testcol/plugins/lookup/noop.py
  test/integration/targets/ansible-doc/broken-docs/collections/ansible_collections/testns/testcol/plugins/modules/fakemodule.py
  test/integration/targets/ansible-doc/broken-docs/collections/ansible_collections/testns/testcol/plugins/modules/notrealmodule.py
  test/integration/targets/ansible-doc/broken-docs/collections/ansible_collections/testns/testcol/plugins/modules/randommodule.py
  test/integration/targets/ansible-doc/broken-docs/collections/ansible_collections/testns/testcol/plugins/vars/noop_vars_plugin.py
  test/integration/targets/ansible-doc/runme.sh
Labels: new_plugin, core_review, support:community, support:core, feature, has_issue, affects_2.13

#77357 clarify how to customize ansible cli output
  docs/docsite/rst/user_guide/playbooks_best_practices.rst
  lib/ansible/config/base.yml
Labels: needs_triage, core_review, support:core, docs, affects_2.13

#77371 Add family fallback for RHEL to register as RedHat
  changelogs/fragments/77368-rhel-os-family-compat.yaml
  lib/ansible/module_utils/facts/system/distribution.py
  test/integration/targets/interpreter_discovery_python/tasks/main.yml
Labels: needs_triage, core_review, support:community, support:core, bug, affects_2.13

#77374 New release v2.12.4
  changelogs/CHANGELOG-v2.12.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.12.4_summary.yaml
  lib/ansible/release.py
Labels: backport, core_review, support:core, affects_2.12

#77373 New release v2.11.10
  changelogs/CHANGELOG-v2.11.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.11.10_summary.yaml
  lib/ansible/release.py
Labels: backport, core_review, support:core, affects_2.11

#77376 Porting guide fixes.
  docs/docsite/rst/porting_guides/porting_guide_core_2.13.rst
  hacking/build_library/build_ansible/command_plugins/porting_guide.py
Labels: core_review, support:core, docs, affects_2.13

#77377 Update core porting guide generation.
  hacking/build_library/build_ansible/command_plugins/porting_guide.py
Labels: core_review, support:core, bug, affects_2.13

#77362 Bump requirements for antsibull to 0.42.0 for new docs features and
  docs/docsite/known_good_reqs.txt
  docs/docsite/requirements.txt
  test/lib/ansible_test/_data/requirements/sanity.changelog.txt
  test/sanity/code-smell/docs-build.requirements.txt
  test/sanity/code-smell/package-data.requirements.txt
Labels: test, core_review, support:core, docs, small_patch, has_issue, affects_2.13

#77379 Update Ansible release version to v2.11.10.post0.
  lib/ansible/release.py
Labels: backport, core_review, support:core, small_patch, affects_2.11

#77381 ansible-test - Update default test containers.
  changelogs/fragments/ansible-test-default-container-update-5.8.0.yaml
  test/lib/ansible_test/_data/completion/docker.txt
Labels: test, core_review, support:core, feature, affects_2.13

#77380 Update Ansible release version to v2.12.4.post0.
  lib/ansible/release.py
Labels: backport, core_review, support:core, small_patch, affects_2.12

#77355 Only require a keyring if collections with signatures will be installed
  lib/ansible/cli/galaxy.py
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  test/integration/targets/ansible-galaxy-collection/tasks/install.yml
Labels: core_review, support:community, support:core, bug, affects_2.13

#77386 Report relative path in deprecated-config test.
  test/sanity/code-smell/deprecated-config.py
Labels: test, core_review, support:core, affects_2.14

#77014 Fall back to implicit namespace.name:version if metadata is invalid
  changelogs/fragments/77014-ansible-galaxy-list-fix-null-metadata-namespace-name.yml
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  test/integration/targets/ansible-galaxy-collection/tasks/list.yml
Labels: core_review, stale_ci, support:community, support:core, bug, affects_2.13

#77400 Add script to handle more deprecations.
  hacking/create_deprecation_bug_reports.py
  test/sanity/code-smell/package-data.py
Labels: test, core_review, support:core, affects_2.14

#77401 winrm - ensure callers PATH for kinit is set
  changelogs/fragments/winrm-kinit-path.yml
  lib/ansible/plugins/connection/__init__.py
  lib/ansible/plugins/connection/winrm.py
  test/units/plugins/connection/test_winrm.py
Labels: windows, needs_triage, core_review, support:core, bug, affects_2.14

#77410 Remove deprecated ALLOW_WORLD_READABLE_TMPFILES config option
  changelogs/fragments/77393-remove-allow_world_readable_tmpfiles.yml
  lib/ansible/config/base.yml
  lib/ansible/plugins/action/__init__.py
  test/units/plugins/action/test_action.py
Labels: needs_triage, core_review, support:core, feature, affects_2.14

#77411 Remove COMMAND_WARNINGS and warn
  changelogs/fragments/77394-remove-command_warnings.yml
  docs/docsite/rst/user_guide/intro_getting_started.rst
  lib/ansible/config/base.yml
  lib/ansible/modules/command.py
  lib/ansible/modules/shell.py
  lib/ansible/modules/yum_repository.py
  lib/ansible/plugins/action/command.py
  test/integration/targets/ansible-galaxy-collection/tasks/build.yml
  test/integration/targets/command_shell/tasks/main.yml
  test/integration/targets/copy/tasks/main.yml
  test/integration/targets/dnf/tasks/dnf.yml
  test/integration/targets/git/tasks/archive.yml
  test/integration/targets/incidental_setup_docker/tasks/Fedora.yml
  test/integration/targets/incidental_setup_docker/tasks/RedHat-7.yml
  test/integration/targets/setup_cron/tasks/main.yml
  test/integration/targets/setup_paramiko/uninstall-Fedora-35-python-3.yml
  test/integration/targets/setup_paramiko/uninstall-dnf.yml
  test/integration/targets/setup_paramiko/uninstall-yum.yml
  test/integration/targets/setup_paramiko/uninstall-zypper-python-2.yml
  test/integration/targets/setup_paramiko/uninstall-zypper-python-3.yml
  test/integration/targets/yum_repository/tasks/main.yml
  test/sanity/ignore.txt
Labels: test, module, needs_triage, core_review, support:community, support:core, docs, feature, affects_2.14

#77419 ansible-test - Fix origin host target filtering.
  changelogs/fragments/ansible-test-target-filter.yml
  test/lib/ansible_test/_internal/commands/integration/filters.py
  test/lib/ansible_test/_internal/host_configs.py
Labels: test, core_review, support:core, bug, affects_2.14

#77415 add links.yml to collection structure docs
  docs/docsite/rst/dev_guide/developing_collections_structure.rst
Labels: needs_triage, core_review, support:core, docs, docsite, docs_only, affects_2.14

#77421 [stable-2.13] ansible-test - Fix origin host target filtering.
  changelogs/fragments/ansible-test-target-filter.yml
  test/lib/ansible_test/_internal/commands/integration/filters.py
  test/lib/ansible_test/_internal/host_configs.py
Labels: backport, test, core_review, support:core, bug, affects_2.13

#77422 [stable-2.12] ansible-test - Fix origin host target filtering.
  changelogs/fragments/ansible-test-target-filter.yml
  test/lib/ansible_test/_internal/commands/integration/filters.py
  test/lib/ansible_test/_internal/host_configs.py
Labels: backport, test, core_review, support:core, bug, affects_2.12

#77364 Update playbooks_reuse_roles.rst
  docs/docsite/rst/user_guide/playbooks_reuse_roles.rst
Labels: core_review, support:core, new_contributor, docs, small_patch, docs_only, affects_2.13

#77354 Fix list formatting
  docs/docsite/rst/community/reporting_bugs_and_features.rst
Labels: core_review, support:core, docs, docsite, docs_only, affects_2.13

#77426 Remove deprecated LIBVIRT_LXC_NOSECLABEL env var
  changelogs/fragments/77395-remove-libvirt_lxc_noseclabel.yml
  lib/ansible/config/base.yml
Labels: core_review, support:core, feature, affects_2.14

#77428 Remove deprecated NETWORK_GROUP_MODULES env var
  changelogs/fragments/77397-remove-network_group_modules.yml
  lib/ansible/config/base.yml
Labels: core_review, support:core, feature, affects_2.14

#77429 Remove deprecated default.plugin_filters_cfg config option
  changelogs/fragments/77398-remove-plugin_filters_cfg-default.yml
  lib/ansible/config/base.yml
  test/integration/targets/plugin_filtering/filter_lookup.ini
  test/integration/targets/plugin_filtering/filter_modules.ini
  test/integration/targets/plugin_filtering/filter_ping.ini
  test/integration/targets/plugin_filtering/filter_stat.ini
  test/integration/targets/plugin_filtering/no_filters.ini
Labels: core_review, support:community, support:core, feature, affects_2.14

#77431 import_playbook: remove deprecated free form params
  changelogs/fragments/import_playbook-remove-params.yml
  lib/ansible/playbook/playbook_include.py
  test/integration/targets/include_import/playbook/test_import_playbook.yml
  test/integration/targets/include_import/runme.sh
  test/integration/targets/includes/test_includes.yml
Labels: core_review, support:community, support:core, feature, affects_2.14

#77434 Catch ImportError when pyyaml doesn't have libyaml extension
  lib/ansible/module_utils/common/yaml.py
Labels: core_review, support:core, bug, small_patch, affects_2.14

#77352 Most Matrix channels are ansible.com and not .im
  docs/docsite/rst/community/communication.rst
Labels: core_review, support:core, docs, docsite, has_issue, docs_only, affects_2.13

#76655 Docs cheatsheet - skeleton and ansible-playbook
  docs/docsite/rst/user_guide/cheatsheet.rst
  docs/docsite/rst/user_guide/index.rst
Labels: core_review, support:core, docs, has_issue, docs_only, affects_2.13
