Repository ansible/ansible, pull requests merged in 2022-07, with the labels that each got.

#78070 Pr 72292- Add context to inventory plugins
  docs/docsite/rst/plugins/inventory.rst
Labels: core_review, stale_ci, support:core, docs, docs_only, affects_2.14

#78196 documentation: become plugins: correct pluralization in description
  lib/ansible/plugins/become/runas.py
  lib/ansible/plugins/become/su.py
  lib/ansible/plugins/become/sudo.py
Labels: test, core_review, support:core, docs, docs_only, affects_2.14

#78179 2.13: Move undefined check from concat to finalize (#78165)
  changelogs/fragments/78156-undefined-check-in-finalize.yml
  lib/ansible/template/__init__.py
  lib/ansible/template/native_helpers.py
  test/integration/targets/template/runme.sh
  test/integration/targets/template/undefined_in_import-import.j2
  test/integration/targets/template/undefined_in_import.j2
  test/integration/targets/template/undefined_in_import.yml
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.13

#78054 Backport/2.13/78040
  changelogs/fragments/permission-denied-spwd-module.yml
  lib/ansible/modules/user.py
Labels: backport, module, needs_triage, core_review, support:core, bug, affects_2.13

#78102 password lookup argument parsing fix (#78080)
  changelogs/fragments/password_lookup_fix.yml
  lib/ansible/plugins/lookup/password.py
  test/integration/targets/lookup_password/tasks/main.yml
Labels: backport, needs_triage, core_review, support:community, support:core, bug, affects_2.13

#78208 Ensure atomic writes for cache file
  changelogs/fragments/atomic_cache_files.yml
  lib/ansible/plugins/cache/__init__.py
Labels: needs_triage, core_review, support:core, bug, affects_2.14

#78217 Ensure atomic writes for cache file (#78208)
  changelogs/fragments/atomic_cache_files.yml
  lib/ansible/plugins/cache/__init__.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.13

#78221 Fix wording for :ref|term: substitution (#78216)
  changelogs/fragments/fix_adoc_text.yml
  lib/ansible/cli/doc.py
  test/units/cli/test_doc.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.13

#78181 Remove unnecessary special case in Role.load_data
  lib/ansible/playbook/role/__init__.py
Labels: core_review, support:core, bug, affects_2.14

#78175 Preflight encodings check
  changelogs/fragments/ansible-require-utf8.yml
  docs/docsite/rst/porting_guides/porting_guide_core_2.14.rst
  lib/ansible/cli/__init__.py
  lib/ansible/utils/display.py
  test/integration/targets/connection/test.sh
  test/integration/targets/preflight_encoding/aliases
  test/integration/targets/preflight_encoding/tasks/main.yml
  test/integration/targets/preflight_encoding/vars/main.yml
  test/units/utils/test_display.py
Labels: core_review, support:community, support:core, docs, feature, affects_2.14

#78229 New release v2.13.2rc1
  changelogs/CHANGELOG-v2.13.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.13.2rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, core_review, support:core, affects_2.13

#78238 Update Ansible release version to v2.13.2rc1.post0.
  lib/ansible/release.py
Labels: backport, core_review, support:core, small_patch, affects_2.13

#78233 dnf: fix output parsing on non-English LANGUAGE systems
  changelogs/fragments/dnf-fix-locale-language.yml
  lib/ansible/modules/dnf.py
Labels: module, needs_triage, core_review, support:core, bug, affects_2.14

#78066 yum: fix releasever for latest
  changelogs/fragments/78058-yum-releasever-latest.yml
  lib/ansible/modules/yum.py
  test/integration/targets/yum/tasks/yuminstallroot.yml
Labels: module, core_review, support:core, bug, affects_2.14

#78231 validate-modules - allow raw module return type
  changelogs/fragments/validate-modules-module-raw-return-type.yml
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/schema.py
Labels: test, core_review, support:core, feature, affects_2.14

#78232 Added Kylin Linux Advanced Server Support
  changelogs/fragments/kylin_linux_advanced_server_distribution_support.yml
  lib/ansible/module_utils/facts/system/distribution.py
  test/units/module_utils/facts/system/distribution/fixtures/kylin_linux_advanced_server_v10.json
Labels: core_review, support:core, new_contributor, bug, affects_2.14

#78236 Decode vaulted args before sending over ansible-connection.
  changelogs/fragments/ansible-connection_decode.yml
  lib/ansible/module_utils/connection.py
Labels: core_review, support:core, bug, affects_2.14

#78239 Fix invalid characters warning when using suggested inventory group names on python_3_support.rst
  docs/docsite/rst/reference_appendices/python_3_support.rst
Labels: core_review, support:core, docs, small_patch, docs_only, affects_2.14

#78248 Fix module_utils_common.respawn test.
  test/integration/targets/module_utils_common.respawn/tasks/main.yml
Labels: community_review, support:community, affects_2.14

#78245 Ansible 6.1.0: Updated porting_guide_6.rst
  docs/docsite/rst/porting_guides/porting_guide_6.rst
Labels: core_review, support:core, docs, docs_only, affects_2.14

#78250 Ansible 6.1.0: Updated porting_guide_6.rst (#78245)
  docs/docsite/rst/porting_guides/porting_guide_6.rst
Labels: backport, core_review, support:core, docs, docs_only, affects_2.13

#78244 listify_lookup_plugin_terms deprecate dataloader
  changelogs/fragments/loader_in_listify.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/plugins/lookup/nested.py
  lib/ansible/plugins/lookup/subelements.py
  lib/ansible/plugins/lookup/together.py
  lib/ansible/template/__init__.py
  lib/ansible/utils/listify.py
  lib/ansible/vars/manager.py
Labels: core_review, support:core, bug, affects_2.14

#75989 Add default value for lvm_facts when lvm or lvm2 is not installed or …
  changelogs/fragments/17393-fix_silently_failing_lvm_facts.yaml
  lib/ansible/module_utils/facts/hardware/linux.py
Labels: needs_revision, stale_ci, support:core, stale_review, bug, affects_2.13

#78255 Migrate vmware.vmware_rest Dev Guide to collection
  docs/docsite/rst/dev_guide/platforms/vmware_rest_guidelines.rst
Labels: core_review, support:core, docs, docsite, has_issue, docs_only, affects_2.14

#76412 Cleanup write_file method in uri
  changelogs/fragments/write_file_uri_cleanup.yml
  lib/ansible/modules/uri.py
  test/integration/targets/uri/tasks/unexpected-failures.yml
Labels: module, core_review, support:core, bug, affects_2.13

#78162 Adding applicable licensing requirements
  docs/docsite/rst/dev_guide/shared_snippets/licensing.txt
Labels: core_review, support:core, docs, small_patch, docsite, has_issue, docs_only, affects_2.14

#78164 Document choice to use Ansible Project in copyright lines
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
Labels: core_review, support:core, docs, docsite, has_issue, docs_only, affects_2.14

#78183 stat only returns pw_name/gr_name if those can be looked up
  lib/ansible/modules/stat.py
Labels: module, core_review, support:core, docs, small_patch, affects_2.14

#78206 example showing how to deal with keys w/o apt_key
  lib/ansible/modules/apt_key.py
  lib/ansible/modules/apt_repository.py
Labels: module, core_review, support:core, docs, docs_only, affects_2.14

#78260 Add note about package managers
  docs/docsite/rst/user_guide/intro_adhoc.rst
Labels: needs_triage, core_review, support:core, docs, small_patch, has_issue, docs_only, affects_2.14

#78197 Adding some troubleshooting detail for Kerberos connections
  docs/docsite/rst/win_guide/windows_winrm.rst
Labels: core_review, support:core, docs, small_patch, docs_only, affects_2.14

#78257 Deprecate use of Python crypt
  changelogs/fragments/deprecate-crypt-support.yml
  lib/ansible/utils/encrypt.py
Labels: core_review, support:core, bug, affects_2.14

#78273 Fix templating nested vars with convert_data=False
  lib/ansible/template/__init__.py
  test/integration/targets/template/tasks/main.yml
  test/integration/targets/template/templates/indirect_dict.j2
Labels: needs_triage, WIP, support:core, bug, small_patch, affects_2.14

#78272 Updated release_and_maintenance.rst
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: core_review, support:core, docs, small_patch, docs_only, affects_2.14

#78277 Backportapalooza 7 15
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
  docs/docsite/rst/dev_guide/platforms/vmware_rest_guidelines.rst
  docs/docsite/rst/dev_guide/shared_snippets/licensing.txt
  docs/docsite/rst/plugins/inventory.rst
  docs/docsite/rst/reference_appendices/python_3_support.rst
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
  lib/ansible/modules/apt_key.py
  lib/ansible/modules/apt_repository.py
  lib/ansible/modules/dpkg_selections.py
  lib/ansible/modules/stat.py
  lib/ansible/plugins/become/runas.py
  lib/ansible/plugins/become/su.py
  lib/ansible/plugins/become/sudo.py
Labels: backport, module, core_review, support:core, docs, docsite, affects_2.13

#78279 ansible-test - Enable ACLs on FreeBSD remotes.
  changelogs/fragments/ansible-test-freebsd-remote-acl.yml
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: test, core_review, support:core, feature, affects_2.14

#78276 New release v2.13.2
  changelogs/CHANGELOG-v2.13.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.13.2_summary.yaml
  lib/ansible/release.py
Labels: backport, core_review, support:core, affects_2.13

#78290 Update Ansible release version to v2.13.2.post0.
  lib/ansible/release.py
Labels: backport, core_review, support:core, small_patch, affects_2.13

#78281 Split integration test fixes.
  test/integration/targets/module_utils/aliases
  test/integration/targets/module_utils/module_utils_basic_setcwd.yml
  test/integration/targets/setup_test_user/handlers/main.yml
  test/integration/targets/setup_test_user/tasks/default.yml
  test/integration/targets/setup_test_user/tasks/macosx.yml
  test/integration/targets/setup_test_user/tasks/main.yml
  test/integration/targets/slurp/aliases
  test/integration/targets/slurp/defaults/main.yml
  test/integration/targets/slurp/handlers/main.yml
  test/integration/targets/slurp/meta/main.yml
  test/integration/targets/slurp/tasks/test_unreadable.yml
  test/integration/targets/unarchive/meta/main.yml
  test/integration/targets/unarchive/tasks/test_ownership_top_folder.yml
  test/integration/targets/unarchive/tasks/test_unprivileged_user.yml
Labels: core_review, support:community, support:core, affects_2.14

#78271 Update cheatsheet to fix meaning of -k
  docs/docsite/rst/user_guide/cheatsheet.rst
Labels: needs_triage, core_review, support:core, docs, small_patch, docs_only, affects_2.14

#78291 add AnsibleFest 2022 registration banner
  docs/docsite/.templates/banner.html
Labels: needs_triage, core_review, support:core, docs, docs_only, affects_2.14

#78293 Re-enable strategy units
  test/units/plugins/strategy/test_strategy.py
Labels: core_review, support:core, affects_2.14

#78300 Revert "Re-enable strategy units (#78293)"
  test/units/plugins/strategy/test_strategy.py
Labels: needs_triage, core_review, support:core, affects_2.14

#78299 ansible-test - Enable ACL support on more remotes.
  changelogs/fragments/ansible-test-freebsd-remote-acl.yml
  changelogs/fragments/ansible-test-remote-acl.yml
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: test, core_review, support:core, feature, affects_2.14

#78292 Documentation: Update japanese translation
  docs/docsite/rst/locales/ja/LC_MESSAGES/404.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/cli.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/community.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/dev_guide.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/galaxy.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/getting_started.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/index.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/installation_guide.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/network.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/plugins.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/porting_guides.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/reference_appendices.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/roadmap.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/scenario_guides.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/shared_snippets.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/sphinx.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/user_guide.po
Labels: backport, needs_triage, core_review, support:core, docs, docs_only, affects_2.13

#78303 ansible-test - Install `acl` on Alpine remotes.
  changelogs/fragments/ansible-test-remote-acl.yml
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: test, core_review, support:core, feature, small_patch, affects_2.14

#78312 Overhaul become integration tests.
  test/integration/targets/become/aliases
  test/integration/targets/become/files/copy.txt
  test/integration/targets/become/meta/main.yml
  test/integration/targets/become/tasks/become.yml
  test/integration/targets/become/tasks/default.yml
  test/integration/targets/become/tasks/main.yml
  test/integration/targets/become/tasks/su.yml
  test/integration/targets/become/tasks/sudo.yml
  test/integration/targets/become/templates/bar.j2
  test/integration/targets/become/vars/default.yml
  test/integration/targets/become/vars/main.yml
Labels: community_review, support:community, affects_2.14

#78305 Drop custom repo from libuser install @ Alpine CI
  test/integration/targets/group/tasks/tests.yml
  test/integration/targets/setup_cron/tasks/main.yml
Labels: needs_triage, core_review, support:community, support:core, affects_2.14

#78313 Fix become integration test.
  test/integration/targets/become/tasks/become.yml
  test/integration/targets/become/tasks/main.yml
  test/integration/targets/become/vars/main.yml
Labels: community_review, support:community, affects_2.14

#78315 Fix expect integration test.
  test/integration/targets/expect/tasks/main.yml
Labels: core_review, support:core, affects_2.14

#78314 Fix fetch integration test on macOS.
  test/integration/targets/fetch/roles/fetch_tests/tasks/setup.yml
  test/integration/targets/fetch/roles/fetch_tests/vars/Darwin.yml
Labels: core_review, support:core, affects_2.14

#78237 ansible-test - Drop Python 3.8 controller support.
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-drop-python-3.8-controller.yml
  test/lib/ansible_test/_internal/commands/sanity/mypy.py
  test/lib/ansible_test/_internal/util.py
  test/lib/ansible_test/_util/target/common/constants.py
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: test, core_review, support:core, feature, affects_2.14

#77566 Python 3.9 min for controller
  changelogs/fragments/python39-min-controller.yml
  lib/ansible/__main__.py
  lib/ansible/cli/__init__.py
  lib/ansible/executor/task_queue_manager.py
  lib/ansible/playbook/block.py
  lib/ansible/playbook/included_file.py
  lib/ansible/playbook/playbook_include.py
  lib/ansible/playbook/role/definition.py
  lib/ansible/playbook/role_include.py
  lib/ansible/playbook/task.py
  lib/ansible/playbook/task_include.py
  lib/ansible/plugins/action/gather_facts.py
  lib/ansible/plugins/action/template.py
  lib/ansible/plugins/action/uri.py
  lib/ansible/plugins/loader.py
  lib/ansible/plugins/strategy/__init__.py
  lib/ansible/template/vars.py
  lib/ansible/utils/collection_loader/_collection_finder.py
  lib/ansible/utils/vars.py
  lib/ansible/vars/manager.py
  lib/ansible/vars/plugins.py
  setup.cfg
Labels: core_review, support:core, feature, affects_2.14

#78180 Use classproperty to access field attributes of a class
  changelogs/fragments/fieldattributes-classproperty.yml
  lib/ansible/playbook/base.py
  test/units/playbook/test_base.py
Labels: core_review, support:core, feature, affects_2.14

#78320 ansible-test - Update coverage to 6.4.2
  test/lib/ansible_test/_data/requirements/ansible-test.txt
  test/lib/ansible_test/_internal/coverage_util.py
Labels: test, core_review, support:core, feature, affects_2.14

#78306 [2.13] Drop custom repo from libuser install @ Alpine CI
  test/integration/targets/group/tasks/tests.yml
  test/integration/targets/setup_cron/tasks/main.yml
Labels: backport, core_review, support:community, support:core, affects_2.13

#78307 [2.12] Drop custom repo from libuser install @ Alpine CI
  test/integration/targets/group/tasks/tests.yml
  test/integration/targets/setup_cron/tasks/main.yml
Labels: backport, core_review, support:community, support:core, affects_2.12

#78311 [2.11-only] Prepare Alpine signing keys for installs from edge
  test/integration/targets/group/tasks/tests.yml
  test/integration/targets/setup_cron/tasks/main.yml
Labels: backport, core_review, support:community, support:core, affects_2.11

#78322 ansible-test - Update distro containers to 4.4.0.
  test/lib/ansible_test/_data/completion/docker.txt
Labels: test, core_review, support:core, feature, affects_2.14

#78316 dnf: clarify comparison operators in docs
  changelogs/fragments/78295-dnf-fix-comparison-operators-docs.yml
  lib/ansible/modules/dnf.py
Labels: module, core_review, support:core, docs, affects_2.14

#78294 Fix minor typos
  docs/docsite/rst/community/collection_contributors/collection_release_with_branches.rst
  docs/docsite/rst/community/maintainers_workflow.rst
Labels: core_review, support:core, docs, small_patch, docsite, docs_only, affects_2.14

#78321 Add cli docs for interacting with gpg for collection signing
  docs/docsite/rst/user_guide/collections_using.rst
Labels: needs_triage, core_review, support:core, docs, docs_only, affects_2.14

#78328 ansible-test - Fix handling of args after `--`
  changelogs/fragments/ansible-test-filter-options.yml
  test/lib/ansible_test/_internal/config.py
  test/lib/ansible_test/_internal/delegation.py
Labels: test, core_review, support:core, bug, has_issue, affects_2.14

#78317 wait_for - Read file and perform comparisons using bytes to avoid decode errors
  changelogs/fragments/78214-wait-for-compare-bytes.yml
  lib/ansible/modules/wait_for.py
  test/integration/targets/wait_for/files/write_utf16.py
  test/integration/targets/wait_for/tasks/main.yml
Labels: module, core_review, support:core, bug, traceback, affects_2.14

#78308 Add pep440 version_type for version test
  changelogs/fragments/pep440-version-type.yml
  docs/docsite/rst/playbook_guide/playbooks_tests.rst
  lib/ansible/plugins/test/core.py
  lib/ansible/plugins/test/version.yml
  lib/ansible/plugins/test/version_compare.yml
  test/integration/targets/test_core/tasks/main.yml
Labels: new_plugin, test, core_review, support:community, support:core, docs, feature, affects_2.14

#78309 add AnsibleFest 2022 registration banner (#78291)
  docs/docsite/.templates/banner.html
Labels: backport, needs_triage, core_review, support:core, docs, docs_only, affects_2.13

#78326 Backportapalooza 07 21
  changelogs/fragments/78295-dnf-fix-comparison-operators-docs.yml
  docs/docsite/rst/community/collection_contributors/collection_release_with_branches.rst
  docs/docsite/rst/community/maintainers_workflow.rst
  docs/docsite/rst/user_guide/cheatsheet.rst
  docs/docsite/rst/user_guide/collections_using.rst
  docs/docsite/rst/user_guide/intro_adhoc.rst
  lib/ansible/modules/dnf.py
Labels: backport, module, needs_triage, core_review, support:core, docs, docsite, affects_2.13

#78325 Fix KeyError for ansible-galaxy when caching paginated responses from v3
  changelogs/fragments/78325-ansible-galaxy-fix-caching-paginated-responses-from-v3-servers.yml
  lib/ansible/galaxy/api.py
  test/units/galaxy/test_api.py
Labels: core_review, support:core, bug, affects_2.14

#78249 chmod aix errors with 255 is not unreachable
  changelogs/fragments/aix_chmod_255.yml
  lib/ansible/plugins/connection/ssh.py
Labels: core_review, support:core, bug, affects_2.14

#78349 Add missing colon to a snippet in complex data doc
  docs/docsite/rst/user_guide/complex_data_manipulation.rst
Labels: core_review, support:core, docs, small_patch, docs_only, affects_2.14

#78350 ansible-test - Fix TTY and output handling.
  changelogs/fragments/ansible-test-tty-output-handling.yml
  test/integration/targets/ansible-test-sanity-lint/aliases
  test/integration/targets/ansible-test-sanity-lint/expected.txt
  test/integration/targets/ansible-test-sanity-lint/runme.sh
  test/integration/targets/ansible-test-shell/aliases
  test/integration/targets/ansible-test-shell/ansible_collections/ns/col/.keep
  test/integration/targets/ansible-test-shell/expected-stderr.txt
  test/integration/targets/ansible-test-shell/expected-stdout.txt
  test/integration/targets/ansible-test-shell/runme.sh
  test/lib/ansible_test/_internal/commands/coverage/analyze/targets/__init__.py
  test/lib/ansible_test/_internal/commands/shell/__init__.py
  test/lib/ansible_test/_internal/config.py
  test/lib/ansible_test/_internal/connections.py
  test/lib/ansible_test/_internal/delegation.py
  test/lib/ansible_test/_internal/docker_util.py
  test/lib/ansible_test/_internal/util.py
  test/lib/ansible_test/_internal/util_common.py
Labels: test, core_review, support:community, support:core, bug, affects_2.14

#78342 update the out-of-date ansible-test sanity ignores
  docs/docsite/rst/dev_guide/testing/sanity/ignores.rst
Labels: needs_revision, support:core, new_contributor, docs, docsite, has_issue, docs_only, affects_2.14

#78361 update Fest url per marketing
  docs/docsite/.templates/banner.html
Labels: core_review, support:core, docs, small_patch, docs_only, affects_2.14

#78329 [stable-2.13] ansible-test - Fix handling of args after `--` (#78328)
  changelogs/fragments/ansible-test-filter-options.yml
  test/lib/ansible_test/_internal/config.py
  test/lib/ansible_test/_internal/delegation.py
Labels: backport, test, core_review, support:core, bug, affects_2.13

#78330 [stable-2.12] ansible-test - Fix handling of args after `--` (#78328)
  changelogs/fragments/ansible-test-filter-options.yml
  test/lib/ansible_test/_internal/config.py
  test/lib/ansible_test/_internal/delegation.py
Labels: backport, test, core_review, support:core, bug, affects_2.12

#78357 [stable-2.13] ansible-test - Fix TTY and output handling. (#78350).
  changelogs/fragments/ansible-test-tty-output-handling.yml
  test/integration/targets/ansible-test-sanity-lint/aliases
  test/integration/targets/ansible-test-sanity-lint/expected.txt
  test/integration/targets/ansible-test-sanity-lint/runme.sh
  test/integration/targets/ansible-test-shell/aliases
  test/integration/targets/ansible-test-shell/ansible_collections/ns/col/.keep
  test/integration/targets/ansible-test-shell/expected-stderr.txt
  test/integration/targets/ansible-test-shell/expected-stdout.txt
  test/integration/targets/ansible-test-shell/runme.sh
  test/lib/ansible_test/_internal/commands/coverage/analyze/targets/__init__.py
  test/lib/ansible_test/_internal/commands/shell/__init__.py
  test/lib/ansible_test/_internal/config.py
  test/lib/ansible_test/_internal/connections.py
  test/lib/ansible_test/_internal/delegation.py
  test/lib/ansible_test/_internal/docker_util.py
  test/lib/ansible_test/_internal/util.py
  test/lib/ansible_test/_internal/util_common.py
Labels: backport, test, core_review, support:community, support:core, bug, affects_2.13

#76121 Make distro.id() report newer versions of OpenSuSE (at least >=15) also report as opensuse
  changelogs/fragments/opensuse_disto_id.yml
  lib/ansible/module_utils/distro/_distro.py
  test/units/module_utils/test_distro.py
Labels: needs_revision, support:core, stale_review, bug, has_issue, affects_2.13

#78364 Make PluginLoader pseudo-import more like Python's
  changelogs/fragments/self_referential.yml
  lib/ansible/plugins/loader.py
  test/integration/targets/plugin_loader/normal/action_plugins/self_referential.py
  test/integration/targets/plugin_loader/normal/self_referential.yml
Labels: core_review, support:community, support:core, bug, affects_2.14

#78368 Remove unit test pytz requirement.
  test/units/module_utils/common/text/converters/test_json_encode_fallback.py
  test/units/parsing/test_ajson.py
  test/units/requirements.txt
Labels: core_review, support:core, affects_2.14

#78365 Fix typo and style
  docs/docsite/rst/playbook_guide/playbooks_handlers.rst
Labels: core_review, support:core, new_contributor, bug, docs, small_patch, docs_only, affects_2.14

#78359 Clarify lifetime of registered variables in playbooks_variables.rst
  docs/docsite/rst/playbook_guide/playbooks_variables.rst
Labels: core_review, support:core, docs, small_patch, docs_only, affects_2.14

#78369 Remove unit test Python 2.6 compat.
  test/units/compat/unittest.py
  test/units/requirements.txt
Labels: core_review, support:core, affects_2.14

#78376 Update unit test controller requirements.
  test/units/requirements.txt
Labels: core_review, support:core, affects_2.14

#78192 Update information on the Intro_patterns.rst
  docs/docsite/rst/user_guide/intro_patterns.rst
Labels: needs_revision, support:core, docs, docs_only, affects_2.14

#78128 add note about permission change
  lib/ansible/plugins/doc_fragments/files.py
Labels: needs_revision, support:core, stale_review, docs, affects_2.14

#78375 Fix escaped asterisk in code block demonstrating wildcards
  docs/docsite/rst/user_guide/intro_patterns.rst
Labels: core_review, support:core, new_contributor, docs, small_patch, docs_only, affects_2.14

#78382 Change the language used in the unarchive test.
  test/integration/targets/unarchive/tasks/test_different_language_var.yml
Labels: needs_triage, core_review, support:core, affects_2.14

#78377 ansible-test - Update base and default containers.
  changelogs/fragments/ansible-test-default-containers.yml
  test/lib/ansible_test/_data/completion/docker.txt
Labels: test, core_review, support:core, feature, small_patch, affects_2.14

#78378 Pause module, return actual echo value
  changelogs/fragments/pause_echo_fix.yml
  lib/ansible/plugins/action/pause.py
Labels: needs_triage, core_review, support:core, bug, affects_2.14

#78363 update Fest url per marketing (#78361)
  docs/docsite/.templates/banner.html
Labels: backport, needs_triage, core_review, support:core, docs, small_patch, docs_only, affects_2.13

#78379 Docs Backportapalooza
  docs/docsite/rst/dev_guide/testing/sanity/ignores.rst
  docs/docsite/rst/user_guide/complex_data_manipulation.rst
  docs/docsite/rst/user_guide/intro_patterns.rst
  lib/ansible/plugins/doc_fragments/files.py
Labels: backport, needs_triage, core_review, support:core, docs, docsite, affects_2.13
