Repository ansible/ansible, pull requests merged in 2022-08, with the labels that each got.

#78125 [WIP] Ansible 7 Roadmap
  docs/docsite/rst/roadmap/COLLECTIONS_7.rst
  docs/docsite/rst/roadmap/ansible_roadmap_index.rst
Labels: WIP, support:core, docs, has_issue, docs_only, affects_2.14

#78383 Correctly get the filename from a url in fetch_file
  changelogs/fragments/29680-fetch-file-file-name-too-long.yml
  lib/ansible/module_utils/urls.py
  test/units/module_utils/urls/test_fetch_file.py
Labels: core_review, support:core, bug, affects_2.14

#78399 Do not allow handlers from dynamic includes to be notified
  changelogs/fragments/dont-expose-included-handlers.yml
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/handlers/runme.sh
  test/integration/targets/handlers/test_notify_included-handlers.yml
  test/integration/targets/handlers/test_notify_included.yml
Labels: needs_triage, core_review, support:community, support:core, bug, affects_2.14

#78403 Fix removing existing dir/files with `ansible-galaxy collection init --force`
  changelogs/fragments/ansible-galaxy-collection-init-force.yml
  lib/ansible/cli/galaxy.py
  test/integration/targets/ansible-galaxy-collection/tasks/init.yml
Labels: needs_triage, core_review, support:community, support:core, bug, affects_2.14

#78407 config error origin
  changelogs/fragments/config_error_origin.yml
  lib/ansible/config/manager.py
  test/integration/targets/config/runme.sh
Labels: core_review, support:community, support:core, bug, affects_2.14

#76596 Fix listing collections that are missing the metadata required by build
  changelogs/fragments/70180-collection-list-more-robust.yml
  lib/ansible/cli/galaxy.py
  lib/ansible/galaxy/collection/concrete_artifact_manager.py
  test/integration/targets/ansible-galaxy-collection/tasks/list.yml
  test/units/galaxy/test_collection.py
Labels: core_review, support:community, support:core, bug, affects_2.13

#78414 Slip data tagging to 2.15
  docs/docsite/rst/roadmap/ROADMAP_2_14.rst
Labels: core_review, support:core, docs, small_patch, docs_only, affects_2.14

#78408 Ansible 6.2.0: porting_guide changes
  docs/docsite/rst/porting_guides/porting_guide_6.rst
Labels: core_review, support:core, docs, docs_only, affects_2.14

#78416 Ansible 6.2.0: porting_guide changes (#78408)
  docs/docsite/rst/porting_guides/porting_guide_6.rst
Labels: backport, needs_triage, core_review, support:core, docs, docs_only, affects_2.13

#78389 ansible-test - Update locale logic to match core.
  changelogs/fragments/ansible-test-locale.yml
  test/lib/ansible_test/_internal/__init__.py
  test/lib/ansible_test/_internal/delegation.py
  test/lib/ansible_test/_internal/locale_util.py
  test/lib/ansible_test/_internal/util.py
Labels: test, core_review, support:core, feature, affects_2.14

#78114 Add support for json in adhoc -a
  changelogs/fragments/78112-adhoc-args-as-json.yml
  docs/docsite/rst/user_guide/intro_adhoc.rst
  lib/ansible/cli/adhoc.py
  test/integration/targets/adhoc/runme.sh
Labels: core_review, support:community, support:core, docs, feature, has_issue, affects_2.14

#78418 ansible-test - Parse content config only once.
  changelogs/fragments/ansible-test-content-config.yml
  test/integration/targets/ansible-test-config-invalid/aliases
  test/integration/targets/ansible-test-config-invalid/ansible_collections/ns/col/tests/config.yml
  test/integration/targets/ansible-test-config-invalid/ansible_collections/ns/col/tests/integration/targets/test/aliases
  test/integration/targets/ansible-test-config-invalid/ansible_collections/ns/col/tests/integration/targets/test/runme.sh
  test/integration/targets/ansible-test-config-invalid/ansible_collections/ns/col/tests/unit/plugins/module_utils/test_test.py
  test/integration/targets/ansible-test-config-invalid/runme.sh
  test/integration/targets/ansible-test-config/aliases
  test/integration/targets/ansible-test-config/ansible_collections/ns/col/plugins/module_utils/test.py
  test/integration/targets/ansible-test-config/ansible_collections/ns/col/tests/config.yml
  test/integration/targets/ansible-test-config/ansible_collections/ns/col/tests/unit/plugins/module_utils/test_test.py
  test/integration/targets/ansible-test-config/runme.sh
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_internal/commands/units/__init__.py
  test/lib/ansible_test/_internal/config.py
  test/lib/ansible_test/_internal/content_config.py
  test/lib/ansible_test/_internal/delegation.py
Labels: new_plugin, test, core_review, support:community, support:core, bug, affects_2.14

#78406 [stable-2.12] Fix KeyError for ansible-galaxy when caching paginated responses from v3 (#78325)
  changelogs/fragments/78325-ansible-galaxy-fix-caching-paginated-responses-from-v3-servers.yml
  lib/ansible/galaxy/api.py
  test/units/galaxy/test_api.py
Labels: backport, needs_triage, core_review, support:core, affects_2.12

#78247 [2.12] Decode vaulted args before sending over ansible-connection. (#78236)
  changelogs/fragments/ansible-connection_decode.yml
  lib/ansible/module_utils/connection.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.12

#78218 Ensure atomic writes for cache file (#78208)
  changelogs/fragments/atomic_cache_files.yml
  lib/ansible/plugins/cache/__init__.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.12

#78405 [stable-2.13] Fix KeyError for ansible-galaxy when caching paginated responses from v3 (#78325)
  changelogs/fragments/78325-ansible-galaxy-fix-caching-paginated-responses-from-v3-servers.yml
  lib/ansible/galaxy/api.py
  test/units/galaxy/test_api.py
Labels: backport, needs_triage, core_review, support:core, affects_2.13

#78246 [2.13] Decode vaulted args before sending over ansible-connection. (#78236)
  changelogs/fragments/ansible-connection_decode.yml
  lib/ansible/module_utils/connection.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.13

#78241 2.13: dnf: fix output parsing on non-English LANGUAGE systems (#78233)
  changelogs/fragments/dnf-fix-locale-language.yml
  lib/ansible/modules/dnf.py
Labels: backport, module, needs_triage, core_review, support:core, bug, affects_2.13

#78242 2.13: yum: fix releasever for latest (#78066)
  changelogs/fragments/78058-yum-releasever-latest.yml
  lib/ansible/modules/yum.py
  test/integration/targets/yum/tasks/yuminstallroot.yml
Labels: backport, module, needs_triage, core_review, support:core, bug, affects_2.13

#78261 Backport PR #77312: honor use_proxy parameter
  changelogs/fragments/58632-uri-include_use_proxy.yaml
  lib/ansible/module_utils/urls.py
  lib/ansible/modules/uri.py
  test/integration/targets/uri/tasks/main.yml
Labels: backport, module, needs_triage, core_review, support:core, new_contributor, has_issue, affects_2.13

#78269 2.13: template module/lookup: fix convert_data for macros (#78259)
  changelogs/fragments/78141-template-fix-convert_data.yml
  lib/ansible/plugins/lookup/template.py
  lib/ansible/template/__init__.py
  test/integration/targets/template/tasks/main.yml
  test/integration/targets/template/templates/indirect_dict.j2
  test/integration/targets/template/templates/json_macro.j2
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.13

#78356 chmod aix errors with 255 is not unreachable (#78249)
  changelogs/fragments/aix_chmod_255.yml
  lib/ansible/plugins/connection/ssh.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.13

#78426 [stable-2.13] ansible-test - Parse content config only once. (#78418)
  changelogs/fragments/ansible-test-content-config.yml
  test/integration/targets/ansible-test-config-invalid/aliases
  test/integration/targets/ansible-test-config-invalid/ansible_collections/ns/col/tests/config.yml
  test/integration/targets/ansible-test-config-invalid/ansible_collections/ns/col/tests/integration/targets/test/aliases
  test/integration/targets/ansible-test-config-invalid/ansible_collections/ns/col/tests/integration/targets/test/runme.sh
  test/integration/targets/ansible-test-config-invalid/ansible_collections/ns/col/tests/unit/plugins/module_utils/test_test.py
  test/integration/targets/ansible-test-config-invalid/runme.sh
  test/integration/targets/ansible-test-config/aliases
  test/integration/targets/ansible-test-config/ansible_collections/ns/col/plugins/module_utils/test.py
  test/integration/targets/ansible-test-config/ansible_collections/ns/col/tests/config.yml
  test/integration/targets/ansible-test-config/ansible_collections/ns/col/tests/unit/plugins/module_utils/test_test.py
  test/integration/targets/ansible-test-config/runme.sh
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_internal/commands/units/__init__.py
  test/lib/ansible_test/_internal/config.py
  test/lib/ansible_test/_internal/content_config.py
  test/lib/ansible_test/_internal/delegation.py
Labels: backport, test, core_review, support:community, support:core, bug, affects_2.13

#78367 [2.13] Make PluginLoader pseudo-import more like Python's (#78364)
  changelogs/fragments/self_referential.yml
  lib/ansible/plugins/loader.py
  test/integration/targets/plugin_loader/normal/action_plugins/self_referential.py
  test/integration/targets/plugin_loader/normal/self_referential.yml
Labels: backport, needs_triage, core_review, support:community, support:core, bug, affects_2.13

#78373 [stable-2.13] swallow all exceptions in type annotation support shim imports (#77860)
  changelogs/fragments/type_shim_exception_swallow.yml
  lib/ansible/module_utils/compat/typing.py
Labels: backport, needs_triage, core_review, support:core, affects_2.13

#78409 config error origin (#78407)
  changelogs/fragments/config_error_origin.yml
  lib/ansible/config/manager.py
  test/integration/targets/config/runme.sh
Labels: backport, needs_triage, core_review, support:community, support:core, bug, affects_2.13

#78410 [2.13] Fix listing collections with null namespace/name metadata
  changelogs/fragments/77014-ansible-galaxy-list-fix-null-metadata-namespace-name.yml
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  test/integration/targets/ansible-galaxy-collection/tasks/list.yml
Labels: backport, needs_triage, core_review, support:community, support:core, bug, affects_2.13

#78412 [2.13] Fix removing existing dir/files with `ansible-galaxy collection init …
  changelogs/fragments/ansible-galaxy-collection-init-force.yml
  lib/ansible/cli/galaxy.py
  test/integration/targets/ansible-galaxy-collection/tasks/init.yml
Labels: backport, needs_triage, core_review, support:community, support:core, bug, affects_2.13

#78411 [2.13] Fix listing collections that are missing the metadata required by build
  changelogs/fragments/70180-collection-list-more-robust.yml
  lib/ansible/cli/galaxy.py
  lib/ansible/galaxy/collection/concrete_artifact_manager.py
  test/integration/targets/ansible-galaxy-collection/tasks/list.yml
  test/units/galaxy/test_collection.py
Labels: backport, needs_triage, core_review, support:community, support:core, bug, affects_2.13

#78419 remove Templar caching
  changelogs/fragments/zap_template_cache.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/template/__init__.py
Labels: needs_triage, core_review, support:core, bug, affects_2.14

#78434 fix broken link in community guide
  docs/docsite/rst/community/contributor_path.rst
Labels: needs_triage, core_review, support:core, docs, small_patch, docsite, has_issue, docs_only, affects_2.14

#78443 add example to import a playbook from collection
  lib/ansible/modules/import_playbook.py
Labels: module, core_review, support:core, docs, small_patch, docs_only, affects_2.14

#78441 connection_pipelining: fix default value documentation for pipelining
  lib/ansible/plugins/doc_fragments/connection_pipelining.py
Labels: core_review, support:core, docs, small_patch, affects_2.14

#78424 docs: Fix control node reference links
  docs/docsite/rst/dev_guide/developing_python_3.rst
Labels: core_review, support:core, docs, small_patch, docsite, docs_only, affects_2.14

#78391 Improve grammar
  docs/docsite/rst/shared_snippets/basic_concepts.txt
Labels: core_review, support:core, new_contributor, docs, docs_only, affects_2.14

#78387 Add basic docs on how to create a collection docsite with antsibull-docs
  docs/docsite/rst/dev_guide/developing_collections.rst
  docs/docsite/rst/dev_guide/developing_collections_documenting.rst
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
  docs/docsite/rst/playbook_guide/playbooks_reuse_roles.rst
Labels: core_review, support:core, docs, docsite, docs_only, affects_2.14

#78398 Update galaxy_server_list
  docs/docsite/rst/shared_snippets/galaxy_server_list.txt
Labels: core_review, support:core, docs, small_patch, docs_only, affects_2.14

#78448 Fix typo: missing 'install'
  docs/docsite/rst/dev_guide/developing_collections_documenting.rst
Labels: core_review, support:core, docs, small_patch, docsite, docs_only, affects_2.14

#78445 [2.13] connection_pipelining: fix default value documentation for pipelining
  lib/ansible/plugins/doc_fragments/connection_pipelining.py
Labels: backport, needs_triage, core_review, support:core, docs, small_patch, affects_2.13

#78446 [2.13] Add basic docs on how to create a collection docsite with antsibull-docs
  docs/docsite/rst/dev_guide/developing_collections.rst
  docs/docsite/rst/dev_guide/developing_collections_documenting.rst
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
Labels: backport, needs_triage, core_review, support:core, docs, docsite, docs_only, affects_2.13

#78447 [2.13] Module/plugin docs:
  lib/ansible/modules/apt.py
  lib/ansible/modules/assemble.py
  lib/ansible/modules/find.py
  lib/ansible/modules/getent.py
  lib/ansible/modules/setup.py
  lib/ansible/modules/template.py
  lib/ansible/plugins/doc_fragments/shell_windows.py
  lib/ansible/plugins/lookup/csvfile.py
Labels: backport, module, needs_triage, core_review, support:core, docs, affects_2.13

#78450 Backportapalooza 08 04
  docs/docsite/rst/community/contributor_path.rst
  docs/docsite/rst/dev_guide/developing_python_3.rst
  docs/docsite/rst/shared_snippets/basic_concepts.txt
  docs/docsite/rst/shared_snippets/galaxy_server_list.txt
  docs/docsite/rst/user_guide/intro_patterns.rst
  lib/ansible/modules/import_playbook.py
Labels: backport, module, needs_triage, core_review, support:core, docs, docsite, docs_only, affects_2.13

#78455 ansible-test - More type hint updates.
  test/lib/ansible_test/_internal/ansible_util.py
  test/lib/ansible_test/_internal/cache.py
  test/lib/ansible_test/_internal/ci/__init__.py
  test/lib/ansible_test/_internal/ci/azp.py
  test/lib/ansible_test/_internal/classification/__init__.py
  test/lib/ansible_test/_internal/cli/commands/coverage/analyze/__init__.py
  test/lib/ansible_test/_internal/cli/commands/coverage/analyze/targets/combine.py
  test/lib/ansible_test/_internal/cli/commands/coverage/analyze/targets/expand.py
  test/lib/ansible_test/_internal/cli/commands/coverage/analyze/targets/filter.py
  test/lib/ansible_test/_internal/cli/commands/coverage/analyze/targets/generate.py
  test/lib/ansible_test/_internal/cli/commands/coverage/analyze/targets/missing.py
  test/lib/ansible_test/_internal/cli/commands/coverage/combine.py
  test/lib/ansible_test/_internal/cli/commands/coverage/erase.py
  test/lib/ansible_test/_internal/cli/commands/coverage/html.py
  test/lib/ansible_test/_internal/cli/commands/coverage/report.py
  test/lib/ansible_test/_internal/cli/commands/coverage/xml.py
  test/lib/ansible_test/_internal/cli/commands/env.py
  test/lib/ansible_test/_internal/cli/commands/integration/__init__.py
  test/lib/ansible_test/_internal/cli/commands/integration/network.py
  test/lib/ansible_test/_internal/cli/commands/integration/posix.py
  test/lib/ansible_test/_internal/cli/commands/integration/windows.py
  test/lib/ansible_test/_internal/cli/commands/sanity.py
  test/lib/ansible_test/_internal/cli/commands/shell.py
  test/lib/ansible_test/_internal/cli/commands/units.py
  test/lib/ansible_test/_internal/cli/compat.py
  test/lib/ansible_test/_internal/cli/environments.py
  test/lib/ansible_test/_internal/commands/coverage/analyze/targets/__init__.py
  test/lib/ansible_test/_internal/commands/coverage/combine.py
  test/lib/ansible_test/_internal/commands/coverage/xml.py
  test/lib/ansible_test/_internal/commands/env/__init__.py
  test/lib/ansible_test/_internal/commands/integration/__init__.py
  test/lib/ansible_test/_internal/commands/integration/cloud/__init__.py
  test/lib/ansible_test/_internal/commands/integration/cloud/aws.py
  test/lib/ansible_test/_internal/commands/integration/cloud/azure.py
  test/lib/ansible_test/_internal/commands/integration/cloud/hcloud.py
  test/lib/ansible_test/_internal/commands/integration/coverage.py
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_internal/commands/sanity/pylint.py
  test/lib/ansible_test/_internal/commands/sanity/shellcheck.py
  test/lib/ansible_test/_internal/config.py
  test/lib/ansible_test/_internal/containers.py
  test/lib/ansible_test/_internal/core_ci.py
  test/lib/ansible_test/_internal/data.py
  test/lib/ansible_test/_internal/docker_util.py
  test/lib/ansible_test/_internal/host_profiles.py
  test/lib/ansible_test/_internal/http.py
  test/lib/ansible_test/_internal/inventory.py
  test/lib/ansible_test/_internal/io.py
  test/lib/ansible_test/_internal/metadata.py
  test/lib/ansible_test/_internal/provider/__init__.py
  test/lib/ansible_test/_internal/provider/layout/__init__.py
  test/lib/ansible_test/_internal/provisioning.py
  test/lib/ansible_test/_internal/pypi_proxy.py
  test/lib/ansible_test/_internal/ssh.py
  test/lib/ansible_test/_internal/target.py
  test/lib/ansible_test/_internal/test.py
  test/lib/ansible_test/_internal/thread.py
  test/lib/ansible_test/_internal/util.py
  test/lib/ansible_test/_internal/util_common.py
  test/lib/ansible_test/_internal/venv.py
Labels: needs_revision, needs_rebase, core_review, feature, affects_2.14

#78327 apt: include apt preferences (e.g. pinning) when selecting packages
  changelogs/fragments/77969-apt-preferences.yml
  lib/ansible/modules/apt.py
  test/integration/targets/apt/tasks/repo.yml
Labels: module, shipit, support:core, bug, has_issue, affects_2.14

#78471 New release v2.12.8rc1
  changelogs/CHANGELOG-v2.12.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.12.8rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, core_review, support:core, affects_2.12

#78476 Update Ansible release version to v2.13.3rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, core_review, support:core, small_patch, affects_2.13

#78477 Release 2.12.8rc1 publish
  lib/ansible/release.py
Labels: backport, needs_triage, core_review, support:core, small_patch, affects_2.12

#78480 Add missing space after keywords.
  hacking/return_skeleton_generator.py
  lib/ansible/cli/__init__.py
  lib/ansible/executor/task_executor.py
  lib/ansible/modules/copy.py
  lib/ansible/modules/find.py
  lib/ansible/parsing/splitter.py
  lib/ansible/plugins/action/pause.py
  test/integration/targets/ansible/callback_plugins/callback_debug.py
  test/integration/targets/throttle/test_throttle.py
  test/lib/ansible_test/_internal/provider/layout/collection.py
Labels: test, module, core_review, support:community, support:core, bug, affects_2.14

#78472 fix configuration name in porting guide 2.12
  docs/docsite/rst/porting_guides/porting_guide_5.rst
  docs/docsite/rst/porting_guides/porting_guide_core_2.12.rst
Labels: core_review, support:core, docs, small_patch, docs_only, affects_2.14

#78466 Python 3.9 Controller minimum for document
  docs/docsite/rst/installation_guide/intro_installation.rst
  docs/docsite/rst/porting_guides/porting_guide_core_2.14.rst
Labels: core_review, support:core, docs, small_patch, docs_only, affects_2.14

#78404 update the documentation for the _collection init_ command
  docs/docsite/rst/dev_guide/developing_collections_creating.rst
Labels: core_review, support:core, docs, docsite, has_issue, docs_only, affects_2.14

#76167 Update attributes of files that are links without specifying link target
  changelogs/fragments/76167-update-attributes-of-files-that-are-links.yml
  lib/ansible/modules/file.py
  test/integration/targets/file/tasks/main.yml
  test/integration/targets/file/tasks/state_link.yml
  test/sanity/ignore.txt
Labels: needs_revision, test, module, support:core, stale_review, bug, affects_2.13

#78497 ansible-test - Sanity test code cleanup.
  test/lib/ansible_test/_util/controller/sanity/pylint/plugins/deprecated.py
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py
  test/lib/ansible_test/_util/target/sanity/compile/compile.py
Labels: test, core_review, support:core, feature, affects_2.14

#78498 Clean up unit tests.
  test/units/errors/test_errors.py
  test/units/executor/test_play_iterator.py
Labels: core_review, support:core, affects_2.14

#78504 ansible-test - Update coverage to 6.4.3.
  test/lib/ansible_test/_data/requirements/ansible-test.txt
  test/lib/ansible_test/_internal/coverage_util.py
Labels: test, core_review, support:core, bug, affects_2.14

#78505 ansible-test - No locale warning with delegation.
  test/lib/ansible_test/_internal/__init__.py
  test/lib/ansible_test/_internal/util.py
Labels: test, core_review, support:core, bug, affects_2.14

#78506 ansible-test - Update distro test containers.
  test/lib/ansible_test/_data/completion/docker.txt
Labels: test, core_review, support:core, feature, affects_2.14

#78495 remove old network link
  docs/docsite/rst/playbook_guide/playbooks_privilege_escalation.rst
Labels: needs_triage, core_review, support:core, docs, small_patch, docs_only, affects_2.14

#78501 module_utils - Fix changing value while iterating.
  changelogs/fragments/fix-change-while-iterating-module-utils-service.yml
  lib/ansible/module_utils/service.py
Labels: core_review, support:core, bug, affects_2.14

#78499 Remove unused code.
  lib/ansible/executor/module_common.py
  lib/ansible/modules/async_wrapper.py
  lib/ansible/parsing/plugin_docs.py
  lib/ansible/plugins/loader.py
Labels: module, core_review, support:core, bug, affects_2.14

#78503 find - Use `getattr` instead of `__getattribute__`
  lib/ansible/modules/find.py
Labels: module, core_review, support:core, bug, small_patch, affects_2.14

#78518 ansible-test - Fix ansible-doc sanity test FQCN.
  changelogs/fragments/ansible-test-ansible-doc-sanity-fqcn.yml
  test/integration/targets/ansible-test-sanity-ansible-doc/aliases
  test/integration/targets/ansible-test-sanity-ansible-doc/ansible_collections/ns/col/plugins/lookup/a/b/lookup2.py
  test/integration/targets/ansible-test-sanity-ansible-doc/ansible_collections/ns/col/plugins/lookup/lookup1.py
  test/integration/targets/ansible-test-sanity-ansible-doc/ansible_collections/ns/col/plugins/modules/a/b/module2.py
  test/integration/targets/ansible-test-sanity-ansible-doc/ansible_collections/ns/col/plugins/modules/module1.py
  test/integration/targets/ansible-test-sanity-ansible-doc/runme.sh
  test/lib/ansible_test/_internal/commands/sanity/ansible_doc.py
Labels: new_plugin, test, core_review, support:community, support:core, bug, has_issue, affects_2.14

#78513 docs: misc fixes in The Ansible Development Cycle
  docs/docsite/rst/community/development_process.rst
Labels: core_review, support:core, docs, small_patch, docsite, docs_only, affects_2.14

#78502 ansible-console - Fix arg name to match base class.
  changelogs/fragments/ansible-console-renamed-arg.yml
  lib/ansible/cli/console.py
Labels: core_review, support:core, bug, affects_2.14

#78496 Fix apt making changes in check mode
  changelogs/fragments/78496-fix-apt-check-mode.yml
  lib/ansible/modules/apt.py
  test/integration/targets/apt/tasks/apt.yml
  test/integration/targets/apt/tasks/repo.yml
Labels: module, core_review, support:core, bug, affects_2.14

#78510 adding .PHONY for 3 rules
  Makefile
Labels: needs_triage, core_review, support:core, new_contributor, bug, feature, small_patch, affects_2.14

#78514 PlayIterator: deprecate cache_block_tasks and get_original_task
  changelogs/fragments/playiterator-deprecate-methods.yml
  lib/ansible/executor/play_iterator.py
Labels: needs_triage, core_review, support:core, feature, affects_2.14

#78453 ansible-config init fixes
  changelogs/fragments/fix_init_commented.yml
  lib/ansible/cli/config.py
Labels: core_review, support:core, bug, affects_2.14

#78521 ansible-test - Fix self-test change handling.
  changelogs/fragments/ansible-test-self-change-classification.yml
  test/lib/ansible_test/_internal/classification/__init__.py
  test/lib/ansible_test/_internal/target.py
Labels: test, core_review, support:core, bug, affects_2.14

#78465 add info about plugin name when ignoring abstract errors
  changelogs/fragments/abstract_errors_info.yml
  lib/ansible/plugins/loader.py
Labels: core_review, support:core, bug, affects_2.14

#78451 allow multiple types for null representation
  changelogs/fragments/null_means_none.yml
  lib/ansible/config/base.yml
  test/integration/targets/template/badnull1.cfg
  test/integration/targets/template/badnull2.cfg
  test/integration/targets/template/badnull3.cfg
  test/integration/targets/template/runme.sh
Labels: core_review, support:core, bug, affects_2.14

#78524 Fix ansible-docs: shipping ansible in wheel format #78485
  docs/docsite/rst/reference_appendices/faq.rst
Labels: core_review, support:core, new_contributor, docs, has_issue, docs_only, affects_2.14

#78500 Fix variable use before definition.
  changelogs/fragments/use-before-definition.yml
  lib/ansible/cli/scripts/ansible_connection_cli_stub.py
  lib/ansible/executor/task_executor.py
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/modules/uri.py
  lib/ansible/plugins/connection/winrm.py
  lib/ansible/plugins/list.py
Labels: windows, networking, module, core_review, support:core, bug, affects_2.14

#78528 ansible-test - Update sanity test requirements.
  changelogs/fragments/ansible-test-sanity-requirements.yml
  lib/ansible/inventory/group.py
  lib/ansible/inventory/host.py
  lib/ansible/module_utils/basic.py
  lib/ansible/module_utils/urls.py
  lib/ansible/modules/apt.py
  lib/ansible/plugins/loader.py
  test/lib/ansible_test/_data/requirements/sanity.ansible-doc.txt
  test/lib/ansible_test/_data/requirements/sanity.changelog.in
  test/lib/ansible_test/_data/requirements/sanity.changelog.txt
  test/lib/ansible_test/_data/requirements/sanity.import.plugin.txt
  test/lib/ansible_test/_data/requirements/sanity.mypy.in
  test/lib/ansible_test/_data/requirements/sanity.mypy.txt
  test/lib/ansible_test/_data/requirements/sanity.pep8.txt
  test/lib/ansible_test/_data/requirements/sanity.pylint.in
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  test/lib/ansible_test/_data/requirements/sanity.runtime-metadata.txt
  test/lib/ansible_test/_data/requirements/sanity.validate-modules.txt
  test/lib/ansible_test/_data/requirements/sanity.yamllint.txt
  test/lib/ansible_test/_internal/commands/sanity/mypy.py
  test/lib/ansible_test/_util/controller/sanity/pylint/config/ansible-test-target.cfg
  test/lib/ansible_test/_util/controller/sanity/pylint/config/ansible-test.cfg
  test/lib/ansible_test/_util/controller/sanity/pylint/config/code-smell.cfg
  test/lib/ansible_test/_util/controller/sanity/pylint/config/collection.cfg
  test/lib/ansible_test/_util/controller/sanity/pylint/config/default.cfg
  test/lib/ansible_test/_util/target/setup/requirements.py
  test/sanity/code-smell/botmeta.requirements.txt
  test/sanity/code-smell/deprecated-config.requirements.txt
  test/sanity/code-smell/docs-build.requirements.in
  test/sanity/code-smell/docs-build.requirements.txt
  test/sanity/code-smell/package-data.requirements.in
  test/sanity/code-smell/package-data.requirements.txt
  test/sanity/code-smell/rstcheck.requirements.in
  test/sanity/code-smell/rstcheck.requirements.txt
  test/sanity/code-smell/update-bundled.requirements.txt
  test/sanity/ignore.txt
Labels: test, module, core_review, inventory, support:core, feature, affects_2.14

#78532 ansible-test - Update base and default containers.
  changelogs/fragments/ansible-test-default-containers.yml
  test/lib/ansible_test/_data/completion/docker.txt
Labels: test, core_review, support:core, feature, small_patch, affects_2.14

#78536 Supply some descriptions for settings used in ansible.cfg
  lib/ansible/plugins/connection/paramiko_ssh.py
Labels: core_review, support:core, docs, docs_only, affects_2.14

#78531 Targeting a small typo correction
  lib/ansible/modules/meta.py
  lib/ansible/modules/pip.py
Labels: module, core_review, support:core, docs, small_patch, affects_2.14

#78529 New release v2.12.8
  changelogs/CHANGELOG-v2.12.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.12.8_summary.yaml
  lib/ansible/release.py
Labels: backport, core_review, support:core, affects_2.12

#78527 New release v2.13.3
  changelogs/CHANGELOG-v2.13.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.13.3_summary.yaml
  lib/ansible/release.py
Labels: backport, core_review, support:core, affects_2.13

#78432 Fix version switcher for Japanese docs
  docs/docsite/Makefile
  docs/docsite/sphinx_conf/core_lang_conf.py
Labels: core_review, support:core, docs, docs_only, affects_2.14

#78547 Update Ansible release version to v2.13.3.post0
  lib/ansible/release.py
Labels: backport, core_review, support:core, small_patch, affects_2.13

#78546 Update Ansible release version to v2.12.8.post0.
  lib/ansible/release.py
Labels: backport, core_review, support:core, small_patch, affects_2.12

#78523 [stable-2.13] ansible-test - Fix self-test change handling. (#78521)
  changelogs/fragments/ansible-test-self-change-classification.yml
  test/lib/ansible_test/_internal/classification/__init__.py
  test/lib/ansible_test/_internal/target.py
Labels: backport, test, core_review, support:core, bug, affects_2.13

#78519 [stable-2.13] ansible-test - Fix ansible-doc sanity test FQCN. (#78518).
  changelogs/fragments/ansible-test-ansible-doc-sanity-fqcn.yml
  test/integration/targets/ansible-test-sanity-ansible-doc/aliases
  test/integration/targets/ansible-test-sanity-ansible-doc/ansible_collections/ns/col/plugins/lookup/a/b/lookup2.py
  test/integration/targets/ansible-test-sanity-ansible-doc/ansible_collections/ns/col/plugins/lookup/lookup1.py
  test/integration/targets/ansible-test-sanity-ansible-doc/ansible_collections/ns/col/plugins/modules/a/b/module2.py
  test/integration/targets/ansible-test-sanity-ansible-doc/ansible_collections/ns/col/plugins/modules/module1.py
  test/integration/targets/ansible-test-sanity-ansible-doc/runme.sh
  test/lib/ansible_test/_internal/commands/sanity/ansible_doc.py
Labels: backport, test, core_review, support:community, support:core, bug, affects_2.13

#78551 ansible-test - Fix Ubuntu 20.04 bootstrapping.
  changelogs/fragments/ansible-test-ubuntu-bootstrap-fix.yml
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: test, core_review, support:core, bug, affects_2.14

#78540 Templar: deprecate shared_loader_obj option
  changelogs/fragments/templar-deprecate-shared_loader_obj.yml
  lib/ansible/template/__init__.py
Labels: core_review, support:core, feature, affects_2.14

#77955 Move handler processing into new PlayIterator state
  changelogs/fragments/play_iterator_iterating_handlers.yml
  docs/docsite/rst/playbook_guide/playbooks_handlers.rst
  lib/ansible/executor/play_iterator.py
  lib/ansible/playbook/block.py
  lib/ansible/playbook/handler.py
  lib/ansible/playbook/play.py
  lib/ansible/playbook/task.py
  lib/ansible/plugins/strategy/__init__.py
  lib/ansible/plugins/strategy/free.py
  lib/ansible/plugins/strategy/linear.py
  test/integration/targets/blocks/72725.yml
  test/integration/targets/blocks/72781.yml
  test/integration/targets/blocks/runme.sh
  test/integration/targets/handlers/46447.yml
  test/integration/targets/handlers/52561.yml
  test/integration/targets/handlers/54991.yml
  test/integration/targets/handlers/include_handlers_fail_force-handlers.yml
  test/integration/targets/handlers/include_handlers_fail_force.yml
  test/integration/targets/handlers/order.yml
  test/integration/targets/handlers/runme.sh
  test/integration/targets/handlers/test_flush_handlers_as_handler.yml
  test/integration/targets/handlers/test_flush_handlers_rescue_always.yml
  test/integration/targets/handlers/test_flush_in_rescue_always.yml
  test/integration/targets/handlers/test_handlers_infinite_loop.yml
  test/integration/targets/handlers/test_handlers_meta.yml
  test/integration/targets/handlers/test_skip_flush.yml
  test/units/plugins/strategy/test_linear.py
  test/units/plugins/strategy/test_strategy.py
Labels: core_review, support:community, support:core, docs, feature, affects_2.14

#78555 Docs: Issue 78082 Create inventory guide
  docs/docsite/rst/ansible_index.rst
  docs/docsite/rst/core_index.rst
  docs/docsite/rst/inventory_guide/connection_details.rst
  docs/docsite/rst/inventory_guide/index.rst
  docs/docsite/rst/inventory_guide/intro_dynamic_inventory.rst
  docs/docsite/rst/inventory_guide/intro_inventory.rst
  docs/docsite/rst/inventory_guide/intro_patterns.rst
  docs/docsite/rst/inventory_guide/shared_snippets/SSH_password_prompt.txt
  docs/docsite/rst/user_guide/connection_details.rst
  docs/docsite/rst/user_guide/index.rst
  docs/docsite/rst/user_guide/intro_dynamic_inventory.rst
  docs/docsite/rst/user_guide/intro_inventory.rst
  docs/docsite/rst/user_guide/intro_patterns.rst
Labels: core_review, support:core, docs, docs_only, affects_2.14

#78386 clarify collection signature not available from Community Galaxy
  docs/docsite/rst/dev_guide/developing_collections_distributing.rst
  docs/docsite/rst/reference_appendices/glossary.rst
  docs/docsite/rst/shared_snippets/installing_collections.txt
  docs/docsite/rst/user_guide/collections_using.rst
Labels: core_review, support:core, docs, docsite, docs_only, affects_2.14

#78483 update FAQ with note about libyaml
  docs/docsite/rst/reference_appendices/faq.rst
Labels: core_review, support:core, docs, docs_only, affects_2.14

#78563 update link for RH customers in docs banner
  docs/docsite/.templates/banner.html
Labels: needs_triage, core_review, support:core, docs, small_patch, docs_only, affects_2.14

#74446 Replace get_persistent_connection_options in task_executor with get_options
  changelogs/fragments/74446-network-conn-options.yaml
  lib/ansible/cli/scripts/ansible_connection_cli_stub.py
  lib/ansible/executor/task_executor.py
  test/units/executor/test_task_executor.py
Labels: networking, needs_triage, core_review, support:core, bug, affects_2.12

#76750 yum_repository: Do not set default value for async
  changelogs/fragments/75364-yum-repository-async.yml
  lib/ansible/modules/yum_repository.py
Labels: module, core_review, support:core, bug, affects_2.13

#78484 add note to use package_facts module
  lib/ansible/modules/dnf.py
Labels: module, core_review, support:core, docs, docs_only, affects_2.14

#77418 add required file to collection skeleton
  changelogs/fragments/77418-ansible-galaxy-init-include-meta-runtime.yml
  lib/ansible/galaxy/data/default/collection/meta/runtime.yml
  test/integration/targets/ansible-galaxy-collection/tasks/init.yml
  test/units/cli/test_galaxy.py
Labels: core_review, support:community, support:core, bug, has_issue, affects_2.14

#78422 Use MANIFEST.in style directives to build collection
  changelogs/fragments/collection-build-manifest.yml
  docs/docsite/rst/dev_guide/developing_collections_distributing.rst
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/data/collections_galaxy_meta.yml
  test/integration/targets/ansible-galaxy-collection-cli/aliases
  test/integration/targets/ansible-galaxy-collection-cli/files/expected.txt
  test/integration/targets/ansible-galaxy-collection-cli/files/expected_full_manifest.txt
  test/integration/targets/ansible-galaxy-collection-cli/files/full_manifest_galaxy.yml
  test/integration/targets/ansible-galaxy-collection-cli/files/galaxy.yml
  test/integration/targets/ansible-galaxy-collection-cli/files/make_collection_dir.py
  test/integration/targets/ansible-galaxy-collection-cli/tasks/main.yml
  test/integration/targets/ansible-galaxy-collection-cli/tasks/manifest.yml
  test/units/galaxy/test_collection.py
Labels: core_review, support:community, support:core, docs, feature, docsite, has_issue, affects_2.14

#78572 Fix incorrect docs about how to enable manifest functionality
  docs/docsite/rst/dev_guide/developing_collections_distributing.rst
Labels: core_review, support:core, docs, docsite, docs_only, affects_2.14

#78574 Relax minimal config to enable manifest functionality
  docs/docsite/rst/dev_guide/developing_collections_distributing.rst
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/collection/concrete_artifact_manager.py
  lib/ansible/galaxy/data/collections_galaxy_meta.yml
  lib/ansible/galaxy/data/default/collection/galaxy.yml.j2
  test/units/galaxy/test_collection.py
Labels: needs_triage, core_review, support:core, docs, feature, docsite, affects_2.14

#78568 Docs: Issue 78082 Move BSD docs content
  docs/docsite/rst/ansible_index.rst
  docs/docsite/rst/core_index.rst
  docs/docsite/rst/os_guide/index.rst
  docs/docsite/rst/os_guide/intro_bsd.rst
  docs/docsite/rst/os_guide/windows_dsc.rst
  docs/docsite/rst/os_guide/windows_faq.rst
  docs/docsite/rst/os_guide/windows_performance.rst
  docs/docsite/rst/os_guide/windows_setup.rst
  docs/docsite/rst/os_guide/windows_usage.rst
  docs/docsite/rst/os_guide/windows_winrm.rst
  docs/docsite/rst/user_guide/index.rst
  docs/docsite/rst/user_guide/intro_bsd.rst
  docs/docsite/rst/user_guide/intro_windows.rst
  docs/docsite/rst/user_guide/windows.rst
Labels: windows, core_review, support:core, docs, docsite, docs_only, affects_2.14

#78567 Docs: Issue 78082 Create command line guide
  docs/docsite/rst/ansible_index.rst
  docs/docsite/rst/command_guide/cheatsheet.rst
  docs/docsite/rst/command_guide/command_line_tools.rst
  docs/docsite/rst/command_guide/index.rst
  docs/docsite/rst/command_guide/intro_adhoc.rst
  docs/docsite/rst/core_index.rst
  docs/docsite/rst/inventory_guide/index.rst
  docs/docsite/rst/user_guide/cheatsheet.rst
  docs/docsite/rst/user_guide/command_line_tools.rst
  docs/docsite/rst/user_guide/index.rst
  docs/docsite/rst/user_guide/intro_adhoc.rst
Labels: core_review, support:core, docs, docs_only, affects_2.14

#78468 docs: Update managed node requirements
  docs/docsite/rst/dev_guide/developing_python_3.rst
  docs/docsite/rst/installation_guide/intro_installation.rst
Labels: core_review, support:core, docs, docsite, has_issue, docs_only, affects_2.14

#78578 Fix exit codes for role search and delete
  changelogs/fragments/78516-galaxy-cli-exit-codes.yml
  lib/ansible/cli/galaxy.py
Labels: needs_triage, core_review, support:core, bug, affects_2.14

#78581 Address inactive but legacy print calls found with code checking.
  lib/ansible/modules/dnf.py
  lib/ansible/modules/service_facts.py
Labels: needs_revision, module, support:core, bug, affects_2.14

#76928 Prevent double failing hosts for includes in loops
  changelogs/fragments/23161-includes-loops-rescue.yml
  lib/ansible/plugins/strategy/__init__.py
  lib/ansible/plugins/strategy/free.py
  lib/ansible/plugins/strategy/linear.py
  test/integration/targets/includes/includes_loop_rescue.yml
  test/integration/targets/includes/runme.sh
Labels: core_review, support:community, support:core, bug, has_issue, affects_2.14

#78589 fix Ansible 2.14 reference
  docs/docsite/rst/dev_guide/developing_collections_distributing.rst
Labels: core_review, support:core, docs, small_patch, docsite, docs_only, affects_2.14

#78587 [stable-2.13] Update mypy test. Fix type hints for Python 3.9.
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/collection/concrete_artifact_manager.py
  lib/ansible/galaxy/collection/gpg.py
  lib/ansible/galaxy/dependency_resolution/providers.py
  test/lib/ansible_test/_data/requirements/sanity.mypy.in
  test/lib/ansible_test/_data/requirements/sanity.mypy.txt
  test/lib/ansible_test/_internal/commands/sanity/mypy.py
  test/sanity/ignore.txt
Labels: backport, test, needs_triage, core_review, support:core, bug, affects_2.13

#78545 Fix version switcher for Japanese docs
  docs/docsite/Makefile
  docs/docsite/sphinx_conf/core_lang_conf.py
Labels: backport, needs_triage, core_review, support:core, docs, affects_2.11, docs_only

#78507 [stable-2.12] fix configuration name in porting guide 2.12
  docs/docsite/rst/porting_guides/porting_guide_core_2.12.rst
Labels: backport, needs_triage, core_review, stale_ci, support:core, docs, small_patch, affects_2.12, docs_only

#78544 Fix version switcher for Japanese docs
  docs/docsite/Makefile
  docs/docsite/sphinx_conf/core_lang_conf.py
Labels: backport, needs_triage, core_review, support:core, docs, affects_2.12, docs_only

#78526 Backportapalooza 08 11
  docs/docsite/rst/community/development_process.rst
  docs/docsite/rst/dev_guide/developing_collections_creating.rst
  docs/docsite/rst/porting_guides/porting_guide_5.rst
  docs/docsite/rst/porting_guides/porting_guide_core_2.12.rst
Labels: backport, needs_triage, core_review, support:core, docs, docsite, docs_only, affects_2.13

#78543 Fix version switcher for Japanese site
  docs/docsite/Makefile
  docs/docsite/sphinx_conf/core_lang_conf.py
Labels: backport, needs_triage, core_review, support:core, docs, docs_only, affects_2.13

#78584 Backportapalooza 08 16
  docs/docsite/.templates/banner.html
  docs/docsite/rst/dev_guide/developing_collections_distributing.rst
  docs/docsite/rst/reference_appendices/faq.rst
  docs/docsite/rst/reference_appendices/glossary.rst
  docs/docsite/rst/shared_snippets/installing_collections.txt
  docs/docsite/rst/user_guide/collections_using.rst
  lib/ansible/modules/dnf.py
  lib/ansible/modules/meta.py
  lib/ansible/modules/pip.py
  lib/ansible/plugins/connection/paramiko_ssh.py
Labels: backport, module, needs_triage, core_review, support:core, docs, docsite, affects_2.13

#78592 Fix pytest collection during test_host partial run
  test/units/inventory/__init__.py
Labels: needs_triage, core_review, support:core, affects_2.14

#78593 fix adhoc dev example
  docs/docsite/rst/dev_guide/developing_modules_general.rst
Labels: core_review, support:core, docs, small_patch, docsite, has_issue, docs_only, affects_2.14

#78606 ansible-test - Verify executables are executable.
  changelogs/fragments/ansible-test-verify-executables.yml
  test/lib/ansible_test/_internal/commands/integration/coverage.py
  test/lib/ansible_test/_internal/util.py
  test/lib/ansible_test/_internal/util_common.py
  test/lib/ansible_test/_util/controller/sanity/pylint/plugins/unwanted.py
Labels: test, core_review, support:core, bug, affects_2.14

#78614 Fix file integration test chattr/lsattr check.
  test/integration/targets/file/tasks/main.yml
Labels: core_review, support:core, affects_2.14

#78605 ansible-test - Use --tmpfs to run containers.
  changelogs/fragments/ansible-test-container-tmpfs.yml
  test/lib/ansible_test/_internal/host_profiles.py
Labels: test, core_review, support:core, bug, affects_2.14

#78615 ansible-test - Update test containers.
  changelogs/fragments/ansible-test-containers-no-volume.yml
  test/lib/ansible_test/_data/completion/docker.txt
Labels: test, core_review, support:core, bug, affects_2.14

#78618 [stable-2.13] Fix file integration test chattr/lsattr check. (#78614)
  test/integration/targets/file/tasks/main.yml
Labels: backport, core_review, support:core, affects_2.13

#78619 [stable-2.12] Fix file integration test chattr/lsattr check. (#78614)
  test/integration/targets/file/tasks/main.yml
Labels: backport, core_review, support:core, affects_2.12

#78620 [stable-2.11] Fix file integration test chattr/lsattr check. (#78614)
  test/integration/targets/file/tasks/main.yml
Labels: backport, core_review, support:core, affects_2.11

#78621 [stable-2.9] Fix file integration test chattr/lsattr check. (#78614)
  test/integration/targets/file/tasks/main.yml
Labels: backport, core_review, support:core, affects_2.9

#78616 Fail fast in stuck `ansible-galaxy-collection`
  test/integration/targets/ansible-galaxy-collection/library/setup_collections.py
Labels: community_review, support:community, affects_2.14

#78586 Docs: fix issue-76133 on apt-repository requirements
  lib/ansible/modules/apt_repository.py
Labels: module, core_review, support:core, docs, small_patch, has_issue, docs_only, affects_2.14

#78625 Add Porting Guide for ansible-community v6
  docs/docsite/rst/porting_guides/porting_guide_6.rst
Labels: core_review, support:core, docs, docs_only, affects_2.14

#78631 Add Porting Guide for ansible-community v6 (#78625)
  docs/docsite/rst/porting_guides/porting_guide_6.rst
Labels: backport, needs_triage, core_review, support:core, docs, docs_only, affects_2.13

#78634 prep intro inventory page to be subdivided
  docs/docsite/rst/inventory_guide/intro_inventory.rst
Labels: core_review, support:core, docs, docs_only, affects_2.14

#78554 Fix validate-modules version_added test
  changelogs/fragments/validate-modules-version_added.yaml
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py
Labels: test, core_review, support:core, bug, affects_2.14

#78642 Skip paramiko test on failing platforms.
  test/integration/targets/connection_paramiko_ssh/aliases
  test/integration/targets/connection_paramiko_ssh/runme.sh
Labels: backport, community_review, support:community, affects_2.11

#78630 Fixes typo on docsite playbook_reuse_roles page
  docs/docsite/rst/playbook_guide/playbooks_reuse_roles.rst
Labels: core_review, support:core, new_contributor, docs, small_patch, docs_only, affects_2.14

#78635 Fixes parameter name in expect module examples
  lib/ansible/modules/expect.py
Labels: module, needs_triage, core_review, support:core, new_contributor, docs, small_patch, docs_only, affects_2.14

#78638 Fixes broken links in docsite where default branch name of linked repo has changed
  docs/docsite/rst/community/communication.rst
  docs/docsite/rst/community/contributing_maintained_collections.rst
  docs/docsite/rst/dev_guide/debugging.rst
  docs/docsite/rst/dev_guide/developing_collections_testing.rst
  docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
  docs/docsite/rst/dev_guide/developing_modules_in_groups.rst
  docs/docsite/rst/dev_guide/testing.rst
  docs/docsite/rst/dev_guide/testing_compile.rst
  docs/docsite/rst/dev_guide/testing_httptester.rst
  docs/docsite/rst/dev_guide/testing_integration.rst
  docs/docsite/rst/locales/ja/LC_MESSAGES/community.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/dev_guide.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/network.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/roadmap.po
  docs/docsite/rst/locales/ja/LC_MESSAGES/scenario_guides.po
  docs/docsite/rst/network/dev_guide/developing_resource_modules_network.rst
  docs/docsite/rst/os_guide/index.rst
  docs/docsite/rst/playbook_guide/index.rst
  docs/docsite/rst/roadmap/ansible_core_roadmap_index.rst
  docs/docsite/rst/scenario_guides/guide_aci.rst
Labels: networking, core_review, support:core, new_contributor, docs, docsite, docs_only, affects_2.14

#78610 doc: Correct mixed up commentary and task name
  lib/ansible/modules/replace.py
Labels: module, core_review, support:core, docs, small_patch, docs_only, affects_2.14

#78603 Note that `become_user` is required for `runas`
  docs/docsite/rst/playbook_guide/playbooks_privilege_escalation.rst
Labels: core_review, support:core, new_contributor, docs, small_patch, has_issue, docs_only, affects_2.14

#78643 [2.13] Disable `connection_paramiko_ssh` under FreeBSD 13.0
  test/integration/targets/connection_paramiko_ssh/aliases
Labels: backport, community_review, support:community, affects_2.13

#78644 [2.12] Disable `connection_paramiko_ssh` u/ FreeBSD 13.0+12.2
  test/integration/targets/connection_paramiko_ssh/aliases
Labels: needs_revision, backport, support:community, affects_2.12

#78646 Fix bcrypt install for paramiko test on macOS.
  test/integration/targets/setup_paramiko/install-Darwin-python-3.yml
Labels: backport, community_review, support:community, affects_2.12

#78647 Backportapalooza 08 25
  docs/docsite/rst/dev_guide/developing_modules_general.rst
  lib/ansible/modules/apt_repository.py
  lib/ansible/modules/expect.py
  lib/ansible/modules/replace.py
Labels: backport, module, needs_triage, core_review, support:core, docs, docsite, docs_only, affects_2.13

#78645 Skip test if no there are no problematic chars for wcswidth
  test/units/utils/test_display.py
Labels: needs_triage, core_review, support:core, affects_2.14

#78632 until is also implicit
  changelogs/fragments/until_also_implicit.yml
  lib/ansible/cli/doc.py
Labels: core_review, support:core, bug, affects_2.14

#78651 Fix typos in stat module examples
  lib/ansible/modules/stat.py
Labels: module, core_review, support:core, new_contributor, docs, small_patch, docs_only, affects_2.14

#78657 _get_next_task_from_state should not mutate anyting outside of state
  changelogs/fragments/78612-rescue-block-ansible_play_hosts.yml
  lib/ansible/executor/play_iterator.py
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/blocks/78612.yml
  test/integration/targets/blocks/runme.sh
Labels: core_review, support:community, support:core, bug, affects_2.14

#78596 [backport][2.11] Fix pytest collection during test_host partial run
  test/units/inventory/__init__.py
Labels: backport, needs_triage, core_review, support:core, affects_2.11

#78669 Filter AWS test AMI selection on any Fedora-Cloud-Base image
  test/integration/targets/incidental_inventory_aws_ec2/playbooks/setup.yml
Labels: backport, test, community_review, needs_triage, support:community, affects_2.13

#78667 Guard urllib3 imports against all exceptions
  changelogs/fragments/78648-urllib3-import-exceptions.yml
  lib/ansible/module_utils/urls.py
Labels: core_review, support:core, bug, affects_2.14

#78671 [stable-2.11] Filter AWS test AMI selection on any Fedora-Cloud-Base image (#78669)
  test/integration/targets/incidental_inventory_aws_ec2/playbooks/setup.yml
Labels: needs_info, backport, test, needs_triage, needs_template, support:community, affects_2.11

#78670 [stable-2.12] Filter AWS test AMI selection on any Fedora-Cloud-Base image (#78669)
  test/integration/targets/incidental_inventory_aws_ec2/playbooks/setup.yml
Labels: needs_info, backport, test, needs_triage, needs_template, support:community, affects_2.12

#78628 [backport][2.12] Fail fast in stuck `ansible-galaxy-collection`
  test/integration/targets/ansible-galaxy-collection/library/setup_collections.py
Labels: backport, community_review, needs_triage, support:community, affects_2.12

#78462 [2.13] apt: include apt preferences (e.g. pinning) when selecting packages
  changelogs/fragments/77969-apt-preferences.yml
  lib/ansible/modules/apt.py
  test/integration/targets/apt/tasks/repo.yml
Labels: backport, module, needs_triage, core_review, support:core, bug, affects_2.13

#78530 [2.13] Fix apt making changes in check mode (#78496)
  changelogs/fragments/78496-fix-apt-check-mode.yml
  lib/ansible/modules/apt.py
  test/integration/targets/apt/tasks/apt.yml
  test/integration/targets/apt/tasks/repo.yml
Labels: backport, module, needs_triage, core_review, support:core, bug, affects_2.13
