Repository ansible/ansible, pull requests merged in 2022-01, with the labels that each got.

#76642 Fix typo in task name
  docs/docsite/rst/user_guide/complex_data_manipulation.rst
Labels: core_review, support:core, new_contributor, docs, small_patch, docs_only, affects_2.13

#76627 Fixed documentation: "[a] ini file" -> "an ini file"
  docs/docsite/rst/scenario_guides/guide_packet.rst
  lib/ansible/plugins/lookup/ini.py
Labels: core_review, support:core, new_contributor, docs, docs_only, affects_2.13

#76645 Fix wait_for integration test.
  test/integration/targets/wait_for/tasks/main.yml
Labels: core_review, support:core, affects_2.13

#76646 [stable-2.12] Fix wait_for integration test.
  test/integration/targets/wait_for/tasks/main.yml
Labels: backport, core_review, support:core, affects_2.12

#76647 [stable-2.11] Fix wait_for integration test.
  test/integration/targets/wait_for/tasks/main.yml
Labels: backport, core_review, support:core, affects_2.11

#76648 [stable-2.10] Fix wait_for integration test.
  test/integration/targets/wait_for/tasks/main.yml
Labels: backport, core_review, support:core, affects_2.10

#76649 [stable-2.9] Fix wait_for integration test.
  test/integration/targets/wait_for/tasks/main.yml
Labels: backport, core_review, support:core, affects_2.9

#76606 [2.12] Disable the _distutils_hack in newer setuptools (#76600)
  test/integration/targets/setup_paramiko/install-FreeBSD-python-3.yml
  test/integration/targets/setup_paramiko/install-RedHat-8-python-3.yml
Labels: backport, community_review, stale_ci, support:community, affects_2.12

#76605 [2.11] Disable the _distutils_hack in newer setuptools (#76600)
  test/integration/targets/setup_paramiko/install-FreeBSD-11-python-3.yml
  test/integration/targets/setup_paramiko/install-RedHat-8-python-3.yml
Labels: backport, community_review, stale_ci, support:community, affects_2.11

#76650 [2.10] Disable the _distutils_hack in newer setuptools (#76600)
  test/integration/targets/setup_paramiko/install-FreeBSD-11-python-3.yml
  test/integration/targets/setup_paramiko/install-RedHat-8-python-3.yml
Labels: backport, community_review, support:community, affects_2.10

#76604 [2.9] Disable the _distutils_hack in newer setuptools (#76600)
  test/integration/targets/setup_paramiko/install-FreeBSD-11-python-3.yml
  test/integration/targets/setup_paramiko/install-RedHat-8-python-3.yml
Labels: backport, community_review, stale_ci, support:community, affects_2.9

#76520 [stable-2.12] ansible-test - Use ansible-core for docs links.
  changelogs/fragments/ansible-test-links.yml
  test/lib/ansible_test/_internal/commands/integration/cloud/aws.py
  test/lib/ansible_test/_internal/commands/sanity/integration_aliases.py
  test/lib/ansible_test/_internal/test.py
  test/lib/ansible_test/_util/controller/sanity/code-smell/runtime-metadata.py
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py
Labels: backport, test, core_review, support:core, bug, affects_2.12

#76510 [stable-2.12] ansible-test - Hide ansible._vendor in import test
  changelogs/fragments/ansible-test-sanity-vendoring.yml
  test/integration/targets/ansible-test/aliases
  test/integration/targets/ansible-test/ansible_collections/ns/col/plugins/lookup/vendor1.py
  test/integration/targets/ansible-test/ansible_collections/ns/col/plugins/lookup/vendor2.py
  test/integration/targets/ansible-test/collection-tests/sanity-vendor.sh
  test/lib/ansible_test/_util/target/sanity/import/importer.py
Labels: backport, test, core_review, support:community, support:core, bug, affects_2.12

#76538 [stable-2.12] ansible-test - Fix delegation from install.
  changelogs/fragments/ansible-test-delegation-pythonpath.yml
  test/lib/ansible_test/_internal/delegation.py
Labels: backport, test, core_review, support:core, bug, affects_2.12

#76624 facts - Set correct OS family for EuroLinux
  changelogs/fragments/support_eurolinux.yml
  lib/ansible/module_utils/facts/system/distribution.py
  lib/ansible/modules/hostname.py
  test/units/module_utils/facts/system/distribution/fixtures/eurolinux_8.5.json
Labels: module, needs_triage, core_review, support:core, new_contributor, bug, affects_2.13

#76658 ansible-test - Fix type hints.
  changelogs/fragments/ansible-test-fix-type-hints.yml
  test/lib/ansible_test/_internal/cli/commands/integration/network.py
  test/lib/ansible_test/_internal/cli/completers.py
  test/lib/ansible_test/_internal/cli/environments.py
  test/lib/ansible_test/_internal/commands/coverage/__init__.py
  test/lib/ansible_test/_internal/commands/coverage/xml.py
  test/lib/ansible_test/_internal/containers.py
  test/lib/ansible_test/_internal/docker_util.py
  test/lib/ansible_test/_internal/provider/__init__.py
  test/lib/ansible_test/_internal/target.py
Labels: test, core_review, support:core, bug, affects_2.13

#76657 ansible-test - Fix plugin loading.
  changelogs/fragments/ansible-test-plugin-loading.yml
  test/lib/ansible_test/_internal/util.py
Labels: test, core_review, support:core, bug, affects_2.13

#76659 Add missing typing import for _distro.py.
  changelogs/fragments/distro-module_utils-typing.yml
  lib/ansible/module_utils/distro/_distro.py
  test/sanity/ignore.txt
Labels: test, core_review, support:core, bug, affects_2.13

#76579 ansible-galaxy - validate version for directories and collections in git repos
  changelogs/fragments/76579-fix-ansible-galaxy-collection-version-error.yml
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/dependency_resolution/providers.py
  test/integration/targets/ansible-galaxy-collection-scm/tasks/main.yml
  test/integration/targets/ansible-galaxy-collection-scm/tasks/setup_collection_bad_version.yml
  test/integration/targets/ansible-galaxy-collection-scm/tasks/test_invalid_version.yml
  test/integration/targets/ansible-galaxy-collection-scm/vars/main.yml
Labels: core_review, support:community, support:core, bug, affects_2.13

#76589 stat document 'version' return doc
  lib/ansible/modules/stat.py
  test/integration/targets/stat/meta/main.yml
  test/integration/targets/stat/tasks/main.yml
Labels: module, core_review, support:core, docs, small_patch, affects_2.13

#76592 user: Update logic to check if user exists in macOS
  changelogs/fragments/user_mac.yaml
  lib/ansible/modules/user.py
Labels: module, core_review, support:core, bug, affects_2.13

#76598 More auto info
  changelogs/fragments/auto_squeal.yml
  lib/ansible/plugins/inventory/auto.py
Labels: core_review, support:core, feature, affects_2.13

#76608 add systemd alias check
  changelogs/fragments/75538-systemd-alias-check.yml
  lib/ansible/modules/systemd.py
Labels: module, core_review, support:core, bug, affects_2.13

#76671 Remove obsolete incidental tests from matrix.
  .azure-pipelines/azure-pipelines.yml
Labels: core_review, support:core, bug, affects_2.13

#76619 hostname: add support for openEuler distro
  changelogs/fragments/openEuler_hostname.yml
  lib/ansible/modules/hostname.py
Labels: module, core_review, support:core, new_contributor, bug, affects_2.13

#76580 package_facts: Add pkg_info support for OpenBSD
  changelogs/fragments/76580-add-pkg_info-support-to-package_facts.yml
  lib/ansible/modules/package_facts.py
Labels: needs_revision, module, support:core, new_contributor, feature, affects_2.13

#76634 ansible_concat: return strings only unless eval
  changelogs/fragments/76610-empty-template-none.yml
  lib/ansible/template/native_helpers.py
  test/integration/targets/template/tasks/main.yml
  test/integration/targets/template/templates/empty_template.j2
Labels: core_review, support:core, bug, affects_2.13

#72405 Update local_mods in git.py to show destination of conflict
  changelogs/fragments/72405-git-module-local_mods-show-conflict-destination-directory.yml
  lib/ansible/modules/git.py
Labels: needs_revision, module, support:core, stale_review, new_contributor, docs, source_control, affects_2.11

#76573 Make all pipelining agree on ini entries
  lib/ansible/config/base.yml
  lib/ansible/plugins/connection/ssh.py
  lib/ansible/plugins/doc_fragments/connection_pipelining.py
Labels: needs_revision, support:core, bug, has_issue, affects_2.13

#76678 Avoid deprecated TestCase functions in unit tests.
  test/units/cli/test_vault.py
  test/units/compat/unittest.py
  test/units/module_utils/facts/test_collector.py
  test/units/parsing/test_dataloader.py
  test/units/parsing/vault/test_vault.py
  test/units/parsing/vault/test_vault_editor.py
  test/units/parsing/yaml/test_loader.py
  test/units/parsing/yaml/test_objects.py
  test/units/playbook/test_base.py
  test/units/playbook/test_conditional.py
  test/units/playbook/test_helpers.py
  test/units/plugins/action/test_action.py
  test/units/plugins/cache/test_cache.py
  test/units/plugins/callback/test_callback.py
  test/units/template/test_templar.py
Labels: needs_revision, support:core, affects_2.13

#76679 ansible-test - Use `--forked` instead of `--boxed`
  changelogs/fragments/ansible-test-pytest-forked.yml
  test/lib/ansible_test/_data/requirements/units.txt
  test/lib/ansible_test/_internal/commands/units/__init__.py
Labels: test, core_review, support:core, bug, affects_2.13

#76683 ansible-test - Set pytest rootdir option.
  changelogs/fragments/ansible-test-pytest-rootdir.yml
  test/lib/ansible_test/_internal/commands/units/__init__.py
Labels: test, core_review, support:core, bug, affects_2.13

#76670 Fix tests failing on pytest 7
  test/units/galaxy/test_role_install.py
Labels: test, core_review, support:core, bug, has_issue, affects_2.13

#76688 Address urllib behavior assumption in tests
  test/units/module_utils/urls/test_RedirectHandlerFactory.py
Labels: needs_triage, core_review, support:core, affects_2.13

#76424 ssh connection, handle 'fun' control paths
  changelogs/fragments/ssh_quote_cp.yml
  lib/ansible/plugins/connection/ssh.py
  test/integration/targets/connection_ssh/runme.sh
Labels: core_review, support:community, support:core, bug, affects_2.13

#76695 Limit pynacl for paramiko tests.
  test/integration/targets/setup_paramiko/constraints.txt
Labels: needs_revision, backport, needs_ci, support:community, affects_2.11

#76696 Limit pynacl for paramiko tests.
  test/integration/targets/setup_paramiko/constraints.txt
Labels: needs_revision, backport, needs_ci, support:community, affects_2.10

#76680 [stable-2.12] ansible-test - Use `--forked` instead of `--boxed`
  changelogs/fragments/ansible-test-pytest-forked.yml
  test/lib/ansible_test/_data/requirements/units.txt
  test/lib/ansible_test/_internal/commands/units/__init__.py
Labels: backport, test, core_review, support:core, bug, affects_2.12

#76698 Fix broken markup
  lib/ansible/plugins/doc_fragments/default_callback.py
Labels: core_review, support:core, docs, small_patch, affects_2.13

#76675 Use antsibull 0.40.1 for docsite build
  docs/docsite/known_good_reqs.txt
  docs/docsite/requirements.txt
  test/sanity/code-smell/docs-build.requirements.txt
Labels: needs_revision, test, needs_triage, support:core, docs, affects_2.13

#76053 enable module defaults for implicit gather_facts
  changelogs/fragments/deprecate_default_fact_path_setting.yml
  lib/ansible/config/base.yml
  lib/ansible/executor/play_iterator.py
  lib/ansible/playbook/play.py
Labels: core_review, support:core, feature, affects_2.13

#76699 fix typo
  lib/ansible/config/base.yml
Labels: needs_triage, core_review, support:core, bug, small_patch, affects_2.13

#75002 apt: add support for package version >=
  changelogs/fragments/75002-apt_min_version.yml
  lib/ansible/modules/apt.py
  test/integration/targets/apt/tasks/repo.yml
  test/integration/targets/setup_deb_repo/files/package_specs/stable/foo-1.0.0
  test/integration/targets/setup_deb_repo/files/package_specs/stable/foo-1.0.1
  test/integration/targets/setup_deb_repo/files/package_specs/stable/foobar-1.0.0
  test/integration/targets/setup_deb_repo/files/package_specs/stable/foobar-1.0.1
  test/integration/targets/setup_deb_repo/files/package_specs/testing/foo-2.0.0
  test/integration/targets/setup_deb_repo/files/package_specs/testing/foo-2.0.1
  test/integration/targets/setup_deb_repo/tasks/main.yml
Labels: module, core_review, stale_ci, support:community, support:core, new_contributor, feature, P3, affects_2.12

#76728 Add rocky to INTERPRETER_PYTHON_DISTRO_MAP
  lib/ansible/config/base.yml
Labels: core_review, support:core, new_contributor, bug, small_patch, affects_2.13

#76673 Fix C&P error
  docs/docsite/rst/roadmap/COLLECTIONS_6.rst
Labels: core_review, support:core, docs, small_patch, docs_only, affects_2.13

#76735 ansible-galaxy - fix the --ignore-certs flag for the implicit galaxy server
  changelogs/fragments/76735-ansible-galaxy-fix-ignore-certs.yaml
  lib/ansible/cli/galaxy.py
  test/units/galaxy/test_collection.py
Labels: needs_triage, core_review, support:core, bug, affects_2.13

#76739 ansible-test - Limit paramiko to < 2.9.0
  changelogs/fragments/ansible-test-paramiko-constraint.yaml
  test/lib/ansible_test/_data/requirements/constraints.txt
Labels: test, core_review, support:core, bug, affects_2.13

#76701 ansible-test - Update default containers.
  changelogs/fragments/ansible-test-default-container-update-5.4.0.yaml
  test/lib/ansible_test/_data/completion/docker.txt
Labels: test, core_review, support:core, bug, affects_2.13

#76736 remove outdated note on limitations of R() in module docs
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
Labels: needs_triage, core_review, support:core, docs, small_patch, docsite, docs_only, affects_2.13

#76743 Update dnf tests to reflect new behavior.
  test/integration/targets/dnf/tasks/cacheonly.yml
Labels: core_review, support:core, affects_2.13

#69776 Added AIX CA certs search paths
  changelogs/fragments/69776-add-aix-root-ca-certs-paths.yml
  lib/ansible/module_utils/urls.py
Labels: test, core_review, support:core, new_contributor, feature, affects_2.10

#63530 Expect upper case message 'levels' for galaxy publish results
  changelogs/fragments/galaxy-import-level-fix.yml
  lib/ansible/galaxy/api.py
  test/units/galaxy/test_api.py
Labels: python3, core_review, support:core, bug, affects_2.10

#76745 ansible-test - Add support for FreeBSD 12.3.
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-freebsd-12.3.yaml
  test/lib/ansible_test/_data/completion/remote.txt
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: test, core_review, support:core, feature, affects_2.13

#76747 ansible-test - Remove AIX provisioning support.
  changelogs/fragments/ansible-test-remove-aix-provisioning.yaml
  test/integration/targets/ansiballz_python/aliases
  test/integration/targets/apt/aliases
  test/integration/targets/apt_key/aliases
  test/integration/targets/apt_repository/aliases
  test/integration/targets/async/aliases
  test/integration/targets/become/aliases
  test/integration/targets/binary_modules/Makefile
  test/integration/targets/command_shell/aliases
  test/integration/targets/copy/aliases
  test/integration/targets/cron/aliases
  test/integration/targets/debconf/aliases
  test/integration/targets/dnf/aliases
  test/integration/targets/dpkg_selections/aliases
  test/integration/targets/file/aliases
  test/integration/targets/get_url/aliases
  test/integration/targets/getent/aliases
  test/integration/targets/git/aliases
  test/integration/targets/group/aliases
  test/integration/targets/hostname/aliases
  test/integration/targets/package/aliases
  test/integration/targets/package_facts/aliases
  test/integration/targets/pip/aliases
  test/integration/targets/remote_tmp/aliases
  test/integration/targets/rpm_key/aliases
  test/integration/targets/service/aliases
  test/integration/targets/service_facts/aliases
  test/integration/targets/subversion/aliases
  test/integration/targets/systemd/aliases
  test/integration/targets/unarchive/aliases
  test/integration/targets/unsafe_writes/aliases
  test/integration/targets/uri/aliases
  test/integration/targets/user/aliases
  test/integration/targets/yum/aliases
  test/integration/targets/yum_repository/aliases
  test/lib/ansible_test/_data/completion/remote.txt
  test/lib/ansible_test/_internal/connections.py
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: test, core_review, support:community, support:core, feature, affects_2.13

#76746 docs: Update porting guide for ansible 5.2.0
  docs/docsite/rst/porting_guides/porting_guide_5.rst
Labels: core_review, support:core, docs, docs_only, affects_2.13

#76751 gather_facts fails silently, when /proc/1/environ can't be read
  changelogs/fragments/76751-facts-check-datafile-before-close.yml
  lib/ansible/module_utils/facts/utils.py
Labels: needs_triage, core_review, support:core, new_contributor, bug, traceback, affects_2.13

#76752 ansible-test - Remove azure support for Sherlock.
  changelogs/fragments/ansible-test-azure-sherlock.yml
  test/lib/ansible_test/_internal/commands/integration/cloud/azure.py
  test/lib/ansible_test/config/cloud-config-azure.ini.template
Labels: test, core_review, support:core, feature, affects_2.13

#76677 Allow specifying specific python via shebang
  changelogs/fragments/restore_python_shebang_adherence.yml
  lib/ansible/executor/module_common.py
  test/units/executor/module_common/test_module_common.py
Labels: core_review, support:core, bug, affects_2.13

#76597 ansible-config avoid _terms and _input in --only-changed
  changelogs/fragments/config_fix_terms.yml
  lib/ansible/cli/config.py
Labels: core_review, support:core, bug, affects_2.13

#76691 prevent fact gathering from breaking on bad caps
  changelogs/fragments/runc_command_exception_toggle.yml
  lib/ansible/module_utils/basic.py
  lib/ansible/module_utils/facts/system/caps.py
Labels: needs_revision, support:core, bug, affects_2.13

#76754 include_vars initialize failed
  changelogs/fragments/include_vars_failed.yml
  lib/ansible/plugins/action/include_vars.py
Labels: needs_triage, core_review, support:core, bug, affects_2.13

#76765 ansible-test: fix typo in validate-modules
  changelogs/fragments/ansible-test-fix-typo-validate-modules.yaml
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/module_args.py
Labels: test, core_review, support:core, bug, affects_2.13

#76767 Fix unsafe handling of variable PYTHON_BIN in hacking/env-setup
  hacking/env-setup
Labels: core_review, support:core, new_contributor, bug, small_patch, affects_2.13

#76760 Change "fatal" to "error" in config docs to match actual behaviour
  lib/ansible/config/base.yml
Labels: core_review, support:core, docs, small_patch, affects_2.13

#76702 Fix documentation around the password parameter of `ansible.builtin.user`
  lib/ansible/modules/user.py
Labels: module, core_review, support:core, new_contributor, docs, small_patch, docs_only, affects_2.13

#76787 Compare FQCN also in lockstep logic
  changelogs/fragments/76782-fqcn-compare-lockstep-strategies.yml
  lib/ansible/plugins/callback/default.py
  test/integration/targets/callback_default/callback_default.out.fqcn_free.stdout
  test/integration/targets/callback_default/runme.sh
Labels: core_review, support:community, support:core, bug, affects_2.13

#76420 [stable-2.11] Fix unarchive ignore handling
  changelogs/fragments/76069-fix-unarchive-file-listing-in-zip.yaml
  lib/ansible/modules/unarchive.py
  test/integration/targets/unarchive/tasks/test_exclude.yml
Labels: backport, module, needs_triage, core_review, support:core, bug, has_issue, affects_2.11

#76418 [stable-2.12] Fix unarchive ignore handling
  changelogs/fragments/76069-fix-unarchive-file-listing-in-zip.yaml
  lib/ansible/modules/unarchive.py
  test/integration/targets/unarchive/tasks/test_exclude.yml
Labels: backport, module, needs_triage, core_review, support:core, has_issue, affects_2.12

#76440 better handling of sudo flag replacement (#76389)
  changelogs/fragments/fix_sudo_flag_mangling.yml
  lib/ansible/plugins/become/sudo.py
  test/units/plugins/become/test_sudo.py
Labels: backport, core_review, support:core, bug, affects_2.12

#76500 galaxy build - ignore existing MANIFEST and FILES (#76479) - 2.12
  changelogs/fragments/galaxy-build-files-ignore.yml
  lib/ansible/galaxy/collection/__init__.py
  test/units/galaxy/test_collection.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.12

#76499 galaxy build - ignore existing MANIFEST and FILES (#76479) - 2.11
  changelogs/fragments/galaxy-build-files-ignore.yml
  lib/ansible/galaxy/collection/__init__.py
  test/units/galaxy/test_collection.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.11

#76498 galaxy build - ignore existing MANIFEST and FILES (#76479) - 2.10
  changelogs/fragments/galaxy-build-files-ignore.yml
  lib/ansible/galaxy/collection.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.10

#76469 2.12: Properly set finalize for the new environment (#76435)
  changelogs/fragments/76379-set-finalize-on-new-env.yml
  lib/ansible/template/__init__.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.12

#76553 2.12: yum: avoid storing unnecessary cache data (#76345)
  changelogs/fragments/76336-yum-makecache-fast.yml
  lib/ansible/modules/yum.py
Labels: backport, module, needs_triage, core_review, support:core, bug, affects_2.12

#76558 2.12: Fix AttributeError when providing file via --conn-password-file (#76534)
  changelogs/fragments/76530-connection-password-file-tb-fix.yml
  lib/ansible/cli/__init__.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.12

#76574 [2.12] Use correct markup in documentation
  lib/ansible/modules/add_host.py
  lib/ansible/modules/apt.py
  lib/ansible/modules/dnf.py
  lib/ansible/modules/git.py
  lib/ansible/modules/iptables.py
  lib/ansible/modules/known_hosts.py
  lib/ansible/modules/package.py
  lib/ansible/modules/pip.py
  lib/ansible/modules/service.py
  lib/ansible/modules/set_fact.py
  lib/ansible/modules/stat.py
  lib/ansible/modules/systemd.py
  lib/ansible/modules/uri.py
  lib/ansible/modules/validate_argument_spec.py
  lib/ansible/modules/yum.py
  lib/ansible/plugins/callback/tree.py
  lib/ansible/plugins/connection/ssh.py
  lib/ansible/plugins/connection/winrm.py
  lib/ansible/plugins/doc_fragments/default_callback.py
  lib/ansible/plugins/doc_fragments/shell_common.py
  lib/ansible/plugins/inventory/ini.py
  lib/ansible/plugins/lookup/inventory_hostnames.py
  lib/ansible/plugins/lookup/sequence.py
Labels: windows, backport, module, needs_triage, core_review, support:core, docs, affects_2.12

#76575 [2.11] Use correct markup in documentation
  lib/ansible/modules/apt.py
  lib/ansible/modules/dnf.py
  lib/ansible/modules/git.py
  lib/ansible/modules/iptables.py
  lib/ansible/modules/known_hosts.py
  lib/ansible/modules/package.py
  lib/ansible/modules/pip.py
  lib/ansible/modules/set_fact.py
  lib/ansible/modules/stat.py
  lib/ansible/modules/systemd.py
  lib/ansible/modules/uri.py
  lib/ansible/modules/validate_argument_spec.py
  lib/ansible/modules/yum.py
  lib/ansible/plugins/callback/tree.py
  lib/ansible/plugins/connection/ssh.py
  lib/ansible/plugins/connection/winrm.py
  lib/ansible/plugins/doc_fragments/default_callback.py
  lib/ansible/plugins/doc_fragments/shell_common.py
  lib/ansible/plugins/inventory/ini.py
  lib/ansible/plugins/lookup/inventory_hostnames.py
  lib/ansible/plugins/lookup/sequence.py
Labels: windows, backport, module, needs_triage, core_review, support:core, docs, affects_2.11

#76693 ssh connection, handle 'fun' control paths (#76424)
  changelogs/fragments/ssh_quote_cp.yml
  lib/ansible/plugins/connection/ssh.py
  test/integration/targets/connection_ssh/runme.sh
Labels: backport, needs_triage, core_review, support:community, support:core, bug, affects_2.12

#76794 Remove obsolete skip/windows test aliases.
  test/integration/targets/connection_windows_ssh/aliases
  test/integration/targets/incidental_win_lineinfile/aliases
Labels: test, community_review, support:community, affects_2.13

#76730 2.12: end_play: end the current play only (#76674)
  changelogs/fragments/76672-fix-end_play-multiple_plays.yml
  lib/ansible/executor/playbook_executor.py
  test/integration/targets/meta_tasks/runme.sh
  test/integration/targets/meta_tasks/test_end_play_multiple_plays.yml
Labels: backport, needs_triage, core_review, support:community, support:core, bug, affects_2.12

#76738 [2.12] ansible-galaxy - fix the --ignore-certs flag for the implicit galaxy server
  changelogs/fragments/76735-ansible-galaxy-fix-ignore-certs.yaml
  lib/ansible/cli/galaxy.py
  test/units/galaxy/test_collection.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.12

#76755 ssh connection avoid parsing own debug (#76732)
  changelogs/fragments/ssh_debug_noparse.yml
  lib/ansible/plugins/connection/ssh.py
  test/units/plugins/connection/test_ssh.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.12

#76694 ssh connection, handle 'fun' control paths (#76424)
  changelogs/fragments/ssh_quote_cp.yml
  lib/ansible/plugins/connection/ssh.py
  test/integration/targets/connection_ssh/runme.sh
Labels: backport, needs_triage, core_review, support:community, support:core, bug, affects_2.11

#76756 ssh connection avoid parsing own debug (#76732)
  changelogs/fragments/ssh_debug_noparse.yml
  lib/ansible/plugins/connection/ssh.py
  test/units/plugins/connection/test_ssh.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.11

#76784 include_vars initialize failed (#76754)
  changelogs/fragments/include_vars_failed.yml
  lib/ansible/plugins/action/include_vars.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.12

#76785 include_vars initialize failed (#76754)
  changelogs/fragments/include_vars_failed.yml
  lib/ansible/plugins/action/include_vars.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.11

#76791 [stable-2.12] Compare FQCN also in lockstep logic. Fixes #76782 (#76787)
  changelogs/fragments/76782-fqcn-compare-lockstep-strategies.yml
  lib/ansible/plugins/callback/default.py
  test/integration/targets/callback_default/callback_default.out.fqcn_free.stdout
  test/integration/targets/callback_default/runme.sh
Labels: backport, needs_triage, core_review, support:community, support:core, affects_2.12

#76669 EOL Ansible 4 docs
  docs/docsite/sphinx_conf/ansible_conf.py
Labels: backport, needs_triage, core_review, stale_ci, support:core, docs, small_patch, affects_2.11, docs_only

#76770 Parameterize disable_lookups
  changelogs/fragments/76769-inventory-constructable-disable-lookups.yml
  lib/ansible/plugins/inventory/__init__.py
Labels: needs_revision, support:core, bug, affects_2.13

#76797 [stable-2.11] Compare FQCN also in lockstep logic. Fixes #76782 (#76787)
  changelogs/fragments/76782-fqcn-compare-lockstep-strategies.yml
  lib/ansible/plugins/callback/default.py
  test/integration/targets/callback_default/callback_default.out.fqcn_free.stdout
  test/integration/targets/callback_default/runme.sh
Labels: backport, needs_triage, core_review, support:community, support:core, affects_2.11

#75819 bacwards compat doc frag
  changelogs/fragments/aca_bcc.yml
  lib/ansible/plugins/doc_fragments/action_common_attributes.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.11

#75820 bacwards compat doc frag
  changelogs/fragments/aca_bcc.yml
  lib/ansible/plugins/doc_fragments/action_common_attributes.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.10

#75821 bacwards compat doc frag
  changelogs/fragments/aca_bcc.yml
  lib/ansible/plugins/doc_fragments/action_common_attributes.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.9

#76018 service_facts, now more accurate on systemd (#75326)
  changelogs/fragments/service_facts_systemd_improve.yml
  lib/ansible/modules/service_facts.py
Labels: backport, module, needs_triage, core_review, support:core, bug, has_issue, affects_2.11

#76763 ansible-config avoid _terms and _input in --only-changed (#76597)
  changelogs/fragments/config_fix_terms.yml
  lib/ansible/cli/config.py
Labels: backport, needs_triage, core_review, support:core, bug, affects_2.12

#76800 Do not require SystemdStrategy subclasses for every distro
  changelogs/fragments/76792-hostname-all-systemd.yml
  lib/ansible/modules/hostname.py
Labels: module, core_review, support:core, bug, affects_2.13

#76806 Attempt 2: Catch errors getting filters and tests
  changelogs/fragments/74127-bad-filter-2.yml
  lib/ansible/template/__init__.py
  test/integration/targets/jinja_plugins/collections/ansible_collections/foo/bar/plugins/filter/bad_collection_filter2.py
  test/integration/targets/jinja_plugins/tasks/main.yml
Labels: new_plugin, core_review, support:community, support:core, bug, traceback, affects_2.13

#76809 [stable-2.12] Attempt 2: Catch errors getting filters and tests (#76806).
  changelogs/fragments/74127-bad-filter-2.yml
  lib/ansible/template/__init__.py
  test/integration/targets/jinja_plugins/collections/ansible_collections/foo/bar/plugins/filter/bad_collection_filter2.py
  test/integration/targets/jinja_plugins/tasks/main.yml
Labels: needs_info, backport, needs_triage, needs_template, support:community, support:core, affects_2.12

#76807 Disable Tower tests and remove from test matrix.
  .azure-pipelines/azure-pipelines.yml
  test/integration/targets/tower_credential/aliases
  test/integration/targets/tower_credential_type/aliases
  test/integration/targets/tower_group/aliases
  test/integration/targets/tower_host/aliases
  test/integration/targets/tower_inventory/aliases
  test/integration/targets/tower_inventory_source/aliases
  test/integration/targets/tower_job_cancel/aliases
  test/integration/targets/tower_job_launch/aliases
  test/integration/targets/tower_job_list/aliases
  test/integration/targets/tower_job_template/aliases
  test/integration/targets/tower_job_wait/aliases
  test/integration/targets/tower_label/aliases
  test/integration/targets/tower_notification/aliases
  test/integration/targets/tower_organization/aliases
  test/integration/targets/tower_project/aliases
  test/integration/targets/tower_receive/aliases
  test/integration/targets/tower_role/aliases
  test/integration/targets/tower_send/aliases
  test/integration/targets/tower_settings/aliases
  test/integration/targets/tower_team/aliases
  test/integration/targets/tower_user/aliases
  test/integration/targets/tower_workflow_launch/aliases
  test/integration/targets/tower_workflow_template/aliases
Labels: backport, core_review, support:community, support:core, tower, web_infrastructure, affects_2.9

#76808 [stable-2.12] Do not require SystemdStrategy subclasses for every distro (#76800).
  changelogs/fragments/76792-hostname-all-systemd.yml
  lib/ansible/modules/hostname.py
Labels: needs_info, backport, module, needs_triage, needs_template, support:core, affects_2.12

#76282 Attach concat func to an environment class
  changelogs/fragments/environment-concat.yml
  lib/ansible/plugins/action/template.py
  lib/ansible/plugins/lookup/template.py
  lib/ansible/template/__init__.py
  lib/ansible/template/native_helpers.py
Labels: core_review, support:core, feature, native_jinja, affects_2.13

#76375 Module Logging with WSL2
  changelogs/fragments/76375-fix-module-logging-WSL2.yml
  lib/ansible/module_utils/basic.py
Labels: core_review, support:core, new_contributor, bug, has_issue, affects_2.13

#76815 Fallback to os family for interpreter discovery distro map
  changelogs/fragments/75560-interp-discovery-family-fallback.yml
  lib/ansible/config/base.yml
  lib/ansible/executor/interpreter_discovery.py
Labels: core_review, support:core, bug, affects_2.13

#76783 Resolve perf issue with async callback events
  changelogs/fragments/76729-async-callback-perf.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/plugins/strategy/__init__.py
Labels: core_review, support:core, bug, affects_2.13

#75158 Use explicit keyword for plugin config
  lib/ansible/cli/doc.py
  lib/ansible/config/manager.py
  lib/ansible/plugins/become/runas.py
  lib/ansible/plugins/become/su.py
  lib/ansible/plugins/become/sudo.py
  lib/ansible/plugins/connection/paramiko_ssh.py
  lib/ansible/plugins/connection/psrp.py
  lib/ansible/plugins/connection/ssh.py
  lib/ansible/plugins/connection/winrm.py
  lib/ansible/plugins/doc_fragments/shell_common.py
  lib/ansible/plugins/doc_fragments/shell_windows.py
Labels: windows, core_review, support:core, bug, has_issue, affects_2.12

#76569 config, moved 'choices info to keys
  lib/ansible/config/base.yml
  lib/ansible/config/manager.py
Labels: needs_revision, needs_ci, support:core, docs, affects_2.13

#76816 [stable-2.12] Resolve perf issue with async callback events (#76783)
  changelogs/fragments/76729-async-callback-perf.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/plugins/strategy/__init__.py
Labels: backport, needs_triage, core_review, support:core, affects_2.12

#76822 doc_fragments/files.py: fix "objecs" typo
  lib/ansible/plugins/doc_fragments/files.py
Labels: core_review, support:core, docs, small_patch, affects_2.13

#76829 New release v2.10.17rc1
  changelogs/CHANGELOG-v2.10.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.10.17rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, core_review, support:core, affects_2.10

#76830 New release v2.11.8rc1
  changelogs/CHANGELOG-v2.11.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.11.8rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, core_review, support:core, affects_2.11

#76831 New release v2.12.2rc1
  changelogs/CHANGELOG-v2.12.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.12.2rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, core_review, support:core, affects_2.12

#76832 Update Ansible release version to v2.10.17rc1.post0.
  lib/ansible/release.py
Labels: backport, core_review, support:core, small_patch, affects_2.10

#76833 Update Ansible release version to v2.11.8rc1.post0.
  lib/ansible/release.py
Labels: backport, core_review, support:core, small_patch, affects_2.11

#76834 Update Ansible release version to v2.12.2rc1.post0.
  lib/ansible/release.py
Labels: backport, core_review, support:core, small_patch, affects_2.12

#76378 iptables: chains creation and deletion
  changelogs/fragments/76378-iptables-chain-management.yml
  lib/ansible/modules/iptables.py
  test/integration/targets/iptables/aliases
  test/integration/targets/iptables/tasks/chain_management.yml
  test/integration/targets/iptables/tasks/main.yml
  test/integration/targets/iptables/vars/alpine.yml
  test/integration/targets/iptables/vars/centos.yml
  test/integration/targets/iptables/vars/default.yml
  test/integration/targets/iptables/vars/fedora.yml
  test/integration/targets/iptables/vars/redhat.yml
  test/integration/targets/iptables/vars/suse.yml
  test/units/modules/test_iptables.py
Labels: module, core_review, stale_ci, support:core, new_contributor, feature, affects_2.13

#76817 remove ansibot from collection docs
  docs/docsite/rst/community/collection_development_process.rst
Labels: needs_triage, core_review, support:core, docs, docsite, docs_only, affects_2.13

#75390 user module password expiration fixes
  changelogs/fragments/75017-user-password-expiry.yml
  lib/ansible/modules/user.py
  test/integration/targets/user/tasks/main.yml
  test/integration/targets/user/tasks/test_expires_min_max.yml
Labels: needs_revision, module, support:core, new_contributor, bug, affects_2.13

#76818 add core roadmaps to ansible docs
  docs/docsite/rst/ansible_index.rst
  docs/docsite/sphinx_conf/ansible_conf.py
Labels: shipit, needs_triage, support:core, docs, docs_only, affects_2.13

#76801 Mention ansible-core 2.11 RPM package in Ansible Core Installation Guide
  docs/docsite/rst/installation_guide/intro_installation.rst
Labels: core_review, support:core, new_contributor, docs, docs_only, affects_2.13

#76852 ansible-test - Defer loading of completion entries.
  changelogs/fragments/ansible-test-unsupported-directory-traceback.yaml
  test/integration/targets/ansible-test/collection-tests/unsupported-directory.sh
  test/lib/ansible_test/_internal/cli/compat.py
  test/lib/ansible_test/_internal/cli/environments.py
  test/lib/ansible_test/_internal/cli/parsers/helpers.py
  test/lib/ansible_test/_internal/cli/parsers/host_config_parsers.py
  test/lib/ansible_test/_internal/completion.py
  test/lib/ansible_test/_internal/host_configs.py
Labels: test, core_review, support:community, support:core, bug, affects_2.13

#76854 [stable-2.12] ansible-test - Defer loading of completion entries.
  changelogs/fragments/ansible-test-unsupported-directory-traceback.yaml
  test/integration/targets/ansible-test/collection-tests/unsupported-directory.sh
  test/lib/ansible_test/_internal/cli/compat.py
  test/lib/ansible_test/_internal/cli/environments.py
  test/lib/ansible_test/_internal/cli/parsers/helpers.py
  test/lib/ansible_test/_internal/cli/parsers/host_config_parsers.py
  test/lib/ansible_test/_internal/completion.py
  test/lib/ansible_test/_internal/host_configs.py
Labels: backport, test, core_review, support:community, support:core, bug, affects_2.12

#76841 Added restart to the argument condition for AIX
  changelogs/fragments/76840-added-restart-to-the-argument-condition-for-AIX.yml
  lib/ansible/modules/service.py
Labels: needs_revision, module, support:core, new_contributor, bug, affects_2.13

#76814 Fix task debugger to work with run_once using linear strategy
  changelogs/fragments/76049-task-debugger-run_once.yml
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/debugger/aliases
  test/integration/targets/debugger/inventory
  test/integration/targets/debugger/runme.sh
  test/integration/targets/debugger/test_run_once.py
  test/integration/targets/debugger/test_run_once_playbook.yml
Labels: core_review, support:community, support:core, bug, affects_2.13

#76839 update ansible.legacy docs
  docs/docsite/rst/dev_guide/developing_locally.rst
  docs/docsite/rst/dev_guide/migrating_roles.rst
Labels: needs_revision, needs_ci, support:core, docs, docsite, docs_only, affects_2.13

#76772 Roadmap for Ansible 6
  docs/docsite/rst/roadmap/COLLECTIONS_6.rst
Labels: WIP, support:core, docs, has_issue, docs_only, affects_2.13

#76845 Remove more whitelist and blacklist occurances
  lib/ansible/config/base.yml
  lib/ansible/inventory/manager.py
  lib/ansible/modules/iptables.py
  lib/ansible/plugins/inventory/auto.py
  lib/ansible/plugins/inventory/ini.py
  lib/ansible/plugins/inventory/script.py
  lib/ansible/plugins/inventory/yaml.py
  lib/ansible/plugins/vars/host_group_vars.py
  lib/ansible/utils/encrypt.py
  lib/ansible/vars/plugins.py
Labels: module, core_review, inventory, support:core, docs, affects_2.13

#76858 add quoted examples
  docs/docsite/rst/user_guide/playbooks_tests.rst
Labels: needs_triage, core_review, support:core, docs, docs_only, affects_2.13

#76846 Correct PowerShell Code Block Typo on developing_modules_general_windows.rst
  docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
Labels: needs_triage, core_review, support:core, new_contributor, docs, small_patch, docsite, docs_only, affects_2.13

#76861 ansible-test - Update outdated links in comments.
  test/lib/ansible_test/_data/requirements/sanity.pslint.ps1
  test/lib/ansible_test/_util/target/setup/quiet_pip.py
Labels: test, core_review, support:core, bug, affects_2.13

#65371 Replace file handling with context managers in files-modules and pars…
  lib/ansible/modules/blockinfile.py
  lib/ansible/parsing/vault/__init__.py
Labels: module, core_review, stale_ci, support:core, bug, small_patch, files, collection, affects_2.10

#76866 ansible-test - Improve help for unsupported cwd.
  changelogs/fragments/ansible-test-help-cwd.yml
  test/integration/targets/ansible-test/collection-tests/unsupported-directory.sh
  test/lib/ansible_test/_internal/__init__.py
  test/lib/ansible_test/_internal/cli/__init__.py
  test/lib/ansible_test/_internal/cli/environments.py
  test/lib/ansible_test/_internal/cli/epilog.py
  test/lib/ansible_test/_internal/data.py
  test/lib/ansible_test/_internal/provider/layout/__init__.py
  test/lib/ansible_test/_internal/provider/layout/unsupported.py
  test/lib/ansible_test/_internal/provider/source/unsupported.py
Labels: test, core_review, support:community, support:core, feature, affects_2.13

#76869 ansible-test - Validate collection ns and name.
  changelogs/fragments/ansible-test-collection-identifier.yml
  test/lib/ansible_test/_internal/data.py
  test/lib/ansible_test/_internal/provider/layout/collection.py
  test/lib/ansible_test/_internal/util.py
Labels: test, core_review, support:core, bug, affects_2.13

#76856 ansible-vault encrypt_string: fix --output to write into file
  changelogs/fragments/75101-ansible-vault-encrypt_string-output-file.yml
  lib/ansible/cli/vault.py
  test/integration/targets/ansible-vault/runme.sh
Labels: core_review, support:community, support:core, bug, affects_2.13

#53688 Track failures in the includes results to avoid special handling of include errors
  changelogs/fragments/50897-include_role-any_errors_fatal.yaml
  lib/ansible/playbook/included_file.py
  lib/ansible/plugins/strategy/__init__.py
  lib/ansible/plugins/strategy/free.py
  lib/ansible/plugins/strategy/linear.py
  test/integration/targets/any_errors_fatal/50897.yml
  test/integration/targets/any_errors_fatal/runme.sh
Labels: core_review, support:community, support:core, bug, affects_2.8, has_issue

#76170 updated metadata dump to do full docs dump
  lib/ansible/cli/doc.py
  setup.cfg
  test/integration/targets/ansible-doc/runme.sh
Labels: core_review, support:community, support:core, feature, has_issue, affects_2.13

#75287 fix block var inheritance
  changelogs/fragments/fix_block_var_inh.yml
  lib/ansible/playbook/block.py
  test/integration/targets/collections/collection_root_user/ansible_collections/testns/testcoll/playbooks/roles/non_coll_role/tasks/main.yml
  test/integration/targets/collections/collection_root_user/ansible_collections/testns/testcoll/playbooks/roles/non_coll_role_to_call/tasks/main.yml
  test/integration/targets/var_inheritance/aliases
  test/integration/targets/var_inheritance/tasks/main.yml
Labels: core_review, support:community, support:core, bug, has_issue, affects_2.12

#76564 Misc typo fixes in module_utils
  lib/ansible/module_utils/common/file.py
  lib/ansible/module_utils/csharp/Ansible.AccessToken.cs
  lib/ansible/module_utils/csharp/Ansible.Become.cs
  lib/ansible/module_utils/facts/hardware/linux.py
  lib/ansible/module_utils/powershell/Ansible.ModuleUtils.CommandUtil.psm1
  lib/ansible/module_utils/powershell/Ansible.ModuleUtils.SID.psm1
  lib/ansible/module_utils/powershell/Ansible.ModuleUtils.WebRequest.psm1
  lib/ansible/module_utils/service.py
  lib/ansible/module_utils/urls.py
Labels: needs_revision, windows, support:core, docs, affects_2.13

#76899 Remove centos8 from CI.
  .azure-pipelines/azure-pipelines.yml
Labels: backport, core_review, support:core, small_patch, affects_2.12

#76900 Remove centos8 from CI.
  .azure-pipelines/azure-pipelines.yml
Labels: backport, core_review, support:core, small_patch, affects_2.11

#76901 Remove centos8 from CI.
  .azure-pipelines/azure-pipelines.yml
Labels: backport, core_review, support:core, small_patch, affects_2.10

#76902 Remove centos8 from CI.
  .azure-pipelines/azure-pipelines.yml
Labels: backport, core_review, support:core, small_patch, affects_2.9

#76871 ansible-test - Use relative paths in junit output.
  changelogs/fragments/ansible-test-junit-relative-paths.yml
  lib/ansible/plugins/callback/junit.py
  test/lib/ansible_test/_internal/commands/integration/__init__.py
Labels: test, core_review, support:core, bug, has_issue, affects_2.13

#76892 New release v2.12.2
  changelogs/CHANGELOG-v2.12.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.12.2_summary.yaml
  lib/ansible/release.py
Labels: backport, core_review, support:core, affects_2.12

#76890 New release v2.10.17
  changelogs/CHANGELOG-v2.10.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.10.17_summary.yaml
  lib/ansible/release.py
Labels: backport, core_review, support:core, affects_2.10

#76891 New release v2.11.8
  changelogs/CHANGELOG-v2.11.rst
  changelogs/changelog.yaml
  changelogs/fragments/v2.11.8_summary.yaml
  lib/ansible/release.py
Labels: needs_revision, backport, needs_ci, support:core, affects_2.11

#76889 doc: fix Jinja2 doc link in templating playbook
  docs/docsite/rst/user_guide/playbooks_templating.rst
Labels: core_review, support:core, new_contributor, docs, small_patch, docs_only, affects_2.13

#76904 Update Ansible release version to v2.12.2.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, needs_ci, support:core, small_patch, affects_2.12

#76905 Update Ansible release version to v2.11.8.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, needs_ci, support:core, small_patch, affects_2.11

#76906 Update Ansible release version to v2.10.17.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, needs_ci, support:core, small_patch, affects_2.10
