Repository ansible/ansible, pull requests merged in 2023-10, with the labels that each got.

#81814 fixes spelling errors
  lib/ansible/modules/apt.py
  lib/ansible/modules/get_url.py
  lib/ansible/modules/pause.py
  lib/ansible/modules/yum.py
  lib/ansible/plugins/connection/winrm.py
  lib/ansible/plugins/filter/comment.yml
  lib/ansible/plugins/filter/extract.yml
Labels: module, needs_triage, stale_review

#81807 Add compat function for parsing Content-Disposition header
  changelogs/fragments/81806-py2-content-disposition.yml
  lib/ansible/module_utils/urls.py
  test/integration/targets/uri/tasks/main.yml
Labels: backport, stale_review, bug, has_issue

#81581 Fix stealth exceptions and blocking select() in daemonize() (#81064) - 2.15
  changelogs/fragments/81064-daemonize-fixes.yml
  changelogs/fragments/81584-daemonize-follow-up-fixes.yml
  lib/ansible/module_utils/service.py
Labels: backport, bug

#81799 ansible-galaxy fix scm dependency error (#81599)
  changelogs/fragments/galaxy_dep_res_msgs.yml
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
Labels: backport, needs_triage, bug

#81829 Fix reporting role as not found when remote_data is None
  changelogs/fragments/fix-ansible-galaxy-info-no-role-found.yml
  lib/ansible/cli/galaxy.py
Labels: needs_revision, bug

#81833 Install upgraded crun from edge
  test/integration/targets/ansible-test-container/runme.py
Labels: test, stale_review

#81835 [2.13] Fix reporting role as not found when remote_data is None (#81829)
  changelogs/fragments/fix-ansible-galaxy-info-no-role-found.yml
  lib/ansible/cli/galaxy.py
Labels: needs_revision, backport, needs_triage, bug

#81836 [2.14] Fix reporting role as not found when remote_data is None (#81829)
  changelogs/fragments/fix-ansible-galaxy-info-no-role-found.yml
  lib/ansible/cli/galaxy.py
Labels: backport, needs_triage, bug

#81834 [2.12] Fix reporting role as not found when remote_data is None (#81829)
  changelogs/fragments/fix-ansible-galaxy-info-no-role-found.yml
  lib/ansible/cli/galaxy.py
Labels: backport, needs_triage, bug

#81772 Import role public
  changelogs/fragments/import_role_goes_public.yml
  lib/ansible/config/base.yml
  lib/ansible/modules/import_role.py
  lib/ansible/playbook/role_include.py
  lib/ansible/vars/manager.py
  test/integration/targets/include_import/public_exposure/no_bleeding.yml
  test/integration/targets/include_import/public_exposure/playbook.yml
  test/integration/targets/roles/vars_scope.yml
Labels: module, stale_review, bug, feature

#81837 [2.15] Fix reporting role as not found when remote_data is None (#81829)
  changelogs/fragments/fix-ansible-galaxy-info-no-role-found.yml
  lib/ansible/cli/galaxy.py
Labels: backport, needs_triage, bug

#81798 ansible-galaxy fix scm dependency error (#81599)
  changelogs/fragments/galaxy_dep_res_msgs.yml
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
Labels: backport, needs_triage, bug

#81720 Remove deprecated JINJA2_NATIVE_WARNING configuration entry
  changelogs/fragments/81714-remove-deprecated-jinja2_native_warning.yml
  lib/ansible/config/base.yml
Labels: stale_review, feature, has_issue

#81838 [2.16] Fix reporting role as not found when remote_data is None (#81829)
  changelogs/fragments/fix-ansible-galaxy-info-no-role-found.yml
  lib/ansible/cli/galaxy.py
Labels: needs_revision, backport, needs_triage, bug

#81841 ansible-test - Improve compatibility with pylint 3
  test/lib/ansible_test/_util/controller/sanity/pylint/plugins/deprecated.py
  test/lib/ansible_test/_util/controller/sanity/pylint/plugins/string_format.py
  test/lib/ansible_test/_util/controller/sanity/pylint/plugins/unwanted.py
Labels: test

#81844 Bump `coverage.py` to v7.3.2 in `ansible-test`
  changelogs/fragments/ansible-test-coverage-update.yml
  test/lib/ansible_test/_data/requirements/ansible-test.txt
  test/lib/ansible_test/_internal/coverage_util.py
Labels: test

#81828 [stable-2.15] Add compat function for parsing Content-Disposition header (#81807)
  changelogs/fragments/81806-py2-content-disposition.yml
  lib/ansible/module_utils/urls.py
  test/integration/targets/uri/tasks/main.yml
Labels: needs_revision, backport, needs_triage

#81845 [backport][stable-2.16] Bump `coverage.py` to v7.3.2 in `ansible-test`
  changelogs/fragments/ansible-test-coverage-update.yml
  test/lib/ansible_test/_data/requirements/ansible-test.txt
  test/lib/ansible_test/_internal/coverage_util.py
Labels: backport, test

#81843 Bump sanity test requirements for 3.12
  lib/ansible/module_utils/urls.py
  test/lib/ansible_test/_data/requirements/sanity.ansible-doc.txt
  test/lib/ansible_test/_data/requirements/sanity.changelog.txt
  test/lib/ansible_test/_data/requirements/sanity.mypy.txt
  test/sanity/code-smell/package-data.requirements.txt
  test/sanity/code-smell/pymarkdown.requirements.txt
  test/sanity/code-smell/update-bundled.requirements.txt
Labels: test

#81848 [backport/2.16] Bump sanity test requirements for 3.12
  lib/ansible/module_utils/urls.py
  test/lib/ansible_test/_data/requirements/sanity.ansible-doc.txt
  test/lib/ansible_test/_data/requirements/sanity.changelog.txt
  test/lib/ansible_test/_data/requirements/sanity.mypy.txt
  test/sanity/code-smell/package-data.requirements.txt
  test/sanity/code-smell/pymarkdown.requirements.txt
  test/sanity/code-smell/update-bundled.requirements.txt
Labels: backport, test

#81853 ansible-test - Invoke container sleep through env
  changelogs/fragments/ansible-test-container-sleep.yml
  test/lib/ansible_test/_internal/host_profiles.py
Labels: bug

#81747 [backport][stable-2.15] Always allow "no-other-choice" pre-release dependencies when resolving collection dependency tree
  changelogs/fragments/81606-ansible-galaxy-collection-pre-releases.yml
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/dependency_resolution/__init__.py
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  lib/ansible/galaxy/dependency_resolution/providers.py
  test/integration/targets/ansible-galaxy-collection/tasks/main.yml
  test/integration/targets/ansible-galaxy-collection/tasks/pinned_pre_releases_in_deptree.yml
  test/integration/targets/ansible-galaxy-collection/tasks/virtual_direct_requests.yml
  test/integration/targets/ansible-galaxy-collection/vars/main.yml
Labels: backport, needs_triage, bug

#81801 Fix dnf module crash for non-existent url
  changelogs/fragments/fix-dnf-install-missing-url.yml
  lib/ansible/module_utils/urls.py
  test/integration/targets/dnf/tasks/dnf.yml
Labels: bug

#81856 [stable-2.16] ansible-test - Invoke container sleep through env (#81853)
  changelogs/fragments/ansible-test-container-sleep.yml
  test/lib/ansible_test/_internal/host_profiles.py
Labels: needs_revision, backport, bug

#81857 [2.16] Update the test containers to include Python 3.12.0 final
  test/lib/ansible_test/_data/completion/docker.txt
Labels: backport, test

#81840 Restore import_role variable exporting behavior
  changelogs/fragments/import_role_goes_public.yml
  lib/ansible/playbook/role_include.py
  lib/ansible/vars/manager.py
  test/integration/targets/include_import/public_exposure/no_bleeding.yml
  test/integration/targets/include_import/public_exposure/playbook.yml
  test/integration/targets/roles/vars_scope.yml
Labels: backport, needs_triage, bug

#81859 [stable-2.16] ansible-test - Update distro containers (#81851)
  changelogs/fragments/ansible-test-distro-containers.yml
  test/lib/ansible_test/_data/completion/docker.txt
Labels: needs_revision, backport, feature

#81667 run_once: unnotify hosts on handlers that are not run
  changelogs/fragments/81666-handlers-run_once.yml
  lib/ansible/playbook/handler.py
  lib/ansible/plugins/strategy/__init__.py
  lib/ansible/plugins/strategy/free.py
  lib/ansible/plugins/strategy/linear.py
  test/integration/targets/handlers/runme.sh
  test/integration/targets/handlers/test_run_once.yml
Labels: bug, has_issue

#81755 Add family fallback for Amzn to register as RedHat
  changelogs/fragments/80882-Amazon-os-family-compat.yaml
  lib/ansible/module_utils/facts/system/distribution.py
Labels: bug, has_issue

#81624 Properly template tags in parent blocks
  changelogs/fragments/81053-templated-tags-inheritance.yml
  lib/ansible/playbook/taggable.py
  test/integration/targets/tags/runme.sh
  test/integration/targets/tags/test_template_parent_tags.yml
  test/units/playbook/test_taggable.py
Labels: stale_ci, bug, has_issue

#81864 New release v2.16.0b2
  changelogs/CHANGELOG-v2.16.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.16.0b2_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81863 New release v2.15.5rc1
  changelogs/CHANGELOG-v2.15.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.15.5rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81862 New release v2.14.11rc1
  changelogs/CHANGELOG-v2.14.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.14.11rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#79945 optimize host_group_vars and vars plugin loading
  changelogs/fragments/79945-host_group_vars-improvements.yml
  lib/ansible/inventory/group.py
  lib/ansible/inventory/host.py
  lib/ansible/plugins/loader.py
  lib/ansible/plugins/vars/__init__.py
  lib/ansible/plugins/vars/host_group_vars.py
  lib/ansible/utils/vars.py
  lib/ansible/vars/manager.py
  lib/ansible/vars/plugins.py
  test/integration/targets/old_style_vars_plugins/deprecation_warning/v2_vars_plugin.py
  test/integration/targets/old_style_vars_plugins/deprecation_warning/vars.py
  test/integration/targets/old_style_vars_plugins/runme.sh
Labels: needs_revision, inventory, bug, docs, docsite, affects_2.15

#81870 switch available_hosts to `frozenset` from `list` in ansible-inventory
  changelogs/fragments/inv_available_hosts_to_frozenset.yml
  lib/ansible/cli/inventory.py
Labels: needs_triage, bug

#81860 New release v2.13.13rc1
  changelogs/CHANGELOG-v2.13.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.13.13rc1_summary.yaml
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#81868 Update Ansible release version to v2.16.0b2.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81866 Drop Python 2.7 and Python 3.6 support
  .azure-pipelines/azure-pipelines.yml
  lib/ansible/config/base.yml
  lib/ansible/module_utils/basic.py
  lib/ansible/module_utils/common/_json_compat.py
  lib/ansible/module_utils/common/validation.py
  test/lib/ansible_test/_data/completion/docker.txt
  test/lib/ansible_test/_data/completion/remote.txt
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_internal/python_requirements.py
  test/lib/ansible_test/_util/controller/sanity/code-smell/future-import-boilerplate.json
  test/lib/ansible_test/_util/controller/sanity/code-smell/future-import-boilerplate.py
  test/lib/ansible_test/_util/controller/sanity/code-smell/metaclass-boilerplate.json
  test/lib/ansible_test/_util/controller/sanity/code-smell/metaclass-boilerplate.py
  test/lib/ansible_test/_util/target/cli/ansible_test_cli_stub.py
  test/lib/ansible_test/_util/target/common/constants.py
  test/lib/ansible_test/_util/target/injector/python.py
  test/lib/ansible_test/_util/target/pytest/plugins/ansible_forked.py
  test/lib/ansible_test/_util/target/pytest/plugins/ansible_pytest_collections.py
  test/lib/ansible_test/_util/target/pytest/plugins/ansible_pytest_coverage.py
  test/lib/ansible_test/_util/target/sanity/compile/compile.py
  test/lib/ansible_test/_util/target/sanity/import/importer.py
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
  test/lib/ansible_test/_util/target/setup/probe_cgroups.py
  test/lib/ansible_test/_util/target/setup/quiet_pip.py
  test/lib/ansible_test/_util/target/setup/requirements.py
  test/lib/ansible_test/_util/target/tools/virtualenvcheck.py
  test/lib/ansible_test/_util/target/tools/yamlcheck.py
  test/sanity/code-smell/ansible-test-future-boilerplate.py
  test/sanity/ignore.txt
  test/units/executor/module_common/test_recursive_finder.py
  test/units/module_utils/basic/test_imports.py
Labels: needs_revision, feature

#81871 Update Ansible release version to v2.14.11rc1.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#81869 Update Ansible release version to v2.15.5rc1.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#81877 Update Ansible release version to v2.13.13rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81883 Misc typo fixes in connection plugin
  lib/ansible/plugins/connection/__init__.py
Labels: needs_triage, bug

#81554 docs: update error message
  changelogs/fragments/81188_better_error.yml
  lib/ansible/module_utils/basic.py
Labels: needs_revision, has_issue

#81884 win_fetch - improve test time by not scanning Win dir
  test/integration/targets/win_fetch/tasks/main.yml
Labels: test

#81888 win_fetch - improve test time by not scanning Win dir (#81884) - 2.16
  test/integration/targets/win_fetch/tasks/main.yml
Labels: backport, test, needs_triage

#81887 win_fetch - improve test time by not scanning Win dir (#81884) - 2.15
  test/integration/targets/win_fetch/tasks/main.yml
Labels: backport, test, needs_triage

#81885 win_fetch - improve test time by not scanning Win dir (#81884) - 2.13
  test/integration/targets/win_fetch/tasks/main.yml
Labels: backport, test, needs_triage

#81903 Rename boilerplate sanity test
  test/sanity/code-smell/boilerplate.json
  test/sanity/code-smell/boilerplate.py
Labels: test

#81910 Add test coverage for winrm
  test/units/plugins/connection/test_winrm.py
Labels: test, needs_triage

#81923 Add more winrm coverage
  test/units/plugins/connection/test_winrm.py
Labels: test, needs_triage

#81917 ansible-galaxy - fix traceback error for invalid req file
  changelogs/fragments/81901-galaxy-requirements-format.yml
  lib/ansible/cli/galaxy.py
  test/units/cli/test_galaxy.py
Labels: needs_triage, bug, has_issue

#81934 New release v2.14.11
  changelogs/CHANGELOG-v2.14.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.14.11_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81696 Fix example in strftime filter plugin help
  lib/ansible/plugins/filter/strftime.yml
  lib/ansible/plugins/filter/to_datetime.yml
Labels: docs

#81875 [2.16] switch available_hosts to `frozenset` from `list` in ansible-inventory (#81870)
  changelogs/fragments/inv_available_hosts_to_frozenset.yml
  lib/ansible/cli/inventory.py
Labels: backport, needs_triage, bug

#81878 [2.16] optimize host_group_vars and vars plugin loading (#79945)
  changelogs/fragments/79945-host_group_vars-improvements.yml
  lib/ansible/inventory/group.py
  lib/ansible/inventory/host.py
  lib/ansible/plugins/loader.py
  lib/ansible/plugins/vars/__init__.py
  lib/ansible/plugins/vars/host_group_vars.py
  lib/ansible/utils/vars.py
  lib/ansible/vars/manager.py
  lib/ansible/vars/plugins.py
  test/integration/targets/old_style_vars_plugins/deprecation_warning/v2_vars_plugin.py
  test/integration/targets/old_style_vars_plugins/deprecation_warning/vars.py
  test/integration/targets/old_style_vars_plugins/runme.sh
Labels: backport, needs_triage, bug

#81914 Add test coverage for winrm (#81910) - 2.16
  test/units/plugins/connection/test_winrm.py
Labels: backport, test, needs_triage

#81936 Update Ansible release version to v2.15.5.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81924 ansible-galaxy - fix traceback error for invalid req file (#81917) - 2.16
  changelogs/fragments/81901-galaxy-requirements-format.yml
  lib/ansible/cli/galaxy.py
  test/units/cli/test_galaxy.py
Labels: backport, needs_triage, bug

#81921 [stable-2.16] Properly template tags in parent blocks (#81624)
  changelogs/fragments/81053-templated-tags-inheritance.yml
  lib/ansible/playbook/taggable.py
  test/integration/targets/tags/runme.sh
  test/integration/targets/tags/test_template_parent_tags.yml
  test/units/playbook/test_taggable.py
Labels: backport, needs_triage, bug

#81920 [stable-2.16] run_once: unnotify hosts on handlers that are not run (#81667)
  changelogs/fragments/81666-handlers-run_once.yml
  lib/ansible/playbook/handler.py
  lib/ansible/plugins/strategy/__init__.py
  lib/ansible/plugins/strategy/free.py
  lib/ansible/plugins/strategy/linear.py
  test/integration/targets/handlers/runme.sh
  test/integration/targets/handlers/test_run_once.yml
Labels: backport, needs_triage, bug

#81938 Update Ansible release version to v2.13.13.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#81953 Update default test container Python to 3.12 and support for PyLint 3.0.1
  changelogs/fragments/ansible-test-pylint-python-3.12.yml
  changelogs/fragments/ansible-test-pylint-update.yml
  changelogs/fragments/ansible-test-python-3.12-compat.yml
  changelogs/fragments/ansible-test-python-default.yml
  test/lib/ansible_test/_data/completion/docker.txt
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  test/lib/ansible_test/_util/controller/sanity/pylint/plugins/hide_unraisable.py
Labels: bug

#81955 [stable-2.16] Update default test container Python to 3.12 and support for PyLint 3.0.1
  changelogs/fragments/ansible-test-pylint-python-3.12.yml
  changelogs/fragments/ansible-test-pylint3-update.yml
  changelogs/fragments/ansible-test-python-3.12-compat.yml
  changelogs/fragments/ansible-test-python-default.yml
  test/lib/ansible_test/_data/completion/docker.txt
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  test/lib/ansible_test/_util/controller/sanity/pylint/plugins/hide_unraisable.py
Labels: backport, bug

#81956 [stable-2.16] ansible-test - Update base/default containers
  test/lib/ansible_test/_data/completion/docker.txt
Labels: backport, feature

#81957 ansible-test - Update base/default containers
  test/lib/ansible_test/_data/completion/docker.txt
Labels: feature

#81958 Remove obsolete unit test code
  test/sanity/ignore.txt
  test/units/module_utils/basic/test_exit_json.py
  test/units/module_utils/basic/test_get_available_hash_algorithms.py
  test/units/module_utils/basic/test_imports.py
  test/units/utils/collection_loader/fixtures/collections/ansible_collections/testns/testcoll/plugins/module_utils/my_util.py
  test/units/utils/collection_loader/test_collection_loader.py
Labels: test

#81960 Cleanup the hacking directory a bit
  hacking/ansible-profile.py
  hacking/test-module
Labels: feature

#81961 Remove obsolete compat code from integration tests
  test/integration/targets/get_url/files/testserver.py
  test/integration/targets/module_precedence/lib_no_extension/ping
  test/integration/targets/module_precedence/lib_with_extension/a.ini
  test/integration/targets/module_precedence/lib_with_extension/ping.ini
  test/integration/targets/module_precedence/roles_no_extension/foo/library/ping
  test/integration/targets/module_precedence/roles_with_extension/foo/library/a.ini
  test/integration/targets/module_precedence/roles_with_extension/foo/library/ping.ini
  test/integration/targets/setup_rpm_repo/library/create_repo.py
  test/integration/targets/uri/files/testserver.py
  test/integration/targets/wait_for/files/testserver.py
Labels: test

#81962 ansible-test - Clean up old Python 2 compat code
  test/lib/ansible_test/__init__.py
  test/lib/ansible_test/_internal/config.py
  test/lib/ansible_test/_internal/content_config.py
  test/lib/ansible_test/_internal/python_requirements.py
  test/lib/ansible_test/_internal/util_common.py
  test/lib/ansible_test/_internal/venv.py
  test/lib/ansible_test/_util/__init__.py
  test/lib/ansible_test/_util/controller/sanity/pylint/config/ansible-test-target.cfg
  test/lib/ansible_test/_util/controller/sanity/pylint/config/ansible-test.cfg
  test/lib/ansible_test/_util/controller/sanity/pylint/config/code-smell.cfg
  test/lib/ansible_test/_util/controller/sanity/pylint/plugins/deprecated.py
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py
  test/lib/ansible_test/_util/target/__init__.py
  test/lib/ansible_test/_util/target/common/__init__.py
  test/lib/ansible_test/_util/target/injector/python.py
  test/lib/ansible_test/_util/target/pytest/plugins/ansible_pytest_collections.py
  test/lib/ansible_test/_util/target/sanity/compile/compile.py
  test/lib/ansible_test/_util/target/sanity/import/importer.py
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: feature

#81964 Fix outdated S3 URLs
  test/integration/targets/dnf/vars/main.yml
  test/integration/targets/unarchive/tasks/test_download.yml
Labels: test

#81971 [stable-2.15] ansible-test - Use Azure for Windows 2012/2012-R2
  changelogs/fragments/ansible-test-windows-2012-and-2012-R2.yml
  test/lib/ansible_test/_data/completion/windows.txt
Labels: backport, feature

#81972 [stable-2.14] ansible-test - Use Azure for Windows 2012/2012-R2
  changelogs/fragments/ansible-test-windows-2012-and-2012-R2.yml
  test/lib/ansible_test/_data/completion/windows.txt
Labels: backport, feature

#81973 [stable-2.13] ansible-test - Use Azure for Windows 2012/2012-R2
  changelogs/fragments/ansible-test-windows-2012-and-2012-R2.yml
  test/lib/ansible_test/_data/completion/windows.txt
Labels: backport, feature

#81969 Fix typos in builtin modules
  lib/ansible/cli/doc.py
  lib/ansible/executor/task_executor.py
  lib/ansible/galaxy/dependency_resolution/providers.py
  lib/ansible/galaxy/dependency_resolution/reporters.py
  lib/ansible/module_utils/common/network.py
  lib/ansible/module_utils/facts/hardware/sunos.py
  lib/ansible/plugins/action/__init__.py
  lib/ansible/plugins/action/add_host.py
  lib/ansible/plugins/action/gather_facts.py
  lib/ansible/plugins/inventory/yaml.py
  lib/ansible/plugins/lookup/dict.py
  lib/ansible/plugins/lookup/first_found.py
  lib/ansible/plugins/shell/__init__.py
  lib/ansible/plugins/terminal/__init__.py
  lib/ansible/template/__init__.py
Labels: networking, needs_triage, bug

#81986 New release v2.16.0rc1
  changelogs/CHANGELOG-v2.16.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.16.0rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, feature

#81987 Update Ansible release version to v2.16.0rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81899 Add ignore invalid options override for mod wrapper
  changelogs/fragments/module-ignore-unknown-options.yml
  lib/ansible/module_utils/basic.py
  lib/ansible/module_utils/common/parameters.py
  lib/ansible/module_utils/csharp/Ansible.Basic.cs
  lib/ansible/plugins/action/__init__.py
  test/integration/targets/module_utils_Ansible.Basic/library/ansible_basic_tests.ps1
  test/units/module_utils/basic/test_argument_spec.py
Labels: needs_triage, feature

#81975 apt documentation fix
  lib/ansible/modules/apt.py
Labels: test, module, bug, feature

#82008 ansible-test - Remove special cryptography install
  changelogs/fragments/ansible-test-cryptography.yml
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_internal/python_requirements.py
  test/lib/ansible_test/_util/controller/tools/sslcheck.py
Labels: feature

#81978 Replace launchpad.net/api with api.launchpad.net @ apt_repository module
  changelogs/fragments/81978-launchpad-api-endpoint.yml
  lib/ansible/modules/apt_repository.py
Labels: module, needs_triage, bug

#82001 var names not matching in example.
  lib/ansible/plugins/test/superset.yml
Labels: needs_triage

#82029 Fix subversion integration test
  test/integration/targets/subversion/aliases
  test/integration/targets/subversion/roles/subversion/tasks/cleanup.yml
  test/integration/targets/subversion/roles/subversion/tasks/setup.yml
  test/integration/targets/subversion/vars/Alpine.yml
  test/support/integration/plugins/modules/htpasswd.py
Labels: test

#82040 ansible-test - Fix parsing of cgroup entries
  changelogs/fragments/ansible-test-cgroup-split.yml
  test/lib/ansible_test/_internal/cgroup.py
Labels: bug, has_issue

#82002 Fix Jinja plugin deduplication
  changelogs/fragments/j2_load_fix.yml
  lib/ansible/plugins/loader.py
  test/integration/targets/plugin_loader/file_collision/play.yml
  test/integration/targets/plugin_loader/file_collision/roles/r1/filter_plugins/custom.py
  test/integration/targets/plugin_loader/file_collision/roles/r1/filter_plugins/filter1.yml
  test/integration/targets/plugin_loader/file_collision/roles/r1/filter_plugins/filter3.yml
  test/integration/targets/plugin_loader/file_collision/roles/r2/filter_plugins/custom.py
  test/integration/targets/plugin_loader/file_collision/roles/r2/filter_plugins/filter2.yml
  test/integration/targets/plugin_loader/runme.sh
Labels: bug, has_issue

#82032 [stable-2.16] Fix subversion integration test (#82029)
  test/integration/targets/subversion/aliases
  test/integration/targets/subversion/roles/subversion/tasks/cleanup.yml
  test/integration/targets/subversion/roles/subversion/tasks/setup.yml
  test/integration/targets/subversion/vars/Alpine.yml
  test/support/integration/plugins/modules/htpasswd.py
Labels: backport, test

#82033 [stable-2.15] Fix subversion integration test (#82029)
  test/integration/targets/subversion/aliases
  test/integration/targets/subversion/roles/subversion/tasks/cleanup.yml
  test/integration/targets/subversion/roles/subversion/tasks/setup.yml
  test/integration/targets/subversion/vars/Alpine.yml
  test/support/integration/plugins/modules/htpasswd.py
Labels: backport, test

#82034 [stable-2.14] Fix subversion integration test (#82029)
  test/integration/targets/subversion/aliases
  test/integration/targets/subversion/roles/subversion/tasks/cleanup.yml
  test/integration/targets/subversion/roles/subversion/tasks/setup.yml
  test/integration/targets/subversion/vars/Alpine.yml
  test/support/integration/plugins/modules/htpasswd.py
Labels: backport, test

#82036 [stable-2.13] Fix subversion integration test (#82029)
  test/integration/targets/subversion/aliases
  test/integration/targets/subversion/roles/subversion/tasks/cleanup.yml
  test/integration/targets/subversion/roles/subversion/tasks/setup.yml
  test/integration/targets/subversion/vars/Alpine.yml
  test/support/integration/plugins/modules/htpasswd.py
Labels: backport, test

#82037 [stable-2.12] Fix subversion integration test (#82029)
  test/integration/targets/subversion/aliases
  test/integration/targets/subversion/roles/subversion/tasks/cleanup.yml
  test/integration/targets/subversion/roles/subversion/tasks/setup.yml
  test/integration/targets/subversion/vars/Alpine.yml
  test/support/integration/plugins/modules/htpasswd.py
Labels: backport, test

#82042 [stable-2.16] ansible-test - Fix parsing of cgroup entries
  changelogs/fragments/ansible-test-cgroup-split.yml
  test/lib/ansible_test/_internal/cgroup.py
Labels: backport, bug

#82043 [stable-2.15] ansible-test - Fix parsing of cgroup entries
  changelogs/fragments/ansible-test-cgroup-split.yml
  test/lib/ansible_test/_internal/cgroup.py
Labels: backport, bug

#82044 [stable-2.14] ansible-test - Fix parsing of cgroup entries
  changelogs/fragments/ansible-test-cgroup-split.yml
  test/lib/ansible_test/_internal/cgroup.py
Labels: backport, bug

#82045 [stable-2.13] ansible-test - Fix parsing of cgroup entries
  changelogs/fragments/ansible-test-cgroup-split.yml
  test/lib/ansible_test/_internal/cgroup.py
Labels: backport, bug

#82046 [stable-2.12] ansible-test - Fix parsing of cgroup entries
  changelogs/fragments/ansible-test-cgroup-split.yml
  test/lib/ansible_test/_internal/cgroup.py
Labels: backport, bug

#82060 remove args passthru on role runme tests that use grep
  test/integration/targets/roles/runme.sh
Labels: test, needs_triage

#82062 Simplify filter_encryption test
  test/integration/targets/filter_encryption/aliases
  test/integration/targets/filter_encryption/base.yml
  test/integration/targets/filter_encryption/runme.sh
  test/integration/targets/filter_encryption/tasks/main.yml
  test/integration/targets/filter_encryption/vars/main.yml
Labels: test, needs_triage, stale_review

#82012 Fix additional spelling errors in builtin modules
  lib/ansible/module_utils/powershell/Ansible.ModuleUtils.WebRequest.psm1
  lib/ansible/modules/copy.py
  lib/ansible/modules/getent.py
  lib/ansible/modules/yum_repository.py
  lib/ansible/playbook/handler.py
  lib/ansible/playbook/task.py
  lib/ansible/plugins/action/gather_facts.py
  lib/ansible/plugins/callback/default.py
  lib/ansible/plugins/connection/local.py
  lib/ansible/plugins/doc_fragments/action_core.py
  lib/ansible/plugins/doc_fragments/decrypt.py
  lib/ansible/plugins/filter/core.py
  lib/ansible/plugins/filter/from_yaml_all.yml
  lib/ansible/plugins/filter/human_readable.yml
  lib/ansible/plugins/filter/human_to_bytes.yml
  lib/ansible/plugins/filter/mandatory.yml
  lib/ansible/plugins/filter/mathstuff.py
  lib/ansible/plugins/filter/zip.yml
  lib/ansible/plugins/filter/zip_longest.yml
  lib/ansible/plugins/list.py
  lib/ansible/plugins/loader.py
  lib/ansible/plugins/lookup/csvfile.py
  lib/ansible/plugins/lookup/first_found.py
  lib/ansible/plugins/test/changed.yml
  lib/ansible/plugins/test/core.py
  lib/ansible/plugins/test/failed.yml
  lib/ansible/plugins/test/finished.yml
  lib/ansible/plugins/test/match.yml
  lib/ansible/plugins/test/reachable.yml
  lib/ansible/plugins/test/regex.yml
  lib/ansible/plugins/test/search.yml
  lib/ansible/plugins/test/skipped.yml
  lib/ansible/plugins/test/started.yml
  lib/ansible/plugins/test/success.yml
  lib/ansible/plugins/test/unreachable.yml
Labels: module, has_issue

#82009 ansible-pull now handles all secret files CLI options
  changelogs/fragments/pull_file_secrets.yml
  lib/ansible/cli/pull.py
  test/integration/targets/ansible-pull/pull-integration-test/conn_secret.yml
  test/integration/targets/ansible-pull/pull-integration-test/secret_connection_password
  test/integration/targets/ansible-pull/runme.sh
Labels: bug, has_issue

#82067 Fix contains example
  lib/ansible/plugins/test/contains.yml
Labels: needs_triage, bug, has_issue

#82031 Remove obsolete requirements from prepare_http_tests
  test/integration/targets/prepare_http_tests/tasks/kerberos.yml
Labels: test

#78680 any_errors_fatal fixes
  changelogs/fragments/any_errors_fatal-fixes.yml
  lib/ansible/plugins/strategy/linear.py
  test/integration/targets/any_errors_fatal/31543.yml
  test/integration/targets/any_errors_fatal/36308.yml
  test/integration/targets/any_errors_fatal/73246.yml
  test/integration/targets/any_errors_fatal/80981.yml
  test/integration/targets/any_errors_fatal/runme.sh
  test/integration/targets/handlers/force_handlers_blocks_81533-1.yml
  test/integration/targets/handlers/force_handlers_blocks_81533-2.yml
  test/integration/targets/handlers/runme.sh
Labels: bug, has_issue

#81809 Consolidate systemd detection logic
  changelogs/fragments/80975-systemd-detect.yml
  lib/ansible/module_utils/service.py
  lib/ansible/modules/service.py
  lib/ansible/modules/service_facts.py
Labels: module, bug, has_issue

#82071 don't warn about using a yescrypt hash as user password
  changelogs/fragments/user-accept-yescrypt-hash.yml
  lib/ansible/modules/user.py
  test/integration/targets/user/tasks/test_create_user_password.yml
Labels: module, needs_triage, bug

#82076 Legacy.psm1 - Add note telling people not to use function
  lib/ansible/module_utils/powershell/Ansible.ModuleUtils.Legacy.psm1
Labels: has_issue

#82078 Create a User with a Home Directory
  lib/ansible/modules/user.py
Labels: module, needs_triage

#82079 docs(template): use unambiguous syntax for mode
  lib/ansible/modules/template.py
Labels: module

#82083 Ignore testing data for gitleaks
  test/integration/targets/user/tasks/test_create_user_password.yml
Labels: test, needs_triage

#82054 Fix Jinja plugin deduplication (#82002)
  changelogs/fragments/j2_load_fix.yml
  lib/ansible/plugins/loader.py
  test/integration/targets/plugin_loader/file_collision/play.yml
  test/integration/targets/plugin_loader/file_collision/roles/r1/filter_plugins/custom.py
  test/integration/targets/plugin_loader/file_collision/roles/r1/filter_plugins/filter1.yml
  test/integration/targets/plugin_loader/file_collision/roles/r1/filter_plugins/filter3.yml
  test/integration/targets/plugin_loader/file_collision/roles/r2/filter_plugins/custom.py
  test/integration/targets/plugin_loader/file_collision/roles/r2/filter_plugins/filter2.yml
  test/integration/targets/plugin_loader/runme.sh
Labels: backport, needs_triage, bug

#81925 ansible-galaxy - fix traceback error for invalid req file (#81917) - 2.15
  changelogs/fragments/81901-galaxy-requirements-format.yml
  lib/ansible/cli/galaxy.py
  test/units/cli/test_galaxy.py
Labels: backport, needs_triage, bug

#81922 [stable-2.15] Properly template tags in parent blocks (#81624)
  changelogs/fragments/81053-templated-tags-inheritance.yml
  lib/ansible/playbook/taggable.py
  test/integration/targets/tags/runme.sh
  test/integration/targets/tags/test_template_parent_tags.yml
  test/units/playbook/test_taggable.py
Labels: backport, needs_triage, bug

#81919 [stable-2.15] run_once: unnotify hosts on handlers that are not run (#81667)
  changelogs/fragments/81666-handlers-run_once.yml
  lib/ansible/playbook/handler.py
  lib/ansible/plugins/strategy/__init__.py
  lib/ansible/plugins/strategy/free.py
  lib/ansible/plugins/strategy/linear.py
  test/integration/targets/handlers/runme.sh
  test/integration/targets/handlers/test_run_once.yml
Labels: backport, needs_triage, bug

#81913 Add test coverage for winrm (#81910) - 2.15
  test/units/plugins/connection/test_winrm.py
Labels: backport, test, needs_triage

#81876 [2.15] switch available_hosts to `frozenset` from `list` in ansible-inventory (#81870)
  changelogs/fragments/inv_available_hosts_to_frozenset.yml
  lib/ansible/cli/inventory.py
Labels: backport, needs_triage, bug

#81873 Restore import_role variable exporting behavior (#81840)
  changelogs/fragments/import_role_goes_public.yml
  lib/ansible/playbook/role_include.py
  lib/ansible/vars/manager.py
  test/integration/targets/include_import/public_exposure/no_bleeding.yml
  test/integration/targets/include_import/public_exposure/playbook.yml
  test/integration/targets/roles/vars_scope.yml
Labels: backport, needs_triage, bug

#82063 Add support for TLS 1.3 Post Handshake Auth
  changelogs/fragments/urls-tls13-post-handshake-auth.yml
  lib/ansible/module_utils/urls.py
Labels: feature, has_issue

#82059 corrected become same user config docs
  lib/ansible/config/base.yml
Labels: has_issue

#80017 FIX - Reboot - delete useless parameter async, not supported
  changelogs/fragments/fix-reboot-plugin.yml
  lib/ansible/plugins/action/reboot.py
Labels: needs_revision, ci_verified, stale_review, new_contributor, bug, has_issue, affects_2.15

#82092 New release v2.15.6rc1
  changelogs/CHANGELOG-v2.15.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.15.6rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#82093 Update Ansible release version to v2.15.6rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#82096 add pep668 note to pip module docs
  lib/ansible/modules/pip.py
Labels: module, needs_triage

#82097 pip - Add break_system_packages option
  lib/ansible/modules/pip.py
  test/integration/targets/pip/aliases
  test/integration/targets/pip/files/sample-project/pyproject.toml
  test/integration/targets/pip/files/sample-project/src/sample_project/__init__.py
  test/integration/targets/pip/tasks/break_system_packages.yml
  test/integration/targets/pip/tasks/main.yml
  test/integration/targets/pip/vars/main.yml
Labels: needs_revision, module, stale_review, feature

#82101 pip - Add module in venv example
  lib/ansible/modules/pip.py
Labels: module
