Repository ansible/ansible, pull requests merged in 2023-04, with the labels that each got.

#79847 Fix getting timeout for get mounts facts on Linux
  changelogs/fragments/79844-fix-timeout-mounts-linux.yml
  lib/ansible/module_utils/facts/hardware/linux.py
Labels: needs_revision, stale_review, new_contributor, bug, affects_2.15

#80385 Replace plain HTTP with HTTPS in URLs within COPYING
  COPYING
Labels: new_contributor, docs, docs_only, affects_2.15

#80395 New release v2.15.0b1
  changelogs/CHANGELOG-v2.15.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.15.0b1_summary.yaml
  lib/ansible/release.py
Labels: backport, feature, affects_2.15

#80396 Update Ansible release version to v2.15.0b1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature, small_patch, affects_2.15

#79931 Only use the selectors code path when we are prompt matching
  changelogs/fragments/run-command-selectors-prompt-only.yml
  lib/ansible/module_utils/basic.py
  test/units/module_utils/basic/test_run_command.py
Labels: bug, has_issue, affects_2.15

#80397 [2.15] Fetch signatures from galaxy after the dependency resolver runs (#80334)
  changelogs/fragments/80334-reduce-ansible-galaxy-api-calls.yml
  lib/ansible/galaxy/api.py
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  lib/ansible/galaxy/dependency_resolution/providers.py
  test/integration/targets/ansible-galaxy-collection/tasks/install.yml
Labels: backport, needs_triage, bug, affects_2.15

#80400 [stable-2.15] Only use the selectors code path when we are prompt matching (#79931)
  changelogs/fragments/run-command-selectors-prompt-only.yml
  lib/ansible/module_utils/basic.py
  test/units/module_utils/basic/test_run_command.py
Labels: needs_info, backport, needs_triage, affects_2.15

#80401 dnf5: use the logs API to determine transaction problems
  changelogs/fragments/dnf5-logs-api.yml
  lib/ansible/modules/dnf5.py
Labels: module, needs_triage, bug, affects_2.16

#80380 Correct bypass_host_loop attribute for group_by
  lib/ansible/modules/group_by.py
Labels: module, docs, small_patch, docs_only, affects_2.15

#80423 Extend bulk issue creator
  hacking/create-bulk-issues.py
  test/sanity/code-smell/package-data.py
Labels: test, feature, affects_2.16

#80407 Extend ansible-doc tests
  test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol/plugins/modules/randommodule.py
  test/integration/targets/ansible-doc/randommodule-text.output
  test/integration/targets/ansible-doc/randommodule.output
Labels: test, affects_2.16

#80406 Replace validate-modules's semantic markup parser with antsibull-docs-parser
  changelogs/fragments/80406-validate-modules-semantic-markup.yml
  test/integration/targets/ansible-test-sanity-validate-modules/ansible_collections/ns/col/plugins/modules/semantic_markup.py
  test/integration/targets/ansible-test-sanity-validate-modules/expected.txt
  test/lib/ansible_test/_data/requirements/sanity.validate-modules.in
  test/lib/ansible_test/_data/requirements/sanity.validate-modules.txt
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/schema.py
  test/units/ansible_test/test_validate_modules.py
Labels: test, bug, affects_2.16

#80431 [stable-2.15] Extend ansible-doc test with more classic markup. (#80407)
  test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol/plugins/modules/randommodule.py
  test/integration/targets/ansible-doc/randommodule-text.output
  test/integration/targets/ansible-doc/randommodule.output
Labels: backport, affects_2.15

#80358 📝 Document macOS user deletion over SSH
  docs/docsite/rst/reference_appendices/faq.rst
  lib/ansible/modules/user.py
Labels: module, docs, docs_only, affects_2.15

#80433 2.15: dnf5: use the logs API to determine transaction problems (#80401)
  changelogs/fragments/dnf5-logs-api.yml
  lib/ansible/modules/dnf5.py
Labels: backport, module, needs_triage, bug, affects_2.15

#80434 2.15: dnf5: fix module/pkg names in the failed respawn msg (#80402)
  changelogs/fragments/dnf5-fix-interpreter-fail-msg.yml
  lib/ansible/modules/dnf5.py
Labels: backport, module, needs_triage, bug, affects_2.15

#80446 ansible.builtin inferred by collection_name == None
  test/lib/ansible_test/_util/controller/sanity/pylint/plugins/deprecated.py
  test/sanity/ignore.txt
Labels: test, bug, affects_2.16

#80392 [Docs] communication.rst: Add a hint about adding Matrix shields to READMEs
  docs/docsite/rst/community/communication.rst
Labels: docs, small_patch, docsite, has_issue, docs_only, affects_2.16

#80391 Documentation changes for #80367 and #80270
  docs/docsite/rst/installation_guide/intro_installation.rst
  docs/docsite/rst/playbook_guide/playbooks_blocks.rst
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: new_contributor, docs, docs_only, affects_2.16

#80375 Update playbooks_templating.rst
  docs/docsite/rst/playbook_guide/playbooks_templating.rst
Labels: new_contributor, docs, docs_only, affects_2.15

#80315 Document how to run all tasks, even the ones with the never tag
  docs/docsite/rst/playbook_guide/playbooks_tags.rst
Labels: new_contributor, docs, small_patch, docs_only, affects_2.15

#80308 Add OpenSUSE to the distro's installation guide
  docs/docsite/rst/installation_guide/installation_distros.rst
Labels: new_contributor, docs, small_patch, has_issue, docs_only, affects_2.15

#80112 documents approaches to octal modes better
  lib/ansible/plugins/doc_fragments/files.py
Labels: docs, affects_2.15

#80297 Update password.py documentation
  lib/ansible/plugins/lookup/password.py
Labels: docs, docs_only, affects_2.15

#80454 Fix the parsing integration tests
  test/integration/targets/parsing/bad_parsing.yml
  test/integration/targets/parsing/parsing.yml
  test/integration/targets/parsing/roles/test_bad_parsing/tasks/main.yml
  test/integration/targets/parsing/roles/test_bad_parsing/tasks/scenario1.yml
  test/integration/targets/parsing/roles/test_bad_parsing/tasks/scenario2.yml
  test/integration/targets/parsing/roles/test_bad_parsing/tasks/scenario3.yml
  test/integration/targets/parsing/roles/test_bad_parsing/tasks/scenario4.yml
  test/integration/targets/parsing/roles/test_bad_parsing/vars/main.yml
  test/integration/targets/parsing/runme.sh
Labels: affects_2.16

#80432 [stable-2.15] Replace validate-modules's semantic markup parser with antsibull-docs-parser
  changelogs/fragments/80406-validate-modules-semantic-markup.yml
  test/integration/targets/ansible-test-sanity-validate-modules/ansible_collections/ns/col/plugins/modules/semantic_markup.py
  test/integration/targets/ansible-test-sanity-validate-modules/expected.txt
  test/lib/ansible_test/_data/requirements/sanity.validate-modules.in
  test/lib/ansible_test/_data/requirements/sanity.validate-modules.txt
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/schema.py
  test/units/ansible_test/test_validate_modules.py
Labels: backport, test, bug, affects_2.15

#80450 Fix missing unrendered sections in manpage generation
  docs/templates/cli_rst.j2
  docs/templates/man.j2
  hacking/build_library/build_ansible/command_plugins/generate_man.py
Labels: needs_triage, bug, docs, affects_2.16

#80464 Update P() semantic markup example
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
Labels: new_contributor, docs, small_patch, docsite, docs_only, affects_2.16

#80461 Fix typo in playbooks_keywords.rst.j2
  docs/templates/playbooks_keywords.rst.j2
Labels: new_contributor, docs, small_patch, docs_only, affects_2.16

#80466 ansible-test - Update default containers
  test/lib/ansible_test/_data/completion/docker.txt
Labels: backport, test, bug, affects_2.15

#80468 ansible-test - Update default containers
  test/lib/ansible_test/_data/completion/docker.txt
Labels: test, feature, affects_2.16

#80469 Update Ansible release version to v2.15.0b2.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature, small_patch, affects_2.15

#80132 Symboic modes with X or =[ugo] always use original mode
  changelogs/fragments/80128-symbolic-modes-X-use-computed.yml
  lib/ansible/module_utils/basic.py
  test/units/modules/test_copy.py
Labels: new_contributor, bug, affects_2.15

#80475 Templar: do not add dict to globals
  changelogs/fragments/templar-globals-dict.yml
  lib/ansible/template/__init__.py
Labels: needs_triage, feature, affects_2.16

#80448 Manage basic.selinux completely, instead of mocking potentially missing module
  test/units/module_utils/basic/test_selinux.py
Labels: affects_2.16

#80473 get_action_args_with_defaults: remove deprecated redirected_names arg
  changelogs/fragments/get_action_args_with_defaults-remove-deprecated-arg.yml
  lib/ansible/executor/module_common.py
  test/sanity/ignore.txt
Labels: test, needs_triage, feature, affects_2.16

#80477 Fix missing " in ansible_tips_tricks.rst for vaulted variables
  docs/docsite/rst/tips_tricks/ansible_tips_tricks.rst
Labels: needs_triage, new_contributor, docs, small_patch, docs_only, affects_2.16

#80482 ansible-test - Add support for argcomplete 3
  changelogs/fragments/ansible-test-argcomplete-3.yml
  test/lib/ansible_test/_internal/cli/argparsing/argcompletion.py
  test/lib/ansible_test/_util/controller/sanity/mypy/ansible-test.ini
Labels: test, bug, affects_2.16

#80484 [stable-2.15] ansible-test - Add support for argcomplete 3 (#80482)
  changelogs/fragments/ansible-test-argcomplete-3.yml
  test/lib/ansible_test/_internal/cli/argparsing/argcompletion.py
  test/lib/ansible_test/_util/controller/sanity/mypy/ansible-test.ini
Labels: backport, test, bug, affects_2.15

#80489 Remove obsolete pkg_resources usage
  hacking/ansible-profile
Labels: bug, affects_2.16

#79558 Last handler defined runs, fix for roles
  changelogs/fragments/73643-handlers-prevent-multiple-runs.yml
  lib/ansible/executor/play_iterator.py
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/handlers/roles/two_tasks_files_role/handlers/main.yml
  test/integration/targets/handlers/roles/two_tasks_files_role/tasks/main.yml
  test/integration/targets/handlers/roles/two_tasks_files_role/tasks/other.yml
  test/integration/targets/handlers/runme.sh
  test/integration/targets/handlers/test_include_role_handler_once.yml
Labels: bug, affects_2.15

#80495 2.15: Last handler defined runs, fix for roles (#79558)
  changelogs/fragments/73643-handlers-prevent-multiple-runs.yml
  lib/ansible/executor/play_iterator.py
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/handlers/roles/two_tasks_files_role/handlers/main.yml
  test/integration/targets/handlers/roles/two_tasks_files_role/tasks/main.yml
  test/integration/targets/handlers/roles/two_tasks_files_role/tasks/other.yml
  test/integration/targets/handlers/runme.sh
  test/integration/targets/handlers/test_include_role_handler_once.yml
Labels: backport, needs_triage, bug, affects_2.15

#80398 [2.14] Fetch signatures from galaxy after the dependency resolver runs (#80334)
  changelogs/fragments/80334-reduce-ansible-galaxy-api-calls.yml
  lib/ansible/galaxy/api.py
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  lib/ansible/galaxy/dependency_resolution/providers.py
  test/integration/targets/ansible-galaxy-collection/tasks/install.yml
Labels: backport, needs_triage, bug, affects_2.14

#80497 Fix unclosed files in unit tests
  test/units/cli/test_galaxy.py
  test/units/module_utils/facts/hardware/linux_data.py
  test/units/module_utils/facts/system/distribution/test_parse_distribution_file_ClearLinux.py
  test/units/module_utils/facts/system/distribution/test_parse_distribution_file_Slackware.py
  test/units/parsing/vault/test_vault_editor.py
Labels: affects_2.16

#80499 Fix unit tests returning values
  test/units/module_utils/facts/base.py
  test/units/module_utils/facts/test_collectors.py
Labels: needs_triage, affects_2.16

#80501 [stable-2.15] pep517 backend - Use correct import_module import (#80480)
  changelogs/fragments/pep517-backend-import-fix.yml
  packaging/pep517_backend/_backend.py
Labels: backport, bug, affects_2.15

#80502 [stable-2.14] pep517 backend - Use correct import_module import (#80480)
  changelogs/fragments/pep517-backend-import-fix.yml
  packaging/pep517_backend/_backend.py
Labels: backport, bug, affects_2.14

#80503 [stable-2.13] pep517 backend - Use correct import_module import (#80480)
  changelogs/fragments/pep517-backend-import-fix.yml
  packaging/pep517_backend/_backend.py
Labels: backport, bug, affects_2.13

#80498 Add Ansible community 8.0.0a1 porting guide
  docs/docsite/rst/porting_guides/porting_guide_8.rst
Labels: docs, docs_only, affects_2.16

#80507 --syntax-check is only applicable to ansible-playbook
  changelogs/fragments/80506-syntax-check-playbook-only.yml
  lib/ansible/cli/arguments/option_helpers.py
  lib/ansible/cli/playbook.py
Labels: needs_triage, bug, has_issue, affects_2.16

#80509 [stable-2.15] --syntax-check is only applicable to ansible-playbook. Fixes #80506 (#80507)
  changelogs/fragments/80506-syntax-check-playbook-only.yml
  lib/ansible/cli/arguments/option_helpers.py
  lib/ansible/cli/playbook.py
Labels: backport, needs_triage, affects_2.15

#80510 [stable-2.14] --syntax-check is only applicable to ansible-playbook. Fixes #80506 (#80507)
  changelogs/fragments/80506-syntax-check-playbook-only.yml
  lib/ansible/cli/arguments/option_helpers.py
  lib/ansible/cli/playbook.py
Labels: backport, needs_triage, affects_2.14

#80331 Improve Ansible.Basic.cs tempdir uniqueness (#80328) - 2.14
  changelogs/fragments/ansible-basic-tmpdir-uniqueness.yml
  lib/ansible/module_utils/csharp/Ansible.Basic.cs
Labels: windows, backport, needs_triage, bug, affects_2.14

#80324 Ansible.Basic - Improve temporary file cleanup process (#80293) - 2.14
  changelogs/fragments/win-temp-cleanup.yml
  lib/ansible/module_utils/csharp/Ansible.Basic.cs
  test/integration/targets/module_utils_Ansible.Basic/library/ansible_basic_tests.ps1
Labels: windows, backport, needs_triage, bug, affects_2.14

#80275 [stable-2.13] ansible-galaxy collection install retry improvements (#80180)
  changelogs/fragments/galaxy-improve-retries.yml
  lib/ansible/galaxy/api.py
  lib/ansible/galaxy/collection/concrete_artifact_manager.py
  lib/ansible/module_utils/api.py
Labels: backport, bug, has_issue, affects_2.13

#80511 Adds Ansible 8 Porting Guide to Index Page
  docs/docsite/rst/porting_guides/porting_guides.rst
Labels: docs, small_patch, docs_only, affects_2.16

#80476 Validate task attributes with first finalized attrs after loop
  changelogs/fragments/80476-fix-loop-task-post-validation.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/plugins/strategy/linear.py
Labels: bug, affects_2.16

#80460 feature: add support for symbolic links when passing "dir"
  changelogs/fragments/80460-add-symbolic-links-with-dir.yml
  lib/ansible/plugins/action/include_vars.py
  test/integration/targets/include_vars/tasks/main.yml
Labels: new_contributor, feature, has_issue, affects_2.16

#80521 Extend OpenBSDStrategy to also update current hostname.
  changelogs/fragments/80520-fix-current-hostname-openbsd.yml
  lib/ansible/modules/hostname.py
Labels: module, needs_triage, new_contributor, bug, affects_2.16

#80399 [2.13] Fetch signatures from galaxy after the dependency resolver runs (#80334)
  changelogs/fragments/80334-reduce-ansible-galaxy-api-calls.yml
  lib/ansible/galaxy/api.py
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  lib/ansible/galaxy/dependency_resolution/providers.py
  test/integration/targets/ansible-galaxy-collection/tasks/install.yml
Labels: backport, needs_triage, bug, affects_2.13

#80330 Improve Ansible.Basic.cs tempdir uniqueness (#80328) - 2.13
  changelogs/fragments/ansible-basic-tmpdir-uniqueness.yml
  lib/ansible/module_utils/csharp/Ansible.Basic.cs
Labels: windows, backport, needs_triage, stale_ci, bug, affects_2.13

#80325 Ansible.Basic - Improve temporary file cleanup process (#80293) - 2.13
  changelogs/fragments/win-temp-cleanup.yml
  lib/ansible/module_utils/csharp/Ansible.Basic.cs
  test/integration/targets/module_utils_Ansible.Basic/library/ansible_basic_tests.ps1
Labels: windows, backport, needs_triage, stale_ci, bug, affects_2.13

#80525 ansible-test - Replace pytest-forked
  changelogs/fragments/ansible-test-pytest-forked.yml
  test/integration/targets/ansible-test-units-assertions/runme.sh
  test/integration/targets/ansible-test-units-forked/aliases
  test/integration/targets/ansible-test-units-forked/ansible_collections/ns/col/tests/unit/plugins/modules/test_ansible_forked.py
  test/integration/targets/ansible-test-units-forked/runme.sh
  test/lib/ansible_test/_data/requirements/units.txt
  test/lib/ansible_test/_internal/commands/units/__init__.py
  test/lib/ansible_test/_util/controller/sanity/pylint/config/ansible-test-target.cfg
  test/lib/ansible_test/_util/target/pytest/plugins/ansible_forked.py
Labels: new_plugin, test, feature, affects_2.16

#80378 [2.14] fix using templated values for include/import role FA (#80320)
  changelogs/fragments/fix-templating-private-role-FA.yml
  lib/ansible/playbook/helpers.py
  lib/ansible/playbook/included_file.py
  lib/ansible/playbook/role_include.py
  test/integration/targets/include_import/roles/role_with_argspec/meta/argument_specs.yml
  test/integration/targets/include_import/roles/role_with_argspec/tasks/main.yml
  test/integration/targets/include_import/runme.sh
  test/integration/targets/include_import/tasks/test_templating_IncludeRole_FA.yml
Labels: backport, needs_triage, bug, has_issue, affects_2.14

#80310 password lookup, handle ident properly when saved (#80251)
  changelogs/fragments/password_lookup_file_fix.yml
  lib/ansible/plugins/lookup/password.py
  lib/ansible/utils/encrypt.py
  test/units/plugins/lookup/test_password.py
Labels: backport, needs_triage, bug, affects_2.14

#80312 password lookup, handle ident properly when saved (#80251)
  changelogs/fragments/password_lookup_file_fix.yml
  lib/ansible/plugins/lookup/password.py
  lib/ansible/utils/encrypt.py
  test/units/plugins/lookup/test_password.py
Labels: backport, needs_triage, bug, affects_2.13

#80535 New release v2.13.9rc1
  changelogs/CHANGELOG-v2.13.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.13.9rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature, affects_2.13

#80536 New release v2.14.5rc1
  changelogs/CHANGELOG-v2.14.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.14.5rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature, affects_2.14

#80537 New release v2.15.0b3
  changelogs/CHANGELOG-v2.15.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.15.0b3_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature, affects_2.15

#79110 strip trailing path separator from type=dir sources
  changelogs/fragments/a-g-col-install-directory-with-trailing-sep.yml
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  test/integration/targets/ansible-galaxy-collection/tasks/install.yml
Labels: shipit, bug, affects_2.15

#80538 Update Ansible release version to v2.13.9rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature, small_patch, affects_2.13

#80539 Update Ansible release version to v2.14.5rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature, small_patch, affects_2.14

#80541 Update Ansible release version to v2.15.0b3.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature, small_patch, affects_2.15

#80370 Implement checks, and backwards compat change, to move forward with UTF-8 only
  changelogs/fragments/80258-defensive-display-non-utf8.yml
  docs/docsite/rst/dev_guide/developing_modules_best_practices.rst
  lib/ansible/config/base.yml
  lib/ansible/module_utils/common/text/converters.py
  lib/ansible/modules/command.py
  lib/ansible/modules/expect.py
  lib/ansible/modules/raw.py
  lib/ansible/modules/script.py
  lib/ansible/modules/shell.py
  lib/ansible/plugins/action/__init__.py
  lib/ansible/utils/display.py
Labels: module, bug, docs, docsite, affects_2.15

#80528 Fix PolicyRcD.__exit__ docstring
  lib/ansible/modules/apt.py
Labels: module, needs_triage, new_contributor, docs, small_patch, docs_only, affects_2.16

#80547 Fix example in docs of validate_argument_spec.py
  lib/ansible/modules/validate_argument_spec.py
Labels: module, needs_triage, new_contributor, docs, small_patch, docs_only, affects_2.16

#80545 [stable-2.15] Implement checks, and backwards compat change, to move forward with UTF-8 only (#80370)
  changelogs/fragments/80258-defensive-display-non-utf8.yml
  docs/docsite/rst/dev_guide/developing_modules_best_practices.rst
  lib/ansible/config/base.yml
  lib/ansible/module_utils/common/text/converters.py
  lib/ansible/modules/command.py
  lib/ansible/modules/expect.py
  lib/ansible/modules/raw.py
  lib/ansible/modules/script.py
  lib/ansible/modules/shell.py
  lib/ansible/plugins/action/__init__.py
  lib/ansible/utils/display.py
Labels: backport, module, needs_triage, docs, docsite, affects_2.15

#80542 [2.15] argspec - fix validating type for required options that are None
  changelogs/fragments/79677-fix-argspec-type-check.yml
  lib/ansible/module_utils/common/parameters.py
  lib/ansible/module_utils/common/validation.py
  test/integration/targets/apt_repository/tasks/apt.yml
  test/integration/targets/roles_arg_spec/roles/c/meta/main.yml
  test/integration/targets/roles_arg_spec/test.yml
Labels: backport, needs_triage, bug, affects_2.15

#80540 [2.15] ansible-galaxy - fix installing dir sources with a trailing path separator
  changelogs/fragments/a-g-col-install-directory-with-trailing-sep.yml
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  test/integration/targets/ansible-galaxy-collection/tasks/install.yml
Labels: backport, needs_triage, bug, affects_2.15

#80493 Update tools and programs page as per community feedback
  docs/docsite/rst/community/other_tools_and_programs.rst
Labels: docs, docsite, docs_only, affects_2.16

#80555 ansible-test - Update pylint to 2.17.2
  changelogs/fragments/ansible-test-pylint-update.yml
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
Labels: test, bug, affects_2.16

#80557 [stable-2.15] ansible-test - Update pylint to 2.17.2 (#80555)
  changelogs/fragments/ansible-test-pylint-update.yml
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
Labels: backport, test, bug, affects_2.15

#80560 ansible-test - Update the default containers
  changelogs/fragments/ansible-test-default-container-update.yml
  test/lib/ansible_test/_data/completion/docker.txt
Labels: backport, test, feature, small_patch, affects_2.15

#80559 ansible-test - Update default containers
  changelogs/fragments/ansible-test-default-containers.yml
  test/lib/ansible_test/_data/completion/docker.txt
Labels: test, feature, affects_2.16

#80558 ansible-test - Remove deprecated features
  changelogs/fragments/ansible-test-deprecated-cleanup.yml
  test/integration/targets/ansible-test-cloud-foreman/aliases
  test/integration/targets/ansible-test-cloud-foreman/tasks/main.yml
  test/integration/targets/ansible-test-cloud-vcenter/aliases
  test/integration/targets/ansible-test-cloud-vcenter/tasks/main.yml
  test/lib/ansible_test/_internal/cli/environments.py
  test/lib/ansible_test/_internal/commands/integration/cloud/foreman.py
  test/lib/ansible_test/_internal/commands/integration/cloud/vcenter.py
  test/lib/ansible_test/_internal/config.py
  test/lib/ansible_test/_internal/delegation.py
Labels: test, feature, affects_2.16

#80573 Disable failing incidental_mongodb_parameter test
  test/integration/targets/incidental_mongodb_parameter/aliases
Labels: backport, test, affects_2.12

#80574 Disable failing mongodb tests
  test/integration/targets/mongodb_replicaset/aliases
  test/integration/targets/mongodb_shard/aliases
Labels: backport, mongodb, database, affects_2.9

#80576 Remove docs references to obsolete test plugins
  docs/docsite/rst/dev_guide/testing/sanity/integration-aliases.rst
Labels: docs, small_patch, docsite, docs_only, affects_2.16

#80554 uri module, fix example
  lib/ansible/modules/uri.py
Labels: module, docs, docs_only, affects_2.16

#80515 fix become yes/no to true/false
  docs/docsite/rst/network/dev_guide/developing_resource_modules_network.rst
  docs/docsite/rst/network/getting_started/network_differences.rst
  docs/docsite/rst/network/user_guide/network_debug_troubleshooting.rst
  docs/docsite/rst/network/user_guide/platform_cnos.rst
  docs/docsite/rst/network/user_guide/platform_dellos10.rst
  docs/docsite/rst/network/user_guide/platform_dellos6.rst
  docs/docsite/rst/network/user_guide/platform_dellos9.rst
  docs/docsite/rst/network/user_guide/platform_enos.rst
  docs/docsite/rst/network/user_guide/platform_eos.rst
  docs/docsite/rst/network/user_guide/platform_icx.rst
  docs/docsite/rst/network/user_guide/platform_ios.rst
  docs/docsite/rst/network/user_guide/platform_ironware.rst
  docs/docsite/rst/network/user_guide/platform_nxos.rst
  docs/docsite/rst/network/user_guide/platform_routeros.rst
  docs/docsite/rst/network/user_guide/platform_voss.rst
  docs/docsite/rst/playbook_guide/playbooks_privilege_escalation.rst
Labels: networking, docs, docsite, docs_only, affects_2.16

#80570 note in systemd that systemctl can change behaviour due to diff order…
  lib/ansible/modules/systemd_service.py
Labels: module, docs, small_patch, docs_only, affects_2.16

#80381 apt key and repository example security patch
  lib/ansible/modules/apt_key.py
  lib/ansible/modules/apt_repository.py
Labels: module, new_contributor, docs, docs_only, affects_2.15

#80470 Vars Plugin Documentation Improvement
  docs/docsite/rst/dev_guide/developing_plugins.rst
Labels: new_contributor, docs, docsite, docs_only, affects_2.16

#80579 Update DOCUMENTATION.yml
  examples/DOCUMENTATION.yml
Labels: docs, docs_only, affects_2.16

#80389 Add note guidelines for additional distributions
  docs/docsite/rst/installation_guide/installation_distros.rst
Labels: new_contributor, docs, docs_only, affects_2.15

#80587 Pin pyasn1 version in uri and unarchive tests
  test/integration/targets/unarchive/tasks/test_download.yml
  test/integration/targets/uri/tasks/main.yml
Labels: backport, affects_2.9

#80550 Use target of /usr/bin/dnf for dnf version detection
  changelogs/fragments/pkg_mgr-default-dnf.yml
  lib/ansible/module_utils/facts/system/pkg_mgr.py
  test/units/module_utils/facts/system/test_pkg_mgr.py
Labels: shipit, bug, affects_2.16

#78487 Add GALAXY_COLLECTIONS_PATH_WARNINGS option.
  changelogs/fragments/78487-galaxy-collections-path-warnings.yml
  lib/ansible/cli/galaxy.py
  lib/ansible/config/base.yml
Labels: needs_revision, support:core, feature, affects_2.14

#80586 Pin pyasn1 version in uri and unarchive tests
  test/integration/targets/unarchive/tasks/test_download.yml
  test/integration/targets/uri/tasks/main.yml
Labels: needs_revision, backport, affects_2.12

#80589 tests: replace a mock import with unittest.mock
  test/units/ansible_test/test_validate_modules.py
Labels: affects_2.16

#80603 [stable-2.15] tests: replace a mock import with unittest.mock (#80589)
  test/units/ansible_test/test_validate_modules.py
Labels: backport, affects_2.15

#80602 [stable-2.9] Use variable instead of container resource in AZP (#80299).
  .azure-pipelines/azure-pipelines.yml
  .azure-pipelines/templates/coverage.yml
  .azure-pipelines/templates/test.yml
Labels: backport, affects_2.9

#80601 fix become yes/no to true/false (#80515)
  docs/docsite/rst/network/dev_guide/developing_resource_modules_network.rst
  docs/docsite/rst/network/getting_started/network_differences.rst
  docs/docsite/rst/network/user_guide/network_debug_troubleshooting.rst
  docs/docsite/rst/network/user_guide/platform_cnos.rst
  docs/docsite/rst/network/user_guide/platform_dellos10.rst
  docs/docsite/rst/network/user_guide/platform_dellos6.rst
  docs/docsite/rst/network/user_guide/platform_dellos9.rst
  docs/docsite/rst/network/user_guide/platform_enos.rst
  docs/docsite/rst/network/user_guide/platform_eos.rst
  docs/docsite/rst/network/user_guide/platform_icx.rst
  docs/docsite/rst/network/user_guide/platform_ios.rst
  docs/docsite/rst/network/user_guide/platform_ironware.rst
  docs/docsite/rst/network/user_guide/platform_nxos.rst
  docs/docsite/rst/network/user_guide/platform_routeros.rst
  docs/docsite/rst/network/user_guide/platform_voss.rst
  docs/docsite/rst/playbook_guide/playbooks_privilege_escalation.rst
Labels: backport, networking, needs_triage, docs, docsite, docs_only, affects_2.15

#80600 Backportapalooza 04 21
  docs/docsite/rst/community/communication.rst
  docs/docsite/rst/community/other_tools_and_programs.rst
  docs/docsite/rst/dev_guide/developing_plugins.rst
  docs/docsite/rst/installation_guide/installation_distros.rst
  docs/docsite/rst/installation_guide/intro_installation.rst
  docs/docsite/rst/playbook_guide/playbooks_blocks.rst
  docs/docsite/rst/playbook_guide/playbooks_tags.rst
  docs/docsite/rst/playbook_guide/playbooks_templating.rst
  docs/docsite/rst/porting_guides/porting_guide_8.rst
  docs/docsite/rst/porting_guides/porting_guides.rst
  docs/docsite/rst/reference_appendices/faq.rst
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
  docs/docsite/rst/scenario_guides/guide_vmware_rest.rst
  docs/templates/playbooks_keywords.rst.j2
  lib/ansible/modules/apt.py
  lib/ansible/modules/apt_key.py
  lib/ansible/modules/apt_repository.py
  lib/ansible/modules/group_by.py
  lib/ansible/modules/systemd_service.py
  lib/ansible/modules/uri.py
  lib/ansible/modules/user.py
  lib/ansible/modules/validate_argument_spec.py
  lib/ansible/plugins/doc_fragments/files.py
  lib/ansible/plugins/lookup/password.py
Labels: backport, module, needs_triage, docs, docsite, affects_2.15

#80610 New release v2.13.9
  changelogs/CHANGELOG-v2.13.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.13.9_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature, affects_2.13

#80611 New release v2.14.5
  changelogs/CHANGELOG-v2.14.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.14.5_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature, affects_2.14

#80614 Update Ansible release version to v2.14.5.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature, small_patch, affects_2.14

#80613 Update Ansible release version to v2.13.9.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature, small_patch, affects_2.13

#80616 [stable-2.15] ansible-test - Use FreeBSD packaged setuptools (#80615)
  changelogs/fragments/ansible-test-freebsd-bootstrap-setuptools.yml
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: backport, test, bug, affects_2.15

#80617 [stable-2.14] ansible-test - Use FreeBSD packaged setuptools (#80615)
  changelogs/fragments/ansible-test-freebsd-bootstrap-setuptools.yml
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: backport, test, bug, affects_2.14

#80619 [stable-2.12] ansible-test - Use FreeBSD packaged setuptools (#80615)
  changelogs/fragments/ansible-test-freebsd-bootstrap-setuptools.yml
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: backport, test, bug, affects_2.12

#80620 ansible-test - Limit setuptools version
  changelogs/fragments/ansible-test-import-sanity-setuptools.yml
  test/lib/ansible_test/_data/requirements/constraints.txt
Labels: backport, test, bug, affects_2.9

#80609 dnf5: use new API to check package signatures
  changelogs/fragments/dnf5-gpg-check-api.yml
  lib/ansible/modules/dnf5.py
Labels: module, bug, affects_2.16

#80437 PlayIterator: remove deprecated methods
  changelogs/fragments/remove-play_iterator-deprecated-methods.yml
  lib/ansible/executor/play_iterator.py
  test/sanity/ignore.txt
Labels: P2, test, feature, affects_2.16

#80622 2.15: dnf5: use new API to check package signatures (#80609)
  changelogs/fragments/dnf5-gpg-check-api.yml
  lib/ansible/modules/dnf5.py
Labels: backport, module, needs_triage, bug, affects_2.15

#80632 ansible-test - Update pylint to 2.17.3
  changelogs/fragments/ansible-test-pylint-update.yml
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
Labels: test, bug, small_patch, affects_2.16

#80634 [stable-2.15] ansible-test - Update pylint to 2.17.3 (#80632)
  changelogs/fragments/ansible-test-pylint-update.yml
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
Labels: backport, test, bug, small_patch, affects_2.15

#80635 ansible-test - Update the default containers
  test/lib/ansible_test/_data/completion/docker.txt
Labels: test, feature, affects_2.16

#80636 ansible-test - Update the default containers
  test/lib/ansible_test/_data/completion/docker.txt
Labels: backport, test, feature, affects_2.15

#80639 New release v2.15.0rc1
  changelogs/CHANGELOG-v2.15.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.15.0rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature, affects_2.15

#80640 Update Ansible release version to v2.15.0rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature, small_patch, affects_2.15

#80630 service_facts, get more info for rcctl services
  changelogs/fragments/service_facts_rcctl.yml
  lib/ansible/modules/service_facts.py
Labels: module, needs_triage, feature, affects_2.16

#80642 Add Ansible community 7.5.0 porting guide
  docs/docsite/rst/porting_guides/porting_guide_7.rst
Labels: needs_triage, bug, docs, docs_only, affects_2.16

#80643 Add Ansible community 8.0.0a2 porting guide
  docs/docsite/rst/porting_guides/porting_guide_8.rst
Labels: needs_triage, docs, docs_only, affects_2.16

#80439 Templar: remove deprecated shared_loader_obj param
  changelogs/fragments/remove-templar-shared_loader_obj-arg.yml
  lib/ansible/template/__init__.py
  test/sanity/ignore.txt
Labels: P2, test, feature, affects_2.16

#80597 Fix gather parallel
  changelogs/fragments/gather_facts_fix_parallel.yml
  lib/ansible/modules/gather_facts.py
  lib/ansible/plugins/action/gather_facts.py
  test/integration/targets/gathering_facts/library/dummy1
  test/integration/targets/gathering_facts/library/dummy2
  test/integration/targets/gathering_facts/library/dummy3
  test/integration/targets/gathering_facts/library/slow
  test/integration/targets/gathering_facts/runme.sh
  test/sanity/ignore.txt
Labels: test, module, bug, P3, affects_2.16

#68260 Add TTY check and argument to disable it (#50603)
  changelogs/fragments/50603-tty-check.yaml
  lib/ansible/cli/vault.py
  test/units/cli/test_vault.py
Labels: needs_revision, stale_ci, support:core, stale_review, new_contributor, bug, affects_2.10, affects_2.13

#80649 Set the minimum setuptools to 45.2.0
  changelogs/fragments/ansible-test-minimum-setuptools.yml
  hacking/update-sanity-requirements.py
  pyproject.toml
  setup.cfg
  test/sanity/code-smell/package-data.py
  test/sanity/code-smell/package-data.requirements.in
  test/sanity/code-smell/package-data.requirements.txt
Labels: test, shipit, bug, affects_2.16

#80647 source module compression setting directly from config
  changelogs/fragments/mc_from_config.yml
  lib/ansible/plugins/action/__init__.py
Labels: needs_triage, feature, affects_2.16

#80441 Remove deprecated default.fact_caching_prefix ini config option
  changelogs/fragments/inventory_cache-remove-deprecated-default-section.yml
  lib/ansible/plugins/doc_fragments/inventory_cache.py
Labels: P2, feature, affects_2.16

#80440 ActionBase: remove deprecated _remote_checksum
  changelogs/fragments/remove-deprecated-actionbase-_remote_checksum.yml
  lib/ansible/plugins/action/__init__.py
  test/sanity/ignore.txt
Labels: P2, test, feature, affects_2.16

#80660 Disable failing incidental_inventory_docker_swarm
  test/integration/targets/incidental_inventory_docker_swarm/aliases
Labels: backport, test, affects_2.12

#80449 _symbolic_mode_to_octal- fix raising ValueError for invalid symbolic modes
  changelogs/fragments/80449-fix-symbolic-mode-error-msg.yml
  lib/ansible/module_utils/basic.py
  test/integration/targets/unarchive/tasks/test_mode.yml
  test/units/modules/test_copy.py
Labels: bug, affects_2.16

#80655 Remove terminal viewing docs
  docs/docsite/rst/plugins/terminal.rst
Labels: docs, docs_only, affects_2.16

#80663 Use assertRaisesRegex in unit test
  test/units/cli/test_vault.py
Labels: affects_2.16

#80628 service module : remove flag confugration from openbsd enable/disable service
  changelogs/fragments/service_fix_obsd.yml
  lib/ansible/modules/service.py
Labels: module, bug, affects_2.16

#80665 [2.15] ansible-galaxy: fix installing signed collections (#80661)
  changelogs/fragments/80648-fix-ansible-galaxy-cache-signatures-bug.yml
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  lib/ansible/galaxy/dependency_resolution/providers.py
Labels: backport, needs_triage, bug, affects_2.15

#80671 Removes extraneous parentheses; Fixes 80670
  lib/ansible/plugins/test/skipped.yml
Labels: needs_triage, new_contributor, docs, small_patch, affects_2.16
