Repository ansible/ansible, pull requests merged in 2023-07, with the labels that each got.

#81072 [stable-2.15] Resolve issues on python pre-3.10.6 with collection dirs longer than 100 characters (#81061)
  changelogs/fragments/long-collection-paths-fix.yml
  lib/ansible/galaxy/collection/__init__.py
  test/units/cli/galaxy/test_collection_extract_tar.py
Labels: needs_info, backport, needs_triage, stale_ci, affects_2.15

#81057 [2.15] Make sure that values that should be strings are actually strings
  changelogs/fragments/81029-connection-types.yml
  lib/ansible/plugins/connection/paramiko_ssh.py
  lib/ansible/plugins/connection/psrp.py
  lib/ansible/plugins/connection/ssh.py
Labels: windows, backport, needs_triage, stale_ci, bug, affects_2.15

#81056 2.15: dnf5 - enable env groups testing in CI (#81032)
  changelogs/fragments/dnf5-test-env-groups.yml
  test/integration/targets/dnf/tasks/dnf.yml
Labels: backport, needs_triage, stale_ci, affects_2.15

#81054 [stable-2.15] Don't mutate templar.environment, only overlay on local myenv (#81005).
  changelogs/fragments/81005-use-overlay-overrides.yml
  lib/ansible/plugins/action/template.py
  lib/ansible/plugins/lookup/template.py
  lib/ansible/template/__init__.py
  test/integration/targets/template/arg_template_overrides.j2
  test/integration/targets/template/in_template_overrides.yml
  test/integration/targets/template/runme.sh
  test/integration/targets/template/template_overrides.yml
Labels: backport, needs_triage, stale_ci, bug, affects_2.15

#81059 2.15: Register handlers immediately if currently iterating handlers (#80898)
  changelogs/fragments/80880-register-handlers-immediately-if-iterating-handlers.yml
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/handlers/80880.yml
  test/integration/targets/handlers/runme.sh
Labels: backport, needs_triage, stale_ci, bug, affects_2.15

#81089 [stable-2.14] Cache field attributes list on the playbook classes (#79091)
  changelogs/fragments/cache-fa-on-pb-cls.yml
  changelogs/fragments/no-stacked-descriptors.yaml
  lib/ansible/playbook/base.py
Labels: needs_info, backport, needs_triage, stale_ci, affects_2.14

#81073 [stable-2.14] Resolve issues on python pre-3.10.6 with collection dirs longer than 100 characters (#81061)
  changelogs/fragments/long-collection-paths-fix.yml
  lib/ansible/galaxy/collection/__init__.py
  test/units/cli/galaxy/test_collection_extract_tar.py
Labels: needs_info, backport, needs_triage, stale_ci, affects_2.14

#81152 Use semantic markup for docs fragments
  lib/ansible/plugins/doc_fragments/constructed.py
  lib/ansible/plugins/doc_fragments/files.py
  lib/ansible/plugins/doc_fragments/result_format_callback.py
  lib/ansible/plugins/doc_fragments/shell_common.py
  lib/ansible/plugins/doc_fragments/shell_windows.py
  lib/ansible/plugins/doc_fragments/template_common.py
  lib/ansible/plugins/doc_fragments/url.py
  lib/ansible/plugins/doc_fragments/url_windows.py
  lib/ansible/plugins/doc_fragments/vars_plugin_staging.py
Labels: windows, docs, affects_2.16

#80796 script inventory plugin, link to dev script howto docs
  lib/ansible/plugins/inventory/script.py
Labels: docs, docs_only, affects_2.16

#81065 ansible-test - remove test remotes: rhel 8.7/9.1
  changelogs/fragments/ansible-test-remove-old-rhel-remotes.yml
  test/lib/ansible_test/_data/completion/remote.txt
Labels: test, feature, affects_2.16

#81184 ansible-test - Fix import sanity test for targets
  changelogs/fragments/ansible-test-import-sanity-fix.yml
  test/lib/ansible_test/_internal/commands/sanity/import.py
Labels: test, bug, affects_2.16

#81185 ansible-test - Remove old pytest-forked constraint
  test/lib/ansible_test/_data/requirements/constraints.txt
Labels: test, feature, affects_2.16

#81160 Re-introduce RHEL 9 modularity testing in CI
  test/integration/targets/dnf/tasks/main.yml
  test/integration/targets/dnf/vars/RedHat-9.yml
Labels: bug, affects_2.16

#81195 Properly disable modularity tests for dnf5 only
  test/integration/targets/dnf/tasks/main.yml
Labels: needs_triage, bug, affects_2.16

#81140 Add multirepo tip to doc issue report
  .github/ISSUE_TEMPLATE/documentation_report.yml
Labels: docs, affects_2.16

#81192 2.15: Re-introduce RHEL 9 modularity testing in CI (#81160)
  test/integration/targets/dnf/tasks/main.yml
  test/integration/targets/dnf/vars/RedHat-9.yml
Labels: backport, needs_triage, bug, affects_2.15

#81193 2.14: Re-introduce RHEL 9 modularity testing in CI (#81160)
  test/integration/targets/dnf/tasks/main.yml
  test/integration/targets/dnf/vars/RedHat-9.yml
Labels: backport, needs_triage, bug, affects_2.14

#81202 fix doc report template
  .github/ISSUE_TEMPLATE/documentation_report.yml
Labels: docs, affects_2.16

#80973 Remove Python 3.9 support
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/remove-python3.9-controller-support.yml
  hacking/README.md
  lib/ansible/cli/__init__.py
  lib/ansible/galaxy/api.py
  lib/ansible/utils/encrypt.py
  lib/ansible/utils/shlex.py
  lib/ansible/utils/vars.py
  requirements.txt
  setup.cfg
  test/integration/targets/canonical-pep517-self-packaging/minimum-build-constraints.txt
  test/lib/ansible_test/_data/requirements/ansible.txt
  test/lib/ansible_test/_data/requirements/constraints.txt
  test/lib/ansible_test/_internal/util.py
  test/lib/ansible_test/_util/target/common/constants.py
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
  test/sanity/ignore.txt
  test/units/requirements.txt
Labels: test, feature, has_issue, affects_2.16

#81194 2.13: Re-introduce RHEL 9 modularity testing in CI (#81160)
  test/integration/targets/dnf/tasks/main.yml
  test/integration/targets/dnf/vars/RedHat-9.yml
Labels: backport, bug, affects_2.13

#81204 New release v2.15.2rc1
  changelogs/CHANGELOG-v2.15.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.15.2rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature, affects_2.15

#81205 New release v2.14.8rc1
  changelogs/CHANGELOG-v2.14.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.14.8rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature, affects_2.14

#81206 New release v2.13.11rc1
  changelogs/CHANGELOG-v2.13.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.13.11rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature, affects_2.13

#81209 Update Ansible release version to v2.15.2rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature, small_patch, affects_2.15

#81210 Update Ansible release version to v2.14.8rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature, small_patch, affects_2.14

#81211 Update Ansible release version to v2.13.11rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature, small_patch, affects_2.13

#78552 Add type annotation for connection plugins
  changelogs/fragments/connection-type-annotation.yml
  lib/ansible/plugins/__init__.py
  lib/ansible/plugins/connection/__init__.py
  lib/ansible/plugins/connection/local.py
  lib/ansible/plugins/connection/paramiko_ssh.py
  lib/ansible/plugins/connection/psrp.py
  lib/ansible/plugins/connection/ssh.py
  lib/ansible/plugins/connection/winrm.py
Labels: windows, support:core, feature, affects_2.14, code_health

#81178 first_found lookup, let lookup handle templating errors
  changelogs/fragments/first_found_template_fix.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/plugins/lookup/first_found.py
  test/integration/targets/lookup_first_found/tasks/main.yml
  test/integration/targets/lookup_first_found/vars/ishouldnotbefound.yml
  test/integration/targets/lookup_first_found/vars/itworks.yml
Labels: bug, affects_2.16

#81213 Module docs fixes
  lib/ansible/modules/getent.py
  lib/ansible/modules/git.py
  lib/ansible/modules/setup.py
  lib/ansible/modules/stat.py
  lib/ansible/modules/validate_argument_spec.py
  lib/ansible/modules/yum.py
Labels: module, needs_triage, docs, affects_2.16

#81217 Convert non-docs *.rst files to *.md
  README.md
  README.rst
  changelogs/CHANGELOG.rst
  changelogs/README.md
  setup.cfg
  test/sanity/code-smell/package-data.py
Labels: test, docs, affects_2.16

#81220 Add pymarkdown sanity test for core
  .github/PULL_REQUEST_TEMPLATE.md
  hacking/README.md
  hacking/azp/README.md
  hacking/backport/README.md
  hacking/deprecated_issue_template.md
  hacking/ticket_stubs/bug_internal_api.md
  hacking/ticket_stubs/bug_wrong_repo.md
  hacking/ticket_stubs/collections.md
  hacking/ticket_stubs/no_thanks.md
  hacking/ticket_stubs/pr_duplicate.md
  hacking/ticket_stubs/pr_merged.md
  hacking/ticket_stubs/proposal.md
  hacking/ticket_stubs/question_not_bug.md
  hacking/ticket_stubs/resolved.md
  hacking/ticket_stubs/wider_discussion.md
  lib/ansible/galaxy/data/container/README.md
  test/integration/targets/ansible-test-sanity-validate-modules/ansible_collections/ns/failure/README.md
  test/integration/targets/ansible-test-sanity-validate-modules/ansible_collections/ns/ps_only/README.md
  test/integration/targets/ansible-test-sanity/ansible_collections/ns/col/README.md
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/sanity/code-smell/pymarkdown.config.json
  test/sanity/code-smell/pymarkdown.json
  test/sanity/code-smell/pymarkdown.py
  test/sanity/code-smell/pymarkdown.requirements.in
  test/sanity/code-smell/pymarkdown.requirements.txt
  test/sanity/ignore.txt
  test/support/README.md
  test/units/cli/test_data/collection_skeleton/README.md
  test/units/cli/test_data/collection_skeleton/docs/My Collection.md
  test/units/galaxy/test_collection.py
Labels: test, affects_2.16

#81208 Update env-setup.fish
  hacking/env-setup.fish
Labels: new_contributor, bug, feature, affects_2.16

#81225 [stable-2.15] Reorganize CI sanity test matrix (#81004)
  .azure-pipelines/azure-pipelines.yml
  .azure-pipelines/commands/sanity.sh
Labels: backport, needs_triage, affects_2.15

#81226 [stable-2.14] Reorganize CI sanity test matrix (#81004)
  .azure-pipelines/azure-pipelines.yml
  .azure-pipelines/commands/sanity.sh
Labels: backport, needs_triage, affects_2.14

#81227 [stable-2.13] Reorganize CI sanity test matrix (#81004)
  .azure-pipelines/azure-pipelines.yml
  .azure-pipelines/commands/sanity.sh
Labels: backport, needs_triage, affects_2.13

#81229 [stable-2.15] Use *.md instead of *.rst for test READMEs (#81009)
  test/integration/targets/ansible-test-sanity-validate-modules/ansible_collections/ns/failure/README.md
  test/integration/targets/ansible-test-sanity-validate-modules/ansible_collections/ns/failure/galaxy.yml
  test/integration/targets/ansible-test-sanity-validate-modules/ansible_collections/ns/ps_only/README.md
  test/integration/targets/ansible-test-sanity-validate-modules/ansible_collections/ns/ps_only/galaxy.yml
  test/integration/targets/ansible-test-sanity/ansible_collections/ns/col/README.md
  test/integration/targets/ansible-test-sanity/ansible_collections/ns/col/galaxy.yml
Labels: backport, needs_triage, affects_2.15

#81230 [stable-2.14] Use *.md instead of *.rst for test READMEs (#81009)
  test/integration/targets/ansible-test-sanity-validate-modules/ansible_collections/ns/failure/README.md
  test/integration/targets/ansible-test-sanity-validate-modules/ansible_collections/ns/failure/galaxy.yml
  test/integration/targets/ansible-test-sanity-validate-modules/ansible_collections/ns/ps_only/README.md
  test/integration/targets/ansible-test-sanity-validate-modules/ansible_collections/ns/ps_only/galaxy.yml
  test/integration/targets/ansible-test-sanity/ansible_collections/ns/col/README.md
  test/integration/targets/ansible-test-sanity/ansible_collections/ns/col/galaxy.yml
Labels: backport, needs_triage, affects_2.14

#81231 [stable-2.13] Use *.md instead of *.rst for test READMEs (#81009).
  test/integration/targets/ansible-test/ansible_collections/ns/col/README.md
  test/integration/targets/ansible-test/ansible_collections/ns/col/galaxy.yml
Labels: backport, needs_triage, affects_2.13

#81016 Update regex_* docs
  lib/ansible/plugins/filter/regex_findall.yml
  lib/ansible/plugins/filter/regex_replace.yml
  lib/ansible/plugins/filter/regex_search.yml
Labels: docs, affects_2.16

#81221 Fix yaml syntax in csvfile_lookup example
  lib/ansible/plugins/lookup/csvfile.py
Labels: new_contributor, docs, small_patch, docs_only, affects_2.16

#81110 filter: add documentation for msg parameter
  lib/ansible/plugins/filter/core.py
  lib/ansible/plugins/filter/mandatory.yml
Labels: stale_ci, docs, has_issue, affects_2.16

#81250 Update wait_for_connection to not reference configure script
  lib/ansible/modules/wait_for_connection.py
Labels: module

#81093 ansible-test - remove Fedora 37 container and remote support
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-fedora-37.yml
  test/lib/ansible_test/_data/completion/docker.txt
  test/lib/ansible_test/_data/completion/remote.txt
Labels: test, WIP, feature, has_issue, affects_2.16

#81218 deprecate 'smart' connection value
  changelogs/fragments/smart_connection_bye.yml
  lib/ansible/config/base.yml
  lib/ansible/utils/ssh_functions.py
Labels: needs_triage, feature, has_issue, affects_2.16

#78956 Replace `reboot_command` integration test with unit tests
  test/integration/targets/reboot/tasks/main.yml
  test/integration/targets/reboot/tasks/test_reboot_command.yml
  test/units/plugins/action/test_reboot.py
Labels: new_plugin, core_review, support:core, affects_2.15

#81244 replace: handle exception while parsing escape char
  changelogs/fragments/79364_replace.yml
  lib/ansible/modules/replace.py
  test/integration/targets/replace/tasks/main.yml
Labels: module, has_issue

#81247 apt: Return calculated diff while running apt clean
  changelogs/fragments/aptclean_diff.yml
  lib/ansible/modules/apt.py
Labels: module

#81237 Add missing use case with module purge
  lib/ansible/modules/apt.py
Labels: module, new_contributor, docs, docs_only, affects_2.16

#81198 Remove BOTMETA.yml and sanity tests for it
  .github/BOTMETA.yml
  test/sanity/code-smell/botmeta.json
  test/sanity/code-smell/botmeta.py
  test/sanity/code-smell/botmeta.requirements.in
  test/sanity/code-smell/botmeta.requirements.txt
Labels: test, WIP, docs, feature, docsite, botmeta, affects_2.16

#81266 [backport][stable-2.15] Replace `reboot_command` integration test with unit tests
  test/integration/targets/reboot/tasks/main.yml
  test/integration/targets/reboot/tasks/test_reboot_command.yml
  test/units/plugins/action/test_reboot.py
Labels: backport, test

#81268 [backport][stable-2.13] Replace `reboot_command` integration test with unit tests
  test/integration/targets/reboot/tasks/main.yml
  test/integration/targets/reboot/tasks/test_reboot_command.yml
  test/units/plugins/action/test_reboot.py
Labels: backport, test

#81267 [backport][stable-2.14] Replace `reboot_command` integration test with unit tests
  test/integration/targets/reboot/tasks/main.yml
  test/integration/targets/reboot/tasks/test_reboot_command.yml
  test/units/plugins/action/test_reboot.py
Labels: backport, test

#81271 ansible-test - Fix sanity traceback with `-e` opt
  changelogs/fragments/ansible-test-explain-traceback.yml
  test/integration/targets/ansible-test-sanity/runme.sh
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_internal/commands/sanity/ansible_doc.py
  test/lib/ansible_test/_internal/commands/sanity/import.py
  test/lib/ansible_test/_internal/commands/sanity/mypy.py
  test/lib/ansible_test/_internal/util.py
  test/lib/ansible_test/_internal/util_common.py
Labels: needs_ci

#81273 ansible-test - Narrow the scope of some sanity tests
  changelogs/fragments/ansible-test-sanity-scope.yml
  test/integration/targets/ansible-test-sanity-no-get-exception/aliases
  test/integration/targets/ansible-test-sanity-no-get-exception/ansible_collections/ns/col/do-not-check-me.py
  test/integration/targets/ansible-test-sanity-no-get-exception/ansible_collections/ns/col/plugins/modules/check-me.py
  test/integration/targets/ansible-test-sanity-no-get-exception/expected.txt
  test/integration/targets/ansible-test-sanity-no-get-exception/runme.sh
  test/integration/targets/ansible-test-sanity-replace-urlopen/aliases
  test/integration/targets/ansible-test-sanity-replace-urlopen/ansible_collections/ns/col/do-not-check-me.py
  test/integration/targets/ansible-test-sanity-replace-urlopen/ansible_collections/ns/col/plugins/modules/check-me.py
  test/integration/targets/ansible-test-sanity-replace-urlopen/expected.txt
  test/integration/targets/ansible-test-sanity-replace-urlopen/runme.sh
  test/integration/targets/ansible-test-sanity-use-compat-six/aliases
  test/integration/targets/ansible-test-sanity-use-compat-six/ansible_collections/ns/col/do-not-check-me.py
  test/integration/targets/ansible-test-sanity-use-compat-six/ansible_collections/ns/col/plugins/modules/check-me.py
  test/integration/targets/ansible-test-sanity-use-compat-six/expected.txt
  test/integration/targets/ansible-test-sanity-use-compat-six/runme.sh
  test/lib/ansible_test/_util/controller/sanity/code-smell/no-get-exception.json
  test/lib/ansible_test/_util/controller/sanity/code-smell/replace-urlopen.json
  test/lib/ansible_test/_util/controller/sanity/code-smell/use-compat-six.json
  test/sanity/ignore.txt
Labels: feature

#81275 The split filter was added in ansible-core 2.11
  lib/ansible/plugins/filter/split.yml
Labels: needs_triage

#81064 Fix stealth exceptions and blocking select() in daemonize()
  changelogs/fragments/81064-daemonize-fixes.yml
  lib/ansible/module_utils/service.py
Labels: stale_ci, bug, affects_2.16

#81283 New release v2.15.2
  changelogs/CHANGELOG-v2.15.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.15.2_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_ci, feature

#81284 New release v2.14.8
  changelogs/CHANGELOG-v2.14.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.14.8_summary.yaml
  lib/ansible/release.py
Labels: needs_revision, backport, feature

#81285 New release v2.13.11
  changelogs/CHANGELOG-v2.13.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.13.11_summary.yaml
  lib/ansible/release.py
Labels: needs_revision, backport, feature

#81286 Update Ansible release version to v2.15.2.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, feature

#81287 Update Ansible release version to v2.14.8.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, feature

#81288 Update Ansible release version to v2.13.11.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, feature

#81113 filter: fix documentation
  lib/ansible/plugins/filter/b64decode.yml
  lib/ansible/plugins/filter/b64encode.yml
  lib/ansible/plugins/filter/bool.yml
  lib/ansible/plugins/filter/commonpath.yml
  lib/ansible/plugins/filter/dict2items.yml
  lib/ansible/plugins/filter/from_yaml.yml
  lib/ansible/plugins/filter/from_yaml_all.yml
  lib/ansible/plugins/filter/normpath.yml
  lib/ansible/plugins/filter/realpath.yml
  lib/ansible/plugins/filter/root.yml
  lib/ansible/plugins/filter/splitext.yml
  lib/ansible/plugins/filter/to_json.yml
  lib/ansible/plugins/filter/to_nice_json.yml
  lib/ansible/plugins/filter/to_yaml.yml
  lib/ansible/plugins/filter/unvault.yml
  lib/ansible/plugins/filter/urldecode.yml
Labels: docs, has_issue, affects_2.16

#81301 Disable cron integration test on Alpine
  test/integration/targets/setup_cron/tasks/main.yml
Labels: test

#81302 [stable-2.15] Disable cron integration test on Alpine (#81301)
  test/integration/targets/setup_cron/tasks/main.yml
Labels: backport, test

#81303 [stable-2.14] Disable cron integration test on Alpine (#81301)
  test/integration/targets/setup_cron/tasks/main.yml
Labels: backport, test

#81304 [stable-2.13] Disable cron integration test on Alpine (#81301)
  test/integration/targets/setup_cron/tasks/main.yml
Labels: backport, test

#81300 ansible-test - Pre-build PyYAML wheels
  changelogs/fragments/ansible-test-pyyaml-build.yml
  hacking/update-sanity-requirements.py
  test/integration/targets/canonical-pep517-self-packaging/modernish-build-constraints.txt
  test/lib/ansible_test/_data/requirements/sanity.ansible-doc.txt
  test/lib/ansible_test/_data/requirements/sanity.changelog.txt
  test/lib/ansible_test/_data/requirements/sanity.import.plugin.txt
  test/lib/ansible_test/_data/requirements/sanity.import.txt
  test/lib/ansible_test/_data/requirements/sanity.integration-aliases.txt
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  test/lib/ansible_test/_data/requirements/sanity.runtime-metadata.txt
  test/lib/ansible_test/_data/requirements/sanity.validate-modules.txt
  test/lib/ansible_test/_data/requirements/sanity.yamllint.txt
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_util/target/setup/requirements.py
  test/sanity/code-smell/deprecated-config.requirements.txt
  test/sanity/code-smell/package-data.requirements.txt
Labels: needs_revision

#81305 Add missing skip entries for selinux module_util
  test/sanity/ignore.txt
Labels: test

#81306 [stable-2.15] ansible-test - Pre-build PyYAML wheels (#81300)
  changelogs/fragments/ansible-test-pyyaml-build.yml
  hacking/update-sanity-requirements.py
  test/integration/targets/canonical-pep517-self-packaging/modernish-build-constraints.txt
  test/lib/ansible_test/_data/requirements/sanity.ansible-doc.txt
  test/lib/ansible_test/_data/requirements/sanity.changelog.txt
  test/lib/ansible_test/_data/requirements/sanity.import.plugin.txt
  test/lib/ansible_test/_data/requirements/sanity.import.txt
  test/lib/ansible_test/_data/requirements/sanity.integration-aliases.txt
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  test/lib/ansible_test/_data/requirements/sanity.runtime-metadata.txt
  test/lib/ansible_test/_data/requirements/sanity.validate-modules.txt
  test/lib/ansible_test/_data/requirements/sanity.yamllint.txt
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_util/target/setup/requirements.py
  test/sanity/code-smell/botmeta.requirements.txt
  test/sanity/code-smell/deprecated-config.requirements.txt
  test/sanity/code-smell/docs-build.requirements.txt
  test/sanity/code-smell/package-data.requirements.txt
  test/sanity/code-smell/release-names.requirements.txt
Labels: backport

#81272 [stable-2.15] ansible-test - Fix sanity traceback with `-e` opt (#81271)
  changelogs/fragments/ansible-test-explain-traceback.yml
  test/integration/targets/ansible-test-sanity/runme.sh
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_internal/commands/sanity/ansible_doc.py
  test/lib/ansible_test/_internal/commands/sanity/import.py
  test/lib/ansible_test/_internal/commands/sanity/mypy.py
  test/lib/ansible_test/_internal/util.py
  test/lib/ansible_test/_internal/util_common.py
Labels: backport

#81222 [stable-2.15] Convert non-docs *.rst files to *.md (#81217)
  MANIFEST.in
  README.md
  README.rst
  changelogs/CHANGELOG.rst
  changelogs/README.md
  setup.cfg
  test/sanity/code-smell/package-data.py
Labels: backport, test, docs, affects_2.15

#81307 [stable-2.15] Add missing skip entries for selinux module_util (#81305)
  test/sanity/ignore.txt
Labels: backport, test

#81310 [stable-2.14] ansible-test - Pre-build PyYAML wheels (#81300)
  changelogs/fragments/ansible-test-pyyaml-build.yml
  hacking/update-sanity-requirements.py
  test/integration/targets/canonical-pep517-self-packaging/modernish-build-constraints.txt
  test/lib/ansible_test/_data/requirements/sanity.ansible-doc.txt
  test/lib/ansible_test/_data/requirements/sanity.changelog.txt
  test/lib/ansible_test/_data/requirements/sanity.import.plugin.txt
  test/lib/ansible_test/_data/requirements/sanity.import.txt
  test/lib/ansible_test/_data/requirements/sanity.integration-aliases.txt
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  test/lib/ansible_test/_data/requirements/sanity.runtime-metadata.txt
  test/lib/ansible_test/_data/requirements/sanity.validate-modules.txt
  test/lib/ansible_test/_data/requirements/sanity.yamllint.txt
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_util/target/setup/requirements.py
  test/sanity/code-smell/botmeta.requirements.txt
  test/sanity/code-smell/deprecated-config.requirements.txt
  test/sanity/code-smell/docs-build.requirements.txt
  test/sanity/code-smell/package-data.requirements.txt
  test/sanity/code-smell/release-names.requirements.txt
Labels: backport

#81308 [stable-2.14] Add missing skip entries for selinux module_util (#81305)
  test/sanity/ignore.txt
Labels: backport, test

#81223 [stable-2.14] Convert non-docs *.rst files to *.md (#81217)
  MANIFEST.in
  README.md
  README.rst
  changelogs/CHANGELOG.rst
  changelogs/README.md
  setup.cfg
  test/sanity/code-smell/package-data.py
Labels: backport, test, docs, affects_2.14

#81311 [stable-2.13] ansible-test - Pre-build PyYAML wheels (#81300)
  changelogs/fragments/ansible-test-pyyaml-build.yml
  hacking/update-sanity-requirements.py
  test/integration/targets/canonical-pep517-self-packaging/aliases
  test/integration/targets/canonical-pep517-self-packaging/modernish-build-constraints.txt
  test/lib/ansible_test/_data/requirements/sanity.ansible-doc.txt
  test/lib/ansible_test/_data/requirements/sanity.changelog.txt
  test/lib/ansible_test/_data/requirements/sanity.import.plugin.txt
  test/lib/ansible_test/_data/requirements/sanity.import.txt
  test/lib/ansible_test/_data/requirements/sanity.integration-aliases.txt
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  test/lib/ansible_test/_data/requirements/sanity.runtime-metadata.txt
  test/lib/ansible_test/_data/requirements/sanity.validate-modules.txt
  test/lib/ansible_test/_data/requirements/sanity.yamllint.txt
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_util/target/setup/requirements.py
  test/sanity/code-smell/botmeta.requirements.txt
  test/sanity/code-smell/deprecated-config.requirements.txt
  test/sanity/code-smell/docs-build.requirements.txt
  test/sanity/code-smell/package-data.requirements.txt
  test/sanity/code-smell/release-names.requirements.txt
Labels: backport

#81309 [stable-2.13] Add missing skip entries for selinux module_util (#81305)
  test/sanity/ignore.txt
Labels: backport, test

#81224 [stable-2.13] Convert non-docs *.rst files to *.md (#81217)
  MANIFEST.in
  README.md
  README.rst
  changelogs/CHANGELOG.rst
  changelogs/README.md
  setup.cfg
  test/sanity/code-smell/package-data.py
Labels: backport, test, docs, affects_2.13

#81312 [stable-2.12] ansible-test - Pre-build PyYAML wheels (#81300)
  changelogs/fragments/ansible-test-pyyaml-build.yml
  test/lib/ansible_test/_data/requirements/sanity.ansible-doc.txt
  test/lib/ansible_test/_data/requirements/sanity.changelog.txt
  test/lib/ansible_test/_data/requirements/sanity.import.plugin.txt
  test/lib/ansible_test/_data/requirements/sanity.import.txt
  test/lib/ansible_test/_data/requirements/sanity.integration-aliases.txt
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  test/lib/ansible_test/_data/requirements/sanity.runtime-metadata.txt
  test/lib/ansible_test/_data/requirements/sanity.validate-modules.txt
  test/lib/ansible_test/_data/requirements/sanity.yamllint.txt
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_util/target/setup/requirements.py
  test/sanity/code-smell/botmeta.requirements.txt
  test/sanity/code-smell/deprecated-config.requirements.txt
  test/sanity/code-smell/docs-build.requirements.txt
  test/sanity/code-smell/package-data.requirements.txt
  test/sanity/code-smell/release-names.requirements.txt
Labels: backport

#78613 Add test for 256-color configuration values
  changelogs/fragments/colors.yml
  lib/ansible/config/base.yml
  test/units/config/test3.cfg
  test/units/config/test_manager.py
Labels: test, core_review, support:core, new_contributor, affects_2.14

#80958 Update user module documentation to include MacOS password change behavior
  lib/ansible/modules/user.py
Labels: module, new_contributor, docs, small_patch, has_issue, docs_only, affects_2.16

#81296 Update urls unit test to support latest cryptography release
  changelogs/fragments/urls-unit-test-latest-cryptography.yml
  test/units/module_utils/urls/test_channel_binding.py
Labels: test

#81313 find, stay simple
  lib/ansible/modules/find.py
Labels: module, needs_triage

#81316 [stable-2.15] ansible-test - update module_utils/urls.py unit test to support cryptography >= 41.0.0
  changelogs/fragments/urls-unit-test-latest-cryptography.yml
  test/units/module_utils/urls/test_channel_binding.py
Labels: backport, test

#81317 [stable-2.14] ansible-test - update module_utils/urls.py unit test to support cryptography >= 41.0.0
  changelogs/fragments/urls-unit-test-latest-cryptography.yml
  test/units/module_utils/urls/test_channel_binding.py
Labels: backport, test

#81318 [stable-2.13] ansible-test - update module_utils/urls.py unit test to support cryptography >= 41.0.0
  changelogs/fragments/urls-unit-test-latest-cryptography.yml
  test/units/module_utils/urls/test_channel_binding.py
Labels: backport, test

#80961 update ansible-galaxy testserver to use SSLContext.load_cert_chain
  test/integration/targets/ansible-galaxy/files/testserver.py
Labels: test, needs_ci, WIP, stale_ci, affects_2.16

#81319 ansible-test: cloudstack: bump test container version
  changelogs/fragments/81319-cloudstack-test-container-bump-version.yml
  test/lib/ansible_test/_internal/commands/integration/cloud/cs.py
Labels: test

#81321 Update sanity requirements comments
  test/lib/ansible_test/_data/requirements/sanity.changelog.in
  test/sanity/code-smell/deprecated-config.requirements.in
  test/sanity/code-smell/package-data.requirements.in
Labels: test

#81322 [stable-2.15] ansible-test: cloudstack: bump test container version
  changelogs/fragments/81319-cloudstack-test-container-bump-version.yml
  test/lib/ansible_test/_internal/commands/integration/cloud/cs.py
Labels: backport, test

#81243 Fix selecting collections outside of the install path as preferred candidates
  changelogs/fragments/a-g-col-prevent-reinstalling-satisfied-req.yml
  lib/ansible/cli/galaxy.py
  lib/ansible/galaxy/collection/__init__.py
  test/integration/targets/ansible-galaxy-collection-scm/tasks/multi_collection_repo_all.yml
  test/units/galaxy/test_collection_install.py
Labels: stale_review, has_issue

#80834 add Python 3.12 support to ansible-test
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-python-3.12.yml
  lib/ansible/config/base.yml
  test/lib/ansible_test/_data/completion/docker.txt
  test/lib/ansible_test/_internal/python_requirements.py
  test/lib/ansible_test/_util/target/common/constants.py
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
  test/sanity/ignore.txt
  test/units/utils/collection_loader/test_collection_loader.py
Labels: test, WIP, feature, affects_2.16

#81330 Update ansible-test containers to test Python 3.12 with the test venvs
  test/lib/ansible_test/_data/completion/docker.txt
Labels: test, stale_review

#81334 Refactor test cases to improve unit test quality
  test/units/parsing/test_mod_args.py
Labels: test, stale_review

#81314 fix ansible_pkg_mgr is unknown in Kylin Linux
  changelogs/fragments/81332-fix-pkg-mgr-in-kylin.yml
  lib/ansible/module_utils/facts/system/pkg_mgr.py
  test/units/module_utils/facts/system/test_pkg_mgr.py
Labels: bug, has_issue

#81348 pep8: fix sanity for 3.12
  lib/ansible/module_utils/compat/selinux.py
  test/units/module_utils/basic/test_argument_spec.py
Labels: code_health

#81323 replace deprecated datetime methods with Python 3
  changelogs/fragments/remove-deprecated-datetime-methods.yml
  lib/ansible/executor/module_common.py
  lib/ansible/galaxy/api.py
  lib/ansible/galaxy/role.py
  lib/ansible/module_utils/compat/datetime.py
  lib/ansible/module_utils/facts/system/date_time.py
  lib/ansible/modules/get_url.py
  lib/ansible/modules/uri.py
  lib/ansible/modules/wait_for.py
  lib/ansible/plugins/action/reboot.py
  lib/ansible/plugins/action/wait_for_connection.py
  lib/ansible/template/__init__.py
  test/support/windows-integration/plugins/action/win_reboot.py
  test/units/module_utils/facts/test_date_time.py
Labels: needs_revision, module

#81083 Add option to blockinfile to wrap inserted block with blank lines
  changelogs/fragments/81083-add-blockinfile-append-and-prepend-new-line-options.yml
  lib/ansible/modules/blockinfile.py
  test/integration/targets/blockinfile/tasks/append_newline.yml
  test/integration/targets/blockinfile/tasks/main.yml
  test/integration/targets/blockinfile/tasks/prepend_newline.yml
Labels: module, stale_review, feature, has_issue, affects_2.16

#81351 Correct blockinfile code comment
  lib/ansible/modules/blockinfile.py
Labels: module, needs_triage

#81295 fix networking path
  changelogs/fragments/forced_local+fix+.yml
  lib/ansible/executor/task_executor.py
Labels: has_issue

#81361 [stable-2.15] Exclude internal options from man pages and docs (#81360)
  changelogs/fragments/suppressed-options.yml
  packaging/pep517_backend/_generate_man.py
Labels: backport

#81362 [stable-2.14] Exclude internal options from man pages and docs (#81360)
  changelogs/fragments/suppressed-options.yml
  packaging/pep517_backend/_generate_man.py
Labels: backport

#81363 [stable-2.13] Exclude internal options from man pages and docs (#81360)
  changelogs/fragments/suppressed-options.yml
  packaging/pep517_backend/_generate_man.py
Labels: backport

#81366 Fix missing command descriptions in manpages/docs
  changelogs/fragments/add-missing-cli-docs.yml
  lib/ansible/cli/config.py
  lib/ansible/cli/galaxy.py
  lib/ansible/cli/inventory.py
Labels: needs_triage

#81369 [stable-2.15] Fix command doc lookup in man page generation (#81365)
  changelogs/fragments/missing-doc-func.yml
  lib/ansible/cli/galaxy.py
  packaging/pep517_backend/_generate_man.py
Labels: backport

#81368 [stable-2.14] Fix command doc lookup in man page generation (#81365)
  changelogs/fragments/missing-doc-func.yml
  lib/ansible/cli/galaxy.py
  packaging/pep517_backend/_generate_man.py
Labels: needs_revision, backport

#81367 [stable-2.13] Fix command doc lookup in man page generation (#81365)
  changelogs/fragments/missing-doc-func.yml
  lib/ansible/cli/galaxy.py
  packaging/pep517_backend/_generate_man.py
Labels: backport

#81370 [stable-2.15] Fix missing command descriptions in manpages/docs (#81366).
  changelogs/fragments/add-missing-cli-docs.yml
  lib/ansible/cli/config.py
  lib/ansible/cli/galaxy.py
  lib/ansible/cli/inventory.py
Labels: backport

#81371 [stable-2.14] Fix missing command descriptions in manpages/docs (#81366).
  changelogs/fragments/add-missing-cli-docs.yml
  lib/ansible/cli/config.py
  lib/ansible/cli/galaxy.py
  lib/ansible/cli/inventory.py
Labels: backport

#81372 [stable-2.13] Fix missing command descriptions in manpages/docs (#81366).
  changelogs/fragments/add-missing-cli-docs.yml
  lib/ansible/cli/config.py
  lib/ansible/cli/galaxy.py
  lib/ansible/cli/inventory.py
Labels: backport

#81379 [stable-2.15] Fix misrendered sections in manpage generation
  packaging/pep517_backend/_generate_man.py
  packaging/pep517_backend/_templates/man.j2
Labels: backport, test, needs_triage, feature

#81381 [stable-2.13] Fix misrendered sections in manpage generation
  docs/templates/cli_rst.j2
  hacking/build_library/build_ansible/command_plugins/generate_man.py
  packaging/pep517_backend/_templates/man.j2
Labels: backport, test, needs_triage, feature

#81382 [stable-2.15] Include subcommands in generated man pages (#81378)
  changelogs/fragments/man-page-subcommands.yml
  packaging/pep517_backend/_templates/man.j2
Labels: backport, needs_triage

#81383 [stable-2.14] Include subcommands in generated man pages (#81378)
  changelogs/fragments/man-page-subcommands.yml
  packaging/pep517_backend/_templates/man.j2
Labels: backport, needs_triage

#81384 [stable-2.13] Include subcommands in generated man pages (#81378)
  changelogs/fragments/man-page-subcommands.yml
  packaging/pep517_backend/_templates/man.j2
Labels: backport, needs_triage
