Repository ansible/ansible, pull requests merged in 2023-09, with the labels that each got.

#81623 changed link ‘Risks of becoming an unprivileged user’
  lib/ansible/plugins/action/__init__.py
Labels: needs_revision, has_issue

#81632 [stable-2.15] tarfile: Handle deprecation warning for extract and extractall (#81545)
  changelogs/fragments/tarfile_extract_warn.yml
  lib/ansible/galaxy/role.py
  packaging/release.py
  test/integration/targets/ansible-galaxy-collection/library/setup_collections.py
  test/lib/ansible_test/_internal/commands/sanity/validate_modules.py
Labels: backport, needs_triage

#81633 [stable-2.14] tarfile: Handle deprecation warning for extract and extractall (#81545)
  changelogs/fragments/tarfile_extract_warn.yml
  lib/ansible/galaxy/role.py
  packaging/release.py
  test/integration/targets/ansible-galaxy-collection/library/setup_collections.py
  test/lib/ansible_test/_internal/commands/sanity/validate_modules.py
Labels: backport, needs_triage

#81634 [stable-2.13] tarfile: Handle deprecation warning for extract and extractall (#81545)
  changelogs/fragments/tarfile_extract_warn.yml
  lib/ansible/galaxy/role.py
  packaging/release.py
  test/integration/targets/ansible-galaxy-collection/library/setup_collections.py
  test/lib/ansible_test/_internal/commands/sanity/validate_modules.py
Labels: backport, needs_triage

#81400 Add type hints to ansible.utils.display::Display
  changelogs/fragments/80841-display-type-annotation.yml
  lib/ansible/executor/playbook_executor.py
  lib/ansible/playbook/play_context.py
  lib/ansible/plugins/connection/ssh.py
  lib/ansible/utils/display.py
  lib/ansible/utils/encrypt.py
  lib/ansible/vars/plugins.py
Labels: P2, stale_review, feature, has_issue

#81635 New release v2.15.4rc1
  changelogs/CHANGELOG-v2.15.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.15.4rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81636 New release v2.14.10rc1
  changelogs/CHANGELOG-v2.14.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.14.10rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81637 New release v2.13.12rc1
  changelogs/CHANGELOG-v2.13.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.13.12rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#79781 fix various Jinja plugin caching issues
  changelogs/fragments/jinja_plugin_cache_cleanup.yml
  lib/ansible/plugins/loader.py
  lib/ansible/template/__init__.py
  test/integration/targets/collections/posix.yml
Labels: bug, has_issue, affects_2.15

#80881 Support packaging and importlib.metadata for pip module
  changelogs/fragments/80488-pip-pkg-resources.yml
  lib/ansible/modules/pip.py
  test/integration/targets/pip/tasks/main.yml
  test/integration/targets/pip/tasks/no_setuptools.yml
Labels: P2, module, bug, has_issue, affects_2.16

#81641 Update Ansible release version to v2.14.10rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81642 Update Ansible release version to v2.13.12rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81640 Update Ansible release version to v2.15.4rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81646 Improve ansible-pull documentation
  lib/ansible/cli/pull.py
Labels: has_issue

#81653 Make `Currently supported...` and `Does nothing...` lines consistent
  lib/ansible/modules/user.py
Labels: module

#81657 Replace ConfigParser.readfp() with read_file()
  changelogs/fragments/81656-cf_readfp-deprecated.yml
  lib/ansible/module_utils/facts/system/local.py
  lib/ansible/plugins/lookup/ini.py
Labels: bug, has_issue

#81660 ansible-vault: Check if the destination is writable
  changelogs/fragments/ansible-vault.yml
  lib/ansible/parsing/vault/__init__.py
  test/integration/targets/ansible-vault/runme.sh
Labels: bug, has_issue

#81571 encrypt: deprecate passlib_or_crypt
  changelogs/fragments/passlib_or_crypt.yml
  lib/ansible/plugins/filter/core.py
  lib/ansible/utils/display.py
  lib/ansible/utils/encrypt.py
  test/units/utils/test_encrypt.py
Labels: stale_review, bug, has_issue

#81650 Lazy load Templar for [changed,failed]_when
  changelogs/fragments/basestrategy-lazy-templar.yml
  lib/ansible/plugins/strategy/__init__.py
Labels: bug

#81565 Only mark role as complete once it has a task run for the target host
  changelogs/fragments/role-deduplication-condition.yml
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/roles/role_complete.yml
  test/integration/targets/roles/roles/failed_when/tasks/main.yml
  test/integration/targets/roles/roles/recover/tasks/main.yml
  test/integration/targets/roles/roles/set_var/tasks/main.yml
  test/integration/targets/roles/roles/test_connectivity/tasks/main.yml
  test/integration/targets/roles/runme.sh
Labels: stale_review, bug, has_issue

#81450 ansible-doc: allow to filter by more than one collection
  changelogs/fragments/81450-list-filters.yml
  lib/ansible/cli/doc.py
  lib/ansible/collections/list.py
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/plugins/list.py
  test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol3/galaxy.yml
  test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol3/plugins/modules/test1.py
  test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol4/galaxy.yml
  test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol4/plugins/modules/test2.py
  test/integration/targets/ansible-doc/runme.sh
Labels: stale_ci, stale_review, bug, feature

#81639 Fix set filters to use set operations
  changelogs/fragments/set-filters.yml
  lib/ansible/plugins/filter/difference.yml
  lib/ansible/plugins/filter/intersect.yml
  lib/ansible/plugins/filter/mathstuff.py
  lib/ansible/plugins/filter/symmetric_difference.yml
  lib/ansible/plugins/filter/union.yml
  test/integration/targets/filter_mathstuff/tasks/main.yml
  test/units/plugins/filter/test_mathstuff.py
Labels: bug

#81681 New release v2.15.4
  changelogs/CHANGELOG-v2.15.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.15.4_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81682 New release v2.14.10
  changelogs/CHANGELOG-v2.14.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.14.10_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81683 New release v2.13.12
  changelogs/CHANGELOG-v2.13.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.13.12_summary.yaml
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#81684 Update Ansible release version to v2.15.4.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81686 Update Ansible release version to v2.13.12.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81679 ansible-galaxy-collection - fix config permissions for galaxy-importer
  test/lib/ansible_test/_internal/commands/integration/cloud/galaxy.py
Labels: test, needs_triage

#81685 Update Ansible release version to v2.14.10.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81677 env-setup.fish: Correct syntax errors
  hacking/env-setup.fish
Labels: bug

#81680 sanity: update requirements
  test/lib/ansible_test/_data/requirements/sanity.changelog.txt
  test/lib/ansible_test/_data/requirements/sanity.mypy.txt
  test/sanity/code-smell/package-data.requirements.txt
  test/sanity/code-smell/pymarkdown.requirements.txt
Labels: test, needs_triage

#81662 blockinfile: avoid crash on Python 3 when creating directory fails
  changelogs/fragments/81662-blockinfile-exc.yml
  lib/ansible/modules/blockinfile.py
  test/integration/targets/blockinfile/tasks/create_dir.yml
  test/integration/targets/blockinfile/tasks/main.yml
Labels: module, bug

#81586 galaxy: check if the target for symlink exists
  changelogs/fragments/galaxy_symlink.yml
  lib/ansible/galaxy/collection/__init__.py
  test/integration/targets/ansible-galaxy-collection/tasks/build.yml
Labels: needs_revision, stale_review, bug

#81697 Add an example for cleaning up the async job cache
  lib/ansible/modules/async_status.py
Labels: module

#81578 reboot: show last error message in verbose log
  changelogs/fragments/reboot.yml
  lib/ansible/plugins/action/reboot.py
Labels: stale_ci, bug, has_issue

#81707 inventory_ini: Handle SyntaxWarning in ini parsing
  changelogs/fragments/inventory_ini.yml
  lib/ansible/plugins/inventory/ini.py
  test/integration/targets/inventory_ini/inventory.ini
  test/integration/targets/inventory_ini/runme.sh
Labels: needs_triage, bug, has_issue

#81700 vars: handle exception in combine_vars
  changelogs/fragments/81659_varswithsources.yml
  lib/ansible/utils/vars.py
  lib/ansible/vars/manager.py
  test/units/utils/test_vars.py
Labels: bug, has_issue

#81724 Typo in documentation `then` -> `than`
  lib/ansible/modules/blockinfile.py
Labels: module, needs_triage

#81726 Fix ansible-test issues with detecting docker host and forwarding ports
  changelogs/fragments/ansible-test-docker-forwards.yml
  test/lib/ansible_test/_internal/docker_util.py
  test/lib/ansible_test/_internal/ssh.py
Labels: needs_revision, test

#81729 Remove deprecated APIs from ansible-doc
  changelogs/fragments/81716-ansible-doc.yml
  lib/ansible/cli/doc.py
  test/sanity/ignore.txt
Labels: stale_review, bug, has_issue

#81606 Always allow "no-other-choice" pre-release dependencies when resolving collection dependency tree
  changelogs/fragments/81606-ansible-galaxy-collection-pre-releases.yml
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/dependency_resolution/__init__.py
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  lib/ansible/galaxy/dependency_resolution/providers.py
  test/integration/targets/ansible-galaxy-collection/tasks/main.yml
  test/integration/targets/ansible-galaxy-collection/tasks/pinned_pre_releases_in_deptree.yml
  test/integration/targets/ansible-galaxy-collection/tasks/virtual_direct_requests.yml
  test/integration/targets/ansible-galaxy-collection/vars/main.yml
Labels: bug, has_issue

#81732 tests: update CloudStack test container to version 1.7.0.
  changelogs/fragments/81732-cloudstack-test-container-1.7.0.yml
  test/lib/ansible_test/_internal/commands/integration/cloud/cs.py
Labels: feature

#81619 Make sure paths are treated correctly when building collection files manifest
  changelogs/fragments/fix-build-files-manifest-walk.yml
  lib/ansible/galaxy/collection/__init__.py
  test/units/galaxy/test_collection.py
Labels: test, bug, feature, has_issue

#81738 Add intentional tests for dnf list
  test/integration/targets/dnf/tasks/repo.yml
Labels: test, needs_triage

#81745 Handle exception in interpreter discovery
  changelogs/fragments/interpreter_discovery.yml
  lib/ansible/executor/interpreter_discovery.py
  test/units/executor/test_interpreter_discovery.py
Labels: stale_review, bug, has_issue

#81733 Allow for searching handler subdir for included task via include_role
  changelogs/fragments/81722-handler-subdir-include_tasks.yml
  lib/ansible/playbook/included_file.py
  test/integration/targets/handlers/roles/include_role_include_tasks_handler/handlers/include_handlers.yml
  test/integration/targets/handlers/roles/include_role_include_tasks_handler/handlers/main.yml
  test/integration/targets/handlers/roles/include_role_include_tasks_handler/tasks/main.yml
  test/integration/targets/handlers/runme.sh
  test/integration/targets/handlers/test_include_tasks_in_include_role.yml
Labels: bug, has_issue

#81593 Deprecating paramiko options in base config
  changelogs/fragments/paramiko_globals.yml
  lib/ansible/config/base.yml
Labels: feature

#81753 Harden the ansiballz and respawn python templates
  changelogs/fragments/py-tmpl-hardening.yml
  lib/ansible/executor/module_common.py
  lib/ansible/module_utils/common/respawn.py
Labels: bug

#81599 ansible-galaxy fix scm dependency error
  changelogs/fragments/galaxy_dep_res_msgs.yml
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
Labels: bug

#81706 ansible-test - Skip pylint test on Python 3.12
  changelogs/fragments/ansible-test-pylint-python-3.12.yml
  test/integration/targets/ansible-test-sanity-pylint/runme.sh
  test/lib/ansible_test/_internal/commands/sanity/pylint.py
Labels: feature

#81757 [stable-2.16] ansible-test - Skip pylint test on Python 3.12 (#81706)
  changelogs/fragments/ansible-test-pylint-python-3.12.yml
  test/integration/targets/ansible-test-sanity-pylint/runme.sh
  test/lib/ansible_test/_internal/commands/sanity/pylint.py
Labels: backport, feature

#81584 Daemonize follow-up fixes
  changelogs/fragments/81584-daemonize-follow-up-fixes.yml
  lib/ansible/module_utils/service.py
Labels: stale_ci, bug

#81756 add intentional coverage for copy with force=false
  test/integration/targets/copy/tasks/tests.yml
Labels: test

#81763 Fix typo in action_core.py
  lib/ansible/plugins/doc_fragments/action_core.py
Labels: needs_triage

#81746 [backport][stable-2.16] Always allow "no-other-choice" pre-release dependencies when resolving collection dependency tree
  changelogs/fragments/81606-ansible-galaxy-collection-pre-releases.yml
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/dependency_resolution/__init__.py
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  lib/ansible/galaxy/dependency_resolution/providers.py
  test/integration/targets/ansible-galaxy-collection/tasks/main.yml
  test/integration/targets/ansible-galaxy-collection/tasks/pinned_pre_releases_in_deptree.yml
  test/integration/targets/ansible-galaxy-collection/tasks/virtual_direct_requests.yml
  test/integration/targets/ansible-galaxy-collection/vars/main.yml
Labels: backport, needs_triage, bug

#81759 2.16: Allow for searching handler subdir for included task via include_role
  changelogs/fragments/81722-handler-subdir-include_tasks.yml
  lib/ansible/playbook/included_file.py
  test/integration/targets/handlers/roles/include_role_include_tasks_handler/handlers/include_handlers.yml
  test/integration/targets/handlers/roles/include_role_include_tasks_handler/handlers/main.yml
  test/integration/targets/handlers/roles/include_role_include_tasks_handler/tasks/main.yml
  test/integration/targets/handlers/runme.sh
  test/integration/targets/handlers/test_include_tasks_in_include_role.yml
Labels: backport, needs_triage, bug

#81766 Daemonize follow-up fixes (#81584) - 2.16
  changelogs/fragments/81584-daemonize-follow-up-fixes.yml
  lib/ansible/module_utils/service.py
Labels: backport, needs_triage, bug

#81778 New release v2.16.0b1
  changelogs/CHANGELOG-v2.16.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.16.0b1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81762 Add lineinfile integration test for removing a nonexistent line
  test/integration/targets/lineinfile/tasks/main.yml
Labels: test

#81768 Add more mount info to facts
  changelogs/fragments/80478-extend-mount-info.yml
  lib/ansible/module_utils/facts/hardware/linux.py
  test/units/module_utils/facts/hardware/test_linux.py
Labels: bug, has_issue

#81771 Misc. fixes in base.yml
  lib/ansible/config/base.yml
Labels: needs_triage, bug

#81779 Update Ansible release version to v2.16.0b1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81780 Prevent roles from using symlinks to overwrite files outside of the installation directory
  changelogs/fragments/cve-2023-5115.yml
  lib/ansible/galaxy/role.py
  test/integration/targets/ansible-galaxy-role/files/create-role-archive.py
  test/integration/targets/ansible-galaxy-role/tasks/dir-traversal.yml
  test/integration/targets/ansible-galaxy-role/tasks/main.yml
Labels: bug

#81788 file: add a note about follow=false
  lib/ansible/modules/file.py
Labels: module, needs_triage, has_issue

#81784 Fix typo in finished.yml
  lib/ansible/plugins/test/finished.yml
Labels: needs_triage

#81730 Test heuristic_log_sanitize
  test/integration/targets/module_utils/library/test_heuristic_log_sanitize.py
  test/integration/targets/module_utils/module_utils_test.yml
Labels: test

#81740 Add intentional tests for dnf install rpm when higher version is installed
  changelogs/fragments/dnf5-from-rpm-allow_downgrade.yml
  lib/ansible/modules/dnf5.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: test, module, stale_review

#81538 winrm - make command input more resiliant
  changelogs/fragments/winrm-send-input.yml
  lib/ansible/plugins/connection/winrm.py
Labels: stale_ci, bug

#81787 [stable-2.13] Prevent roles from using symlinks to overwrite files outside of the installation directory (#81780)
  changelogs/fragments/cve-2023-5115.yml
  lib/ansible/galaxy/role.py
  test/integration/targets/ansible-galaxy-role/files/create-role-archive.py
  test/integration/targets/ansible-galaxy-role/tasks/dir-traversal.yml
  test/integration/targets/ansible-galaxy-role/tasks/main.yml
Labels: backport, needs_triage

#81786 [stable-2.14] Prevent roles from using symlinks to overwrite files outside of the installation directory (#81780)
  changelogs/fragments/cve-2023-5115.yml
  lib/ansible/galaxy/role.py
  test/integration/targets/ansible-galaxy-role/files/create-role-archive.py
  test/integration/targets/ansible-galaxy-role/tasks/dir-traversal.yml
  test/integration/targets/ansible-galaxy-role/tasks/main.yml
Labels: backport, needs_triage

#81785 [stable-2.15] Prevent roles from using symlinks to overwrite files outside of the installation directory (#81780)
  changelogs/fragments/cve-2023-5115.yml
  lib/ansible/galaxy/role.py
  test/integration/targets/ansible-galaxy-role/files/create-role-archive.py
  test/integration/targets/ansible-galaxy-role/tasks/dir-traversal.yml
  test/integration/targets/ansible-galaxy-role/tasks/main.yml
Labels: backport, needs_triage

#81783 [stable-2.16] Prevent roles from using symlinks to overwrite files outside of the installation directory (#81780)
  changelogs/fragments/cve-2023-5115.yml
  lib/ansible/galaxy/role.py
  test/integration/targets/ansible-galaxy-role/files/create-role-archive.py
  test/integration/targets/ansible-galaxy-role/tasks/dir-traversal.yml
  test/integration/targets/ansible-galaxy-role/tasks/main.yml
Labels: backport, needs_triage

#81790 Update test container versions for stable-2.16
  test/lib/ansible_test/_data/completion/docker.txt
Labels: backport, test, needs_triage

#81794 winrm - make command input more resiliant (#81538) - 2.16
  changelogs/fragments/winrm-send-input.yml
  lib/ansible/plugins/connection/winrm.py
Labels: backport, needs_triage, bug

#81643 [2.15] fix various Jinja plugin caching issues (#79781)
  changelogs/fragments/jinja_plugin_cache_cleanup.yml
  lib/ansible/plugins/loader.py
  lib/ansible/template/__init__.py
  test/integration/targets/collections/posix.yml
Labels: backport, needs_triage, bug

#81758 2.15: Allow for searching handler subdir for included task via include_role
  changelogs/fragments/81722-handler-subdir-include_tasks.yml
  lib/ansible/playbook/included_file.py
  test/integration/targets/handlers/roles/include_role_include_tasks_handler/handlers/include_handlers.yml
  test/integration/targets/handlers/roles/include_role_include_tasks_handler/handlers/main.yml
  test/integration/targets/handlers/roles/include_role_include_tasks_handler/tasks/main.yml
  test/integration/targets/handlers/runme.sh
  test/integration/targets/handlers/test_include_tasks_in_include_role.yml
Labels: backport, needs_triage, bug

#81793 winrm - make command input more resiliant (#81538) - 2.15
  changelogs/fragments/winrm-send-input.yml
  lib/ansible/plugins/connection/winrm.py
Labels: backport, needs_triage, bug

#81644 [2.14] fix various Jinja plugin caching issues (#79781)
  changelogs/fragments/jinja_plugin_cache_cleanup.yml
  lib/ansible/plugins/loader.py
  lib/ansible/template/__init__.py
  test/integration/targets/collections/posix.yml
Labels: backport, needs_triage, bug

#81792 winrm - make command input more resiliant (#81538) - 2.14
  changelogs/fragments/winrm-send-input.yml
  lib/ansible/plugins/connection/winrm.py
Labels: backport, needs_triage, bug

#81789 Update test container versions for devel
  test/lib/ansible_test/_data/completion/docker.txt
Labels: test, needs_triage

#81803 systemd_service: add a note about module rename
  lib/ansible/modules/systemd_service.py
Labels: module, has_issue

#81810 ansible-test - Update sanity test requirements
  test/lib/ansible_test/_data/requirements/sanity.changelog.txt
  test/lib/ansible_test/_data/requirements/sanity.mypy.txt
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  test/sanity/code-smell/package-data.requirements.txt
  test/sanity/code-smell/pymarkdown.requirements.txt
Labels: needs_revision, test

#81811 [stable-2.16] ansible-test - Update sanity test requirements (#81810)
  test/lib/ansible_test/_data/requirements/sanity.changelog.txt
  test/lib/ansible_test/_data/requirements/sanity.mypy.txt
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  test/sanity/code-smell/package-data.requirements.txt
  test/sanity/code-smell/pymarkdown.requirements.txt
Labels: needs_revision, backport, test

#81775 Add count and mandatory_count parameters in regex_replace filter
  changelogs/fragments/81775-add-regex_replace-parameters.yml
  lib/ansible/plugins/filter/core.py
  lib/ansible/plugins/filter/regex_replace.yml
  test/integration/targets/filter_core/tasks/main.yml
Labels: stale_review, feature

#81719 Provide more info about plugin in deprecation message
  changelogs/fragments/80561.yml
  lib/ansible/plugins/loader.py
  test/integration/targets/collections/runme.sh
Labels: needs_revision, bug, has_issue
