Repository ansible/ansible, pull requests merged in 2023-08, with the labels that each got.

#81386 Fix backport of #81379
  packaging/pep517_backend/_generate_man.py
Labels: backport, needs_triage

#81387 Fix backport of #81379
  packaging/pep517_backend/_generate_man.py
Labels: backport, needs_triage

#81124 ansible-test: remove alpine 3.17
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/a_test_rmv_alpine_317.yml
  test/lib/ansible_test/_data/completion/remote.txt
Labels: needs_revision, test, WIP, stale_ci, has_issue, affects_2.16

#81395 Omit pre-built man pages from sdist
  MANIFEST.in
  changelogs/fragments/omit-man-pages-from-sdist.yml
  packaging/cli-doc/build.py
  packaging/cli-doc/man.j2
  packaging/cli-doc/rst.j2
  packaging/pep517_backend/__init__.py
  packaging/pep517_backend/_backend.py
  packaging/pep517_backend/_generate_man.py
  packaging/pep517_backend/hooks.py
  packaging/release.py
  pyproject.toml
  test/integration/targets/canonical-pep517-self-packaging/aliases
  test/integration/targets/canonical-pep517-self-packaging/minimum-build-constraints.txt
  test/integration/targets/canonical-pep517-self-packaging/modernish-build-constraints.txt
  test/integration/targets/canonical-pep517-self-packaging/runme.sh
  test/integration/targets/canonical-pep517-self-packaging/runme_test.py
  test/integration/targets/packaging_cli-doc/aliases
  test/integration/targets/packaging_cli-doc/runme.sh
  test/integration/targets/packaging_cli-doc/template.j2
  test/integration/targets/packaging_cli-doc/verify.py
  test/lib/ansible_test/_internal/classification/__init__.py
  test/lib/ansible_test/_internal/commands/sanity/mypy.py
  test/lib/ansible_test/_util/controller/sanity/mypy/packaging.ini
  test/sanity/code-smell/package-data.py
  test/sanity/code-smell/package-data.requirements.in
Labels: has_issue

#81315 CI: remove FreeBSD 12.4 from test matrix
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/freebsd_12_4_removal.yml
  test/lib/ansible_test/_data/completion/remote.txt
Labels: stale_ci, has_issue

#81397 [stable-2.15] Omit pre-built man pages from sdist (#81395)
  MANIFEST.in
  changelogs/fragments/omit-man-pages-from-sdist.yml
  packaging/cli-doc/build.py
  packaging/cli-doc/man.j2
  packaging/cli-doc/rst.j2
  packaging/pep517_backend/__init__.py
  packaging/pep517_backend/_backend.py
  packaging/pep517_backend/_generate_man.py
  packaging/pep517_backend/hooks.py
  packaging/release.py
  pyproject.toml
  test/integration/targets/canonical-pep517-self-packaging/aliases
  test/integration/targets/canonical-pep517-self-packaging/minimum-build-constraints.txt
  test/integration/targets/canonical-pep517-self-packaging/modernish-build-constraints.txt
  test/integration/targets/canonical-pep517-self-packaging/runme.sh
  test/integration/targets/canonical-pep517-self-packaging/runme_test.py
  test/integration/targets/packaging_cli-doc/aliases
  test/integration/targets/packaging_cli-doc/runme.sh
  test/integration/targets/packaging_cli-doc/template.j2
  test/integration/targets/packaging_cli-doc/verify.py
  test/lib/ansible_test/_internal/classification/__init__.py
  test/lib/ansible_test/_internal/commands/sanity/mypy.py
  test/lib/ansible_test/_util/controller/sanity/mypy/packaging.ini
  test/sanity/code-smell/package-data.py
  test/sanity/code-smell/package-data.requirements.in
Labels: backport

#81398 Remove unused sanity test code
  test/sanity/code-smell/package-data.py
Labels: test

#81403 [stable-2.15] Fix os.walk issues in package-data sanity test (#80703).
  test/sanity/code-smell/package-data.json
  test/sanity/code-smell/package-data.py
Labels: backport, test

#81263 2.15: Remove BOTMETA.yml and sanity tests for it (#81198)
  .github/BOTMETA.yml
  test/sanity/code-smell/botmeta.json
  test/sanity/code-smell/botmeta.py
  test/sanity/code-smell/botmeta.requirements.in
  test/sanity/code-smell/botmeta.requirements.txt
Labels: backport, test, needs_triage, feature

#81264 2.14: Remove BOTMETA.yml and sanity tests for it (#81198)
  .github/BOTMETA.yml
  test/sanity/code-smell/botmeta.json
  test/sanity/code-smell/botmeta.py
  test/sanity/code-smell/botmeta.requirements.in
  test/sanity/code-smell/botmeta.requirements.txt
Labels: needs_revision, backport, test, needs_triage, feature

#81265 2.13: Remove BOTMETA.yml and sanity tests for it (#81198)
  .github/BOTMETA.yml
  test/sanity/code-smell/botmeta.json
  test/sanity/code-smell/botmeta.py
  test/sanity/code-smell/botmeta.requirements.in
  test/sanity/code-smell/botmeta.requirements.txt
Labels: needs_revision, backport, test, needs_triage, stale_ci, feature

#81411 [stable-2.15] Add changelog fragment for docs/examples removal (#81410)
  changelogs/fragments/remove-docs-examples.yml
Labels: backport, needs_triage

#81412 [stable-2.14] Add changelog fragment for docs/examples removal (#81410)
  changelogs/fragments/remove-docs-examples.yml
Labels: backport, needs_triage

#81414 [stable-2.15] Clean up MANIFEST.in
  MANIFEST.in
  changelogs/fragments/manifest-in-cleanup.yml
  test/sanity/code-smell/package-data.py
Labels: backport, needs_triage, bug

#81415 [stable-2.14] Clean up MANIFEST.in
  MANIFEST.in
  changelogs/fragments/manifest-in-cleanup.yml
  test/sanity/code-smell/package-data.py
Labels: backport, needs_triage, bug

#81416 [stable-2.13] Clean up MANIFEST.in
  MANIFEST.in
  changelogs/fragments/manifest-in-cleanup.yml
  test/sanity/code-smell/package-data.py
Labels: backport, needs_triage, bug

#81418 ansible-test - Update source layout detection
  changelogs/fragments/ansible-test-layout-detection.yml
  test/lib/ansible_test/_internal/ansible_util.py
  test/lib/ansible_test/_internal/provider/layout/ansible.py
Labels: feature

#81390 Update bot link in the GH templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#81385 password_hash - fix bcrypt algorithm when passlib is not installed
  changelogs/fragments/password_hash-fix-crypt-salt-bcrypt.yml
  lib/ansible/utils/encrypt.py
  test/integration/targets/filter_core/tasks/main.yml
Labels: stale_review, bug

#81401 Fix comment about authorization
  lib/ansible/modules/user.py
Labels: needs_revision, module, needs_triage

#81405 service action: improve documenation about service and service
  lib/ansible/modules/service.py
Labels: module, has_issue

#81426 yum_repository: deprecate keepcache parameter
  changelogs/fragments/yum_repository_keepcache.yml
  lib/ansible/modules/yum_repository.py
Labels: module, bug, has_issue

#81428 [stable-2.15] Revert "define code owners to support branch-protection rules on docs (#81041)"
  .github/CODEOWNERS
Labels: backport, needs_triage, feature

#81429 [stable-2.14] Revert "define code owners to support branch-protection rules on docs (#81041)"
  .github/CODEOWNERS
Labels: backport, needs_triage, feature

#81430 [stable-2.13] Revert "define code owners to support branch-protection rules on docs (#81041)"
  .github/CODEOWNERS
Labels: backport, needs_triage, feature

#81427 Overhaul package-data sanity test
  test/lib/ansible_test/_internal/python_requirements.py
  test/sanity/code-smell/package-data.py
  test/sanity/code-smell/package-data.requirements.in
  test/sanity/code-smell/package-data.requirements.txt
Labels: test

#81431 [stable-2.15] Update update-sanity-requirements.py script (#81424)
  hacking/update-sanity-requirements.py
Labels: backport, test, needs_triage

#81423 galaxy: Cross check the collection type
  changelogs/fragments/galaxy_check_type.yml
  lib/ansible/galaxy/collection/concrete_artifact_manager.py
  test/units/galaxy/test_collection_install.py
Labels: stale_review, bug, has_issue

#81406 dpkg_selections: Check if package exists before selection operation
  changelogs/fragments/dpkg_selections.yml
  lib/ansible/modules/dpkg_selections.py
  test/integration/targets/dpkg_selections/tasks/dpkg_selections.yaml
Labels: module, stale_review, bug, has_issue

#81235 [stable-2.14] Module docs fixes
  lib/ansible/modules/getent.py
  lib/ansible/modules/git.py
  lib/ansible/modules/setup.py
  lib/ansible/modules/stat.py
  lib/ansible/modules/validate_argument_spec.py
Labels: backport, module, needs_triage, docs, affects_2.14

#81290 [stable-2.14] The split filter was added in ansible-core 2.11. (#81275)
  lib/ansible/plugins/filter/split.yml
Labels: backport, needs_triage

#81394 [stable-2.14] fixed become page link in PE error message (#81391)
  lib/ansible/plugins/action/__init__.py
Labels: backport, needs_triage, bug

#81435 [stable-2.14] ansible-test - Update source layout detection (#81418)
  changelogs/fragments/ansible-test-layout-detection.yml
  test/lib/ansible_test/_internal/ansible_util.py
  test/lib/ansible_test/_internal/provider/layout/ansible.py
Labels: backport, needs_triage, feature

#81438 [stable-2.14] Overhaul package-data sanity test (#81427)
  test/lib/ansible_test/_internal/python_requirements.py
  test/sanity/code-smell/package-data.py
  test/sanity/code-smell/package-data.requirements.in
  test/sanity/code-smell/package-data.requirements.txt
Labels: backport, test, needs_triage

#81236 [stable-2.15] Module docs fixes
  lib/ansible/modules/getent.py
  lib/ansible/modules/git.py
  lib/ansible/modules/setup.py
  lib/ansible/modules/stat.py
  lib/ansible/modules/validate_argument_spec.py
  lib/ansible/modules/yum.py
Labels: backport, module, needs_triage, docs, affects_2.15

#81291 [stable-2.15] The split filter was added in ansible-core 2.11. (#81275)
  lib/ansible/plugins/filter/split.yml
Labels: backport, needs_triage

#81393 [stable-2.15] fixed become page link in PE error message (#81391)
  lib/ansible/plugins/action/__init__.py
Labels: backport, needs_triage, bug

#81434 [stable-2.15] ansible-test - Update source layout detection (#81418)
  changelogs/fragments/ansible-test-layout-detection.yml
  test/lib/ansible_test/_internal/ansible_util.py
  test/lib/ansible_test/_internal/provider/layout/ansible.py
Labels: backport, needs_triage, feature

#81439 [stable-2.15] Overhaul package-data sanity test (#81427)
  test/lib/ansible_test/_internal/python_requirements.py
  test/sanity/code-smell/package-data.py
  test/sanity/code-smell/package-data.requirements.in
  test/sanity/code-smell/package-data.requirements.txt
Labels: backport, test, needs_triage

#81257 [stable-2.15] urls - remove deprecated client key calls (#80751)
  changelogs/fragments/urls-client-cert-py12.yml
  lib/ansible/module_utils/urls.py
  test/units/module_utils/urls/test_Request.py
Labels: backport, needs_triage, bug

#81324 [2.15] Consider all configured collection paths when installing collections
  changelogs/fragments/a-g-col-prevent-reinstalling-satisfied-req.yml
  lib/ansible/cli/galaxy.py
  lib/ansible/galaxy/collection/__init__.py
  test/integration/targets/ansible-galaxy-collection-scm/tasks/multi_collection_repo_all.yml
  test/units/galaxy/test_collection_install.py
Labels: backport, bug

#81353 [stable-2.15] fix networking path (#81295)
  changelogs/fragments/forced_local+fix+.yml
  lib/ansible/executor/task_executor.py
Labels: backport, needs_triage, bug

#81425 [2.15] password_hash - fix bcrypt algorithm when passlib is not installed
  changelogs/fragments/password_hash-fix-crypt-salt-bcrypt.yml
  lib/ansible/utils/encrypt.py
  test/integration/targets/filter_core/tasks/main.yml
Labels: backport, bug

#81437 [stable-2.13] Overhaul package-data sanity test (#81427)
  test/lib/ansible_test/_internal/python_requirements.py
  test/sanity/code-smell/package-data.py
  test/sanity/code-smell/package-data.requirements.in
  test/sanity/code-smell/package-data.requirements.txt
Labels: needs_revision, backport, test, needs_triage

#81436 [stable-2.13] ansible-test - Update source layout detection (#81418)
  changelogs/fragments/ansible-test-layout-detection.yml
  test/lib/ansible_test/_internal/ansible_util.py
  test/lib/ansible_test/_internal/provider/layout/ansible.py
Labels: needs_revision, backport, needs_triage, feature

#80257 iptables chain creation does not populate with a rule
  changelogs/fragments/80257-iptables-chain-creation-does-not-populate-a-rule.yml
  lib/ansible/modules/iptables.py
  test/integration/targets/iptables/tasks/chain_management.yml
  test/units/modules/test_iptables.py
Labels: module, bug, has_issue, affects_2.15

#81422 filters vault/unvault fix vault_id parameter usage
  changelogs/fragments/vault_unvault_id_fix.yml
  lib/ansible/plugins/filter/encryption.py
  test/integration/targets/filter_encryption/base.yml
  test/integration/targets/unvault/main.yml
  test/integration/targets/unvault/runme.sh
Labels: bug, has_issue

#81459 New release v2.15.3rc1
  changelogs/CHANGELOG-v2.15.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.15.3rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81458 New release v2.14.9rc1
  changelogs/CHANGELOG-v2.14.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.14.9rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81461 Update Ansible release version to v2.14.9rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81462 Update Ansible release version to v2.15.3rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81399 Sanity: Bump version to match Python 3.12
  test/lib/ansible_test/_data/requirements/sanity.ansible-doc.txt
  test/lib/ansible_test/_data/requirements/sanity.changelog.txt
  test/lib/ansible_test/_data/requirements/sanity.import.plugin.txt
  test/lib/ansible_test/_data/requirements/sanity.import.txt
  test/lib/ansible_test/_data/requirements/sanity.integration-aliases.txt
  test/lib/ansible_test/_data/requirements/sanity.mypy.txt
  test/lib/ansible_test/_data/requirements/sanity.pep8.txt
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  test/lib/ansible_test/_data/requirements/sanity.runtime-metadata.txt
  test/lib/ansible_test/_data/requirements/sanity.validate-modules.txt
  test/lib/ansible_test/_data/requirements/sanity.yamllint.txt
  test/sanity/code-smell/deprecated-config.requirements.txt
  test/sanity/code-smell/package-data.requirements.txt
  test/sanity/code-smell/pymarkdown.requirements.txt
  test/sanity/code-smell/update-bundled.requirements.txt
Labels: bug

#81471 Bump test container versions to latest
  test/lib/ansible_test/_data/completion/docker.txt
Labels: bug

#81460 restore conditional lookup nerfing
  lib/ansible/playbook/conditional.py
  test/integration/targets/conditionals/play.yml
Labels: bug

#80874 Revert logic to use Popen.communicate
  lib/ansible/module_utils/basic.py
  test/integration/targets/command_shell/scripts/yoink.sh
  test/integration/targets/command_shell/tasks/main.yml
  test/units/module_utils/basic/test_run_command.py
Labels: stale_review, bug, has_issue, affects_2.16

#81481 Fix constructed inventory plugin unit test
  test/units/plugins/inventory/test_constructed.py
Labels: test

#81482 Remove unreachable code in password lookup test
  test/units/plugins/lookup/test_password.py
Labels: test

#81483 Add unit tests for module_utils.compat.datetime
  test/units/module_utils/compat/__init__.py
  test/units/module_utils/compat/test_datetime.py
Labels: test

#79097 Update cliconf-> __init__.py -> get_capabilities()
  lib/ansible/plugins/cliconf/__init__.py
Labels: networking, needs_triage, stale_ci, new_contributor, docs, small_patch, affects_2.15

#81473 Add documentation for systemd reload
  lib/ansible/modules/systemd_service.py
Labels: module, has_issue

#81488 Clean up release script
  packaging/release.py
  test/lib/ansible_test/_internal/commands/sanity/mypy.py
Labels: bug

#75980 Document return values of template module
  lib/ansible/modules/template.py
Labels: module, core_review, support:core, stale_review, new_contributor, docs, P3

#81495 sanity: Document pep8 known issue with Python 3.12
  changelogs/fragments/pep8-known-issue.yml
Labels: needs_revision, bug

#79129 fix incorrect ansible_managed formatting
  changelogs/fragments/79129-ansible-managed-filename-format.yaml
  lib/ansible/template/__init__.py
  test/integration/targets/template/ansible_managed_79129.yml
  test/integration/targets/template/runme.sh
  test/integration/targets/template/templates/%necho Onii-chan help Im stuck;exit 1%n.j2
  test/integration/targets/template/templates/completely{{ 1 % 0 }} safe template.j2
Labels: needs_revision, new_contributor, bug, affects_2.15

#81506 New release v2.15.3
  changelogs/CHANGELOG-v2.15.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.15.3_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81507 New release v2.14.9
  changelogs/CHANGELOG-v2.14.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.14.9_summary.yaml
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#81509 Update Ansible release version to v2.15.3.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#81510 Update Ansible release version to v2.14.9.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#81497 [stable-2.14] Replace FreeBSD 12.3 w/ 12.4 in CI & ansible-test
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/freebsd-12.3-replacement.yml
  test/lib/ansible_test/_data/completion/remote.txt
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: backport

#81498 [stable-2.13] Replace FreeBSD 12.{3->4} & 13.{0->1} @ testing
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/freebsd-12.3-replacement.yml
  changelogs/fragments/freebsd-13.0-replacement.yml
  test/lib/ansible_test/_data/completion/remote.txt
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: backport

#81489 [stable-2.15] Clean up release script (#81488)
  packaging/release.py
  test/lib/ansible_test/_internal/commands/sanity/mypy.py
Labels: backport, test, bug, feature

#81490 [stable-2.14] Clean up release script (#81488)
  packaging/release.py
Labels: backport, bug

#81478 [stable-2.15] Fix f-string whitespace in release script (#81477)
  packaging/release.py
Labels: backport, bug

#81479 [stable-2.14] Fix f-string whitespace in release script (#81477)
  packaging/release.py
Labels: backport, bug

#81480 [stable-2.13] Fix f-string whitespace in release script (#81477)
  packaging/release.py
Labels: backport, bug

#81358 Last handler with same name wins for listen too
  changelogs/fragments/81013-handlers-listen-last-defined-only.yml
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/handlers/roles/test_listen_role_dedup_global/handlers/main.yml
  test/integration/targets/handlers/roles/test_listen_role_dedup_role1/meta/main.yml
  test/integration/targets/handlers/roles/test_listen_role_dedup_role1/tasks/main.yml
  test/integration/targets/handlers/roles/test_listen_role_dedup_role2/meta/main.yml
  test/integration/targets/handlers/roles/test_listen_role_dedup_role2/tasks/main.yml
  test/integration/targets/handlers/runme.sh
  test/integration/targets/handlers/test_listen_role_dedup.yml
Labels: bug, has_issue

#81518 docs: Update examples in systemd_service to use the new name
  lib/ansible/modules/systemd_service.py
Labels: module

#81485 Add ability to filter find on mode
  changelogs/fragments/find-mode.yml
  lib/ansible/modules/find.py
  test/integration/targets/find/tasks/main.yml
  test/integration/targets/find/tasks/mode.yml
Labels: module, stale_review, feature

#78860 Deprecate STRING_CONVERSION_ACTION
  changelogs/fragments/deprecated_string_conversion_action.yml
  lib/ansible/config/base.yml
Labels: windows, core_review, stale_ci, support:core, bug, affects_2.15

#81526 Remove obsolete text from release.py PR template
  packaging/release.py
Labels: feature

#81527 [stable-2.15] Remove obsolete text from release.py PR template (#81526)
  packaging/release.py
Labels: backport, feature

#81528 [stable-2.14] Remove obsolete text from release.py PR template (#81526)
  packaging/release.py
Labels: backport, feature

#81529 [stable-2.13] Remove obsolete text from release.py PR template (#81526)
  packaging/release.py
Labels: backport, feature

#81521 Pre-calculate date early and use it for all zipfile writes
  changelogs/fragments/80089-prevent-module-build-date-issue.yml
  lib/ansible/executor/module_common.py
Labels: stale_review, bug, has_issue

#81524 include_role: expose vars from parent roles to role's handlers
  changelogs/fragments/80459-handlers-nested-includes-vars.yml
  lib/ansible/playbook/role_include.py
  test/integration/targets/handlers/roles/r1-dep_chain-vars/defaults/main.yml
  test/integration/targets/handlers/roles/r1-dep_chain-vars/tasks/main.yml
  test/integration/targets/handlers/roles/r2-dep_chain-vars/handlers/main.yml
  test/integration/targets/handlers/roles/r2-dep_chain-vars/tasks/main.yml
  test/integration/targets/handlers/runme.sh
Labels: needs_triage, bug, has_issue

#81531 "retries" without "until": retry until success
  changelogs/fragments/20802-until-default.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/playbook/task.py
  test/integration/targets/until/tasks/main.yml
Labels: needs_triage, feature

#81537 ansible-test - Always use managed entry points
  changelogs/fragments/ansible-test-entry-points.yml
  test/integration/targets/ansible-test-installed/aliases
  test/integration/targets/ansible-test-installed/ansible_collections/ns/col/tests/integration/targets/installed/aliases
  test/integration/targets/ansible-test-installed/ansible_collections/ns/col/tests/integration/targets/installed/runme.sh
  test/integration/targets/ansible-test-installed/runme.sh
  test/lib/ansible_test/_internal/ansible_util.py
  test/lib/ansible_test/_internal/commands/sanity/bin_symlinks.py
  test/lib/ansible_test/_internal/constants.py
  test/lib/ansible_test/_internal/delegation.py
  test/lib/ansible_test/_internal/util.py
Labels: bug

#79999 Fix macos defaults
  changelogs/fragments/79999-ansible-user-tweak-macos-defaults.yaml
  lib/ansible/modules/user.py
  test/integration/targets/user/tasks/test_create_user.yml
  test/integration/targets/user/vars/main.yml
Labels: module, stale_review, new_contributor, bug, has_issue, affects_2.15

#81552 ansible-test - Limit deprecated check to core
  changelogs/fragments/pylint-deprecated-comment-checker.yml
  test/lib/ansible_test/_util/controller/sanity/pylint/config/collection.cfg
Labels: feature

#81556 Unit test cleanup
  test/units/utils/test_cleanup_tmp_file.py
  test/units/utils/test_display.py
Labels: test

#81484 debconf: idempotency for password question
  changelogs/fragments/debconf.yml
  lib/ansible/modules/debconf.py
  test/integration/targets/debconf/tasks/main.yml
Labels: module, bug, has_issue

#81557 group: remove extraneous warning
  changelogs/fragments/group_warning.yml
  lib/ansible/modules/group.py
Labels: module, bug, has_issue

#81559 fix typo in example human_to_bytes filter
  lib/ansible/plugins/filter/human_to_bytes.yml
Labels: needs_triage

#81519 Fix pause cpu consumption
  changelogs/fragments/fix-display-prompt-cpu-consumption.yml
  lib/ansible/utils/display.py
Labels: stale_review, bug, has_issue

#81539 [stable-2.15] ansible-test - Always use managed entry points (#81537)
  changelogs/fragments/ansible-test-entry-points.yml
  test/integration/targets/ansible-test-installed/aliases
  test/integration/targets/ansible-test-installed/ansible_collections/ns/col/tests/integration/targets/installed/aliases
  test/integration/targets/ansible-test-installed/ansible_collections/ns/col/tests/integration/targets/installed/runme.sh
  test/integration/targets/ansible-test-installed/runme.sh
  test/lib/ansible_test/_internal/ansible_util.py
  test/lib/ansible_test/_internal/commands/sanity/bin_symlinks.py
  test/lib/ansible_test/_internal/constants.py
  test/lib/ansible_test/_internal/delegation.py
  test/lib/ansible_test/_internal/util.py
Labels: backport, bug

#81540 [stable-2.14] ansible-test - Always use managed entry points (#81537)
  changelogs/fragments/ansible-test-entry-points.yml
  test/integration/targets/ansible-test-installed/aliases
  test/integration/targets/ansible-test-installed/ansible_collections/ns/col/tests/integration/targets/installed/aliases
  test/integration/targets/ansible-test-installed/ansible_collections/ns/col/tests/integration/targets/installed/runme.sh
  test/integration/targets/ansible-test-installed/runme.sh
  test/lib/ansible_test/_internal/ansible_util.py
  test/lib/ansible_test/_internal/commands/sanity/bin_symlinks.py
  test/lib/ansible_test/_internal/constants.py
  test/lib/ansible_test/_internal/delegation.py
  test/lib/ansible_test/_internal/util.py
Labels: backport, bug

#81541 [stable-2.13] ansible-test - Always use managed entry points (#81537).
  changelogs/fragments/ansible-test-entry-points.yml
  test/integration/targets/ansible-test-installed/aliases
  test/integration/targets/ansible-test-installed/ansible_collections/ns/col/tests/integration/targets/installed/aliases
  test/integration/targets/ansible-test-installed/ansible_collections/ns/col/tests/integration/targets/installed/runme.sh
  test/integration/targets/ansible-test-installed/runme.sh
  test/lib/ansible_test/_internal/ansible_util.py
  test/lib/ansible_test/_internal/commands/sanity/bin_symlinks.py
  test/lib/ansible_test/_internal/constants.py
  test/lib/ansible_test/_internal/delegation.py
  test/lib/ansible_test/_internal/util.py
Labels: backport, bug

#81494 Remove duplicated and unused FILE_ATTRIBUTES constant
  changelogs/fragments/81494-remove-duplicated-file-attribute-constant.yml
  lib/ansible/module_utils/basic.py
Labels: stale_review, bug

#75194 user - set current expiration correctly when no shadow entry exists
  changelogs/fragments/71916-user-expires-int.yml
  lib/ansible/modules/user.py
  test/integration/targets/user/tasks/main.yml
  test/integration/targets/user/tasks/test_expires_no_shadow.yml
Labels: module, core_review, support:core, bug, P3, has_issue, affects_2.12

#81472 PowerShell - remove uneeded dotnet code for future compatibility
  changelogs/fragments/dotnet-preparation.yml
  lib/ansible/module_utils/csharp/Ansible.AccessToken.cs
  lib/ansible/module_utils/csharp/Ansible.Become.cs
  lib/ansible/module_utils/csharp/Ansible.Privilege.cs
  lib/ansible/module_utils/csharp/Ansible.Process.cs
  test/integration/targets/module_utils_Ansible.Become/library/ansible_become_tests.ps1
  test/support/windows-integration/plugins/module_utils/Ansible.Service.cs
Labels: bug

#80984 PowerShell - Improve error checking
  changelogs/fragments/powershell-module-error-handling.yml
  lib/ansible/executor/powershell/module_wrapper.ps1
  test/integration/targets/win_exec_wrapper/action_plugins/test_rc_1.py
  test/integration/targets/win_exec_wrapper/library/test_rc_1.ps1
  test/integration/targets/win_exec_wrapper/tasks/main.yml
Labels: windows, bug, affects_2.16

#81512 find: correct typo
  lib/ansible/modules/find.py
Labels: module, verified

#81469 script: add argument validation
  lib/ansible/modules/command.py
  lib/ansible/modules/script.py
  lib/ansible/plugins/action/script.py
  test/integration/targets/script/tasks/main.yml
Labels: module, bug, has_issue

#81568 dnf module can be used to update packages to latest
  changelogs/fragments/dnf-update-only-latest.yml
  lib/ansible/modules/dnf.py
  test/integration/targets/dnf/tasks/dnf.yml
Labels: module, stale_review, bug

#81555 fix/81553 Add warnings for illegal file names in role
  changelogs/fragments/81555-add-warning-for-illegal-filenames-in-roles.yaml
  lib/ansible/galaxy/role.py
  test/integration/targets/ansible-galaxy-role/tasks/main.yml
Labels: stale_review, bug, has_issue

#81127 Improve ansible.builtin.copy directory_mode parameter docs
  lib/ansible/modules/copy.py
Labels: module, new_contributor, docs, docs_only, affects_2.16

#81590 Fix copy module markup
  lib/ansible/modules/copy.py
Labels: module

#81591 Fix nested jinja statements in integration tests
  test/integration/targets/lookup_fileglob/issue72873/test.yml
  test/integration/targets/lookup_url/tasks/main.yml
  test/integration/targets/lookup_url/tasks/use_netrc.yml
  test/integration/targets/template/tasks/main.yml
  test/integration/targets/template_jinja2_non_native/macro_override.yml
Labels: test, needs_triage

#81587 Fix typos in url lookup plugin options
  changelogs/fragments/fix-url-lookup-plugin-docs.yml
  lib/ansible/plugins/lookup/url.py
  test/integration/targets/lookup_url/tasks/main.yml
Labels: stale_review, bug

#81077 Bump `coverage.py` to v7.3.0 in `ansible-test`
  changelogs/fragments/ansible-test-coverage-update.yml
  test/lib/ansible_test/_data/requirements/ansible-test.txt
  test/lib/ansible_test/_internal/coverage_util.py
Labels: test, stale_review, has_issue, affects_2.16

#81602 ansible-test - Update mypy to 1.5.1
  test/lib/ansible_test/_data/requirements/sanity.mypy.txt
  test/lib/ansible_test/_util/controller/sanity/mypy/ansible-core.ini
Labels: test

#81517 [stable-2.15] Revert logic to use Popen.communicate (#80874)
  lib/ansible/module_utils/basic.py
  test/integration/targets/command_shell/scripts/yoink.sh
  test/integration/targets/command_shell/tasks/main.yml
  test/units/module_utils/basic/test_run_command.py
Labels: backport, needs_triage

#81525 2.15: Last handler with same name wins for listen too (#81358)
  changelogs/fragments/81013-handlers-listen-last-defined-only.yml
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/handlers/roles/test_listen_role_dedup_global/handlers/main.yml
  test/integration/targets/handlers/roles/test_listen_role_dedup_role1/meta/main.yml
  test/integration/targets/handlers/roles/test_listen_role_dedup_role1/tasks/main.yml
  test/integration/targets/handlers/roles/test_listen_role_dedup_role2/meta/main.yml
  test/integration/targets/handlers/roles/test_listen_role_dedup_role2/tasks/main.yml
  test/integration/targets/handlers/runme.sh
  test/integration/targets/handlers/test_listen_role_dedup.yml
Labels: backport, needs_triage, bug

#81562 [2.15] Fix pause CPU consumption (#81519)
  changelogs/fragments/fix-display-prompt-cpu-consumption.yml
  lib/ansible/utils/display.py
Labels: backport, needs_triage, bug

#81577 PowerShell - remove uneeded dotnet code for future compatibility - 2.15
  changelogs/fragments/dotnet-preparation.yml
  lib/ansible/module_utils/csharp/Ansible.AccessToken.cs
  lib/ansible/module_utils/csharp/Ansible.Become.cs
  lib/ansible/module_utils/csharp/Ansible.Privilege.cs
  lib/ansible/module_utils/csharp/Ansible.Process.cs
  test/integration/targets/module_utils_Ansible.Become/library/ansible_become_tests.ps1
  test/support/windows-integration/plugins/module_utils/Ansible.Service.cs
Labels: backport, needs_triage, bug

#81604 ansible-test - Enable thread code coverage
  changelogs/fragments/ansible-test-thread-coverage.yml
  test/lib/ansible_test/_internal/coverage_util.py
Labels: feature

#80527 fix #80523 - adding short option for --ask-vault-pass
  changelogs/fragments/80523_-_adding_short_option_for_--ask-vault-pass.yml
  lib/ansible/cli/arguments/option_helpers.py
Labels: stale_review, new_contributor, feature, affects_2.16

#81611 ansible-test - Fix Python coverage stub generation
  test/lib/ansible_test/_internal/commands/coverage/combine.py
Labels: bug

#81545 tarfile: Handle deprecation warning for extract and extractall
  changelogs/fragments/tarfile_extract_warn.yml
  lib/ansible/galaxy/role.py
  packaging/release.py
  test/integration/targets/ansible-galaxy-collection/library/setup_collections.py
  test/lib/ansible_test/_internal/commands/sanity/validate_modules.py
Labels: needs_revision, bug, has_issue

#81592 Docs: Clarify copy module's purpose; tweak wording
  lib/ansible/modules/copy.py
Labels: module, needs_triage, has_issue

#81448 filters vault/unvault fix vault_id parameter usage (#81422)
  changelogs/fragments/vault_unvault_id_fix.yml
  lib/ansible/plugins/filter/encryption.py
  test/integration/targets/filter_encryption/base.yml
  test/integration/targets/unvault/main.yml
  test/integration/targets/unvault/runme.sh
Labels: backport, needs_triage, bug

#81548 2.15: include_role: expose vars from parent roles to role's handlers (#81524)
  changelogs/fragments/80459-handlers-nested-includes-vars.yml
  lib/ansible/playbook/role_include.py
  test/integration/targets/handlers/roles/r1-dep_chain-vars/defaults/main.yml
  test/integration/targets/handlers/roles/r1-dep_chain-vars/tasks/main.yml
  test/integration/targets/handlers/roles/r2-dep_chain-vars/handlers/main.yml
  test/integration/targets/handlers/roles/r2-dep_chain-vars/tasks/main.yml
  test/integration/targets/handlers/runme.sh
Labels: backport, needs_triage, bug

#81576 PowerShell - remove uneeded dotnet code for future compatibility - 2.14
  changelogs/fragments/dotnet-preparation.yml
  lib/ansible/module_utils/csharp/Ansible.AccessToken.cs
  lib/ansible/module_utils/csharp/Ansible.Become.cs
  lib/ansible/module_utils/csharp/Ansible.Privilege.cs
  lib/ansible/module_utils/csharp/Ansible.Process.cs
  test/integration/targets/module_utils_Ansible.Become/library/ansible_become_tests.ps1
  test/support/windows-integration/plugins/module_utils/Ansible.Service.cs
Labels: backport, needs_triage, bug

#81601 yum/dnf/dnf5/zypper documentation - fix small grammatical error
  lib/ansible/modules/dnf.py
  lib/ansible/modules/dnf5.py
  lib/ansible/modules/yum.py
  test/support/integration/plugins/modules/zypper.py
Labels: module

#81451 lookups first_found fix no terms option (#76527)
  changelogs/fragments/first_found_fixes.yml
  lib/ansible/plugins/lookup/first_found.py
  test/integration/targets/lookup_first_found/tasks/main.yml
Labels: backport, needs_triage, bug
