Repository ansible/ansible, pull requests merged in 2023-11, with the labels that each got.

#82110 Remove Python 2 compat (via six) from unit tests
  test/units/config/test_manager.py
  test/units/executor/test_task_executor.py
  test/units/galaxy/test_api.py
  test/units/galaxy/test_collection.py
  test/units/galaxy/test_collection_install.py
  test/units/inventory/test_host.py
  test/units/mock/procenv.py
  test/units/module_utils/basic/test_argument_spec.py
  test/units/module_utils/basic/test_dict_converters.py
  test/units/module_utils/basic/test_filesystem.py
  test/units/module_utils/basic/test_get_module_path.py
  test/units/module_utils/basic/test_imports.py
  test/units/module_utils/basic/test_log.py
  test/units/module_utils/basic/test_platform_distribution.py
  test/units/module_utils/basic/test_run_command.py
  test/units/module_utils/basic/test_selinux.py
  test/units/module_utils/common/arg_spec/test_validate_invalid.py
  test/units/module_utils/common/test_collections.py
  test/units/module_utils/common/test_sys_info.py
  test/units/module_utils/common/text/converters/test_to_str.py
  test/units/module_utils/common/warnings/test_deprecate.py
  test/units/module_utils/common/warnings/test_warn.py
  test/units/module_utils/compat/test_datetime.py
  test/units/module_utils/conftest.py
  test/units/module_utils/facts/system/distribution/test_distribution_version.py
  test/units/module_utils/test_distro.py
  test/units/module_utils/test_text.py
  test/units/module_utils/urls/test_generic_urlparse.py
  test/units/modules/test_hostname.py
  test/units/modules/test_service.py
  test/units/parsing/vault/test_vault.py
  test/units/parsing/yaml/test_loader.py
  test/units/playbook/test_base.py
  test/units/plugins/action/test_action.py
  test/units/plugins/connection/test_ssh.py
  test/units/plugins/inventory/test_inventory.py
  test/units/plugins/lookup/test_password.py
  test/units/utils/collection_loader/test_collection_loader.py
  test/units/vars/test_variable_manager.py
Labels: test

#82111 Remove scheduled CI runs
  .azure-pipelines/azure-pipelines.yml
Labels: backport, test

#82112 Remove unused test support plugins
  test/support/integration/plugins/filter/json_query.py
  test/support/integration/plugins/modules/zypper.py
Labels: test

#82120 ansible-test - Remove no-unicode-literals test
  changelogs/fragments/ansible-test-sanity-unicode-literals.yml
  test/lib/ansible_test/_util/controller/sanity/code-smell/no-unicode-literals.json
  test/lib/ansible_test/_util/controller/sanity/code-smell/no-unicode-literals.py
Labels: needs_rebase, feature

#82121 ansible-test - Removed no-dict-* sanity tests
  changelogs/fragments/ansible-test-sanity-no-dict.yml
  test/lib/ansible_test/_util/controller/sanity/code-smell/no-dict-iteritems.json
  test/lib/ansible_test/_util/controller/sanity/code-smell/no-dict-iteritems.py
  test/lib/ansible_test/_util/controller/sanity/code-smell/no-dict-iterkeys.json
  test/lib/ansible_test/_util/controller/sanity/code-smell/no-dict-iterkeys.py
  test/lib/ansible_test/_util/controller/sanity/code-smell/no-dict-itervalues.json
  test/lib/ansible_test/_util/controller/sanity/code-smell/no-dict-itervalues.py
  test/sanity/ignore.txt
Labels: feature

#82122 ansible-test - Removed no-basestring sanity test
  changelogs/fragments/ansible-test-sanity-no-basestring.yml
  test/lib/ansible_test/_util/controller/sanity/code-smell/no-basestring.json
  test/lib/ansible_test/_util/controller/sanity/code-smell/no-basestring.py
  test/sanity/ignore.txt
Labels: feature

#82123 ansible-test - Remove no-main-display sanity test
  changelogs/fragments/ansible-test-sanity-no-main-display.yml
  test/lib/ansible_test/_util/controller/sanity/code-smell/no-main-display.json
  test/lib/ansible_test/_util/controller/sanity/code-smell/no-main-display.py
Labels: feature

#82124 Remove duplicate winrm test
  test/units/plugins/connection/test_winrm.py
Labels: test, needs_triage

#82125 Ignore code which coverage can't analyze
  test/units/ansible_test/test_diff.py
  test/units/utils/collection_loader/test_collection_loader.py
Labels: test

#82113 Fix the strategy plugin description in keywords
  lib/ansible/keyword_desc.yml
Labels: has_issue

#82128 Ignore coverage on code intended never to execute
  test/sanity/code-smell/boilerplate.py
  test/units/utils/collection_loader/fixtures/collections/ansible_collections/ansible/builtin/plugins/modules/shouldnotload.py
  test/units/utils/collection_loader/fixtures/collections/ansible_collections/testns/testcoll/plugins/action/my_action.py
  test/units/utils/collection_loader/fixtures/collections/ansible_collections/testns/testcoll/plugins/modules/__init__.py
  test/units/utils/collection_loader/fixtures/collections/ansible_collections/testns/testcoll/plugins/modules/amodule.py
  test/units/utils/collection_loader/fixtures/collections_masked/ansible_collections/__init__.py
  test/units/utils/collection_loader/fixtures/collections_masked/ansible_collections/ansible/__init__.py
  test/units/utils/collection_loader/fixtures/collections_masked/ansible_collections/testns/testcoll/__init__.py
Labels: test

#73116 remove the obsolete TODO comments
  lib/ansible/plugins/connection/winrm.py
Labels: needs_revision, windows, core_review, support:core, new_contributor, bug, small_patch, affects_2.11

#80777 dnf: properly set gpg options on repos
  changelogs/fragments/80110-repos-gpgcheck.yml
  lib/ansible/modules/dnf.py
Labels: module, bug, has_issue, affects_2.16

#82106 restore role param precedence
  changelogs/fragments/restore_role_param_precedence.yml
  lib/ansible/vars/manager.py
  test/integration/targets/var_precedence/test_var_precedence.yml
Labels: bug, has_issue

#82066 Remove create_new_password parameter in CLI.build_vault_ids
  changelogs/fragments/82066.yml
  lib/ansible/cli/__init__.py
  test/units/cli/test_cli.py
Labels: needs_revision, needs_verified

#82140 New release v2.15.6
  changelogs/CHANGELOG-v2.15.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.15.6_summary.yaml
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#82141 New release v2.16.0
  changelogs/CHANGELOG-v2.16.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.16.0_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#82144 Update Ansible release version to v2.16.0.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#82143 Update Ansible release version to v2.15.6.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#82129 Use functools.update_wrapper instead of a copy
  changelogs/fragments/functools-update-wrapper.yml
  lib/ansible/template/__init__.py
Labels: feature

#82148 Ignore coverage of test code that does not run
  test/units/utils/collection_loader/fixtures/collections_masked/ansible_collections/testns/__init__.py
Labels: test

#80795 dnf: check strict before failing to respect skip_broken
  changelogs/fragments/80590-dnf-skip_broken-unavailable-pkgs.yml
  lib/ansible/modules/dnf.py
  test/integration/targets/dnf/tasks/skip_broken_and_nobest.yml
Labels: module, bug, has_issue, affects_2.16

#82137 Add example for responses for multiple prompts
  lib/ansible/modules/expect.py
Labels: module

#82145 iptables - set jump to DSCP when set_dscp_mark or set_dscp_mark_class is set
  changelogs/fragments/77077_iptables.yml
  lib/ansible/modules/iptables.py
Labels: module, needs_triage, bug, has_issue

#82147 Reword note on default determination on other OSes
  lib/ansible/modules/user.py
Labels: module, has_issue

#82151 setup.cfg: add `Programming Language :: Python :: 3.12` classifier
  setup.cfg
Labels: bug

#82153 ansible-test - Use pylint unidiomatic-typecheck
  changelogs/fragments/ansible-test-unidiomatic-type-check.yml
  test/lib/ansible_test/_util/controller/sanity/pylint/config/collection.cfg
  test/lib/ansible_test/_util/controller/sanity/pylint/config/default.cfg
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py
  test/sanity/ignore.txt
Labels: feature, has_issue

#82163 Remove type_regex testcase
  test/units/ansible_test/test_validate_modules.py
Labels: test

#82161 Remove unit tests dependent on systemd bindings
  test/units/module_utils/basic/test_log.py
Labels: test

#82160 Remove unused/unreachable unit test code
  test/units/module_utils/basic/test_filesystem.py
  test/units/module_utils/basic/test_no_log.py
  test/units/module_utils/basic/test_run_command.py
  test/units/module_utils/basic/test_tmpdir.py
  test/units/module_utils/test_distro.py
  test/units/utils/collection_loader/test_collection_loader.py
Labels: needs_rebase, test

#82164 Remove unused validate-modules unit test code
  test/units/ansible_test/test_validate_modules.py
Labels: test

#82167 Update Python3
  test/integration/targets/setup_rpm_repo/tasks/main.yml
Labels: needs_revision, test

#82168 Remove unused unit test code
  test/units/module_utils/facts/test_collectors.py
Labels: test

#82169 Remove sefcontext support plugin
  test/integration/targets/subversion/roles/subversion/tasks/setup.yml
  test/integration/targets/subversion/roles/subversion/tasks/setup_selinux.yml
  test/support/integration/plugins/modules/sefcontext.py
Labels: test

#82159 Fix two misspellings of occurred
  lib/ansible/cli/__init__.py
Labels: needs_triage

#82195 Fix typo in validation.py
  lib/ansible/module_utils/common/validation.py
Labels: needs_triage

#81572 flush_handlers: handle a failure in a nested block with force_handlers
  changelogs/fragments/81532-fix-nested-flush_handlers.yml
  lib/ansible/executor/play_iterator.py
  test/integration/targets/handlers/nested_flush_handlers_failure_force.yml
  test/integration/targets/handlers/runme.sh
Labels: bug, has_issue

#82158 copy keep suffix on temp file for validation
  changelogs/fragments/copy_keep_suffix_temp.yml
  lib/ansible/plugins/action/copy.py
  test/integration/targets/callback_default/callback_default.out.result_format_yaml_lossy_verbose.stdout
  test/integration/targets/callback_default/callback_default.out.result_format_yaml_verbose.stdout
  test/integration/targets/callback_default/runme.sh
Labels: stale_review, feature, has_issue

#82202 union filter, fix typo in example
  lib/ansible/plugins/filter/union.yml
Labels: needs_triage, has_issue

#82203 [bp-2.16] Update Python3
  test/integration/targets/setup_rpm_repo/tasks/main.yml
Labels: backport, needs_triage

#82178 ansible-test - Add RHEL 9.3 support
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-rhel-9.3.yml
  test/lib/ansible_test/_data/completion/remote.txt
Labels: feature, has_issue

#82210 Restart a Service with Sleep Between Stop and Start
  lib/ansible/modules/sysvinit.py
Labels: module

#82030 ansible-pull: expand destinantion directoy to avoid purgin in /
  changelogs/fragments/pull_unfrack_dest.yml
  lib/ansible/cli/pull.py
  test/integration/targets/ansible-pull/runme.sh
Labels: bug

#82209 Create prefix of file using ansible.builtin.tempfile
  lib/ansible/modules/tempfile.py
Labels: module

#81692 log verbosity
  changelogs/fragments/log_verbosity.yml
  lib/ansible/config/base.yml
  lib/ansible/plugins/connection/ssh.py
  lib/ansible/utils/display.py
Labels: stale_ci, feature

#82157 fix pc misuse
  changelogs/fragments/pc_fixes.yml
  lib/ansible/plugins/action/assemble.py
  lib/ansible/plugins/action/copy.py
  lib/ansible/plugins/action/fetch.py
  lib/ansible/plugins/action/raw.py
  lib/ansible/plugins/action/reboot.py
  lib/ansible/plugins/action/script.py
  lib/ansible/plugins/action/wait_for_connection.py
  test/units/plugins/action/test_raw.py
  test/units/plugins/action/test_reboot.py
Labels: bug

#82215 Fix ManifestControl dataclass to work with future annotations
  changelogs/fragments/distlib-dataclass-annotation.yml
  lib/ansible/galaxy/collection/__init__.py
  test/integration/targets/ansible-galaxy-collection-cli/files/empty_manifest_galaxy.yml
  test/integration/targets/ansible-galaxy-collection-cli/files/expected_empty.txt
  test/integration/targets/ansible-galaxy-collection-cli/tasks/manifest.yml
Labels: needs_triage, bug

#82230 Skip DNF modularity test for Fedora 39 and up
  test/integration/targets/dnf/tasks/main.yml
Labels: needs_revision, test

#82231 Downgrade containerd for F39 in integration tests
  test/integration/targets/ansible-test-container/runme.py
Labels: test

#82227 handle when caplevel is already taken care of
  lib/ansible/utils/display.py
  test/integration/targets/ansible_log/aliases
  test/integration/targets/ansible_log/logit.yml
  test/integration/targets/ansible_log/runme.sh
Labels: needs_revision, ci_verified, bug, has_issue

#82064 wait_for, fallback to read for non mmapable files
  changelogs/fragments/wait_for_mmap.yml
  lib/ansible/modules/wait_for.py
  test/integration/targets/wait_for/tasks/main.yml
Labels: module, bug, has_issue

#82232 Enable vendored copy of distutils in entry_point test
  test/integration/targets/entry_points/runme.sh
Labels: test

#82225 syslog: Handle ValueError raised while sending logs to syslog
  changelogs/fragments/syslog_exception.yml
  lib/ansible/module_utils/basic.py
Labels: test

#82218 ansible-test: Added Fedora 39
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-added-fedora-39.yml
  test/lib/ansible_test/_data/completion/docker.txt
  test/lib/ansible_test/_data/completion/remote.txt
Labels: needs_revision, test, has_issue

#82250 Re-enable "group removal" integration test for dnf5
  test/integration/targets/dnf/tasks/main.yml
Labels: test

#82256 docs: improve readability & scope of docs for ansible.builtin.assert
  lib/ansible/modules/assert.py
Labels: module

#82242 csvfile - add a keycol parameter to specify in which column to search.
  changelogs/fragments/csvfile-keycol.yml
  lib/ansible/plugins/lookup/csvfile.py
  test/integration/targets/lookup_csvfile/tasks/main.yml
Labels: needs_revision, needs_rebase, feature

#82253 unarchive: force unarchive if the symlink target changes
  changelogs/fragments/unarchive.yml
  lib/ansible/modules/unarchive.py
  test/integration/targets/unarchive/tasks/test_symlink.yml
Labels: test, module, has_issue

#81705 support 8 character permission strings
  changelogs/fragments/81699-zip-permission.yml
  lib/ansible/modules/unarchive.py
Labels: module, bug

#70340 Update known_hosts module to better handle @cert-authority keys
  changelogs/fragments/known_hosts_cert-authority_keys.yml
  lib/ansible/modules/known_hosts.py
  test/integration/targets/known_hosts/defaults/main.yml
  test/integration/targets/known_hosts/files/existing_known_hosts
  test/integration/targets/known_hosts/tasks/main.yml
Labels: needs_revision, needs_rebase, module, support:core, bug, system, has_issue, affects_2.11

#82248 Allow include_tasks handlers for searching role subdirs
  changelogs/fragments/82241-handler-include-tasks-from.yml
  lib/ansible/playbook/included_file.py
  test/integration/targets/handlers/82241.yml
  test/integration/targets/handlers/roles/role-82241/handlers/main.yml
  test/integration/targets/handlers/roles/role-82241/tasks/entry_point.yml
  test/integration/targets/handlers/roles/role-82241/tasks/included_tasks.yml
  test/integration/targets/handlers/runme.sh
Labels: bug, has_issue

#80291 user: Remove superfluous user not found warning
  changelogs/fragments/80267-ansible_builtin_user-remove-user-not-found-warning.yml
  lib/ansible/modules/user.py
  test/integration/targets/user/tasks/test_local.yml
Labels: module, stale_review, new_contributor, bug, small_patch, has_issue, affects_2.15

#82211 ansible-test - remove rhel 9.2 test remote
  changelogs/fragments/ansible-test-remove-rhel-9_2-remote.yml
  test/lib/ansible_test/_data/completion/remote.txt
Labels: feature, has_issue

#82223 [stable-2.14] ansible-pull: expand destinantion directoy to avoid purgin in / (#82030)
  changelogs/fragments/pull_unfrack_dest.yml
  lib/ansible/cli/pull.py
  test/integration/targets/ansible-pull/runme.sh
Labels: backport, needs_triage, bug

#82236 no_log avoid masking booleans (#82217)
  changelogs/fragments/no_log_booly.yml
  lib/ansible/module_utils/basic.py
  test/integration/targets/module_no_log/library/module_that_has_secret.py
  test/integration/targets/module_no_log/tasks/main.yml
Labels: backport, needs_triage, bug

#82234 wait_for, fallback to read for non mmapable files (#82064)
  changelogs/fragments/wait_for_mmap.yml
  lib/ansible/modules/wait_for.py
  test/integration/targets/wait_for/tasks/main.yml
Labels: backport, module, needs_triage, bug

#82222 [stable-2.15] ansible-pull: expand destinantion directoy to avoid purgin in / (#82030)
  changelogs/fragments/pull_unfrack_dest.yml
  lib/ansible/cli/pull.py
  test/integration/targets/ansible-pull/runme.sh
Labels: backport, needs_triage, bug

#82139 restore role param precedence (#82106)
  changelogs/fragments/restore_role_param_precedence.yml
  lib/ansible/vars/manager.py
  test/integration/targets/var_precedence/test_var_precedence.yml
Labels: backport, needs_triage, bug

#82132 [bp-2.15] Fix the strategy plugin description in keywords
  lib/ansible/keyword_desc.yml
Labels: backport, needs_triage

#82126 [stable-2.15] Remove duplicate winrm test (#82124)
  test/units/plugins/connection/test_winrm.py
Labels: backport, test, needs_triage

#82286 import_*/include_* documentation: fix broken docs RST reference
  lib/ansible/modules/import_playbook.py
  lib/ansible/modules/import_role.py
  lib/ansible/modules/import_tasks.py
  lib/ansible/modules/include_role.py
  lib/ansible/modules/include_tasks.py
Labels: module, needs_triage

#82053 [stable-2.16] Fix Jinja plugin deduplication (#82002)
  changelogs/fragments/j2_load_fix.yml
  lib/ansible/plugins/loader.py
  test/integration/targets/plugin_loader/file_collision/play.yml
  test/integration/targets/plugin_loader/file_collision/roles/r1/filter_plugins/custom.py
  test/integration/targets/plugin_loader/file_collision/roles/r1/filter_plugins/filter1.yml
  test/integration/targets/plugin_loader/file_collision/roles/r1/filter_plugins/filter3.yml
  test/integration/targets/plugin_loader/file_collision/roles/r2/filter_plugins/custom.py
  test/integration/targets/plugin_loader/file_collision/roles/r2/filter_plugins/filter2.yml
  test/integration/targets/plugin_loader/runme.sh
Labels: backport, needs_triage, bug

#82070 [stable-2.16] ansible-pull now handles all secret files CLI options (#82009)
  changelogs/fragments/pull_file_secrets.yml
  lib/ansible/cli/pull.py
  test/integration/targets/ansible-pull/pull-integration-test/conn_secret.yml
  test/integration/targets/ansible-pull/pull-integration-test/secret_connection_password
  test/integration/targets/ansible-pull/runme.sh
Labels: backport, needs_triage, bug

#82098 [stable-2.16] add pep668 note to pip module docs (#82096)
  lib/ansible/modules/pip.py
Labels: backport, module, needs_triage

#82138 restore role param precedence (#82106)
  changelogs/fragments/restore_role_param_precedence.yml
  lib/ansible/vars/manager.py
  test/integration/targets/var_precedence/test_var_precedence.yml
Labels: backport, needs_triage, bug

#82152 [stable-2.16] setup.cfg: add `Programming Language :: Python :: 3.12` classifier
  setup.cfg
Labels: backport, needs_triage, bug

#82197 2.16: flush_handlers: handle a failure in a nested block with force_handlers (#81572)
  changelogs/fragments/81532-fix-nested-flush_handlers.yml
  lib/ansible/executor/play_iterator.py
  test/integration/targets/handlers/nested_flush_handlers_failure_force.yml
  test/integration/targets/handlers/runme.sh
Labels: backport, needs_triage, bug

#82233 wait_for, fallback to read for non mmapable files (#82064)
  changelogs/fragments/wait_for_mmap.yml
  lib/ansible/modules/wait_for.py
  test/integration/targets/wait_for/tasks/main.yml
Labels: backport, module, needs_triage, stale_ci, bug

#82235 no_log avoid masking booleans (#82217)
  changelogs/fragments/no_log_booly.yml
  lib/ansible/module_utils/basic.py
  test/integration/targets/module_no_log/library/module_that_has_secret.py
  test/integration/targets/module_no_log/tasks/main.yml
Labels: backport, needs_triage, bug

#82221 [stable-2.16] ansible-pull: expand destinantion directoy to avoid purgin in / (#82030)
  changelogs/fragments/pull_unfrack_dest.yml
  lib/ansible/cli/pull.py
  test/integration/targets/ansible-pull/runme.sh
Labels: backport, needs_triage, bug

#82268 2.16: Allow include_tasks handlers for searching role subdirs (#82248)
  changelogs/fragments/82241-handler-include-tasks-from.yml
  lib/ansible/playbook/included_file.py
  test/integration/targets/handlers/82241.yml
  test/integration/targets/handlers/roles/role-82241/handlers/main.yml
  test/integration/targets/handlers/roles/role-82241/tasks/entry_point.yml
  test/integration/targets/handlers/roles/role-82241/tasks/included_tasks.yml
  test/integration/targets/handlers/runme.sh
Labels: backport, needs_triage, stale_review, bug

#82105 Add DCO and update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: needs_revision, stale_ci

#82293 Ensure that unsafe is more difficult to lose [stable-2.16]
  changelogs/fragments/cve-2023-5764.yml
  lib/ansible/module_utils/common/json.py
  lib/ansible/parsing/yaml/dumper.py
  lib/ansible/playbook/conditional.py
  lib/ansible/playbook/task.py
  lib/ansible/plugins/action/assert.py
  lib/ansible/plugins/callback/__init__.py
  lib/ansible/plugins/filter/core.py
  lib/ansible/plugins/lookup/first_found.py
  lib/ansible/template/__init__.py
  lib/ansible/utils/unsafe_proxy.py
  test/integration/targets/ansible-galaxy-collection-scm/tasks/scm_dependency_deduplication.yml
  test/integration/targets/ansible-vault/roles/test_vault_embedded/tasks/main.yml
  test/integration/targets/ansible-vault/roles/test_vault_file_encrypted_embedded/tasks/main.yml
  test/integration/targets/apt_repository/tasks/apt.yml
  test/integration/targets/assert/assert.out.nested_tmpl.stderr
  test/integration/targets/assert/assert.out.nested_tmpl.stdout
  test/integration/targets/assert/assert.out.quiet.stderr
  test/integration/targets/assert/assert.out.quiet.stdout
  test/integration/targets/assert/nested_tmpl.yml
  test/integration/targets/assert/quiet.yml
  test/integration/targets/assert/runme.sh
  test/integration/targets/command_shell/tasks/main.yml
  test/integration/targets/copy/tasks/tests.yml
  test/integration/targets/debug/runme.sh
  test/integration/targets/debug/unsafe.yml
  test/integration/targets/expect/tasks/main.yml
  test/integration/targets/file/tasks/main.yml
  test/integration/targets/file/tasks/state_link.yml
  test/integration/targets/find/tasks/main.yml
  test/integration/targets/find/tasks/mode.yml
  test/integration/targets/gathering_facts/test_gathering_facts.yml
  test/integration/targets/git/tasks/depth.yml
  test/integration/targets/git/tasks/localmods.yml
  test/integration/targets/git/tasks/submodules.yml
  test/integration/targets/incidental_vyos_config/tests/cli/check_config.yaml
  test/integration/targets/incidental_vyos_lldp_interfaces/tests/cli/deleted.yaml
  test/integration/targets/incidental_vyos_lldp_interfaces/tests/cli/merged.yaml
  test/integration/targets/incidental_vyos_lldp_interfaces/tests/cli/overridden.yaml
  test/integration/targets/incidental_vyos_lldp_interfaces/tests/cli/replaced.yaml
  test/integration/targets/include_vars/tasks/main.yml
  test/integration/targets/lookup_first_found/tasks/main.yml
  test/integration/targets/lookup_ini/test_lookup_properties.yml
  test/integration/targets/lookup_subelements/tasks/main.yml
  test/integration/targets/loop_control/inner.yml
  test/integration/targets/module_precedence/modules_test_multiple_roles.yml
  test/integration/targets/module_precedence/modules_test_multiple_roles_reverse_order.yml
  test/integration/targets/module_precedence/multiple_roles/bar/tasks/main.yml
  test/integration/targets/module_precedence/multiple_roles/foo/tasks/main.yml
  test/integration/targets/script/tasks/main.yml
  test/integration/targets/slurp/tasks/main.yml
  test/integration/targets/template/tasks/main.yml
  test/integration/targets/unarchive/tasks/test_missing_binaries.yml
  test/integration/targets/unarchive/tasks/test_mode.yml
  test/integration/targets/unarchive/tasks/test_unprivileged_user.yml
  test/integration/targets/unarchive/tasks/test_zip.yml
  test/integration/targets/wait_for/tasks/main.yml
  test/units/parsing/yaml/test_dumper.py
Labels: backport, needs_triage, bug

#82294 Ensure that unsafe is more difficult to lose [stable-2.15]
  changelogs/fragments/cve-2023-5764.yml
  lib/ansible/module_utils/common/json.py
  lib/ansible/parsing/yaml/dumper.py
  lib/ansible/playbook/conditional.py
  lib/ansible/playbook/task.py
  lib/ansible/plugins/action/assert.py
  lib/ansible/plugins/callback/__init__.py
  lib/ansible/plugins/filter/core.py
  lib/ansible/plugins/lookup/first_found.py
  lib/ansible/template/__init__.py
  lib/ansible/utils/unsafe_proxy.py
  test/integration/targets/ansible-galaxy-collection-scm/tasks/scm_dependency_deduplication.yml
  test/integration/targets/ansible-vault/roles/test_vault_embedded/tasks/main.yml
  test/integration/targets/ansible-vault/roles/test_vault_file_encrypted_embedded/tasks/main.yml
  test/integration/targets/apt_repository/tasks/apt.yml
  test/integration/targets/assert/assert.out.nested_tmpl.stderr
  test/integration/targets/assert/assert.out.nested_tmpl.stdout
  test/integration/targets/assert/assert.out.quiet.stderr
  test/integration/targets/assert/assert.out.quiet.stdout
  test/integration/targets/assert/nested_tmpl.yml
  test/integration/targets/assert/quiet.yml
  test/integration/targets/assert/runme.sh
  test/integration/targets/command_shell/tasks/main.yml
  test/integration/targets/copy/tasks/tests.yml
  test/integration/targets/debug/runme.sh
  test/integration/targets/debug/unsafe.yml
  test/integration/targets/expect/tasks/main.yml
  test/integration/targets/file/tasks/main.yml
  test/integration/targets/file/tasks/state_link.yml
  test/integration/targets/find/tasks/main.yml
  test/integration/targets/gathering_facts/test_gathering_facts.yml
  test/integration/targets/git/tasks/depth.yml
  test/integration/targets/git/tasks/localmods.yml
  test/integration/targets/git/tasks/submodules.yml
  test/integration/targets/incidental_vyos_config/tests/cli/check_config.yaml
  test/integration/targets/incidental_vyos_lldp_interfaces/tests/cli/deleted.yaml
  test/integration/targets/incidental_vyos_lldp_interfaces/tests/cli/merged.yaml
  test/integration/targets/incidental_vyos_lldp_interfaces/tests/cli/overridden.yaml
  test/integration/targets/incidental_vyos_lldp_interfaces/tests/cli/replaced.yaml
  test/integration/targets/include_vars/tasks/main.yml
  test/integration/targets/lookup_ini/test_lookup_properties.yml
  test/integration/targets/lookup_subelements/tasks/main.yml
  test/integration/targets/loop_control/inner.yml
  test/integration/targets/module_precedence/modules_test_multiple_roles.yml
  test/integration/targets/module_precedence/modules_test_multiple_roles_reverse_order.yml
  test/integration/targets/module_precedence/multiple_roles/bar/tasks/main.yml
  test/integration/targets/module_precedence/multiple_roles/foo/tasks/main.yml
  test/integration/targets/script/tasks/main.yml
  test/integration/targets/slurp/tasks/main.yml
  test/integration/targets/template/tasks/main.yml
  test/integration/targets/unarchive/tasks/test_missing_binaries.yml
  test/integration/targets/unarchive/tasks/test_mode.yml
  test/integration/targets/unarchive/tasks/test_unprivileged_user.yml
  test/integration/targets/unarchive/tasks/test_zip.yml
  test/integration/targets/wait_for/tasks/main.yml
  test/units/parsing/yaml/test_dumper.py
Labels: backport, needs_triage, bug

#82301 New release v2.16.1rc1
  changelogs/CHANGELOG-v2.16.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.16.1rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#82302 New release v2.15.7rc1
  changelogs/CHANGELOG-v2.15.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.15.7rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#82303 New release v2.14.12rc1
  changelogs/CHANGELOG-v2.14.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.14.12rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#82306 Update Ansible release version to v2.14.12rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#82305 Update Ansible release version to v2.15.7rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#82266 validate-modules: Check for correct values in choice
  test/integration/targets/ansible-test-sanity-validate-modules/ansible_collections/ns/col/plugins/modules/invalid_choice_value.py
  test/integration/targets/ansible-test-sanity-validate-modules/expected.txt
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/utils.py
Labels: test, has_issue

#82274 changed the salt type from int to string
  lib/ansible/plugins/filter/password_hash.yml
Labels: has_issue

#82288 Remove unneeded Task.is_static assignment
  lib/ansible/playbook/helpers.py
Labels: bug

#82309 Amend doc of name= parameter to indicate a list of packages can be used
  lib/ansible/modules/package.py
Labels: needs_revision, module

#82321 ansible-test - Update nios-test-container to 3.0.0
  changelogs/fragments/ansible-test-nios-container.yml
  test/lib/ansible_test/_internal/commands/integration/cloud/nios.py
Labels: needs_triage, feature

#82165 Targeted fix for installing roles with symlinks containing '..'
  changelogs/fragments/ansible-galaxy-role-install-symlink.yml
  lib/ansible/galaxy/role.py
  test/integration/targets/ansible-galaxy-role/files/create-role-archive.py
  test/integration/targets/ansible-galaxy-role/tasks/dir-traversal.yml
  test/integration/targets/ansible-galaxy-role/tasks/main.yml
  test/integration/targets/ansible-galaxy-role/tasks/valid-role-symlinks.yml
Labels: bug, has_issue
