Repository ansible/ansible, pull requests merged in 2024-05, with the labels that each got.

#83169 uri: deprecate 'yes' or 'no' value in follow_redirects param
  changelogs/fragments/uri_follow_redirect.yml
  lib/ansible/modules/uri.py
  lib/ansible/plugins/lookup/url.py
Labels: module, needs_triage, bug

#83183 Don't hardcode the dnf module, dynamically select one
  test/integration/targets/dnf/filter_plugins/dnf_module_list.py
  test/integration/targets/dnf/tasks/main.yml
  test/integration/targets/dnf/tasks/modularity.yml
  test/integration/targets/dnf/vars/CentOS.yml
  test/integration/targets/dnf/vars/Fedora.yml
  test/integration/targets/dnf/vars/RedHat-9.yml
  test/integration/targets/dnf/vars/RedHat.yml
Labels: test

#83185 [stable-2.16] Don't hardcode the dnf module, dynamically select one (#83183)
  test/integration/targets/dnf/filter_plugins/dnf_module_list.py
  test/integration/targets/dnf/tasks/main.yml
  test/integration/targets/dnf/tasks/modularity.yml
  test/integration/targets/dnf/vars/CentOS.yml
  test/integration/targets/dnf/vars/Fedora.yml
  test/integration/targets/dnf/vars/RedHat-9.yml
  test/integration/targets/dnf/vars/RedHat.yml
Labels: backport, needs_triage

#83186 [stable-2.15] Don't hardcode the dnf module, dynamically select one (#83183)
  test/integration/targets/dnf/filter_plugins/dnf_module_list.py
  test/integration/targets/dnf/tasks/main.yml
  test/integration/targets/dnf/tasks/modularity.yml
  test/integration/targets/dnf/vars/CentOS.yml
  test/integration/targets/dnf/vars/Fedora.yml
  test/integration/targets/dnf/vars/RedHat-9.yml
  test/integration/targets/dnf/vars/RedHat.yml
Labels: backport, needs_triage

#83187 [stable-2.14] Don't hardcode the dnf module, dynamically select one (#83183)
  test/integration/targets/dnf/filter_plugins/dnf_module_list.py
  test/integration/targets/dnf/tasks/main.yml
  test/integration/targets/dnf/tasks/modularity.yml
  test/integration/targets/dnf/vars/CentOS.yml
  test/integration/targets/dnf/vars/Fedora.yml
  test/integration/targets/dnf/vars/RedHat-9.yml
  test/integration/targets/dnf/vars/RedHat.yml
Labels: backport, needs_triage

#83149 package_facts add alias support
  changelogs/fragments/package_facts_aliases.yml
  lib/ansible/modules/package_facts.py
  test/integration/targets/package_facts/tasks/main.yml
Labels: module, stale_review, feature, has_issue

#82992 clean up ansible-connection
  bin/ansible-connection
  changelogs/fragments/ansible_connection_path.yml
  lib/ansible/cli/scripts/ansible_connection_cli_stub.py
  lib/ansible/config/base.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/module_utils/connection.py
  lib/ansible/utils/display.py
  lib/ansible/utils/jsonrpc.py
  setup.cfg
  setup.py
  test/integration/targets/packaging_cli-doc/verify.py
  test/lib/ansible_test/_internal/ansible_util.py
  test/lib/ansible_test/_internal/constants.py
  test/lib/ansible_test/_internal/util_common.py
  test/lib/ansible_test/_util/target/injector/python.py
  test/lib/ansible_test/config/config.yml
  test/sanity/ignore.txt
Labels: needs_revision, networking, stale_review, bug

#83179 display: fix log verbosity
  changelogs/fragments/fix_log_verbosity.yml
  lib/ansible/utils/display.py
  test/integration/targets/ansible_log/runme.sh
Labels: bug

#82173 git: Check if version is populated or not
  changelogs/fragments/72321_git.yml
  lib/ansible/modules/git.py
Labels: test, module, has_issue

#83195 Build test modules for aarch64
  test/integration/targets/binary_modules/Makefile
Labels: test

#83196 Multi-arch support for container test
  test/integration/targets/ansible-test-container/runme.py
Labels: test

#81377 Fix order of CLI arguments on FreeBSD
  changelogs/fragments/freebsd_service.yml
  lib/ansible/modules/service.py
Labels: waiting_on_contributor, module, stale_ci, bug

#83205 ansible-doc: fix typo in output
  changelogs/fragments/ansible-doc-inicate.yml
  lib/ansible/cli/doc.py
  test/integration/targets/ansible-doc/fakecollrole.output
  test/integration/targets/ansible-doc/fakemodule.output
  test/integration/targets/ansible-doc/fakerole.output
  test/integration/targets/ansible-doc/randommodule-text-verbose.output
  test/integration/targets/ansible-doc/randommodule-text.output
  test/integration/targets/ansible-doc/test_docs_suboptions.output
  test/integration/targets/ansible-doc/test_docs_yaml_anchors.output
  test/integration/targets/ansible-doc/yolo-text.output
Labels: needs_revision, needs_triage, bug

#82081 facts: Update RAID devices regex for FreeBSD
  changelogs/fragments/freebsd_disk_regex.yml
  lib/ansible/module_utils/facts/hardware/freebsd.py
  test/units/module_utils/facts/hardware/freebsd/fixtures/devices
  test/units/module_utils/facts/hardware/freebsd/fixtures/expected_devices
  test/units/module_utils/facts/hardware/freebsd/test_get_device_facts.py
Labels: feature

#83150 pymarkdown: update docs
  .github/CONTRIBUTING.md
  hacking/backport/README.md
  hacking/ticket_stubs/bug_internal_api.md
  hacking/ticket_stubs/bug_wrong_repo.md
  hacking/ticket_stubs/collections.md
  hacking/ticket_stubs/guide_newbie_about_gh_and_contributing_to_ansible.md
  hacking/ticket_stubs/no_thanks.md
  hacking/ticket_stubs/pr_duplicate.md
  hacking/ticket_stubs/pr_merged.md
  hacking/ticket_stubs/proposal.md
  hacking/ticket_stubs/question_not_bug.md
  hacking/ticket_stubs/resolved.md
  hacking/ticket_stubs/wider_discussion.md
  lib/ansible/galaxy/data/apb/README.md
  test/integration/targets/ansible-vault/invalid_format/README.md
  test/sanity/ignore.txt
  test/support/README.md
Labels: stale_ci

#83192 added examples for systemd service usage
  lib/ansible/modules/service_facts.py
Labels: module, needs_triage

#83132 package_facts: apk fix when cache is empty
  changelogs/fragments/apk_package_facts.yml
  lib/ansible/modules/package_facts.py
Labels: module, stale_ci, bug, has_issue

#83203 dnf: integration tests cleanup
  test/integration/targets/dnf/tasks/dnf.yml
  test/integration/targets/dnf/tasks/main.yml
  test/integration/targets/dnf5/playbook.yml
Labels: test, needs_triage

#83212 Darwin: add unit tests for hardware fact gathering
  changelogs/fragments/darwin_facts.yml
  lib/ansible/module_utils/facts/hardware/darwin.py
  test/units/module_utils/facts/hardware/fixtures/sysctl_darwin.txt
  test/units/module_utils/facts/hardware/fixtures/vm_stat_darwin.txt
  test/units/module_utils/facts/hardware/test_darwin_facts.py
Labels: test

#83105 dnf5: implement enable_plugin and disable_plugin options
  changelogs/fragments/dnf5-enable-disable-plugins.yml
  lib/ansible/modules/dnf5.py
  test/integration/targets/dnf/tasks/dnf.yml
Labels: module, feature

#83116 Refactor yum_repository, deprecate yum only options
  changelogs/fragments/yum_repository.yml
  lib/ansible/modules/yum_repository.py
Labels: module, feature

#83207 [stable-2.17] ansible-doc: fix typo in output
  changelogs/fragments/ansible-doc-inicate.yml
  lib/ansible/cli/doc.py
  test/integration/targets/ansible-doc/fakecollrole.output
  test/integration/targets/ansible-doc/fakemodule.output
  test/integration/targets/ansible-doc/fakerole.output
  test/integration/targets/ansible-doc/randommodule-text-verbose.output
  test/integration/targets/ansible-doc/randommodule-text.output
  test/integration/targets/ansible-doc/test_docs_suboptions.output
  test/integration/targets/ansible-doc/test_docs_yaml_anchors.output
  test/integration/targets/ansible-doc/yolo-text.output
Labels: backport, needs_triage, bug

#83139 [stable-2.14] Fix installing roles containing symlinks (#82911)
  changelogs/fragments/ansible-galaxy-role-install-symlink.yml
  lib/ansible/galaxy/role.py
  test/integration/targets/ansible-galaxy-role/files/safe-symlinks/defaults/common_vars/subdir/group0/main.yml
  test/integration/targets/ansible-galaxy-role/files/safe-symlinks/defaults/main.yml
  test/integration/targets/ansible-galaxy-role/files/safe-symlinks/handlers/utils.yml
  test/integration/targets/ansible-galaxy-role/files/safe-symlinks/meta/main.yml
  test/integration/targets/ansible-galaxy-role/files/safe-symlinks/tasks/utils/suite.yml
  test/integration/targets/ansible-galaxy-role/tasks/valid-role-symlinks.yml
Labels: backport, needs_triage, stale_ci, bug

#83177 [stable-2.16] uri: update docs for follow_redirects
  changelogs/fragments/uri_follow_redirect_bool.yml
  lib/ansible/modules/uri.py
  lib/ansible/plugins/lookup/url.py
Labels: backport, module, needs_triage

#83176 [stable-2.17] uri: update docs for follow_redirects
  changelogs/fragments/uri_follow_redirect_bool.yml
  lib/ansible/modules/uri.py
  lib/ansible/plugins/lookup/url.py
Labels: backport, module, needs_triage

#83137 [stable-2.16] Fix installing roles containing symlinks (#82911)
  changelogs/fragments/ansible-galaxy-role-install-symlink.yml
  lib/ansible/galaxy/role.py
  test/integration/targets/ansible-galaxy-role/files/safe-symlinks/defaults/common_vars/subdir/group0/main.yml
  test/integration/targets/ansible-galaxy-role/files/safe-symlinks/defaults/main.yml
  test/integration/targets/ansible-galaxy-role/files/safe-symlinks/handlers/utils.yml
  test/integration/targets/ansible-galaxy-role/files/safe-symlinks/meta/main.yml
  test/integration/targets/ansible-galaxy-role/files/safe-symlinks/tasks/utils/suite.yml
  test/integration/targets/ansible-galaxy-role/tasks/valid-role-symlinks.yml
Labels: backport, needs_triage, stale_ci, bug

#83138 [stable-2.15] Fix installing roles containing symlinks (#82911)
  changelogs/fragments/ansible-galaxy-role-install-symlink.yml
  lib/ansible/galaxy/role.py
  test/integration/targets/ansible-galaxy-role/files/safe-symlinks/defaults/common_vars/subdir/group0/main.yml
  test/integration/targets/ansible-galaxy-role/files/safe-symlinks/defaults/main.yml
  test/integration/targets/ansible-galaxy-role/files/safe-symlinks/handlers/utils.yml
  test/integration/targets/ansible-galaxy-role/files/safe-symlinks/meta/main.yml
  test/integration/targets/ansible-galaxy-role/files/safe-symlinks/tasks/utils/suite.yml
  test/integration/targets/ansible-galaxy-role/tasks/valid-role-symlinks.yml
Labels: backport, needs_triage, stale_ci, bug

#83124 [stable-2.16] assemble: fixed missing parameter error
  changelogs/fragments/82359_assemble_diff.yml
  lib/ansible/plugins/action/__init__.py
  test/integration/targets/assemble/tasks/main.yml
Labels: backport, needs_triage, stale_ci, bug

#83084 [stable-2.16] dnf fixes
  changelogs/fragments/82461-dnf-provides.yml
  changelogs/fragments/dnf-installed-checks-api.yml
  lib/ansible/modules/dnf.py
  lib/ansible/modules/dnf5.py
  test/integration/targets/dnf/tasks/repo.yml
  test/integration/targets/setup_rpm_repo/library/create_repo.py
Labels: backport, module, needs_triage, stale_ci, bug

#83191 [stable-2.17] display: fix log verbosity (#83179)
  changelogs/fragments/fix_log_verbosity.yml
  lib/ansible/utils/display.py
  test/integration/targets/ansible_log/runme.sh
Labels: backport, bug

#83040 [stable-2.16] Add the task info for tombstoned module/action plugins (#82451)
  changelogs/fragments/improve-tombstone-error.yml
  lib/ansible/parsing/mod_args.py
  test/integration/targets/collections/runme.sh
  test/units/playbook/test_included_file.py
Labels: backport, stale_ci, bug

#83128 [stable-2.16] inspect components, ansible_managed templatable (#83053)
  changelogs/fragments/ansible_managed_restore.yml
  lib/ansible/template/__init__.py
  test/integration/targets/template/ansible_managed.yml
  test/integration/targets/template/ansible_managed_79129.yml
  test/integration/targets/template/ansible_managed_templated.cfg
  test/integration/targets/template/runme.sh
Labels: backport, needs_triage, stale_ci, bug

#83078 [stable-2.16] Issue #80267: Remove user not found warning (#80291)
  changelogs/fragments/80267-ansible_builtin_user-remove-user-not-found-warning.yml
  lib/ansible/modules/user.py
  test/integration/targets/user/tasks/test_local.yml
Labels: backport, module, stale_ci

#83073 [stable-2.16] handlers: fix executing in lockstep using linear (#83030)
  changelogs/fragments/82307-handlers-lockstep-linear-fix.yml
  lib/ansible/executor/play_iterator.py
  test/integration/targets/handlers/handlers_lockstep_82307.yml
  test/integration/targets/handlers/runme.sh
Labels: backport, stale_ci, bug

#83109 [stable-2.15] facts: Add a generic detection for VMware product name
  changelogs/fragments/vmware_facts.yml
  lib/ansible/module_utils/facts/virtual/linux.py
Labels: backport, needs_triage, stale_ci, bug

#83164 [stable-2.17] Add version ceiling for pypsrp (#83122)
  changelogs/fragments/psrp-version-req.yml
  lib/ansible/plugins/connection/psrp.py
  test/lib/ansible_test/_data/requirements/constraints.txt
Labels: backport, needs_triage, bug

#83173 [stable-2.17] ansible-doc: correctly treat separate paragraphs in top-level descriptions as separate paragraphs
  changelogs/fragments/83155-ansible-doc-paragraphs.yml
  lib/ansible/cli/doc.py
  test/integration/targets/ansible-doc/randommodule-text.output
Labels: needs_revision, backport, bug

#83226 [stable-2.16] ansible-test - Use PyPI proxy for centos7
  changelogs/fragments/ansible-test-centos7-pypi-proxy.yml
  test/lib/ansible_test/_internal/pypi_proxy.py
Labels: backport, bug

#83228 [stable-2.15] ansible-test - Use PyPI proxy for centos7 (#83226)
  changelogs/fragments/ansible-test-centos7-pypi-proxy.yml
  test/lib/ansible_test/_internal/pypi_proxy.py
Labels: backport, needs_triage, bug

#83163 [stable-2.16] Add version ceiling for pypsrp (#83122)
  changelogs/fragments/psrp-version-req.yml
  lib/ansible/plugins/connection/psrp.py
  test/lib/ansible_test/_data/requirements/constraints.txt
Labels: needs_revision, backport, needs_triage, bug

#83229 [stable-2.14] ansible-test - Use PyPI proxy for centos7 (#83226)
  changelogs/fragments/ansible-test-centos7-pypi-proxy.yml
  test/lib/ansible_test/_internal/pypi_proxy.py
Labels: backport, needs_triage, bug

#83162 [stable-2.15] Add version ceiling for pypsrp (#83122)
  changelogs/fragments/psrp-version-req.yml
  lib/ansible/plugins/connection/psrp.py
  test/lib/ansible_test/_data/requirements/constraints.txt
Labels: needs_revision, backport, needs_triage, bug

#83232 Use inclusive word: logical
  lib/ansible/module_utils/basic.py
  lib/ansible/module_utils/csharp/Ansible.Process.cs
  lib/ansible/modules/dnf.py
  test/integration/targets/ansible-doc/runme.sh
  test/integration/targets/apt/tasks/apt.yml
Labels: module, needs_triage, bug

#83233 [backport-2.12] ansible-test - Use PyPI proxy for centos7 (#83226)
  changelogs/fragments/ansible-test-centos7-pypi-proxy.yml
  test/lib/ansible_test/_internal/pypi_proxy.py
Labels: backport, bug

#83231 [stable-2.17] setup_rpm_repo/create_repo: "Arch dependent binaries in noarch package (#83108)
  test/integration/targets/dnf/tasks/repo.yml
  test/integration/targets/setup_rpm_repo/library/create_repo.py
Labels: backport, test, needs_triage

#83239 New release v2.14.17rc1
  changelogs/CHANGELOG-v2.14.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.14.17rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83240 New release v2.15.12rc1
  changelogs/CHANGELOG-v2.15.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.15.12rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83241 New release v2.16.7rc1
  changelogs/CHANGELOG-v2.16.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.16.7rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83242 New release v2.17.0rc2
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.0rc2_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83243 Update Ansible release version to v2.14.17rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83245 Update Ansible release version to v2.16.7rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83194 remove old install info when installing collections
  changelogs/fragments/cleanup-outdated-galaxy-install-info.yml
  lib/ansible/galaxy/collection/__init__.py
  test/integration/targets/ansible-galaxy-collection/tasks/install.yml
Labels: bug, has_issue

#83211 Refactor dmidecode fact gathering code
  changelogs/fragments/freebsd_facts_refactor.yml
  lib/ansible/module_utils/facts/hardware/freebsd.py
  lib/ansible/module_utils/facts/hardware/linux.py
Labels: bug

#83246 Update Ansible release version to v2.17.0rc2.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#83244 Update Ansible release version to v2.15.12rc1.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#81297 setup module, make missing sysctl minor issue
  changelogs/fragments/sysctl_fact_fix.yml
  lib/ansible/module_utils/basic.py
  lib/ansible/module_utils/common/process.py
  lib/ansible/module_utils/facts/hardware/aix.py
  lib/ansible/module_utils/facts/hardware/darwin.py
  lib/ansible/module_utils/facts/hardware/freebsd.py
  lib/ansible/module_utils/facts/hardware/hpux.py
  lib/ansible/module_utils/facts/hardware/netbsd.py
  lib/ansible/module_utils/facts/hardware/openbsd.py
  lib/ansible/module_utils/facts/hardware/sunos.py
  lib/ansible/module_utils/facts/network/aix.py
  lib/ansible/module_utils/facts/network/fc_wwn.py
  lib/ansible/module_utils/facts/network/generic_bsd.py
  lib/ansible/module_utils/facts/network/hpux.py
  lib/ansible/module_utils/facts/network/hurd.py
  lib/ansible/module_utils/facts/network/iscsi.py
  lib/ansible/module_utils/facts/other/facter.py
  lib/ansible/module_utils/facts/other/ohai.py
  lib/ansible/module_utils/facts/sysctl.py
  test/units/module_utils/facts/network/test_fc_wwn.py
  test/units/module_utils/facts/network/test_generic_bsd.py
  test/units/module_utils/facts/network/test_iscsi_get_initiator.py
Labels: bug

#83258 Warn if binary is unavailable using get_bin_path
  lib/ansible/module_utils/basic.py
  lib/ansible/module_utils/facts/hardware/linux.py
  test/units/module_utils/basic/test_get_bin_path.py
  test/units/module_utils/facts/hardware/test_linux_get_cpu_info.py
Labels: needs_triage, bug

#83259 Remove deprecated VariableManager._get_delegated_vars
  changelogs/fragments/remove-deprecated-get_delegated_vars.yml
  lib/ansible/vars/manager.py
  test/sanity/ignore.txt
Labels: feature, has_issue

#83152 MUNI tech writers: timeout documentation.
  lib/ansible/config/base.yml
  lib/ansible/keyword_desc.yml
Labels: stale_ci

#83276 New release v2.14.17
  changelogs/CHANGELOG-v2.14.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.14.17_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83277 New release v2.15.12
  changelogs/CHANGELOG-v2.15.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.15.12_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83279 New release v2.16.7
  changelogs/CHANGELOG-v2.16.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.16.7_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83280 New release v2.17.0
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.0_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83281 Update Ansible release version to v2.14.17.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83282 Update Ansible release version to v2.15.12.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83283 Update Ansible release version to v2.16.7.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83284 Update Ansible release version to v2.17.0.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83269 Correct code comment in the PlaybookExecutor class to reflect current behavior
  lib/ansible/executor/playbook_executor.py
Labels: needs_triage, bug

#83301 filter: update the documentation for win_splitdrive
  lib/ansible/plugins/filter/win_splitdrive.yml
Labels: has_issue

#83230 apt_*: add more info message while updating apt cache
  changelogs/fragments/apt_cache.yml
  lib/ansible/modules/apt.py
  lib/ansible/modules/apt_repository.py
  test/integration/targets/apt/tasks/apt.yml
Labels: module, bug, has_issue

#83305 get_url: update docs for checksum
  lib/ansible/modules/get_url.py
Labels: module

#83311 ansible-doc: make color configurable
  changelogs/fragments/ansible-doc-color.yml
  lib/ansible/cli/doc.py
  lib/ansible/config/base.yml
Labels: bug

#83129 config, integrate dynamic galaxy servers
  lib/ansible/cli/config.py
  lib/ansible/cli/galaxy.py
  lib/ansible/config/manager.py
  lib/ansible/errors/__init__.py
  test/integration/targets/ansible-config/files/galaxy_server.ini
  test/integration/targets/ansible-config/tasks/main.yml
  test/units/galaxy/test_collection.py
  test/units/galaxy/test_token.py
Labels: bug

#83278 gather_facts, mention ansible_facts_parallel var
  lib/ansible/modules/gather_facts.py
Labels: module

#34228 file module, follow symlink when doing hardlink
  changelogs/fragments/file_hardlink.yml
  lib/ansible/modules/file.py
  test/integration/targets/file/tasks/link_follow.yml
Labels: module, support:core, stale_review, affects_2.5, new_contributor, bug, small_patch, verified, files, has_issue

#82003 Fix task.resolved_action callbacks
  changelogs/fragments/correct-callback-fqcn-old-style-action-invocation.yml
  lib/ansible/parsing/mod_args.py
  lib/ansible/playbook/task.py
  test/integration/targets/collections/test_task_resolved_plugin/unqualified_and_collections_kw.yml
  test/integration/targets/module_defaults/tasks/main.yml
  test/units/playbook/test_block.py
  test/units/playbook/test_helpers.py
Labels: bug

#83256 test: Cleanup facts/network/* tests
  test/units/module_utils/facts/network/test_fc_wwn.py
  test/units/module_utils/facts/network/test_generic_bsd.py
  test/units/module_utils/facts/network/test_iscsi_get_initiator.py
  test/units/module_utils/facts/network/test_locally_reachable_ips.py
Labels: test, code_health

#82803 The extension returned by the splitext contains the dot
  lib/ansible/plugins/filter/splitext.yml
Labels: has_issue

#83267 Documented v2_runner_on_failed method in Callback class
  lib/ansible/plugins/callback/__init__.py
Labels: stale_review
