Repository ansible/ansible, pull requests merged in 2024-09, with the labels that each got.

#83876 Add location on include_tasks fail inside include
  changelogs/fragments/83874-include-parse-error-location.yml
  lib/ansible/playbook/task_include.py
  test/integration/targets/include_import/null_filename/tasks.yml
  test/integration/targets/include_import/runme.sh
  test/integration/targets/include_import/test_null_include_filename.yml
Labels: needs_triage, bug

#83760 psrp - Remove extras lookups
  changelogs/fragments/psrp-extras.yml
  lib/ansible/plugins/connection/psrp.py
  test/units/plugins/connection/test_psrp.py
Labels: stale_ci, feature

#83882 [stable-2.16] - Add location on include_tasks fail inside include (#83876)
  changelogs/fragments/83874-include-parse-error-location.yml
  lib/ansible/playbook/task_include.py
  test/integration/targets/include_import/null_filename/tasks.yml
  test/integration/targets/include_import/runme.sh
  test/integration/targets/include_import/test_null_include_filename.yml
Labels: backport, needs_triage, bug

#83883 [stable-2.17] - Add location on include_tasks fail inside include (#83876)
  changelogs/fragments/83874-include-parse-error-location.yml
  lib/ansible/playbook/task_include.py
  test/integration/targets/include_import/null_filename/tasks.yml
  test/integration/targets/include_import/runme.sh
  test/integration/targets/include_import/test_null_include_filename.yml
Labels: backport, needs_triage, bug

#83857 [stable-2.16] runtime-metadata sanity test: do not fail deprecation version checks if galaxy.yml has empty `version`
  changelogs/fragments/83831-runtime-metadata-fix.yml
  lib/ansible/utils/version.py
  test/integration/targets/ansible-test-sanity-runtime-metadata/aliases
  test/integration/targets/ansible-test-sanity-runtime-metadata/ansible_collections/ns/no_version/galaxy.yml
  test/integration/targets/ansible-test-sanity-runtime-metadata/ansible_collections/ns/no_version/meta/runtime.yml
  test/integration/targets/ansible-test-sanity-runtime-metadata/ansible_collections/ns/version/galaxy.yml
  test/integration/targets/ansible-test-sanity-runtime-metadata/ansible_collections/ns/version/meta/runtime.yml
  test/integration/targets/ansible-test-sanity-runtime-metadata/expected-no_version.txt
  test/integration/targets/ansible-test-sanity-runtime-metadata/expected-version.txt
  test/integration/targets/ansible-test-sanity-runtime-metadata/runme.sh
  test/integration/targets/collection/setup.sh
  test/lib/ansible_test/_util/controller/sanity/code-smell/runtime-metadata.py
Labels: backport, needs_triage, bug

#83856 [stable-2.17] runtime-metadata sanity test: do not fail deprecation version checks if galaxy.yml has empty `version`
  changelogs/fragments/83831-runtime-metadata-fix.yml
  lib/ansible/utils/version.py
  test/integration/targets/ansible-test-sanity-runtime-metadata/aliases
  test/integration/targets/ansible-test-sanity-runtime-metadata/ansible_collections/ns/no_version/galaxy.yml
  test/integration/targets/ansible-test-sanity-runtime-metadata/ansible_collections/ns/no_version/meta/runtime.yml
  test/integration/targets/ansible-test-sanity-runtime-metadata/ansible_collections/ns/version/galaxy.yml
  test/integration/targets/ansible-test-sanity-runtime-metadata/ansible_collections/ns/version/meta/runtime.yml
  test/integration/targets/ansible-test-sanity-runtime-metadata/expected-no_version.txt
  test/integration/targets/ansible-test-sanity-runtime-metadata/expected-version.txt
  test/integration/targets/ansible-test-sanity-runtime-metadata/runme.sh
  test/integration/targets/collection/setup.sh
  test/lib/ansible_test/_util/controller/sanity/code-smell/runtime-metadata.py
Labels: backport, needs_triage, bug

#83880 Add DaemonThreadPoolExecutor impl
  lib/ansible/module_utils/_internal/__init__.py
  lib/ansible/module_utils/_internal/_concurrent/__init__.py
  lib/ansible/module_utils/_internal/_concurrent/_daemon_threading.py
  lib/ansible/module_utils/_internal/_concurrent/_futures.py
  test/units/module_utils/_internal/__init__.py
  test/units/module_utils/_internal/_concurrent/__init__.py
  test/units/module_utils/_internal/_concurrent/test_daemon_threading.py
  test/units/module_utils/_internal/_concurrent/test_futures.py
Labels: stale_review, feature

#83887 release.py - Add missing setuptools arg to prepare
  packaging/release.py
Labels: bug

#83889 [stable-2.16] release.py - Add missing setuptools arg to prepare
  packaging/release.py
Labels: backport, needs_triage, bug

#83888 [stable-2.17] release.py - Add missing setuptools arg to prepare
  packaging/release.py
Labels: backport, needs_triage, bug

#83891 New release v2.17.4rc1
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.4rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83890 New release v2.16.11rc1
  changelogs/CHANGELOG-v2.16.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.16.11rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83894 Update Ansible release version to v2.17.4rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83893 Update Ansible release version to v2.16.11rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83892 release.py - Include pyproject.toml in git add
  packaging/release.py
Labels: bug

#62151 loop_control "early exit" feature
  changelogs/fragments/62151-loop_control-until.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/playbook/loop_control.py
  test/integration/targets/loop_control/break_when.yml
  test/integration/targets/loop_control/runme.sh
  test/units/executor/test_task_executor.py
Labels: WIP, support:community, support:core, stale_review, docs, feature, has_issue, affects_2.10

#83908 Update subset.yml
  lib/ansible/plugins/test/subset.yml
Labels: needs_triage

#83901 delay keyword changed from int to float
  changelogs/fragments/delay_type.yml
  lib/ansible/playbook/task.py
  test/units/playbook/test_task.py
Labels: bug

#83909 Stop suggesting `easy_install` in hacking
  hacking/README.md
Labels: needs_triage

#83907 Fix iptables test for case when iptables exists
  lib/ansible/modules/iptables.py
  test/units/modules/test_iptables.py
Labels: test, module

#83920 release.py - Use changelog requirements
  packaging/release.py
  test/sanity/code-smell/package-data.requirements.in
  test/sanity/code-smell/package-data.requirements.txt
Labels: feature

#83921 ansible-test - Update sanity test requirements
  test/lib/ansible_test/_data/requirements/sanity.changelog.in
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  test/sanity/code-smell/mypy.requirements.txt
  test/sanity/code-smell/pymarkdown.requirements.txt
Labels: feature

#83923 New release v2.16.11
  changelogs/CHANGELOG-v2.16.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.16.11_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83924 New release v2.17.4
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.4_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83927 Update Ansible release version to v2.17.4.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83930 ansible-test - Update base/default containers
  test/lib/ansible_test/_data/completion/docker.txt
Labels: feature

#83925 Replace binary_modules Makefile with Python script
  test/integration/targets/binary_modules/Makefile
  test/integration/targets/binary_modules/build.py
Labels: test

#83866 fact gathering, mounts, fixes for single proc code and tests
  lib/ansible/module_utils/facts/hardware/linux.py
  test/integration/targets/gathering_facts/lib/multriprocessing/__init__.py
  test/integration/targets/gathering_facts/lib/multriprocessing/pool/__init__.py
  test/integration/targets/gathering_facts/no_threads.yml
  test/integration/targets/gathering_facts/runme.sh
Labels: bug

#83424 service_facts, fix systemd/ubuntu failed reporting
  changelogs/fragments/service_facts_systemd_fix.yml
  lib/ansible/modules/service_facts.py
Labels: module, bug, has_issue

#83913 file module: Clarify the docs that the force parameter works for hardlinks too
  lib/ansible/modules/file.py
Labels: module

#83827 runas - create new SYSTEM token for become
  changelogs/fragments/become-runas-system.yml
  lib/ansible/module_utils/csharp/Ansible.Become.cs
Labels: stale_ci, bug

#83862 Update communication links for the forum
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  README.md
Labels: stale_review

#83744 [stable-2.15] release.py - Auto-update setuptools upper bound (#83713)
  packaging/release.py
  pyproject.toml
  test/sanity/code-smell/package-data.py
Labels: backport, feature

#83953 timedout extended
  changelogs/fragments/timedout_test.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/plugins/test/core.py
  lib/ansible/plugins/test/timedout.yml
  test/integration/targets/test_core/tasks/main.yml
Labels: needs_revision, needs_triage, feature

#83919 Clarify galaxy CLI --help about install locations
  changelogs/fragments/ansible-galaxy-install-help.yml
  lib/ansible/cli/galaxy.py
Labels: stale_review, bug, P3

#83508 Add mount_facts module
  changelogs/fragments/83508_mount_facts.yml
  lib/ansible/modules/mount_facts.py
  test/integration/targets/mount_facts/aliases
  test/integration/targets/mount_facts/meta/main.yml
  test/integration/targets/mount_facts/tasks/main.yml
  test/units/modules/mount_facts_data.py
  test/units/modules/test_mount_facts.py
Labels: module, feature, has_issue

#83961 dnf5: re-introduce ``state: installed`` alias
  changelogs/fragments/83960-dnf5-state-installed-fix.yml
  lib/ansible/modules/dnf5.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: module, needs_triage, bug, has_issue

#83979 ansible-galaxy - include the action in the usage
  lib/ansible/cli/galaxy.py
Labels: needs_triage, bug

#83984 ansible-test - Use Python version in pylint contexts
  changelogs/fragments/ansible-test-pylint-py-version.yml
  test/lib/ansible_test/_internal/commands/sanity/pylint.py
  test/lib/ansible_test/_util/controller/sanity/pylint/plugins/deprecated.py
Labels: bug

#83688 isidentifier: Remove Python 2 specific code
  changelogs/fragments/isidentifier.yml
  lib/ansible/utils/vars.py
  test/units/utils/test_isidentifier.py
Labels: test, stale_ci

#83985 bump devel to 2.19
  .github/RELEASE_NAMES.txt
  lib/ansible/release.py
  test/sanity/ignore.txt
Labels: needs_triage, feature

#83989 Move ansible-deprecated ignores for tests inline
  test/sanity/ignore.txt
  test/units/module_utils/basic/test_deprecate_warn.py
  test/units/module_utils/common/warnings/test_deprecate.py
Labels: test

#83990 [stable-2.18] Move ansible-deprecated ignores for tests inline (#83989)
  test/sanity/ignore.txt
  test/units/module_utils/basic/test_deprecate_warn.py
  test/units/module_utils/common/warnings/test_deprecate.py
Labels: backport, test

#83969 dnf5: fix tb when plugins API is not available
  changelogs/fragments/dnf5-plugins-compat.yml
  lib/ansible/modules/dnf5.py
Labels: module, needs_triage, bug

#83965 Add basic validation for action_groups
  changelogs/fragments/83965-action-groups-schema.yml
  test/integration/targets/ansible-test-sanity-runtime-metadata/ansible_collections/ns/no_version/meta/runtime.yml
  test/integration/targets/ansible-test-sanity-runtime-metadata/ansible_collections/ns/version/meta/runtime.yml
  test/integration/targets/ansible-test-sanity-runtime-metadata/expected-no_version.txt
  test/integration/targets/ansible-test-sanity-runtime-metadata/expected-version.txt
  test/lib/ansible_test/_util/controller/sanity/code-smell/runtime-metadata.py
Labels: feature

#83982 split: Fix incorrect example result of the split builtin filter
  lib/ansible/plugins/filter/split.yml
Labels: needs_triage

#83933 Ansible Errors, Don't hide stacked messages when yaml
  changelogs/fragments/fix_errors.yml
  lib/ansible/errors/__init__.py
  lib/ansible/playbook/base.py
  test/integration/targets/template/tasks/main.yml
Labels: bug

#84002 Test entry points with editable install
  test/integration/targets/entry_points/runme.sh
Labels: test

#83897 [stable-2.17] release.py - Include pyproject.toml in git add (#83892)
  packaging/release.py
Labels: backport, stale_ci, bug

#84003 [stable-2.14] Reduce CI test matrix
  .azure-pipelines/azure-pipelines.yml
Labels: backport, test

#84004 New release v2.18.0b1
  changelogs/CHANGELOG-v2.18.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.18.0b1_summary.yaml
  lib/ansible/release.py
  pyproject.toml
Labels: backport, feature

#84005 Update Ansible release version to v2.18.0b1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83995 package/dnf action plugins: better facts failure msg
  changelogs/fragments/package-dnf-action-plugins-facts-fail-msg.yml
  lib/ansible/plugins/action/dnf.py
  lib/ansible/plugins/action/package.py
Labels: feature

#84012 facts: Skip path if the distribution path is directory
  changelogs/fragments/os_family.yml
  lib/ansible/module_utils/facts/system/distribution.py
  test/units/module_utils/facts/system/distribution/test_distribution_files.py
Labels: bug, has_issue

#84001 INVENTORY_IGNORE_EXTS stop ignoring ini
  changelogs/fragments/remove_ini_ignored_dir.yml
  lib/ansible/config/base.yml
  lib/ansible/plugins/inventory/script.py
Labels: feature

#83977 [stable-2.16] dnf5: re-introduce ``state: installed`` alias (#83961)
  changelogs/fragments/83960-dnf5-state-installed-fix.yml
  lib/ansible/modules/dnf5.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: backport, module, needs_triage, bug

#83976 [stable-2.17] dnf5: re-introduce ``state: installed`` alias (#83961)
  changelogs/fragments/83960-dnf5-state-installed-fix.yml
  lib/ansible/modules/dnf5.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: backport, module, needs_triage, bug

#83963 [2.17] Clarify galaxy CLI --help about install locations (#83919)
  changelogs/fragments/ansible-galaxy-install-help.yml
  lib/ansible/cli/galaxy.py
Labels: backport, needs_triage, bug

#84000 Ansible Errors, Don't hide stacked messages when yaml (#83933)
  changelogs/fragments/fix_errors.yml
  lib/ansible/errors/__init__.py
  lib/ansible/playbook/base.py
  test/integration/targets/template/tasks/main.yml
Labels: backport, needs_triage, bug

#83991 [stable-2.18] dnf5: fix tb when plugins API is not available (#83969)
  changelogs/fragments/dnf5-plugins-compat.yml
  lib/ansible/modules/dnf5.py
Labels: backport, module, needs_triage, bug

#84013 [stable-2.18] package/dnf action plugins: better facts failure msg (#83995)
  changelogs/fragments/package-dnf-action-plugins-facts-fail-msg.yml
  lib/ansible/plugins/action/dnf.py
  lib/ansible/plugins/action/package.py
Labels: backport, needs_triage, bug

#84008 Add additional logging for SSH runtime output timeouts and escalation messages
  changelogs/fragments/84008-additional-logging.yml
  lib/ansible/plugins/connection/ssh.py
Labels: feature

#84023 Prevent condor from being installed and fulfilling libfmt dependency
  test/integration/targets/dnf5/playbook.yml
Labels: test, needs_triage

#84025 [stable-2.17] Prevent condor from being installed and fulfilling libfmt dependency (#84023)
  test/integration/targets/dnf5/playbook.yml
Labels: backport, needs_triage

#84024 [stable-2.18] Prevent condor from being installed and fulfilling libfmt dependency (#84023)
  test/integration/targets/dnf5/playbook.yml
Labels: backport, needs_triage

#83792 [stable-2.17] fix copy module update atime/mtime (#83235)
  changelogs/fragments/83235-copy-module-update-mtime.yml
  lib/ansible/module_utils/basic.py
  test/integration/targets/copy/tasks/tests.yml
  test/units/module_utils/basic/test_atomic_move.py
Labels: backport, needs_triage, stale_ci, bug

#83912 delay keyword changed from int to float (#83901)
  changelogs/fragments/delay_type.yml
  lib/ansible/playbook/task.py
  test/units/playbook/test_task.py
Labels: backport, needs_triage, stale_ci, bug

#83859 [stable-2.17] copy, fix permissions and atime on diff partitions (#83824)
  changelogs/fragments/atomic_update_perms_time.yml
  lib/ansible/module_utils/basic.py
  test/integration/targets/copy/tasks/tests.yml
Labels: needs_revision, backport, needs_triage, ci_verified, stale_ci, bug

#84026 New release v2.16.12rc1
  changelogs/CHANGELOG-v2.16.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.16.12rc1_summary.yaml
  lib/ansible/release.py
  pyproject.toml
Labels: backport, needs_triage, feature

#84027 New release v2.17.5rc1
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.5rc1_summary.yaml
  lib/ansible/release.py
  pyproject.toml
Labels: backport, needs_triage, feature

#84030 Update Ansible release version to v2.17.5rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#84029 Update Ansible release version to v2.16.12rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature
