Repository ansible/ansible, pull requests merged in 2024-08, with the labels that each got.

#83686 test: update tests
  test/units/cli/test_galaxy.py
  test/units/module_utils/basic/test_filesystem.py
  test/units/module_utils/facts/test_collector.py
  test/units/module_utils/urls/test_fetch_url.py
  test/units/template/test_templar.py
  test/units/utils/test_helpers.py
  test/units/utils/test_vars.py
Labels: test

#82718 add error handling when parsing values in ini files
  changelogs/fragments/local_facts_d.yml
  lib/ansible/module_utils/facts/system/local.py
  test/integration/targets/facts_d/files/bad.fact
  test/integration/targets/facts_d/tasks/main.yml
Labels: stale_ci, bug, has_issue

#81770 Add UID and GID min/max keys
  changelogs/fragments/81770-add-uid-guid-minmax-keys.yml
  lib/ansible/modules/group.py
  lib/ansible/modules/user.py
  test/integration/targets/group/tasks/main.yml
  test/integration/targets/group/tasks/test_create_group_min_max.yml
  test/integration/targets/user/tasks/main.yml
  test/integration/targets/user/tasks/test_create_user_min_max.yml
Labels: module, stale_ci, stale_review, feature, has_issue

#83701 [stable-2.17] tests: use keyserver with keyid while using apt_key
  test/integration/targets/apt_repository/tasks/apt.yml
Labels: backport, test

#83702 [stable-2.16] tests: use keyserver with keyid while using apt_key
  test/integration/targets/apt_repository/tasks/apt.yml
Labels: backport, test

#83703 [stable-2.15] tests: use keyserver with keyid while using apt_key
  test/integration/targets/apt_repository/tasks/apt.yml
Labels: backport, test

#83704 [stable-2.14] tests: use keyserver with keyid while using apt_key
  test/integration/targets/apt_repository/tasks/apt.yml
Labels: backport, test

#83684 systemd facts: Handle AttributeError
  changelogs/fragments/systemd_facts.yml
  lib/ansible/module_utils/facts/collector.py
  lib/ansible/module_utils/facts/system/systemd.py
  test/units/module_utils/facts/test_ansible_collector.py
Labels: needs_revision, ci_verified, bug

#83706 Remove EXTERNALLY-MANAGED marker in apt test
  test/integration/targets/apt/tasks/main.yml
Labels: test

#83628 [stable-2.17] debconf: handle boolean value representation consistently
  changelogs/fragments/83601-debconf-normalize-bools.yml
  lib/ansible/modules/debconf.py
  test/integration/targets/debconf/tasks/main.yml
Labels: backport, module, needs_triage, stale_ci, bug

#83607 [stable-2.17] Update any.yml
  lib/ansible/plugins/test/any.yml
Labels: backport, test, needs_triage

#83591 module compression is now again settable via var (#83573)
  changelogs/fragments/mc_fix.yml
  lib/ansible/config/base.yml
Labels: backport, needs_triage, bug

#83528 [stable-2.17] linear: fix included handlers executing in lockstep (#83209)
  changelogs/fragments/83019-linear-handlers-lockstep-fix.yml
  lib/ansible/plugins/strategy/linear.py
  test/integration/targets/handlers/handlers_lockstep_83019-include-nested.yml
  test/integration/targets/handlers/handlers_lockstep_83019-include.yml
  test/integration/targets/handlers/handlers_lockstep_83019.yml
  test/integration/targets/handlers/runme.sh
Labels: backport, bug

#83529 [stable-2.16] linear: fix included handlers executing in lockstep (#83209)
  changelogs/fragments/83019-linear-handlers-lockstep-fix.yml
  lib/ansible/plugins/strategy/linear.py
  test/integration/targets/handlers/handlers_lockstep_83019-include-nested.yml
  test/integration/targets/handlers/handlers_lockstep_83019-include.yml
  test/integration/targets/handlers/handlers_lockstep_83019.yml
  test/integration/targets/handlers/runme.sh
Labels: backport, bug

#83592 module compression is now again settable via var (#83573)
  changelogs/fragments/mc_fix.yml
  lib/ansible/config/base.yml
Labels: backport, needs_triage, bug

#83606 [stable-2.16] Update any.yml
  lib/ansible/plugins/test/any.yml
Labels: backport, test, needs_triage

#83605 [stable-2.15] Update any.yml
  lib/ansible/plugins/test/any.yml
Labels: backport, test, needs_triage

#83322 Provide filename and line number of variable which triggered the deprecation warning
  changelogs/fragments/82528summary.yml
  lib/ansible/playbook/base.py
Labels: backport, stale_review

#83675 Remove extraneous get_bin_path call
  changelogs/fragments/linux_network_get.yml
  lib/ansible/module_utils/facts/network/linux.py
Labels: needs_revision, bug

#83719 New release v2.16.10rc1
  changelogs/CHANGELOG-v2.16.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.16.10rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83720 New release v2.17.3rc1
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.3rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83722 Update Ansible release version to v2.17.3rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83721 Update Ansible release version to v2.16.10rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83713 release.py - Auto-update setuptools upper bound
  packaging/release.py
  pyproject.toml
  test/sanity/code-smell/package-data.py
Labels: feature

#83723 ansible-test - Update coverage to 7.6.1
  changelogs/fragments/ansible-test-coverage-update.yml
  test/lib/ansible_test/_data/requirements/ansible-test.txt
  test/lib/ansible_test/_internal/coverage_util.py
Labels: feature

#83724 Fix type hints and misc mypy/pylint issues
  lib/ansible/galaxy/collection/galaxy_api_proxy.py
  lib/ansible/utils/display.py
  test/lib/ansible_test/_internal/timeout.py
  test/lib/ansible_test/_internal/util_common.py
Labels: bug

#83712 Fix display to log severity mapping
  changelogs/fragments/display_fix_log_severity.yml
  lib/ansible/utils/display.py
  test/integration/targets/ansible_log/logit.yml
  test/integration/targets/ansible_log/runme.sh
Labels: needs_triage, bug

#83726 core: raw params better error msg
  changelogs/fragments/raw_clean_msg.yml
  lib/ansible/constants.py
  lib/ansible/parsing/mod_args.py
Labels: needs_triage, bug

#83710 fix error message when csvfile receives no search term
  changelogs/fragments/fix-inconsistent-csvfile-missing-search-error.yml
  lib/ansible/plugins/lookup/csvfile.py
  test/integration/targets/lookup_csvfile/tasks/main.yml
Labels: bug, has_issue

#83621 Fix task-adjacent search path in roles
  changelogs/fragments/dwim_is_role_fix_task_relative.yml
  lib/ansible/parsing/dataloader.py
  test/integration/targets/lookup_first_found/roles/a/tasks/main.yml
  test/integration/targets/lookup_first_found/roles/a/tasks/subdir/main.yml
  test/integration/targets/lookup_first_found/roles/a/tasks/subdir/relative
  test/integration/targets/lookup_first_found/tasks/main.yml
Labels: bug, has_issue

#83729 ansible-test - Update venv management and sanity requirements
  changelogs/fragments/ansible-test-sanity-test-requirements.yml
  changelogs/fragments/ansible-test-venv-bootstrap.yml
  hacking/update-sanity-requirements.py
  test/lib/ansible_test/_data/requirements/constraints.txt
  test/lib/ansible_test/_data/requirements/sanity.ansible-doc.txt
  test/lib/ansible_test/_data/requirements/sanity.changelog.txt
  test/lib/ansible_test/_data/requirements/sanity.import.plugin.txt
  test/lib/ansible_test/_data/requirements/sanity.import.txt
  test/lib/ansible_test/_data/requirements/sanity.integration-aliases.txt
  test/lib/ansible_test/_data/requirements/sanity.mypy.in
  test/lib/ansible_test/_data/requirements/sanity.mypy.txt
  test/lib/ansible_test/_data/requirements/sanity.pep8.txt
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  test/lib/ansible_test/_data/requirements/sanity.runtime-metadata.txt
  test/lib/ansible_test/_data/requirements/sanity.validate-modules.txt
  test/lib/ansible_test/_internal/python_requirements.py
  test/lib/ansible_test/_util/controller/sanity/mypy/ansible-core.ini
  test/lib/ansible_test/_util/controller/sanity/mypy/ansible-test.ini
  test/lib/ansible_test/_util/controller/sanity/pylint/config/collection.cfg
  test/lib/ansible_test/_util/controller/sanity/pylint/config/default.cfg
  test/lib/ansible_test/_util/target/setup/requirements.py
  test/sanity/code-smell/deprecated-config.requirements.txt
  test/sanity/code-smell/package-data.requirements.in
  test/sanity/code-smell/package-data.requirements.txt
  test/sanity/code-smell/pymarkdown.requirements.txt
  test/sanity/code-smell/update-bundled.requirements.txt
  test/sanity/ignore.txt
Labels: feature

#83734 ansible-test - Update mypy and package-data tests
  MANIFEST.in
  test/lib/ansible_test/_internal/commands/sanity/__init__.py
  test/lib/ansible_test/_internal/commands/sanity/mypy.py
  test/sanity/code-smell/mypy.json
  test/sanity/code-smell/mypy.py
  test/sanity/code-smell/mypy.requirements.in
  test/sanity/code-smell/mypy.requirements.txt
  test/sanity/code-smell/mypy/ansible-core.ini
  test/sanity/code-smell/mypy/ansible-test.ini
  test/sanity/code-smell/mypy/modules.ini
  test/sanity/code-smell/mypy/packaging.ini
  test/sanity/code-smell/package-data.json
  test/sanity/code-smell/package-data.py
  test/sanity/code-smell/pymarkdown.py
Labels: feature

#83735 try disabling negative values win_reboot test
  test/integration/targets/incidental_win_reboot/tasks/main.yml
Labels: test, needs_triage

#83736 ansible-test - Update default and distro containers
  test/lib/ansible_test/_data/completion/docker.txt
Labels: feature

#83293 Deprecate remaining safe evals
  changelogs/fragments/deprecate-safe-evals.yml
  lib/ansible/module_utils/basic.py
  lib/ansible/module_utils/common/validation.py
  test/units/module_utils/common/validation/test_check_type_dict.py
Labels: feature

#83751 Fix csvfile testcase - quote string, not intended to be a variable
  test/integration/targets/lookup_csvfile/tasks/main.yml
Labels: test, needs_triage

#83717 Add vaulted_file test
  changelogs/fragments/vaulted_file_and_fixes.yml
  lib/ansible/parsing/dataloader.py
  lib/ansible/parsing/vault/__init__.py
  lib/ansible/plugins/test/core.py
  lib/ansible/plugins/test/vault_encrypted.yml
  lib/ansible/plugins/test/vaulted_file.yml
  test/integration/targets/test_core/files/notvault
  test/integration/targets/test_core/files/vault1
  test/integration/targets/test_core/files/vault2
  test/integration/targets/test_core/tasks/main.yml
  test/units/parsing/vault/test_vault.py
Labels: feature

#83738 use diff intermediate var to preserve functionality
  lib/ansible/parsing/mod_args.py
  test/integration/targets/run_modules/run_raw_args.yml
  test/integration/targets/run_modules/runme.sh
Labels: stale_review, bug, has_issue

#83711 fix: `COLOR_INCLUDED` to colorize `included` output
  changelogs/fragments/colors_for_included_events.yml
  lib/ansible/config/base.yml
  lib/ansible/plugins/callback/default.py
  lib/ansible/utils/display.py
Labels: stale_review, bug, has_issue

#83716 Enable validation of subkeys in rpm key module
  changelogs/fragments/83716-enable-subkey-fingerprint-validation-in-rpm-key-module.yml
  lib/ansible/modules/rpm_key.py
  test/integration/targets/rpm_key/tasks/rpm_key.yaml
Labels: module, bug, P3

#81443 Drop use of setup.py and setup.cfg
  .gitignore
  MANIFEST.in
  pyproject.toml
  setup.cfg
  setup.py
  test/lib/ansible_test/_internal/classification/__init__.py
  test/sanity/code-smell/package-data.py
Labels: stale_review, feature

#83767 New release v2.16.10
  changelogs/CHANGELOG-v2.16.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.16.10_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83768 New release v2.17.3
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.3_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83771 Update Ansible release version to v2.17.3.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83770 Update Ansible release version to v2.16.10.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83772 Suppress cryptography warnings for paramiko
  changelogs/fragments/suppress-paramiko-warnings.yml
  lib/ansible/module_utils/compat/paramiko.py
Labels: feature

#83773 ini lookup: add new interpolation option
  changelogs/fragments/83755-ini-new-interpolation-option.yml
  lib/ansible/plugins/lookup/ini.py
  test/integration/targets/lookup_ini/interpolation.ini
  test/integration/targets/lookup_ini/nointerpolation.ini
  test/integration/targets/lookup_ini/test_ini.yml
  test/integration/targets/lookup_ini/test_interpolation.yml
Labels: feature, has_issue

#83438 Fix meta tasks breaking host/fork affinity with host_pinned
  changelogs/fragments/83294-meta-host_pinned-affinity.yml
  lib/ansible/plugins/strategy/free.py
  test/integration/targets/strategy_host_pinned/aliases
  test/integration/targets/strategy_host_pinned/callback_plugins/callback_host_count.py
  test/integration/targets/strategy_host_pinned/hosts
  test/integration/targets/strategy_host_pinned/playbook.yml
  test/integration/targets/strategy_host_pinned/runme.sh
Labels: bug, has_issue

#83756 Ensure skipped loop iteration register var is available
  changelogs/fragments/83619-loop-label-register.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/playbook/task.py
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/loops/tasks/main.yml
Labels: bug, has_issue

#83777 Fix ansible-vault integration test
  test/integration/targets/ansible-vault/runme.sh
Labels: test

#83263 Add end_role meta task
  changelogs/fragments/end_role.yml
  lib/ansible/modules/meta.py
  lib/ansible/playbook/helpers.py
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/roles/end_role.yml
  test/integration/targets/roles/end_role_handler_error.yml
  test/integration/targets/roles/end_role_nested.yml
  test/integration/targets/roles/roles/end_role_inside/handlers/main.yml
  test/integration/targets/roles/roles/end_role_inside/tasks/main.yml
  test/integration/targets/roles/roles/end_role_inside/tasks/nested.yml
  test/integration/targets/roles/roles/end_role_inside_nested/tasks/import_tasks.yml
  test/integration/targets/roles/roles/end_role_inside_nested/tasks/include_tasks.yml
  test/integration/targets/roles/roles/end_role_inside_nested/tasks/main.yml
  test/integration/targets/roles/runme.sh
Labels: module, feature

#83235 fix copy module update atime/mtime
  changelogs/fragments/83235-copy-module-update-mtime.yml
  lib/ansible/module_utils/basic.py
  test/integration/targets/copy/tasks/tests.yml
  test/units/module_utils/basic/test_atomic_move.py
Labels: stale_ci, bug

#83786 ansible-test - Remove generation of egg-info
  changelogs/fragments/ansible-test-no-egg-info.yml
  hacking/env-setup
  hacking/env-setup.fish
  test/lib/ansible_test/_internal/ansible_util.py
Labels: feature

#83795 ansible-test - Update sanity test requirements
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  test/lib/ansible_test/_data/requirements/sanity.yamllint.in
  test/lib/ansible_test/_data/requirements/sanity.yamllint.txt
  test/sanity/code-smell/mypy.requirements.txt
Labels: feature

#83796 ansible-test - Update base/default containers
  test/lib/ansible_test/_data/completion/docker.txt
Labels: feature

#83769 Add explicit winrm/psrp tests for HTTP and HTTPS
  test/integration/targets/connection_psrp/tests.yml
  test/integration/targets/connection_winrm/tests.yml
Labels: test

#83753 ssh and psrp - Support more complex characters in fetch_file
  changelogs/fragments/fetch-filename.yml
  lib/ansible/plugins/connection/psrp.py
  lib/ansible/plugins/connection/ssh.py
  test/integration/targets/connection/test_connection.yml
  test/integration/targets/win_fetch/aliases
Labels: bug, has_issue

#83750 Gather mount facts, fallback for when multiproc is not feasable
  changelogs/fragments/gather_facts_single.yml
  lib/ansible/module_utils/facts/hardware/linux.py
  test/integration/targets/gathering_facts/lib/multriprocessing/__init__.py
  test/integration/targets/gathering_facts/lib/multriprocessing/pool/__init__.py
  test/integration/targets/gathering_facts/no_threads.yml
  test/integration/targets/gathering_facts/runme.sh
Labels: stale_review, bug, has_issue

#83353 connection plugins: extras fix
  changelogs/fragments/extras_fix.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/plugins/__init__.py
  test/units/plugins/connection/test_psrp.py
Labels: bug, has_issue

#83830 Fix up raw_params for ansible.windows modules
  lib/ansible/parsing/mod_args.py
  test/integration/targets/windows-minimal/tasks/main.yml
Labels: needs_triage, bug

#83297 dnf: stop filtering exceptions by matching on text
  changelogs/fragments/dnf-exceptions-vs-text.yml
  lib/ansible/modules/dnf.py
Labels: module, bug

#83695 Handle authentication errors and token expiration
  changelogs/fragments/galaxy-reauth-error-handling.yml
  lib/ansible/galaxy/token.py
Labels: stale_ci, bug

#83847 powershell - Improve CLIXML parsing
  changelogs/fragments/powershell-clixml.yml
  lib/ansible/plugins/shell/powershell.py
  test/integration/targets/connection_winrm/tests.yml
  test/units/plugins/shell/test_powershell.py
Labels: needs_triage, bug

#83803 galaxy-cli tasking polling interval from environment variable
  changelogs/fragments/83803-collection-import-poll-interval.yml
  lib/ansible/config/base.yml
  lib/ansible/galaxy/api.py
Labels: needs_revision, feature

#83831 runtime-metadata sanity test: do not fail deprecation version checks if galaxy.yml has empty `version`
  changelogs/fragments/83831-runtime-metadata-fix.yml
  lib/ansible/utils/version.py
  test/integration/targets/ansible-test-sanity-runtime-metadata/aliases
  test/integration/targets/ansible-test-sanity-runtime-metadata/ansible_collections/ns/no_version/galaxy.yml
  test/integration/targets/ansible-test-sanity-runtime-metadata/ansible_collections/ns/no_version/meta/runtime.yml
  test/integration/targets/ansible-test-sanity-runtime-metadata/ansible_collections/ns/version/galaxy.yml
  test/integration/targets/ansible-test-sanity-runtime-metadata/ansible_collections/ns/version/meta/runtime.yml
  test/integration/targets/ansible-test-sanity-runtime-metadata/expected-no_version.txt
  test/integration/targets/ansible-test-sanity-runtime-metadata/expected-version.txt
  test/integration/targets/ansible-test-sanity-runtime-metadata/runme.sh
  test/integration/targets/collection/setup.sh
  test/lib/ansible_test/_util/controller/sanity/code-smell/runtime-metadata.py
Labels: bug, has_issue

#83824 copy, fix permissions and atime on diff partitions
  changelogs/fragments/atomic_update_perms_time.yml
  lib/ansible/module_utils/basic.py
  test/integration/targets/copy/tasks/tests.yml
Labels: bug, has_issue

#83865 Fix false pass in `delegate_to` integration test
  test/integration/targets/delegate_to/delegate_with_fact_from_delegate_host.yml
Labels: test, needs_triage

#83761 Print the name of the option being deprecated
  lib/ansible/cli/__init__.py
  lib/ansible/config/manager.py
  lib/ansible/constants.py
  test/integration/targets/deprecations/runme.sh
Labels: bug, has_issue

#83764 [2.17] atomic_move - fix creating file in directory with setgid bit (#83718)
  changelogs/fragments/46742-atomic_move-fix-setgid.yml
  lib/ansible/module_utils/basic.py
  test/integration/targets/copy/defaults/main.yml
  test/integration/targets/copy/tasks/main.yml
  test/integration/targets/copy/tasks/setgid.yml
Labels: backport, needs_triage, stale_ci, bug

#83742 [stable-2.17] release.py - Auto-update setuptools upper bound (#83713)
  packaging/release.py
  pyproject.toml
  test/sanity/code-smell/package-data.py
Labels: backport, stale_ci, feature

#83732 [2.17] csvfile lookup - fix giving an error when no search term is provided (#83710)
  changelogs/fragments/fix-inconsistent-csvfile-missing-search-error.yml
  lib/ansible/plugins/lookup/csvfile.py
  test/integration/targets/lookup_csvfile/tasks/main.yml
Labels: backport, needs_triage, stale_ci, bug

#83870 ansible-test - Update nios-test-container to 5.0.0
  changelogs/fragments/ansible-test-nios-container.yml
  test/lib/ansible_test/_internal/commands/integration/cloud/nios.py
Labels: feature

#83778 [stable-2.17] Fix meta tasks breaking host/fork affinity with host_pinned (#83438)
  changelogs/fragments/83294-meta-host_pinned-affinity.yml
  lib/ansible/plugins/strategy/free.py
  test/integration/targets/strategy_host_pinned/aliases
  test/integration/targets/strategy_host_pinned/callback_plugins/callback_host_count.py
  test/integration/targets/strategy_host_pinned/hosts
  test/integration/targets/strategy_host_pinned/playbook.yml
  test/integration/targets/strategy_host_pinned/runme.sh
Labels: backport, needs_triage, bug

#83788 [stable-2.17] Ensure skipped loop iteration register var is available (#83756)
  changelogs/fragments/83619-loop-label-register.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/playbook/task.py
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/loops/tasks/main.yml
Labels: backport, needs_triage, bug

#83810 [stable-2.17] Add explicit winrm/psrp tests for HTTP and HTTPS (#83769)
  test/integration/targets/connection_psrp/tests.yml
  test/integration/targets/connection_winrm/tests.yml
Labels: backport, test, needs_triage

#83817 [stable-2.17] - ssh and psrp - Support more complex characters in fetch_file (#83753)
  changelogs/fragments/fetch-filename.yml
  lib/ansible/plugins/connection/psrp.py
  lib/ansible/plugins/connection/ssh.py
  test/integration/targets/connection/test_connection.yml
  test/integration/targets/win_fetch/aliases
Labels: backport, needs_triage, bug

#83819 [stable-2.17] connection plugins: extras fix (#83353)
  changelogs/fragments/extras_fix.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/plugins/__init__.py
  test/units/plugins/connection/test_psrp.py
Labels: backport, needs_triage, bug

#83731 [stable-2.16] Fix task-adjacent search path in roles (#83621)
  changelogs/fragments/dwim_is_role_fix_task_relative.yml
  lib/ansible/parsing/dataloader.py
  test/integration/targets/lookup_first_found/roles/a/tasks/main.yml
  test/integration/targets/lookup_first_found/roles/a/tasks/subdir/main.yml
  test/integration/targets/lookup_first_found/roles/a/tasks/subdir/relative
  test/integration/targets/lookup_first_found/tasks/main.yml
Labels: backport, needs_triage, bug

#83733 [stable-2.16] csvfile lookup - fix giving an error when no search term is provided (#83710)
  changelogs/fragments/fix-inconsistent-csvfile-missing-search-error.yml
  lib/ansible/plugins/lookup/csvfile.py
  test/integration/targets/lookup_csvfile/tasks/main.yml
Labels: backport, needs_triage, bug

#83779 [stable-2.16] Fix meta tasks breaking host/fork affinity with host_pinned (#83438)
  changelogs/fragments/83294-meta-host_pinned-affinity.yml
  lib/ansible/plugins/strategy/free.py
  test/integration/targets/strategy_host_pinned/aliases
  test/integration/targets/strategy_host_pinned/callback_plugins/callback_host_count.py
  test/integration/targets/strategy_host_pinned/hosts
  test/integration/targets/strategy_host_pinned/playbook.yml
  test/integration/targets/strategy_host_pinned/runme.sh
Labels: backport, needs_triage, bug

#83789 [stable-2.16] Ensure skipped loop iteration register var is available (#83756)
  changelogs/fragments/83619-loop-label-register.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/playbook/task.py
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/loops/tasks/main.yml
Labels: backport, needs_triage, bug

#83809 [stable-2.16] Add explicit winrm/psrp tests for HTTP and HTTPS (#83769)
  test/integration/targets/connection_psrp/tests.yml
  test/integration/targets/connection_winrm/tests.yml
Labels: backport, test, needs_triage

#83816 [stable-2.16] - ssh and psrp - Support more complex characters in fetch_file (#83753)
  changelogs/fragments/fetch-filename.yml
  lib/ansible/plugins/connection/psrp.py
  lib/ansible/plugins/connection/ssh.py
  test/integration/targets/connection/test_connection.yml
  test/integration/targets/win_fetch/aliases
Labels: backport, needs_triage, bug

#83849 [stable-2.17] powershell - Improve CLIXML parsing (#83847)
  changelogs/fragments/powershell-clixml.yml
  lib/ansible/plugins/shell/powershell.py
  test/integration/targets/connection_winrm/tests.yml
  test/units/plugins/shell/test_powershell.py
Labels: backport, needs_triage, bug

#83843 [stable-2.17] config base: fix typo in option description
  lib/ansible/config/base.yml
Labels: backport, needs_triage, bug

#83783 [stable-2.16] Fix ansible-vault integration test for missing vault ids (#83777)
  test/integration/targets/ansible-vault/runme.sh
Labels: backport, test, needs_triage

#83820 [stable-2.16] connection plugins: extras fix (#83353)
  changelogs/fragments/extras_fix.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/plugins/__init__.py
  test/units/plugins/connection/test_psrp.py
Labels: backport, needs_triage, bug

#83846 [stable-2.16] Fix module arg parsing with respawned module on Python 2
  changelogs/fragments/83812-py2-respawn.yml
  lib/ansible/module_utils/common/respawn.py
Labels: backport, needs_triage, bug

#83743 [stable-2.16] release.py - Auto-update setuptools upper bound (#83713)
  packaging/release.py
  pyproject.toml
  test/sanity/code-smell/package-data.py
Labels: backport, stale_ci, feature

#83873 Fix Windows entries in test matrix
  .azure-pipelines/azure-pipelines.yml
Labels: test

#83875 Remove references to IRC & Google Groups
  hacking/ticket_stubs/bug_wrong_repo.md
  hacking/ticket_stubs/proposal.md
  hacking/ticket_stubs/question_not_bug.md
  hacking/ticket_stubs/wider_discussion.md
Labels: needs_triage

#83782 [stable-2.17] Fix ansible-vault integration test for missing vault ids (#83777)
  test/integration/targets/ansible-vault/runme.sh
Labels: backport, test, needs_triage, stale_ci

#83765 [stable-2.16] atomic_move - fix creating file in directory with setgid bit (#83718)
  changelogs/fragments/46742-atomic_move-fix-setgid.yml
  lib/ansible/module_utils/basic.py
  test/integration/targets/copy/defaults/main.yml
  test/integration/targets/copy/tasks/main.yml
  test/integration/targets/copy/tasks/setgid.yml
Labels: backport, needs_triage, stale_ci, bug

#83879 Update boilerplate sanity test
  test/sanity/code-smell/boilerplate.py
Labels: test

#83878 ansible-test - Reduce scope of empty-init test
  changelogs/fragments/ansible-test-sanity-empty-init.yml
  test/lib/ansible_test/_util/controller/sanity/code-smell/empty-init.json
  test/sanity/ignore.txt
Labels: feature
