Repository ansible/ansible, pull requests merged in 2024-07, with the labels that each got.

#83500 Replace references to archived ansible/ansible-examples repository
  lib/ansible/modules/git.py
Labels: module

#82593 actually show plugin config warnings/deprecations
  changelogs/fragments/getoffmylawn.yml
  lib/ansible/cli/doc.py
  lib/ansible/config/base.yml
  lib/ansible/config/manager.py
  lib/ansible/constants.py
  lib/ansible/plugins/__init__.py
  test/integration/targets/ansible-doc/test.yml
  test/integration/targets/deprecations/aliases
  test/integration/targets/deprecations/cache_plugins/notjsonfile.py
  test/integration/targets/deprecations/entry_key_deprecated.cfg
  test/integration/targets/deprecations/entry_key_deprecated2.cfg
  test/integration/targets/deprecations/entry_key_not_deprecated.cfg
  test/integration/targets/deprecations/library/removeoption.py
  test/integration/targets/deprecations/library/willremove.py
  test/integration/targets/deprecations/runme.sh
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/schema.py
Labels: stale_review, bug

#83509 hostvars templating fix, override serialization
  changelogs/fragments/hostvars_fix.yml
  lib/ansible/vars/hostvars.py
  test/integration/targets/template/runme.sh
Labels: bug, has_issue

#83523 [2.16] 🧪 Switch CentOS 7 yum repo mirrors to the vault
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: backport, test

#83526 [2.14] 🧪 Switch CentOS 7 yum repo mirrors to the vault
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: backport, test

#83525 [2.15] 🧪 Switch CentOS 7 yum repo mirrors to the vault
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: needs_revision, backport, test

#83522 Fix incorrect rc when executing end_host in rescue
  changelogs/fragments/83447-end_host-rescue-rc.yml
  lib/ansible/executor/play_iterator.py
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/meta_tasks/runme.sh
  test/integration/targets/meta_tasks/test_end_host_rescue_rc.yml
Labels: needs_triage, bug, has_issue

#83209 linear: fix included handlers executing in lockstep
  changelogs/fragments/83019-linear-handlers-lockstep-fix.yml
  lib/ansible/plugins/strategy/linear.py
  test/integration/targets/handlers/handlers_lockstep_83019-include-nested.yml
  test/integration/targets/handlers/handlers_lockstep_83019-include.yml
  test/integration/targets/handlers/handlers_lockstep_83019.yml
  test/integration/targets/handlers/runme.sh
Labels: bug, has_issue

#83530 validate-modules: reject option/alias names equal up to casing belonging to different options
  changelogs/fragments/83530-validate-modules-casing.yml
  test/integration/targets/ansible-test-sanity-validate-modules/ansible_collections/ns/col/plugins/modules/option_name_casing.py
  test/integration/targets/ansible-test-sanity-validate-modules/expected.txt
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py
Labels: needs_triage, feature

#83113 Fix Creating user directory using tilde always reports "changed"
  changelogs/fragments/82490_creating_user_dir_using_tilde_always_reports_changed.yml
  lib/ansible/modules/user.py
  test/integration/targets/user/tasks/test_create_user.yml
Labels: module, bug, has_issue

#83541 Add SL-Micro to Suse family list
  changelogs/fragments/83541-add-sl-micro-suse-family.yaml
  lib/ansible/module_utils/facts/system/distribution.py
  test/units/module_utils/facts/system/distribution/fixtures/sl-micro.json
Labels: stale_review

#83425 [stable-2.17] Clarify documentation for `INJECT_FACTS_AS_VARS`
  lib/ansible/config/base.yml
Labels: backport, needs_triage, stale_ci

#83430 [stable-2.16] Use f38 official repo for libdnf5 package
  test/integration/targets/dnf5/playbook.yml
Labels: backport, test, stale_ci

#83471 [stable-2.17] Update the dnf5 copr repo (#83459)
  test/integration/targets/dnf5/playbook.yml
Labels: backport, test, needs_triage, stale_ci

#83451 [stable-2.17] dnf: update `use_backend` documentation
  lib/ansible/modules/dnf.py
Labels: backport, module, needs_triage, stale_ci

#83472 [stable-2.17] replace: update after/before example
  changelogs/fragments/replace_regex.yml
  lib/ansible/modules/replace.py
Labels: backport, module, needs_triage, stale_ci

#83491 [stable-2.17] dnf, dnf5: fix installing via wildcard (#83481)
  changelogs/fragments/83373-dnf5-wildcard.yml
  lib/ansible/modules/dnf.py
  lib/ansible/modules/dnf5.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: backport, module, needs_triage, bug

#83492 [stable-2.16] dnf, dnf5: fix installing via wildcard (#83481)
  changelogs/fragments/83373-dnf5-wildcard.yml
  lib/ansible/modules/dnf.py
  lib/ansible/modules/dnf5.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: backport, module, needs_triage, stale_ci, bug

#83506 [stable-2.17] Fix tb for when env var contains % (#83499)
  changelogs/fragments/83498-command-tb-env.yml
  lib/ansible/plugins/shell/__init__.py
  test/integration/targets/shell/tasks/command-building.yml
Labels: backport, stale_ci, bug

#83516 [stable-2.16] hostvars templating fix, override serialization (#83509)
  changelogs/fragments/hostvars_fix.yml
  lib/ansible/vars/hostvars.py
  test/integration/targets/template/runme.sh
Labels: backport, needs_triage, bug

#83515 [stable-2.17] hostvars templating fix, override serialization (#83509)
  changelogs/fragments/hostvars_fix.yml
  lib/ansible/vars/hostvars.py
  test/integration/targets/template/runme.sh
Labels: backport, test, needs_triage, bug, feature

#83486 [stable-2.17] linear strategy, show templated task name on start (#83473)
  changelogs/fragments/linear_started_name.yml
  lib/ansible/plugins/strategy/linear.py
  test/integration/targets/retry_task_name_in_callback/runme.sh
Labels: backport, stale_ci, bug

#83487 [stable-2.16] linear strategy, show templated task name on start (#83473)
  changelogs/fragments/linear_started_name.yml
  lib/ansible/plugins/strategy/linear.py
  test/integration/targets/retry_task_name_in_callback/runme.sh
Labels: backport, stale_ci, bug

#83505 [stable-2.16] dnf - arches must be the same in the is_newer_installed check (#83417)
  changelogs/fragments/83406-dnf-fix-arch-cmp.yml
  lib/ansible/modules/dnf.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: needs_revision, backport, module, bug

#83504 [stable-2.17] dnf - arches must be the same in the is_newer_installed check (#83417)
  changelogs/fragments/83406-dnf-fix-arch-cmp.yml
  lib/ansible/modules/dnf.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: backport, module, bug

#83545 New release v2.17.2rc1
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.2rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83489 Add dinit as a service_mgr
  changelogs/fragments/dinit.yml
  lib/ansible/module_utils/facts/system/service_mgr.py
Labels: needs_revision, feature

#83548 Update Ansible release version to v2.17.2rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83549 Revert "dnf - arches must be the same in the is_newer_installed check…
  changelogs/fragments/83406-dnf-fix-arch-cmp.yml
  lib/ansible/modules/dnf.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: backport, module, bug

#83550 New release v2.16.9rc1
  changelogs/CHANGELOG-v2.16.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.16.9rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83517 known_hosts: don't modify `AnsibleModule.params`
  changelogs/fragments/known_hosts_module_args.yml
  lib/ansible/modules/known_hosts.py
Labels: module, needs_triage, bug

#83552 Update Ansible release version to v2.16.9rc1.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#83540 update distro version
  changelogs/fragments/83540-update_disto_version.yml
  lib/ansible/module_utils/distro/__init__.py
  lib/ansible/module_utils/distro/_distro.py
Labels: needs_revision, bug, has_issue

#83431 review modules docs - batch(fragments)
  lib/ansible/plugins/doc_fragments/connection_pipelining.py
  lib/ansible/plugins/doc_fragments/constructed.py
  lib/ansible/plugins/doc_fragments/default_callback.py
  lib/ansible/plugins/doc_fragments/files.py
  lib/ansible/plugins/doc_fragments/inventory_cache.py
  lib/ansible/plugins/doc_fragments/result_format_callback.py
  lib/ansible/plugins/doc_fragments/return_common.py
  lib/ansible/plugins/doc_fragments/shell_common.py
  lib/ansible/plugins/doc_fragments/url.py
  lib/ansible/plugins/doc_fragments/url_windows.py
  lib/ansible/plugins/doc_fragments/validate.py
Labels: stale_ci

#83553 ansible-test - Update base/default containers
  test/lib/ansible_test/_data/completion/docker.txt
Labels: needs_revision, feature

#83558 [stable-2.17] Quality-of-life improvements for release tool (#83551)
  packaging/release.py
Labels: backport, feature

#83559 [stable-2.16] Quality-of-life improvements for release tool (#83551)
  packaging/release.py
Labels: backport, feature

#83560 [stable-2.15] Quality-of-life improvements for release tool (#83551)
  packaging/release.py
Labels: backport, feature

#83561 [stable-2.14] Quality-of-life improvements for release tool (#83551)
  packaging/release.py
Labels: backport, feature

#83539 ansible-test - Update nios-test-container to 4.0.0
  changelogs/fragments/ansible-test-nios-container.yml
  test/lib/ansible_test/_internal/commands/integration/cloud/nios.py
Labels: feature

#83420 review modules docs - batch(s)
  lib/ansible/modules/service.py
  lib/ansible/modules/set_stats.py
  lib/ansible/modules/setup.py
  lib/ansible/modules/stat.py
  lib/ansible/modules/subversion.py
  lib/ansible/modules/systemd_service.py
  lib/ansible/modules/sysvinit.py
Labels: module

#83556 dnf: follow-up on is_newer_installed arches fix
  lib/ansible/modules/dnf.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: module, bug

#83519 [stable-2.17] package_facts: ignore warnings by apk on stderr
  changelogs/fragments/package_facts_apk.yml
  lib/ansible/modules/package_facts.py
  test/integration/targets/package_facts/tasks/main.yml
Labels: backport, module, bug

#83563 [stable-2.17] dnf: follow-up on is_newer_installed arches fix (#83556)
  lib/ansible/modules/dnf.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: backport, module, bug

#83566 Revert #83504
  changelogs/fragments/83406-dnf-fix-arch-cmp.yml
  changelogs/fragments/dnf-revert.yaml
  lib/ansible/modules/dnf.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: backport, module, bug

#83567 New release v2.17.2rc2
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.2rc2_summary.yaml
  lib/ansible/release.py
Labels: backport, feature

#83568 Update Ansible release version to v2.17.2rc2.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83543 Ensure that we are handling `DownloadError` properly in the `dnf` module
  changelogs/fragments/dnf_handle_downloaderror.yml
  lib/ansible/modules/dnf.py
Labels: module, bug

#83577 remove ignore clauses for module blockinfile
  lib/ansible/modules/blockinfile.py
  test/sanity/ignore.txt
Labels: test, module

#83573 module compression is not again settable via var
  changelogs/fragments/mc_fix.yml
  lib/ansible/config/base.yml
Labels: needs_triage, bug, has_issue

#83588 Update any.yml
  lib/ansible/plugins/test/any.yml
Labels: docs

#83610 ansible-test - Improve unknown env error message
  changelogs/fragments/ansible-test-error-message-improvement.yml
  test/lib/ansible_test/_internal/cli/compat.py
Labels: feature

#83611 New release v2.17.2
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.2_summary.yaml
  lib/ansible/release.py
Labels: backport, feature

#83612 New release v2.16.9
  changelogs/CHANGELOG-v2.16.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.16.9_summary.yaml
  lib/ansible/release.py
Labels: backport, feature

#83613 Update Ansible release version to v2.17.2.post0.
  lib/ansible/release.py
Labels: backport, feature

#83614 Update Ansible release version to v2.16.9.post0.
  lib/ansible/release.py
Labels: backport, feature

#83574 remove ignore clauses for module replace
  lib/ansible/modules/replace.py
  test/sanity/ignore.txt
Labels: test, module, bug

#83601 debconf: handle boolean value representation consistently
  changelogs/fragments/83601-debconf-normalize-bools.yml
  lib/ansible/modules/debconf.py
  test/integration/targets/debconf/tasks/main.yml
Labels: module, needs_triage, bug, has_issue

#83595 remove ignore clauses for module lineinfile
  lib/ansible/modules/lineinfile.py
  test/sanity/ignore.txt
Labels: test, module, needs_triage

#83627 🧪 Use `setuptools [core]` @ collections_runtime_pythonpath
  test/integration/targets/collections_runtime_pythonpath/ansible-collection-python-dist-boo/pyproject.toml
Labels: test, needs_triage

#83637 Update collections_runtime_pythonpath test
  test/integration/targets/collections_runtime_pythonpath/ansible-collection-python-dist-boo/pyproject.toml
  test/integration/targets/collections_runtime_pythonpath/runme.sh
Labels: test, needs_triage

#83639 [stable-2.16] Use build instead of pep517 for integration test
  test/integration/targets/collections_runtime_pythonpath/ansible-collection-python-dist-boo/pyproject.toml
  test/integration/targets/collections_runtime_pythonpath/runme.sh
Labels: backport, test

#83640 [stable-2.15] Use build instead of pep517 for integration test
  test/integration/targets/collections_runtime_pythonpath/ansible-collection-python-dist-boo/pyproject.toml
  test/integration/targets/collections_runtime_pythonpath/runme.sh
Labels: backport, test

#83641 [stable-2.14] Use build instead of pep517 for integration test
  test/integration/targets/collections_runtime_pythonpath/ansible-collection-python-dist-boo/pyproject.toml
  test/integration/targets/collections_runtime_pythonpath/runme.sh
Labels: backport, test

#83638 [stable-2.17] Use build instead of pep517 for integration test
  test/integration/targets/collections_runtime_pythonpath/ansible-collection-python-dist-boo/pyproject.toml
  test/integration/targets/collections_runtime_pythonpath/runme.sh
Labels: backport, test

#83341 docs adjustments (batch 1)
  lib/ansible/modules/add_host.py
  lib/ansible/modules/apt.py
  lib/ansible/modules/apt_key.py
  lib/ansible/modules/apt_repository.py
Labels: module, stale_ci, stale_review

#83575 remove ignore clauses for module find
  changelogs/fragments/83575-fix-sanity-ignore-for-find.yml
  lib/ansible/modules/find.py
  test/integration/targets/find/tasks/main.yml
  test/sanity/ignore.txt
Labels: test, module, stale_review, bug

#83620 Added info about MacOS targets for cron module
  lib/ansible/modules/cron.py
Labels: module

#83381 display: warn user about empty log path value
  changelogs/fragments/empty_log_path.yml
  lib/ansible/config/base.yml
  lib/ansible/utils/display.py
  test/units/utils/display/test_logger.py
Labels: stale_ci, bug, has_issue

#83562 increase timeout downloading galaxy role URLs
  changelogs/fragments/ansible-galaxy-install-archive-url-timeout.yml
  lib/ansible/galaxy/role.py
Labels: needs_revision, bug, has_issue

#83547 apt: Report change when package is removed
  changelogs/fragments/46314.yml
  lib/ansible/modules/apt.py
  test/integration/targets/apt/tasks/repo.yml
  test/integration/targets/apt/tasks/upgrade_autoremove.yml
Labels: module, stale_review, bug, has_issue

#83668 Replace random with secrets
  changelogs/fragments/secrets.yml
  lib/ansible/cli/pull.py
  lib/ansible/executor/powershell/module_manifest.py
  lib/ansible/module_utils/api.py
  lib/ansible/modules/apt.py
  lib/ansible/modules/apt_repository.py
  lib/ansible/plugins/action/__init__.py
  lib/ansible/plugins/action/reboot.py
  lib/ansible/plugins/become/__init__.py
  lib/ansible/plugins/lookup/random_choice.py
  lib/ansible/plugins/shell/__init__.py
  lib/ansible/utils/display.py
  lib/ansible/utils/vars.py
Labels: module, bug

#83649 Remove explicit shell environment docs
  changelogs/fragments/shell-environment.yml
  lib/ansible/plugins/doc_fragments/shell_common.py
  lib/ansible/plugins/doc_fragments/shell_windows.py
  lib/ansible/plugins/shell/__init__.py
Labels: feature, has_issue

#83671 Set LANGUAGE environment variable is set to a non-English locale
  changelogs/fragments/language.yml
  lib/ansible/modules/apt.py
  lib/ansible/modules/apt_key.py
  lib/ansible/modules/apt_repository.py
  lib/ansible/modules/dpkg_selections.py
Labels: module, needs_triage, bug, has_issue

#83599 validate-modules: detect names set mismatch between argument spec and documentation
  changelogs/fragments/83599-validate-modules-aliases.yml
  test/integration/targets/ansible-test-sanity-validate-modules/ansible_collections/ns/col/plugins/modules/wrong_aliases.py
  test/integration/targets/ansible-test-sanity-validate-modules/expected.txt
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/main.py
Labels: stale_ci, bug, feature, has_issue

#83624 dnf/setup_rpm_repo: simplify dummy testing repos
  test/integration/targets/dnf/tasks/main.yml
  test/integration/targets/dnf/tasks/multilib.yml
  test/integration/targets/dnf/tasks/repo.yml
  test/integration/targets/dnf/tasks/skip_broken_and_nobest.yml
  test/integration/targets/dnf/vars/main.yml
  test/integration/targets/setup_rpm_repo/library/create_repo.py
  test/integration/targets/setup_rpm_repo/tasks/main.yml
  test/integration/targets/setup_rpm_repo/vars/Fedora.yml
  test/integration/targets/setup_rpm_repo/vars/RedHat-6.yml
  test/integration/targets/setup_rpm_repo/vars/RedHat-7.yml
  test/integration/targets/setup_rpm_repo/vars/RedHat-8.yml
  test/integration/targets/setup_rpm_repo/vars/RedHat-9.yml
  test/integration/targets/setup_rpm_repo/vars/main.yml
Labels: test

#83677 [stable-2.17] ansible-test - Improve unknown env error message
  changelogs/fragments/ansible-test-error-message-improvement.yml
  test/lib/ansible_test/_internal/cli/compat.py
Labels: backport, needs_triage, bug

#83678 [stable-2.16] ansible-test - Improve unknown env error message
  changelogs/fragments/ansible-test-error-message-improvement.yml
  test/lib/ansible_test/_internal/cli/compat.py
Labels: backport, needs_triage, bug

#83510 fix module_defaults group incorrectly giving deprecation warnings
  changelogs/fragments/fix-module-defaults-deprecations.yml
  lib/ansible/playbook/base.py
  test/integration/targets/module_defaults/collections/ansible_collections/testns/testcoll/meta/runtime.yml
  test/integration/targets/module_defaults/runme.sh
Labels: needs_revision, stale_review, bug, has_issue

#83656 winrm - quota retry handling
  changelogs/fragments/winrm-quota.yml
  lib/ansible/plugins/connection/winrm.py
  test/integration/targets/connection_winrm/aliases
  test/integration/targets/connection_winrm/tests.yml
  test/lib/ansible_test/_data/requirements/constraints.txt
Labels: bug

#83694 tests: use keyserver with keyid while using apt_key
  test/integration/targets/apt_repository/tasks/apt.yml
Labels: test
