Repository ansible/ansible, pull requests merged in 2024-06, with the labels that each got.

#83080 powershell - Improve Add-Type tempdir handler
  changelogs/fragments/PowerShell-AddType-temp.yml
  lib/ansible/executor/powershell/exec_wrapper.ps1
  lib/ansible/executor/powershell/module_powershell_wrapper.ps1
  lib/ansible/module_utils/csharp/Ansible.Basic.cs
  lib/ansible/module_utils/powershell/Ansible.ModuleUtils.AddType.psm1
  test/integration/targets/module_utils_Ansible.Basic/library/ansible_basic_tests.ps1
  test/integration/targets/win_exec_wrapper/tasks/main.yml
Labels: bug, has_issue

#83347 Fix Test failure with cowsay installed/present
  changelogs/fragments/83327.yml
  test/units/utils/display/test_broken_cowsay.py
Labels: needs_triage, bug, has_issue

#83206 timeout give extra info
  changelogs/fragments/timeout_show_frame.yml
  lib/ansible/executor/task_executor.py
  test/integration/targets/playbook/timeout.yml
Labels: feature, has_issue

#83364 additional timeout info
  lib/ansible/executor/task_executor.py
Labels: needs_triage, feature

#83356 facts: add facts about x86_64 flags to detect microarchitecture
  changelogs/fragments/83331.yml
  lib/ansible/module_utils/facts/hardware/linux.py
  test/units/module_utils/facts/fixtures/cpuinfo/x86_64-2cpu-cpuinfo
  test/units/module_utils/facts/fixtures/cpuinfo/x86_64-4cpu-cpuinfo
  test/units/module_utils/facts/hardware/linux_data.py
Labels: bug, has_issue

#83382 [stable-2.14] Drop Alpine 3 docker jobs from CI
  .azure-pipelines/azure-pipelines.yml
Labels: backport, test

#83379 [stable-2.15] ansible-test - Drop Windows 2012/2012-R2 support
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-windows-2012.yml
  test/lib/ansible_test/_data/completion/windows.txt
Labels: backport, test

#83380 [stable-2.14] ansible-test - Drop Windows 2012/2012-R2 support
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-windows-2012.yml
  test/lib/ansible_test/_data/completion/windows.txt
Labels: backport, test

#83362 bool filter, add booleanization strategy option
  changelogs/fragments/normalize_booleanization.yml
  lib/ansible/plugins/filter/bool.yml
  lib/ansible/plugins/filter/core.py
  test/integration/targets/filter_core/tasks/main.yml
Labels: feature

#83374 [stable-2.12] Remove scheduled runs
  .azure-pipelines/azure-pipelines.yml
Labels: backport, test

#83368 docs adjustments (batch 2)
  lib/ansible/modules/assemble.py
  lib/ansible/modules/assert.py
  lib/ansible/modules/blockinfile.py
  lib/ansible/modules/command.py
  lib/ansible/modules/copy.py
  lib/ansible/modules/cron.py
Labels: module

#83365 Properly quote all needed components of shell commands
  changelogs/fragments/82535-properly-quote-shell.yml
  lib/ansible/plugins/shell/__init__.py
  lib/ansible/plugins/shell/sh.py
  test/integration/targets/json_cleanup/library/bad_json
  test/integration/targets/json_cleanup/module_output_cleaning.yml
  test/integration/targets/shell/meta/main.yml
  test/integration/targets/shell/tasks/command-building.yml
  test/integration/targets/shell/tasks/main.yml
  test/integration/targets/shell/test-command-building-playbook.yml
Labels: bug

#83335 [stable-2.17] The extension returned by the splitext contains the dot
  lib/ansible/plugins/filter/splitext.yml
Labels: backport, needs_triage

#83329 [2.17] Fix task.resolved_action for callbacks and module_defaults (#82003)
  changelogs/fragments/correct-callback-fqcn-old-style-action-invocation.yml
  lib/ansible/parsing/mod_args.py
  lib/ansible/playbook/task.py
  test/integration/targets/collections/test_task_resolved_plugin/unqualified_and_collections_kw.yml
  test/integration/targets/module_defaults/tasks/main.yml
  test/units/playbook/test_block.py
  test/units/playbook/test_helpers.py
Labels: backport, needs_triage, bug

#83308 [stable-2.17] filter: update the documentation for win_splitdrive
  lib/ansible/plugins/filter/win_splitdrive.yml
Labels: backport, needs_triage

#83351 [stable-2.17] Fix Test failure with cowsay installed/present
  changelogs/fragments/83327.yml
  test/units/utils/display/test_broken_cowsay.py
Labels: backport, test, needs_triage

#83345 [stable-2.17] powershell - Improve Add-Type tempdir handler (#83080)
  changelogs/fragments/PowerShell-AddType-temp.yml
  lib/ansible/executor/powershell/exec_wrapper.ps1
  lib/ansible/executor/powershell/module_powershell_wrapper.ps1
  lib/ansible/module_utils/csharp/Ansible.Basic.cs
  lib/ansible/module_utils/powershell/Ansible.ModuleUtils.AddType.psm1
  test/integration/targets/module_utils_Ansible.Basic/library/ansible_basic_tests.ps1
  test/integration/targets/win_exec_wrapper/tasks/main.yml
Labels: backport, needs_triage, bug

#83350 [stable-2.16] Fix Test failure with cowsay installed/present
  changelogs/fragments/83327.yml
  test/units/utils/display/test_broken_cowsay.py
Labels: backport, test, needs_triage

#83344 [stable-2.16] powershell - Improve Add-Type tempdir handler (#83080)
  changelogs/fragments/PowerShell-AddType-temp.yml
  lib/ansible/executor/powershell/exec_wrapper.ps1
  lib/ansible/executor/powershell/module_powershell_wrapper.ps1
  lib/ansible/module_utils/csharp/Ansible.Basic.cs
  lib/ansible/module_utils/powershell/Ansible.ModuleUtils.AddType.psm1
  test/integration/targets/module_utils_Ansible.Basic/library/ansible_basic_tests.ps1
  test/integration/targets/win_exec_wrapper/tasks/main.yml
Labels: backport, needs_triage, bug

#83334 [stable-2.16] The extension returned by the splitext contains the dot
  lib/ansible/plugins/filter/splitext.yml
Labels: backport, needs_triage

#83330 [2.16] Fix task.resolved_action for callbacks and module_defaults (#82003)
  changelogs/fragments/correct-callback-fqcn-old-style-action-invocation.yml
  lib/ansible/parsing/mod_args.py
  lib/ansible/playbook/task.py
  test/integration/targets/collections/test_task_resolved_plugin/unqualified_and_collections_kw.yml
  test/integration/targets/module_defaults/tasks/main.yml
  test/units/playbook/test_block.py
  test/units/playbook/test_helpers.py
Labels: backport, needs_triage, bug

#83307 [stable-2.16] filter: update the documentation for win_splitdrive
  lib/ansible/plugins/filter/win_splitdrive.yml
Labels: backport, needs_triage

#83391 Revert bool filter booleanization strategy option
  changelogs/fragments/normalize_booleanization.yml
  lib/ansible/plugins/filter/bool.yml
  lib/ansible/plugins/filter/core.py
  test/integration/targets/filter_core/tasks/main.yml
Labels: test, bug, feature

#83302 [devel] Update azure-pipelines-test-container
  .azure-pipelines/azure-pipelines.yml
Labels: test

#83375 [stable-2.17] Update azure-pipelines-test-container
  .azure-pipelines/azure-pipelines.yml
Labels: backport, test

#83376 [stable-2.16] Update azure-pipelines-test-container
  .azure-pipelines/azure-pipelines.yml
Labels: backport, test

#83377 [stable-2.15] Update azure-pipelines-test-container
  .azure-pipelines/azure-pipelines.yml
Labels: backport, test

#83378 [stable-2.14] Update azure-pipelines-test-container
  .azure-pipelines/azure-pipelines.yml
Labels: backport, test

#83396 [stable-2.17] Properly quote all needed components of shell commands (#83365)
  changelogs/fragments/82535-properly-quote-shell.yml
  lib/ansible/plugins/shell/__init__.py
  lib/ansible/plugins/shell/sh.py
  test/integration/targets/json_cleanup/library/bad_json
  test/integration/targets/json_cleanup/module_output_cleaning.yml
  test/integration/targets/shell/meta/main.yml
  test/integration/targets/shell/tasks/command-building.yml
  test/integration/targets/shell/tasks/main.yml
  test/integration/targets/shell/test-command-building-playbook.yml
Labels: backport, needs_triage

#83398 [2.17] fix any_errors_fatal tests (#83389)
  test/integration/targets/any_errors_fatal/80981.yml
  test/integration/targets/any_errors_fatal/runme.sh
Labels: backport, needs_triage, bug

#83400 Validate and process Handler.listen only once
  changelogs/fragments/83392-fix-memory-issues-handlers.yml
  lib/ansible/playbook/handler.py
  lib/ansible/plugins/strategy/__init__.py
Labels: needs_triage, bug, has_issue

#83405 2.17: Validate and process Handler.listen only once (#83400)
  changelogs/fragments/83392-fix-memory-issues-handlers.yml
  lib/ansible/playbook/handler.py
  lib/ansible/plugins/strategy/__init__.py
Labels: backport, needs_triage, bug

#83407 New release v2.16.8rc1
  changelogs/CHANGELOG-v2.16.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.16.8rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83408 New release v2.17.1rc1
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.1rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83409 Update Ansible release version to v2.16.8rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83410 Update Ansible release version to v2.17.1rc1.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#83412 Fix quoting in fork_safe_stdio test
  test/integration/targets/fork_safe_stdio/runme.sh
Labels: test

#83413 Fix issues reported by mypy
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/collection/concrete_artifact_manager.py
  lib/ansible/galaxy/collection/gpg.py
  lib/ansible/parsing/yaml/constructor.py
  test/sanity/ignore.txt
Labels: bug

#83369 docs adjustments - batch(def)
  lib/ansible/modules/deb822_repository.py
  lib/ansible/modules/debconf.py
  lib/ansible/modules/debug.py
  lib/ansible/modules/dnf.py
  lib/ansible/modules/dnf5.py
  lib/ansible/modules/dpkg_selections.py
  lib/ansible/modules/expect.py
  lib/ansible/modules/fetch.py
  lib/ansible/modules/file.py
  lib/ansible/modules/find.py
Labels: module

#83257 Remove extraneous pylint ignore
  test/units/executor/module_common/test_module_common.py
  test/units/module_utils/basic/test_exit_json.py
  test/units/module_utils/basic/test_log.py
  test/units/module_utils/basic/test_run_command.py
  test/units/module_utils/basic/test_tmpdir.py
  test/units/plugins/connection/test_psrp.py
  test/units/plugins/connection/test_winrm.py
Labels: test, code_health

#83414 ansible-test - Prepare for Python 3.13
  changelogs/fragments/ansible-test-coverage-update.yml
  test/lib/ansible_test/_data/requirements/ansible-test.txt
  test/lib/ansible_test/_data/requirements/constraints.txt
  test/lib/ansible_test/_internal/coverage_util.py
  test/lib/ansible_test/_internal/python_requirements.py
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: feature

#83399 docs adjustments - batch(ghi)
  lib/ansible/modules/gather_facts.py
  lib/ansible/modules/get_url.py
  lib/ansible/modules/git.py
  lib/ansible/modules/group.py
  lib/ansible/modules/hostname.py
  lib/ansible/modules/include_vars.py
  lib/ansible/modules/iptables.py
Labels: module, needs_triage

#83404 Clarify documentation for `INJECT_FACTS_AS_VARS`
  lib/ansible/config/base.yml
Labels: needs_triage

#83426 Specify -O in windows ssh tests as needed for scp to work with openssh 9+
  test/integration/targets/connection_windows_ssh/windows.sh
Labels: test, needs_triage

#83416 Add Python 3.13 support
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/python-3.13.yml
  lib/ansible/config/base.yml
  test/lib/ansible_test/_data/completion/docker.txt
  test/lib/ansible_test/_data/requirements/sanity.yamllint.in
  test/lib/ansible_test/_data/requirements/sanity.yamllint.txt
  test/lib/ansible_test/_util/controller/sanity/shellcheck/exclude.txt
  test/lib/ansible_test/_util/target/common/constants.py
  test/sanity/code-smell/test-constraints.py
Labels: needs_revision, feature

#83427 Revert warning message in setup/gather_facts
  changelogs/fragments/sysctl_fact_fix.yml
  lib/ansible/module_utils/basic.py
  lib/ansible/module_utils/facts/hardware/aix.py
  lib/ansible/module_utils/facts/hardware/darwin.py
  lib/ansible/module_utils/facts/hardware/linux.py
  lib/ansible/module_utils/facts/hardware/netbsd.py
  lib/ansible/module_utils/facts/hardware/openbsd.py
  lib/ansible/module_utils/facts/hardware/sunos.py
  lib/ansible/module_utils/facts/network/aix.py
  lib/ansible/module_utils/facts/network/fc_wwn.py
  lib/ansible/module_utils/facts/network/generic_bsd.py
  lib/ansible/module_utils/facts/network/hpux.py
  lib/ansible/module_utils/facts/network/hurd.py
  lib/ansible/module_utils/facts/network/iscsi.py
  lib/ansible/module_utils/facts/other/facter.py
  lib/ansible/module_utils/facts/other/ohai.py
  lib/ansible/module_utils/facts/sysctl.py
  test/units/module_utils/basic/test_get_bin_path.py
  test/units/module_utils/facts/network/test_fc_wwn.py
  test/units/module_utils/facts/network/test_generic_bsd.py
Labels: stale_review, bug

#83325 ansible-test action-plugin-docs Support sidecar docs
  changelogs/fragments/action-plugin-docs-sidecar.yml
  test/integration/targets/ansible-test-sanity-action-plugin-docs/aliases
  test/integration/targets/ansible-test-sanity-action-plugin-docs/ansible_collections/ns/col/plugins/action/other.yml
  test/integration/targets/ansible-test-sanity-action-plugin-docs/ansible_collections/ns/col/plugins/action/with_py.py
  test/integration/targets/ansible-test-sanity-action-plugin-docs/ansible_collections/ns/col/plugins/action/with_yaml.py
  test/integration/targets/ansible-test-sanity-action-plugin-docs/ansible_collections/ns/col/plugins/action/with_yml.py
  test/integration/targets/ansible-test-sanity-action-plugin-docs/ansible_collections/ns/col/plugins/modules/with_py.py
  test/integration/targets/ansible-test-sanity-action-plugin-docs/ansible_collections/ns/col/plugins/modules/with_yaml.yaml
  test/integration/targets/ansible-test-sanity-action-plugin-docs/ansible_collections/ns/col/plugins/modules/with_yml.yml
  test/integration/targets/ansible-test-sanity-action-plugin-docs/runme.sh
  test/lib/ansible_test/_util/controller/sanity/code-smell/action-plugin-docs.json
  test/lib/ansible_test/_util/controller/sanity/code-smell/action-plugin-docs.py
Labels: stale_ci, bug

#81246 Fix Linux Sector count Fact
  lib/ansible/module_utils/facts/hardware/linux.py
Labels: stale_ci, bug, has_issue

#83433 ansible-test - Fix unit test coverage collection
  test/lib/ansible_test/_util/target/pytest/plugins/ansible_pytest_coverage.py
Labels: bug

#83432 ansible-test - Update PyPI test container to 3.1.0
  changelogs/fragments/ansible-test-pypi-test-container-update.yml
  test/lib/ansible_test/_internal/pypi_proxy.py
Labels: feature

#83418 review modules docs - batch(klmpr)
  lib/ansible/modules/known_hosts.py
  lib/ansible/modules/package_facts.py
  lib/ansible/modules/pause.py
  lib/ansible/modules/pip.py
  lib/ansible/modules/rpm_key.py
Labels: module

#83153 Adds `limit` parameter to `ansible.builtin.find`
  lib/ansible/modules/find.py
Labels: module, stale_review, feature

#83419 [stable-2.15] Use f38 official repo for libdnf5 package
  test/integration/targets/dnf5/playbook.yml
Labels: backport, test

#81520 unarchive: Better handling of files with an invalid timestamp in zip file
  changelogs/fragments/unarchive_timestamp.yml
  lib/ansible/modules/unarchive.py
  test/units/modules/test_unarchive.py
Labels: module, bug, has_issue

#83439 [stable-2.17] ansible-test - Update PyPI test container to 3.1.0
  changelogs/fragments/ansible-test-pypi-test-container-update.yml
  test/lib/ansible_test/_internal/pypi_proxy.py
Labels: backport, bug

#83440 [stable-2.16] ansible-test - Update PyPI test container to 3.1.0
  changelogs/fragments/ansible-test-pypi-test-container-update.yml
  test/lib/ansible_test/_internal/pypi_proxy.py
Labels: backport, bug

#83441 [stable-2.15] ansible-test - Update PyPI test container to 3.1.0
  changelogs/fragments/ansible-test-pypi-test-container-update.yml
  test/lib/ansible_test/_internal/pypi_proxy.py
Labels: backport, bug

#83443 [stable-2.14] ansible-test - Update PyPI test container to 3.1.0
  changelogs/fragments/ansible-test-pypi-test-container-update.yml
  test/lib/ansible_test/_internal/pypi_proxy.py
Labels: backport, bug

#83429 dnf: update `use_backend` documentation
  lib/ansible/modules/dnf.py
Labels: module

#83384 vault: Handle directory value to vault password file
  changelogs/fragments/42960_vault_password.yml
  lib/ansible/parsing/vault/__init__.py
  test/integration/targets/ansible-vault/runme.sh
Labels: bug, has_issue

#83221 Remove Python 3.10 support for the controller
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/remove-python3.10-controller-support.yml
  hacking/README.md
  lib/ansible/cli/__init__.py
  lib/ansible/galaxy/api.py
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/utils/collection_loader/_collection_finder.py
  packaging/release.py
  setup.cfg
  test/lib/ansible_test/_data/requirements/constraints.txt
  test/lib/ansible_test/_util/target/common/constants.py
  test/sanity/ignore.txt
  test/units/cli/galaxy/test_collection_extract_tar.py
  test/units/requirements.txt
Labels: feature, has_issue

#83462 New release v2.17.1
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83464 Update Ansible release version to v2.17.1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83463 Update Ansible release version to v2.16.8.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#83460 selinux compat - add ignore, proper ex chaining
  lib/ansible/module_utils/compat/selinux.py
  test/sanity/ignore.txt
Labels: bug

#83465 Remove timezone support module and tests
  test/integration/targets/user/tasks/test_expires.yml
  test/integration/targets/user/tasks/test_local_expires.yml
  test/support/integration/plugins/modules/timezone.py
Labels: test

#83446 ansible-test - Update tested platforms
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-platform-updates.yml
  test/integration/targets/ansible-test-container/runme.py
  test/integration/targets/apt/vars/Ubuntu-24.yml
  test/integration/targets/prepare_http_tests/tasks/default.yml
  test/integration/targets/setup_deb_repo/tasks/main.yml
  test/lib/ansible_test/_data/completion/docker.txt
  test/lib/ansible_test/_data/completion/remote.txt
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: feature

#83458 service_facts on OpenBSD: Don't crash on '=' in rcctl flags.
  changelogs/fragments/83457-service_facts-openbsd-dont-crash-in-equals.yml
  lib/ansible/modules/service_facts.py
Labels: module, needs_triage, stale_review, bug, has_issue

#83453 replace: update after/before example
  changelogs/fragments/replace_regex.yml
  lib/ansible/modules/replace.py
Labels: module, has_issue

#83459 Update the dnf5 copr repo
  test/integration/targets/dnf5/playbook.yml
Labels: test, needs_triage

#83403 human_to_bytes: strictly parse strings
  changelogs/fragments/82075.yml
  lib/ansible/module_utils/common/text/formatters.py
  lib/ansible/plugins/filter/human_to_bytes.yml
  test/units/module_utils/common/text/formatters/test_human_to_bytes.py
Labels: stale_review, bug, has_issue

#83469 ansible-test: update http-test-container to 3.2.0
  changelogs/fragments/83469-http-test-container.yml
  test/lib/ansible_test/_internal/commands/integration/cloud/httptester.py
Labels: test, stale_review, feature

#83475 ansible-test - Update PyPI and utility container
  changelogs/fragments/ansible-test-pypi-test-container-update.yml
  changelogs/fragments/ansible-test-utility-container-update.yml
  test/lib/ansible_test/_internal/docker_util.py
  test/lib/ansible_test/_internal/pypi_proxy.py
Labels: feature

#64092 get_url: Verify checksum using tmpsrc, not dest
  changelogs/fragments/64092-get_url_verify_tmpsrc_checksum.yml
  lib/ansible/modules/get_url.py
  test/integration/targets/get_url/tasks/main.yml
Labels: module, net_tools, support:core, bug, P3, verified, affects_2.10

#83454 unarchive: handle content and size differences
  changelogs/fragments/unarchive_differs.yml
  lib/ansible/modules/unarchive.py
  test/integration/targets/unarchive/files/content_differs.tar.gz
  test/integration/targets/unarchive/files/content_differs_2.tar.gz
  test/integration/targets/unarchive/files/size_differs.tar.gz
  test/integration/targets/unarchive/files/size_differs_2.tar.gz
  test/integration/targets/unarchive/tasks/main.yml
  test/integration/targets/unarchive/tasks/test_tar_gz_content_differs.yml
  test/integration/targets/unarchive/tasks/test_tar_gz_size_differs.yml
Labels: module, stale_review, bug, has_issue

#83477 ansible-test - Replace FreeBSD 14.0 with 14.1
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-platform-updates.yml
  test/lib/ansible_test/_data/completion/remote.txt
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: feature

#83355 add support for inactive option
  lib/ansible/modules/user.py
  test/integration/targets/user/tasks/main.yml
  test/integration/targets/user/tasks/test_inactive_new_account.yml
Labels: module, stale_ci, feature

#83354 Ensure the correct connection name is shown in results
  changelogs/fragments/correct_connection_callback.yml
  lib/ansible/executor/task_executor.py
  test/integration/targets/callback_results/aliases
  test/integration/targets/callback_results/callback_plugins/track_connections.py
  test/integration/targets/callback_results/runme.sh
  test/integration/targets/callback_results/task_name.yml
Labels: bug, has_issue

#83473 linear strategy, show templated task name on start
  changelogs/fragments/linear_started_name.yml
  lib/ansible/plugins/strategy/linear.py
  test/integration/targets/callback_results/runme.sh
Labels: bug

#83466 Enable Ubuntu 24.04 group 6 in CI
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-platform-updates.yml
  test/integration/targets/ansible-test-container/runme.py
Labels: test

#83481 dnf, dnf5: fix installing via wildcard
  changelogs/fragments/83373-dnf5-wildcard.yml
  lib/ansible/modules/dnf.py
  lib/ansible/modules/dnf5.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: module, needs_triage, bug, has_issue

#83497 Fix similar branches
  lib/ansible/modules/hostname.py
Labels: module, bug

#83417 dnf - arches must be the same in the is_newer_installed check
  changelogs/fragments/83406-dnf-fix-arch-cmp.yml
  lib/ansible/modules/dnf.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: module, bug, has_issue

#83480 facts/hardware: Fix support_discard block device fact
  changelogs/fragments/83480-fix-support-discard.yml
  lib/ansible/module_utils/facts/hardware/linux.py
Labels: bug

#83298 dnf: remove legacy code
  changelogs/fragments/dnf-remove-legacy-code.yml
  lib/ansible/modules/dnf.py
Labels: module, feature

#83499 Fix tb for when env var contains %
  changelogs/fragments/83498-command-tb-env.yml
  lib/ansible/plugins/shell/__init__.py
  test/integration/targets/shell/tasks/command-building.yml
Labels: bug, has_issue
