Repository ansible/ansible, pull requests merged in 2025-04, with the labels that each got.

#84868 Windows Exec Runner Update
  changelogs/fragments/windows-exec.yml
  lib/ansible/executor/module_common.py
  lib/ansible/executor/powershell/async_watchdog.ps1
  lib/ansible/executor/powershell/async_wrapper.ps1
  lib/ansible/executor/powershell/become_wrapper.ps1
  lib/ansible/executor/powershell/bootstrap_wrapper.ps1
  lib/ansible/executor/powershell/coverage_wrapper.ps1
  lib/ansible/executor/powershell/exec_wrapper.ps1
  lib/ansible/executor/powershell/module_manifest.py
  lib/ansible/executor/powershell/module_powershell_wrapper.ps1
  lib/ansible/executor/powershell/module_script_wrapper.ps1
  lib/ansible/executor/powershell/module_wrapper.ps1
  lib/ansible/executor/powershell/psrp_fetch_file.ps1
  lib/ansible/executor/powershell/psrp_put_file.ps1
  lib/ansible/executor/powershell/winrm_fetch_file.ps1
  lib/ansible/executor/powershell/winrm_put_file.ps1
  lib/ansible/module_utils/csharp/Ansible.Basic.cs
  lib/ansible/module_utils/csharp/Ansible.Become.cs
  lib/ansible/module_utils/csharp/Ansible._Async.cs
  lib/ansible/plugins/action/__init__.py
  lib/ansible/plugins/action/script.py
  lib/ansible/plugins/become/runas.py
  lib/ansible/plugins/connection/psrp.py
  lib/ansible/plugins/connection/winrm.py
  lib/ansible/plugins/shell/powershell.py
  test/integration/targets/connection_psrp/tests.yml
  test/integration/targets/module_utils_Ansible.Basic/library/ansible_basic_tests.ps1
  test/integration/targets/win_become/tasks/main.yml
  test/integration/targets/win_exec_wrapper/library/test_common_functions.ps1
  test/integration/targets/win_exec_wrapper/library/test_exec_wrapper_scope.ps1
  test/integration/targets/win_exec_wrapper/module_utils/Ansible.ModuleUtils.ScopedUtil.psm1
  test/integration/targets/win_exec_wrapper/tasks/main.yml
  test/integration/targets/win_script/files/test_script_with_native_stderr.ps1
  test/integration/targets/win_script/tasks/main.yml
  test/integration/targets/windows-minimal/library/test_no_exec_wrapper.ps1
  test/integration/targets/windows-minimal/tasks/main.yml
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/module_args.py
  test/sanity/ignore.txt
  test/units/plugins/action/test_action.py
Labels: feature

#84912 ansible-config: Dump galaxy server config in proper JSON format
  changelogs/fragments/config_dump.yml
  lib/ansible/cli/config.py
  lib/ansible/config/manager.py
  test/integration/targets/ansible-config/tasks/main.yml
Labels: bug, has_issue

#84915 Add fallible 2025.4.1 to issue template
  .github/ISSUE_TEMPLATE/fallible_dt.yml
Labels: needs_triage, feature

#84916 Fix errant warning about client_secret and access_token
  lib/ansible/galaxy/token.py
Labels: needs_revision, needs_triage, bug

#84767 Support download_url without a scheme:host
  changelogs/fragments/84213-ansible-galaxy-url-building.yml
  lib/ansible/galaxy/api.py
Labels: stale_ci, bug, has_issue

#84394 Clean up interpreter discovery
  changelogs/fragments/interpreter-discovery-auto-legacy.yml
  lib/ansible/config/base.yml
  lib/ansible/executor/discovery/python_target.py
  lib/ansible/executor/interpreter_discovery.py
  test/integration/targets/interpreter_discovery_python/bad-connection.yml
  test/integration/targets/interpreter_discovery_python/discovery.yml
  test/integration/targets/interpreter_discovery_python/runme.sh
  test/integration/targets/interpreter_discovery_python/tasks/main.yml
  test/units/executor/test_interpreter_discovery.py
Labels: stale_ci, bug

#84699 basic: remember the user sensitive information to use later
  changelogs/fragments/no_log.yml
  lib/ansible/module_utils/basic.py
  lib/ansible/modules/git.py
  test/integration/targets/git/tasks/formats.yml
  test/integration/targets/git/tasks/main.yml
  test/integration/targets/git/vars/main.yml
Labels: module, stale_review, bug, has_issue

#84938 [stable-2.18] Handle forwarded exceptions from dnf5-5.2.13 (#84933)
  changelogs/fragments/dnf5-exception-forwarding.yml
  lib/ansible/modules/dnf5.py
Labels: backport, module, needs_triage

#78111 pipelining 4.3
  changelogs/fragments/pipelining_refactor.yml
  lib/ansible/plugins/action/__init__.py
  lib/ansible/plugins/become/__init__.py
  lib/ansible/plugins/become/su.py
  lib/ansible/plugins/connection/__init__.py
  lib/ansible/plugins/connection/ssh.py
Labels: WIP, support:core, bug, feature, affects_2.14

#84943 Pin `wheel` to resolve build issues
  changelogs/fragments/pin-wheel.yml
  pyproject.toml
Labels: bug

#84944 [stable-2.18] Pin `wheel` to resolve build issues (#84943)
  changelogs/fragments/pin-wheel.yml
  pyproject.toml
Labels: backport, bug

#84945 [stable-2.17] Pin `wheel` to resolve build issues (#84943)
  changelogs/fragments/pin-wheel.yml
  pyproject.toml
Labels: backport, bug

#84946 [stable-2.16] Pin `wheel` to resolve build issues (#84943)
  changelogs/fragments/pin-wheel.yml
  pyproject.toml
Labels: backport, bug

#84947 [stable-2.14] Pin `wheel` to resolve build issues (#84943)
  changelogs/fragments/pin-wheel.yml
  pyproject.toml
Labels: backport, bug

#84941 distro: detect debian for OS_FAMILY for LMDE 6
  changelogs/fragments/distro_LMDE_6.yml
  lib/ansible/module_utils/facts/system/distribution.py
  test/units/module_utils/facts/system/distribution/fixtures/lmde_6.json
Labels: needs_triage, bug, has_issue

#84860 [stable 2.17] needed intesect, not difference (#84839)
  changelogs/fragments/gather_facts_smart_fix.yml
  lib/ansible/plugins/action/gather_facts.py
  test/integration/targets/gathering_facts/runme.sh
  test/integration/targets/gathering_facts/smart_added.yml
Labels: backport, needs_triage, bug

#84876 [stable-2.17] Fix wait_for examples (#84870)
  lib/ansible/modules/wait_for.py
Labels: backport, module, needs_triage

#84902 [stable-2.17] import_role docs: fix markup for config variable reference
  lib/ansible/modules/import_role.py
Labels: backport, module, needs_triage

#84940 [stable-2.17] basic: remember the user sensitive information to use later
  changelogs/fragments/no_log.yml
  lib/ansible/module_utils/basic.py
  lib/ansible/modules/git.py
  test/integration/targets/git/tasks/formats.yml
  test/integration/targets/git/tasks/main.yml
  test/integration/targets/git/vars/main.yml
Labels: backport, module, needs_triage, bug

#84854 [stable-2.18] uri - fix return value 'location' from relative redirect (#84541)
  changelogs/fragments/84540-uri-relative-redirect.yml
  lib/ansible/modules/uri.py
  test/integration/targets/uri/tasks/redirect-none.yml
  test/integration/targets/uri/tasks/redirect-safe.yml
Labels: backport, module, needs_triage, bug

#84857 [stable-2.18] Changed human_to_bytes input to a string (#84336)
  lib/ansible/plugins/filter/human_to_bytes.yml
Labels: backport, needs_triage

#84859 [stable 2.18] needed intesect, not difference (#84839)
  changelogs/fragments/gather_facts_smart_fix.yml
  lib/ansible/plugins/action/gather_facts.py
  test/integration/targets/gathering_facts/runme.sh
  test/integration/targets/gathering_facts/smart_added.yml
Labels: backport, needs_triage, bug

#84875 [stable 2.18] Fix wait_for examples (#84870)
  lib/ansible/modules/wait_for.py
Labels: backport, module, needs_triage

#84886 [bp-2.18] find: skip ENOENT while enumerating files
  changelogs/fragments/find_enoent.yml
  lib/ansible/modules/find.py
Labels: backport, module, needs_triage, bug

#84903 [stable-2.18] import_role docs: fix markup for config variable reference
  lib/ansible/modules/import_role.py
Labels: backport, module, needs_triage

#84955 fix typo
  lib/ansible/plugins/become/__init__.py
Labels: needs_triage

#84959 Revert "basic: remember the user sensitive information to use later (…
  changelogs/fragments/no_log.yml
  lib/ansible/module_utils/basic.py
  lib/ansible/modules/git.py
  test/integration/targets/git/tasks/formats.yml
  test/integration/targets/git/tasks/main.yml
  test/integration/targets/git/vars/main.yml
Labels: module, needs_triage

#84960 Revert "[stable-2.18] basic: remember the user sensitive information …
  changelogs/fragments/no_log.yml
  lib/ansible/module_utils/basic.py
  lib/ansible/modules/git.py
  test/integration/targets/git/tasks/formats.yml
  test/integration/targets/git/tasks/main.yml
  test/integration/targets/git/vars/main.yml
Labels: backport, module, needs_triage

#84961 Revert "[stable-2.17] basic: remember the user sensitive information …
  changelogs/fragments/no_log.yml
  lib/ansible/module_utils/basic.py
  lib/ansible/modules/git.py
  test/integration/targets/git/tasks/formats.yml
  test/integration/targets/git/tasks/main.yml
  test/integration/targets/git/vars/main.yml
Labels: backport, module, needs_triage

#84869 ansible-pull fix adhoc output inconsistencies on changed
  changelogs/fragments/pull_changed_fix.yml
  lib/ansible/cli/pull.py
  test/integration/targets/ansible-pull/aliases
  test/integration/targets/ansible-pull/runme.sh
Labels: stale_review, bug, has_issue

#84962 respawn: Update ENV dict copy with PYTHONPATH value
  changelogs/fragments/respawn_os_env.yml
  lib/ansible/module_utils/common/respawn.py
Labels: has_issue

#84963 git: Document security risk involved in embedding user creds
  lib/ansible/modules/git.py
Labels: module, has_issue

#84754 Add ssh-agent launching, and ssh-agent python client
  changelogs/fragments/ssh-agent.yml
  lib/ansible/cli/__init__.py
  lib/ansible/cli/adhoc.py
  lib/ansible/cli/console.py
  lib/ansible/cli/playbook.py
  lib/ansible/config/base.yml
  lib/ansible/plugins/connection/ssh.py
  lib/ansible/utils/_ssh_agent.py
  licenses/BSD-3-Clause.txt
  test/integration/targets/ssh_agent/action_plugins/ssh_agent.py
  test/integration/targets/ssh_agent/action_plugins/ssh_keygen.py
  test/integration/targets/ssh_agent/aliases
  test/integration/targets/ssh_agent/auto.yml
  test/integration/targets/ssh_agent/tasks/main.yml
  test/integration/targets/ssh_agent/tasks/tests.yml
  test/integration/targets/ssh_agent/test_key.yml
Labels: needs_revision, feature

#84949 Filter: add support for URL-safe encoding/decoding in b64*
  changelogs/fragments/url_safe_b64_encode_decode.yml
  lib/ansible/plugins/filter/b64decode.yml
  lib/ansible/plugins/filter/b64encode.yml
  lib/ansible/plugins/filter/core.py
  test/integration/targets/filter_core/tasks/main.yml
Labels: stale_review, bug, has_issue

#84972 ansible-test - Improve runme.sh error handling
  changelogs/fragments/ansible-test-no-exec-script.yml
  test/integration/targets/ansible-test-integration-no-exec-script/aliases
  test/integration/targets/ansible-test-integration-no-exec-script/ansible_collections/ns/col/tests/integration/targets/hello/aliases
  test/integration/targets/ansible-test-integration-no-exec-script/ansible_collections/ns/col/tests/integration/targets/hello/runme.sh
  test/integration/targets/ansible-test-integration-no-exec-script/runme.sh
  test/lib/ansible_test/_internal/commands/integration/__init__.py
Labels: feature, has_issue

#84973 Fix uninstall tests
  test/integration/targets/setup_paramiko/uninstall-dnf5.yml
Labels: test, needs_triage

#84976 [backport 2.16] Fix uninstall tests (#84973)
  test/integration/targets/setup_paramiko/uninstall-dnf5.yml
Labels: backport, test, needs_triage

#84975 [backport 2.17] Fix uninstall tests (#84973)
  test/integration/targets/setup_paramiko/uninstall-dnf5.yml
Labels: backport, test, needs_triage

#84974 [backport 2.18] Fix paramiko tests
  test/integration/targets/setup_paramiko/uninstall-dnf5.yml
Labels: backport, test, needs_triage

#84982 Convert DT issue template to pre-release template
  .github/ISSUE_TEMPLATE/pre_release.yml
Labels: feature

#84981 New release v2.17.11rc1
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.11rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#84979 New release v2.19.0b1
  changelogs/CHANGELOG-v2.19.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.19.0b1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#84986 Update Ansible release version to v2.17.11rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#84987 Update Ansible release version to v2.18.5rc1.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#84988 Update Ansible release version to v2.19.0b1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#84690 ansible-doc: fix indent and line wrapping for first line of (sub-)option and (sub-)return value descriptions
  changelogs/fragments/84690-ansible-doc-indent-wrapping.yml
  lib/ansible/cli/doc.py
  test/integration/targets/ansible-doc/randommodule-text-verbose.output
  test/integration/targets/ansible-doc/randommodule-text.output
  test/integration/targets/ansible-doc/test_docs_returns.output
  test/integration/targets/ansible-doc/test_docs_suboptions.output
  test/integration/targets/ansible-doc/test_docs_yaml_anchors.output
Labels: bug

#84995 get_bin_path('ssh-agent'): required is deprecated
  changelogs/fragments/get_bin_path-remove-use-of-deprecated-param.yml
  lib/ansible/cli/__init__.py
Labels: needs_triage, bug

#85000 Disable parallel publish in galaxy test
  test/integration/targets/ansible-galaxy-collection/library/setup_collections.py
Labels: test

#84991 Miscellaneous DT fixes
  lib/ansible/_internal/_templating/_jinja_plugins.py
  lib/ansible/cli/__init__.py
  lib/ansible/module_utils/basic.py
  lib/ansible/module_utils/common/warnings.py
  lib/ansible/parsing/yaml/objects.py
  lib/ansible/plugins/test/core.py
  lib/ansible/template/__init__.py
  lib/ansible/utils/display.py
  test/integration/targets/apt/tasks/upgrade_autoremove.yml
  test/integration/targets/deprecations/disabled.yml
  test/integration/targets/deprecations/library/noisy.py
  test/integration/targets/deprecations/runme.sh
  test/integration/targets/lookup_template/tasks/main.yml
  test/integration/targets/template/tasks/main.yml
  test/units/parsing/yaml/test_objects.py
  test/units/template/test_template.py
Labels: bug

#85008 Remove unused local function _get_plugin_vars from vars manager
  lib/ansible/vars/manager.py
Labels: bug, has_issue

#85013 Disable retries on ansible-galaxy-collection
  test/integration/targets/ansible-galaxy-collection/aliases
Labels: test, needs_triage

#85012 Miscellaneous fixes
  lib/ansible/executor/process/worker.py
  lib/ansible/executor/task_executor.py
  lib/ansible/executor/task_queue_manager.py
  lib/ansible/executor/task_result.py
  lib/ansible/plugins/strategy/__init__.py
  lib/ansible/utils/display.py
  lib/ansible/vars/manager.py
  test/units/executor/test_task_result.py
  test/units/playbook/test_included_file.py
  test/units/plugins/callback/test_callback.py
Labels: bug

#85007 Fix test_range_templating on 32-bit architectures
  test/units/_internal/templating/test_lazy_containers.py
Labels: test

#85016 Increase galaxy test publish timeout
  test/integration/targets/ansible-galaxy-collection/library/setup_collections.py
Labels: test

#84998 normalize error handler choices
  lib/ansible/_internal/_errors/_handler.py
  lib/ansible/_internal/_templating/_jinja_bits.py
  lib/ansible/config/base.yml
  test/integration/targets/adhoc/runme.sh
  test/integration/targets/data_tagging_controller/runme.sh
  test/units/_internal/templating/test_templar.py
  test/units/conftest.py
  test/units/errors/test_handler.py
Labels: bug

#85018 [stable-2.14] Disable unsupported integration tests
  test/integration/targets/ansible-test-cloud-foreman/aliases
  test/integration/targets/ansible-test-cloud-vcenter/aliases
Labels: backport, test

#85025 New release v2.18.5
  changelogs/CHANGELOG-v2.18.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.18.5_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#85028 [stable-2.17] ansible-test - Replace FreeBSD 14.0 with 14.1
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-platform-updates.yml
  test/lib/ansible_test/_data/completion/remote.txt
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: backport, feature

#85024 New release v2.17.11
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.11_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#85029 Update Ansible release version to v2.17.11.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#85031 [stable-2.16] default svn URL to 127.0.0.1 for subversion integration tests (#82551)
  test/integration/targets/subversion/roles/subversion/defaults/main.yml
  test/integration/targets/subversion/roles/subversion/tasks/setup.yml
  test/integration/targets/subversion/roles/subversion/templates/subversion.conf.j2
Labels: backport, test

#85032 restore parsing/utils/jsonify.py
  lib/ansible/parsing/utils/jsonify.py
Labels: needs_revision, ci_verified, stale_review, bug, has_issue

#85030 [stable-2.16] ansible-test - Replace FreeBSD 13.2 with 13.3
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible_test_freebsd-13.3.yml
  test/integration/targets/setup_paramiko/constraints.txt
  test/integration/targets/wait_for/tasks/main.yml
  test/lib/ansible_test/_data/completion/remote.txt
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: needs_revision, backport, feature

#85039 Implement TaskResult backward compatibility for callbacks
  changelogs/fragments/templates_types_datatagging.yml
  lib/ansible/_internal/_collection_proxy.py
  lib/ansible/_internal/_json/__init__.py
  lib/ansible/_internal/_json/_profiles/_legacy.py
  lib/ansible/executor/process/worker.py
  lib/ansible/executor/task_executor.py
  lib/ansible/executor/task_queue_manager.py
  lib/ansible/executor/task_result.py
  lib/ansible/inventory/manager.py
  lib/ansible/playbook/included_file.py
  lib/ansible/plugins/callback/__init__.py
  lib/ansible/plugins/callback/default.py
  lib/ansible/plugins/callback/junit.py
  lib/ansible/plugins/callback/minimal.py
  lib/ansible/plugins/callback/oneline.py
  lib/ansible/plugins/callback/tree.py
  lib/ansible/plugins/strategy/__init__.py
  lib/ansible/plugins/strategy/free.py
  lib/ansible/plugins/strategy/linear.py
  lib/ansible/utils/vars.py
  lib/ansible/vars/clean.py
  test/integration/targets/callback-legacy-warnings/aliases
  test/integration/targets/callback-legacy-warnings/callback_plugins/legacy_warning_display.py
  test/integration/targets/callback-legacy-warnings/library/noisy.py
  test/integration/targets/callback-legacy-warnings/runme.sh
  test/integration/targets/callback-legacy-warnings/test.yml
  test/integration/targets/callback_results/callback_plugins/track_connections.py
  test/integration/targets/collections/test_task_resolved_plugin/callback_plugins/display_resolved_action.py
  test/integration/targets/module_utils/callback/pure_json.py
  test/integration/targets/strategy_host_pinned/callback_plugins/callback_host_count.py
  test/units/executor/test_task_queue_manager_callbacks.py
  test/units/executor/test_task_result.py
  test/units/playbook/test_included_file.py
  test/units/plugins/callback/test_callback.py
Labels: bug

#85040 New release v2.19.0b2
  changelogs/CHANGELOG-v2.19.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.19.0b2_summary.yaml
  lib/ansible/release.py
Labels: backport, feature

#85041 Update Ansible release version to v2.19.0b2.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#84997 show internal but not hidden config options, while still hiding test options
  changelogs/fragments/config_priv.yml
  lib/ansible/config/manager.py
  test/integration/targets/ansible-config/tasks/main.yml
Labels: feature

#85019 ansible-test - Use `-t` for container stop timeout
  changelogs/fragments/ansible-test-container-stop.yml
  test/lib/ansible_test/_internal/docker_util.py
Labels: feature

#85057 [stable-2.17] ansible-test - Use `-t` for container stop timeout
  changelogs/fragments/ansible-test-container-stop.yml
  test/lib/ansible_test/_internal/docker_util.py
Labels: backport, needs_triage, feature

#85056 [stable-2.18] ansible-test - Use `-t` for container stop timeout
  changelogs/fragments/ansible-test-container-stop.yml
  test/lib/ansible_test/_internal/docker_util.py
Labels: backport, needs_triage, feature

#85055 [stable-2.19] ansible-test - Use `-t` for container stop timeout
  changelogs/fragments/ansible-test-container-stop.yml
  test/lib/ansible_test/_internal/docker_util.py
Labels: backport, needs_triage, feature

#85058 [stable-2.16] ansible-test - Use `-t` for container stop timeout
  changelogs/fragments/ansible-test-container-stop.yml
  test/lib/ansible_test/_internal/docker_util.py
Labels: backport, needs_triage, feature

#85059 [stable-2.14] ansible-test - Use `-t` for container stop timeout
  changelogs/fragments/ansible-test-container-stop.yml
  test/lib/ansible_test/_internal/docker_util.py
Labels: needs_revision, backport, feature

#85066 async_status: fix example to use finished test
  lib/ansible/modules/async_status.py
Labels: module, needs_triage, has_issue

#85065 dnf5: avoid generating excessive history entries
  changelogs/fragments/85046-dnf5-history-entries.yml
  lib/ansible/modules/dnf5.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: module, needs_triage, bug, has_issue

#85077 [stable-2.18] - script fix become on Windows
  changelogs/fragments/win-script-become.yml
  lib/ansible/plugins/action/script.py
  test/integration/targets/win_script/tasks/main.yml
Labels: backport, needs_triage, bug

#85079 Add win_script become tests
  test/integration/targets/win_script/tasks/main.yml
Labels: test, needs_triage
