Repository ansible/ansible, pull requests merged in 2025-08, with the labels that each got.

#85526 plugin config options are now correctly fetched with origin (#85488)
  changelogs/fragments/plugins_fix_origin.yml
  lib/ansible/config/manager.py
  lib/ansible/plugins/__init__.py
  lib/ansible/plugins/callback/__init__.py
  test/integration/targets/config/lookup_plugins/broken.py
  test/integration/targets/config/match_option_methods.yml
  test/integration/targets/config/runme.sh
Labels: backport, needs_triage, bug

#85607 [stable-2.19] dnf/dnf5: address issues discovered in 2.16 yum tests (#83659)
  lib/ansible/modules/dnf.py
  lib/ansible/modules/dnf5.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: backport, module, needs_triage, bug

#85525 plugin config options are now correctly fetched with origin (#85488)
  changelogs/fragments/plugins_fix_origin.yml
  lib/ansible/config/manager.py
  lib/ansible/plugins/__init__.py
  lib/ansible/plugins/callback/__init__.py
  test/integration/targets/config/lookup_plugins/broken.py
  test/integration/targets/config/match_option_methods.yml
  test/integration/targets/config/runme.sh
Labels: backport, needs_triage, bug

#85465 meta: clear_host_errors, clarify what this applies to (#85463)
  lib/ansible/modules/meta.py
Labels: backport, module, needs_triage

#85453 [stable-2.19] default _ansible_tracebacks_for to [] when not specified (#85427)
  lib/ansible/module_utils/_internal/_traceback.py
  test/units/module_utils/_internal/test_traceback.py
Labels: backport, test, needs_triage

#85620 Update Ansible release version to v2.18.8rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#85609 Add temporary module result serialization hook
  changelogs/fragments/module_direct_exec.yml
  lib/ansible/module_utils/basic.py
  test/units/module_utils/basic/test_exit_json.py
Labels: feature

#85572 service_facts: Handle KeyError while processing service name
  changelogs/fragments/openrc.yml
  lib/ansible/modules/service_facts.py
Labels: module, needs_triage, stale_review, bug

#85628 IncludedFile: store _from args for proper deduplication
  changelogs/fragments/66497-include_role-_from-dedup.yml
  lib/ansible/playbook/included_file.py
  test/integration/targets/includes/includes_from_dedup.yml
  test/integration/targets/includes/roles/role_from_args/tasks/localhost.yml
  test/integration/targets/includes/roles/role_from_args/tasks/testhost.yml
  test/integration/targets/includes/roles/role_from_args/vars/localhost.yml
  test/integration/targets/includes/roles/role_from_args/vars/testhost.yml
  test/integration/targets/includes/runme.sh
  test/units/playbook/test_included_file.py
Labels: bug, has_issue

#81796 ansible-doc: show 'notes', 'seealso', and top-level 'version_added' for role entrypoints
  changelogs/fragments/81796-ansible-doc-roles.yml
  lib/ansible/cli/doc.py
  test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol/roles/testrole/meta/main.yml
  test/integration/targets/ansible-doc/fakecollrole.output
  test/integration/targets/ansible-doc/fakerole.output
  test/integration/targets/ansible-doc/roles/test_role1/meta/argument_specs.yml
Labels: needs_revision, stale_ci, feature

#85629 regex: validate input before processing
  changelogs/fragments/regex_test.yml
  lib/ansible/plugins/test/core.py
  lib/ansible/plugins/test/regex.yml
  test/integration/targets/test_core/tasks/main.yml
Labels: needs_triage, bug

#85652 Backward-compatible None handling in template concat and argspec str
  changelogs/fragments/concat_coerce_none_to_empty.yml
  lib/ansible/_internal/_templating/_jinja_bits.py
  lib/ansible/module_utils/common/validation.py
  test/integration/targets/apt_repository/tasks/apt.yml
  test/integration/targets/roles_arg_spec/test.yml
  test/units/_internal/templating/test_templar.py
  test/units/module_utils/common/validation/test_check_type_str.py
Labels: stale_review, bug, has_issue

#85662 [stable-2.19] Fix filter plugin result processing (#85653)
  changelogs/fragments/templating-filter-generators.yml
  lib/ansible/_internal/_templating/_jinja_plugins.py
  test/units/_internal/templating/test_templar.py
Labels: backport, bug

#85664 test: Remove redundant Python 3 condition
  test/integration/targets/lookup_ini/test_errors.yml
Labels: test

#85687 Expose ansible_failed_task in rescue for explicit flush_handlers
  changelogs/fragments/85682-rescue-flush_handlers.yml
  lib/ansible/executor/play_iterator.py
  test/integration/targets/handlers/rescue_flush_handlers.yml
  test/integration/targets/handlers/runme.sh
Labels: bug, has_issue

#85673 vars deprecation
  changelogs/fragments/vars_begone.yml
  lib/ansible/vars/manager.py
  test/integration/targets/var_templating/runme.sh
  test/integration/targets/var_templating/vars_deprecation.yml
Labels: feature

#85730 New release v2.19.1
  changelogs/CHANGELOG-v2.19.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.19.1_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#85737 CI - Add missing args to generic.sh
  .azure-pipelines/commands/generic.sh
Labels: test

#85740 [stable-2.17] CI - Add missing args to generic.sh (#85737)
  .azure-pipelines/commands/generic.sh
Labels: backport, test

#85741 [stable-2.16] CI - Add missing args to generic.sh (#85737)
  .azure-pipelines/commands/generic.sh
Labels: backport, test

#85742 [stable-2.14] CI - Add missing args to generic.sh (#85737)
  .azure-pipelines/commands/generic.sh
Labels: backport, test

#85739 [stable-2.18] CI - Add missing args to generic.sh (#85737)
  .azure-pipelines/commands/generic.sh
Labels: needs_revision, backport, test

#85710 Remove excessive apostrophe in documentation of package_facts.py
  lib/ansible/modules/package_facts.py
Labels: module

#85651 sanity: warn on ansible.module_utils.six imports
  test/lib/ansible_test/_util/controller/sanity/pylint/plugins/unwanted.py
Labels: feature

#85752 ternary: evaluate values lazily
  changelogs/fragments/85743-lazy-ternary.yml
  lib/ansible/plugins/filter/core.py
  test/integration/targets/filter_core/tasks/main.yml
Labels: bug, has_issue

#85717 ansible-test - Update Ansible Core CI auth
  changelogs/fragments/ansible-test-auth-update.yml
  test/lib/ansible_test/_internal/ci/__init__.py
  test/lib/ansible_test/_internal/ci/azp.py
  test/lib/ansible_test/_internal/ci/local.py
  test/lib/ansible_test/_internal/core_ci.py
  test/lib/ansible_test/_internal/host_profiles.py
  test/lib/ansible_test/_internal/provisioning.py
  test/lib/ansible_test/_internal/util.py
  test/units/ansible_test/ci/__init__.py
  test/units/ansible_test/ci/test_azp.py
  test/units/ansible_test/ci/util.py
Labels: feature

#85769 [stable-2.18] ansible-test - Update Ansible Core CI auth (#85717)
  changelogs/fragments/ansible-test-auth-update.yml
  test/lib/ansible_test/_internal/ci/__init__.py
  test/lib/ansible_test/_internal/ci/azp.py
  test/lib/ansible_test/_internal/ci/local.py
  test/lib/ansible_test/_internal/core_ci.py
  test/lib/ansible_test/_internal/host_profiles.py
  test/lib/ansible_test/_internal/provisioning.py
  test/lib/ansible_test/_internal/util.py
  test/units/ansible_test/ci/__init__.py
  test/units/ansible_test/ci/test_azp.py
  test/units/ansible_test/ci/util.py
Labels: backport, feature

#85770 [stable-2.17] ansible-test - Update Ansible Core CI auth (#85717)
  changelogs/fragments/ansible-test-auth-update.yml
  test/lib/ansible_test/_internal/ci/__init__.py
  test/lib/ansible_test/_internal/ci/azp.py
  test/lib/ansible_test/_internal/ci/local.py
  test/lib/ansible_test/_internal/core_ci.py
  test/lib/ansible_test/_internal/host_profiles.py
  test/lib/ansible_test/_internal/provisioning.py
  test/lib/ansible_test/_internal/util.py
  test/units/ansible_test/ci/__init__.py
  test/units/ansible_test/ci/test_azp.py
  test/units/ansible_test/ci/util.py
Labels: backport, feature

#85771 [stable-2.16] ansible-test - Update Ansible Core CI auth (#85717)
  changelogs/fragments/ansible-test-auth-update.yml
  test/lib/ansible_test/_internal/ci/__init__.py
  test/lib/ansible_test/_internal/ci/azp.py
  test/lib/ansible_test/_internal/ci/local.py
  test/lib/ansible_test/_internal/core_ci.py
  test/lib/ansible_test/_internal/host_profiles.py
  test/lib/ansible_test/_internal/provisioning.py
  test/lib/ansible_test/_internal/util.py
  test/units/ansible_test/ci/__init__.py
  test/units/ansible_test/ci/test_azp.py
  test/units/ansible_test/ci/util.py
Labels: backport, feature

#85772 [stable-2.14] ansible-test - Update Ansible Core CI auth (#85717)
  changelogs/fragments/ansible-test-auth-update.yml
  test/lib/ansible_test/_internal/ci/__init__.py
  test/lib/ansible_test/_internal/ci/azp.py
  test/lib/ansible_test/_internal/ci/local.py
  test/lib/ansible_test/_internal/core_ci.py
  test/lib/ansible_test/_internal/host_profiles.py
  test/lib/ansible_test/_internal/provisioning.py
  test/lib/ansible_test/_internal/util.py
  test/units/ansible_test/ci/__init__.py
  test/units/ansible_test/ci/test_azp.py
  test/units/ansible_test/ci/util.py
Labels: backport, feature
