Repository ansible/ansible, pull requests merged in 2025-06, with the labels that each got.

#85247 Resolve misc DTFIX0/1
  lib/ansible/_internal/_templating/_jinja_bits.py
  lib/ansible/_internal/_templating/_jinja_common.py
  lib/ansible/_internal/_templating/_lazy_containers.py
  lib/ansible/_internal/ansible_collections/ansible/_protomatter/plugins/filter/true_type.py
  lib/ansible/executor/task_result.py
  lib/ansible/parsing/ajson.py
  lib/ansible/parsing/vault/__init__.py
  lib/ansible/playbook/taggable.py
  lib/ansible/plugins/__init__.py
  lib/ansible/plugins/callback/__init__.py
  lib/ansible/plugins/filter/core.py
  lib/ansible/plugins/filter/encryption.py
  lib/ansible/plugins/lookup/first_found.py
  lib/ansible/plugins/test/core.py
  lib/ansible/template/__init__.py
  test/integration/targets/assert/tasks/main.yml
Labels: feature

#85255 New release v2.19.0b5
  changelogs/CHANGELOG-v2.19.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.19.0b5_summary.yaml
  lib/ansible/release.py
  pyproject.toml
Labels: backport, needs_triage, feature

#85257 Update Ansible release version to v2.19.0b5.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#82050 Use a Specific Package Manager
  lib/ansible/modules/package.py
Labels: module, stale_ci

#85258 Fix logic error in ansible-galaxy
  lib/ansible/galaxy/api.py
Labels: bug

#85270 Add missing docs for sftp_batch_mode
  lib/ansible/plugins/connection/ssh.py
Labels: bug, has_issue

#85271 [stable-2.17] dnf5 tests: do not remove attr (#85218)
  test/integration/targets/dnf/tasks/gpg.yml
Labels: backport, test

#85275 Restore 2.18 vault tag YAML dump behavior
  changelogs/fragments/templates_types_datatagging.yml
  lib/ansible/_internal/_yaml/_dumper.py
  lib/ansible/cli/inventory.py
  lib/ansible/plugins/filter/core.py
  test/integration/targets/templating/tasks/main.yml
  test/units/_internal/_yaml/test_dumper.py
  test/units/parsing/yaml/test_dumper.py
Labels: feature

#85277 adjust PluginInfo to use PluginType enum
  lib/ansible/_internal/_templating/_transform.py
  lib/ansible/module_utils/_internal/_datatag/__init__.py
  lib/ansible/module_utils/_internal/_deprecator.py
  lib/ansible/module_utils/_internal/_json/_profiles/__init__.py
  lib/ansible/module_utils/_internal/_messages.py
  lib/ansible/module_utils/_internal/_plugin_info.py
  lib/ansible/utils/display.py
  test/integration/targets/protomatter/lookup_plugins/synthetic_plugin_info.py
  test/integration/targets/protomatter/tasks/main.yml
  test/units/executor/module_common/test_recursive_finder.py
  test/units/module_utils/_internal/test_deprecator.py
  test/units/module_utils/datatag/test_datatag.py
  test/units/parsing/vault/test_vault.py
  test/units/utils/test_display.py
Labels: feature

#85280 fix Marker handling on Jinja macro invocations
  changelogs/fragments/macro_support.yml
  lib/ansible/_internal/_templating/_jinja_bits.py
  lib/ansible/_internal/_templating/_jinja_plugins.py
  test/units/_internal/templating/test_jinja_bits.py
Labels: bug

#85288 Fix deprecation versions in template lookup
  lib/ansible/plugins/lookup/template.py
Labels: needs_triage, bug

#85295 Fix nested include with templating
  lib/ansible/playbook/included_file.py
  test/integration/targets/include_with_templating/aliases
  test/integration/targets/include_with_templating/tasks/main.yml
  test/integration/targets/include_with_templating/tests/one.yml
  test/integration/targets/include_with_templating/tests/two.yml
Labels: needs_revision, bug, has_issue

#85297 ansible-test - Code cleanup
  test/lib/ansible_test/_internal/host_profiles.py
  test/lib/ansible_test/_internal/provisioning.py
  test/lib/ansible_test/_internal/ssh.py
  test/lib/ansible_test/_internal/thread.py
  test/lib/ansible_test/_internal/timeout.py
  test/lib/ansible_test/_internal/util.py
Labels: feature

#85293 module_utils/basic.py: properly deprecate importing `text_type`
  lib/ansible/module_utils/basic.py
Labels: needs_triage, bug

#85305 New release v2.19.0b6
  changelogs/CHANGELOG-v2.19.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.19.0b6_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#85306 Update Ansible release version to v2.19.0b6.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#85307 ansible-test - Move metadata to environment
  test/lib/ansible_test/_internal/cli/commands/__init__.py
  test/lib/ansible_test/_internal/cli/environments.py
  test/lib/ansible_test/_internal/config.py
  test/lib/ansible_test/_internal/delegation.py
  test/lib/ansible_test/_internal/metadata.py
Labels: needs_triage, feature

#85313 Minor Documentation and Comment Corrections
  test/integration/targets/ansible-doc/collections/ansible_collections/testns/testcol/plugins/filter/ultimatequestion.yml
  test/integration/targets/win_app_control/files/New-AnsiblePowerShellSignature.ps1
Labels: needs_triage

#85219 apt: Consider timeout while invoking apt-get command
  changelogs/fragments/apt_timeout.yml
  lib/ansible/modules/apt.py
Labels: module, bug, has_issue

#85321 ansible-test - Fix ansible-test debug from remote shell
  test/lib/ansible_test/_internal/commands/shell/__init__.py
Labels: bug

#85326 fix script failed_when bypass
  lib/ansible/plugins/action/__init__.py
  lib/ansible/plugins/action/script.py
  test/integration/targets/script/files/exit_1.sh
  test/integration/targets/script/tasks/main.yml
Labels: bug, has_issue

#85329 Add type annotations to set_module_args
  test/units/modules/conftest.py
Labels: bug

#85338 Fix Typo in Variable Name and Update Test Data for Identifier Validation
  test/integration/targets/module_utils_Ansible.ModuleUtils.CommandUtil/library/command_util_test.ps1
  test/units/playbook/test_base.py
Labels: needs_triage

#85344 Misc callback fixes/cleanup
  changelogs/fragments/callback_base.yml
  lib/ansible/cli/adhoc.py
  lib/ansible/cli/console.py
  lib/ansible/executor/task_queue_manager.py
  lib/ansible/module_utils/_internal/_deprecator.py
  lib/ansible/plugins/callback/__init__.py
  lib/ansible/plugins/callback/default.py
  lib/ansible/plugins/callback/junit.py
  lib/ansible/plugins/loader.py
  lib/ansible/utils/display.py
  test/integration/targets/callback-dispatch/aliases
  test/integration/targets/callback-dispatch/callback_plugins/legacy_warning_display.py
  test/integration/targets/callback-dispatch/callback_plugins/missing_base_class.py
  test/integration/targets/callback-dispatch/callback_plugins/oops_always_enabled.py
  test/integration/targets/callback-dispatch/callback_plugins/v1_only_methods.py
  test/integration/targets/callback-dispatch/library/noisy.py
  test/integration/targets/callback-dispatch/one-task.yml
  test/integration/targets/callback-dispatch/runme.sh
  test/integration/targets/callback-dispatch/test_legacy_warning_display.yml
  test/integration/targets/callback-dispatch/test_v1_methods.yml
  test/integration/targets/callback-legacy-warnings/runme.sh
  test/units/plugins/callback/test_callback.py
Labels: needs_revision, bug, has_issue

#85347 Update Comments for Pause Test Cases for Clarity
  test/integration/targets/pause/test-pause.py
Labels: needs_triage

#85324 Show context for reserved variable warnings
  changelogs/fragments/warn-on-reserved.yml
  lib/ansible/vars/manager.py
  lib/ansible/vars/reserved.py
  test/integration/targets/var_reserved/tasks/main.yml
Labels: feature

#85318 Improve password lookup lock acquisition so it checks the error type
  changelogs/fragments/fix-lookup-password-lock-acquisition.yml
  lib/ansible/plugins/lookup/password.py
  test/units/plugins/lookup/test_password.py
Labels: bug, has_issue

#85351 feature-flag experimental module metadata
  changelogs/fragments/ansible-test-env-set.yml
  lib/ansible/config/base.yml
  lib/ansible/executor/module_common.py
  test/integration/targets/ansible-test-integration/ansible_collections/ns/col/tests/integration/targets/hello/aliases
  test/integration/targets/ansible-test-integration/ansible_collections/ns/col/tests/integration/targets/hello/tasks/main.yml
  test/integration/targets/module-serialization-profiles/aliases
  test/lib/ansible_test/_internal/commands/integration/__init__.py
  test/lib/ansible_test/_internal/target.py
Labels: needs_triage, feature

#85353 Remove Python 2 mentions
  lib/ansible/module_utils/basic.py
  lib/ansible/modules/pip.py
  lib/ansible/modules/raw.py
Labels: module

#85358 import_playbook validation cleanup
  lib/ansible/playbook/base.py
  lib/ansible/playbook/playbook_include.py
  test/integration/targets/include_import/playbook/test_import_playbook.yml
Labels: needs_triage, bug

#85342 Test both original and latest dnf versions
  .azure-pipelines/azure-pipelines.yml
  test/integration/targets/dnf-latest/aliases
  test/integration/targets/dnf-latest/tasks/main.yml
  test/integration/targets/dnf-oldest/aliases
  test/integration/targets/dnf-oldest/tasks/main.yml
  test/integration/targets/dnf/tasks/dnf.yml
  test/integration/targets/dnf/tasks/main.yml
  test/integration/targets/dnf/tasks/repo.yml
  test/lib/ansible_test/_internal/commands/sanity/integration_aliases.py
Labels: test

#85374 [stable-2.18] Use f40 official repo for libdnf5
  test/integration/targets/dnf/tasks/dnf.yml
  test/integration/targets/dnf/tasks/repo.yml
  test/integration/targets/dnf5/playbook.yml
Labels: backport, test

#85383 New release v2.19.0b7
  changelogs/CHANGELOG-v2.19.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.19.0b7_summary.yaml
  lib/ansible/release.py
Labels: backport, feature

#85385 Jinja sandbox refinement
  changelogs/fragments/template-sandbox.yml
  lib/ansible/_internal/_json/__init__.py
  lib/ansible/_internal/_templating/_jinja_bits.py
  lib/ansible/_internal/_templating/_utils.py
  lib/ansible/cli/console.py
  lib/ansible/executor/module_common.py
  test/integration/targets/callback-dispatch/callback_plugins/legacy_warning_display.py
  test/integration/targets/protomatter/tasks/main.yml
  test/units/_internal/templating/test_jinja_bits.py
  test/units/_internal/templating/test_templar.py
Labels: needs_revision, ci_verified, stale_review, bug, has_issue

#85388 Docs: fix small typo
  lib/ansible/modules/systemd_service.py
Labels: module, needs_triage

#85389 ensure transform_to_native_types converts keys
  lib/ansible/_internal/_json/__init__.py
  lib/ansible/_internal/_json/_profiles/_legacy.py
  lib/ansible/utils/vars.py
  test/units/utils/test_vars.py
Labels: bug, has_issue

#85395 Remove redundant vars FA on PlaybookInclude
  lib/ansible/playbook/playbook_include.py
  test/integration/targets/include_import/playbook/playbook_using_a_var.yml
  test/integration/targets/include_import/playbook/test_import_playbook.yml
Labels: bug

#85396 Test multiple inheritance in _utils get_all_subclasses
  test/units/module_utils/common/test_utils.py
Labels: test

#85364 Limit askpass prompts to single attempt
  changelogs/fragments/85359-askpass-incorrect-password-retries.yml
  lib/ansible/cli/_ssh_askpass.py
  lib/ansible/plugins/connection/ssh.py
  test/integration/targets/connection_ssh/test_ssh_askpass.yml
Labels: needs_revision, stale_review, bug, has_issue

#85402 Fix deprecated pylint plugin version parsing
  test/lib/ansible_test/_util/controller/sanity/pylint/plugins/deprecated_calls.py
Labels: bug

#85403 New release v2.19.0rc1
  changelogs/CHANGELOG-v2.19.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.19.0rc1_summary.yaml
  lib/ansible/release.py
Labels: backport, feature

#85405 Update Ansible release version to v2.19.0rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#85406 Short-circuit legacy network module prefix->action mapping
  lib/ansible/executor/task_executor.py
  test/units/executor/test_task_executor.py
Labels: bug, has_issue

#85404 Ensure config env/ini values are tagged
  lib/ansible/config/manager.py
  test/integration/targets/lookup_template/tasks/ansible_managed.yml
  test/units/config/test_manager.py
Labels: stale_review, bug
