Repository ansible/ansible, pull requests merged in 2025-10, with the labels that each got.

#85877 import_tasks processing closer to include_tasks
  changelogs/fragments/import_tasks-fixes.yml
  lib/ansible/playbook/helpers.py
  test/integration/targets/include_import/roles/nested_tasks/tasks/bar.yml
  test/integration/targets/include_import/roles/nested_tasks/tasks/foo.yml
  test/integration/targets/include_import/roles/nested_tasks/tasks/main.yml
  test/integration/targets/include_import/runme.sh
  test/integration/targets/include_import/test_nested_non_existent_tasks.yml
  test/integration/targets/include_import_tasks_nested/tasks/main.yml
  test/integration/targets/include_import_tasks_nested/tests/tests_relative.yml
Labels: bug, has_issue

#85949 New release v2.19.3
  changelogs/CHANGELOG-v2.19.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.19.3_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#85951 Update Ansible release version to v2.18.10.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature, pending_ci

#85953 Fix flakey get_url test
  test/integration/targets/get_url/tasks/main.yml
Labels: test

#85545 Type-annotate ansible.galaxy.dependency_resolution
  lib/ansible/galaxy/collection/__init__.py
  lib/ansible/galaxy/dependency_resolution/__init__.py
  lib/ansible/galaxy/dependency_resolution/dataclasses.py
  lib/ansible/galaxy/dependency_resolution/providers.py
  lib/ansible/galaxy/dependency_resolution/versioning.py
  test/sanity/code-smell/mypy.requirements.in
  test/sanity/code-smell/mypy.requirements.txt
  test/sanity/code-smell/mypy/ansible-core.ini
Labels: test, feature
