Repository ansible/ansible, pull requests merged in 2025-01, with the labels that each got.

#84209 test: Update regex for required and default in FieldAttributes
  test/sanity/code-smell/required-and-default-attributes.py
  test/sanity/ignore.txt
Labels: stale_ci, bug, has_issue

#84506 Fix result_pickle_error integration test
  test/integration/targets/result_pickle_error/action_plugins/result_pickle_error.py
  test/integration/targets/result_pickle_error/tasks/main.yml
Labels: test

#84507 [stable-2.18] Fix result_pickle_error integration test (#84506)
  test/integration/targets/result_pickle_error/action_plugins/result_pickle_error.py
  test/integration/targets/result_pickle_error/tasks/main.yml
Labels: backport, test

#84508 [stable-2.17] Fix result_pickle_error integration test (#84506)
  test/integration/targets/result_pickle_error/action_plugins/result_pickle_error.py
  test/integration/targets/result_pickle_error/tasks/main.yml
Labels: backport, test

#84509 [stable-2.16] Fix result_pickle_error integration test (#84506)
  test/integration/targets/result_pickle_error/action_plugins/result_pickle_error.py
  test/integration/targets/result_pickle_error/tasks/main.yml
Labels: backport, test

#84511 [stable-2.16] Bump subversion to latest in its test on openSUSE
  test/integration/targets/subversion/vars/Suse.yml
Labels: backport, needs_triage, bug

#84517 ansible-test - Update nios-test-container to 7.0.0
  changelogs/fragments/ansible-test-nios-container.yml
  test/lib/ansible_test/_internal/commands/integration/cloud/nios.py
Labels: feature

#84518 Fix uri integration test on Python 3.13
  test/integration/targets/uri/tasks/redirect-urllib2.yml
Labels: test

#84519 [stable-2.18] Fix uri integration test on Python 3.13 (#84518)
  test/integration/targets/uri/tasks/redirect-urllib2.yml
Labels: backport, test

#83145 Add Keycloak service account auth capability to ansible-galaxy
  changelogs/fragments/ansible-galaxy-keycloak-service-accounts.yml
  lib/ansible/cli/galaxy.py
  lib/ansible/config/manager.py
  lib/ansible/galaxy/token.py
Labels: P2, feature, has_issue

#84281 ansible-test - Replace Fedora 40 with 41
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-containers.yml
  changelogs/fragments/ansible-test-remotes.yml
  test/integration/targets/ansible-test-container/runme.py
  test/integration/targets/dnf/tasks/main.yml
  test/integration/targets/package/tasks/main.yml
  test/integration/targets/subversion/vars/Debian.yml
  test/integration/targets/subversion/vars/Suse.yml
  test/integration/targets/subversion/vars/Ubuntu-18.yml
  test/integration/targets/subversion/vars/Ubuntu-20.yml
  test/lib/ansible_test/_data/completion/docker.txt
  test/lib/ansible_test/_data/completion/remote.txt
Labels: feature, has_issue

#84525 ansible-test - Replace Alpine 3.20 with 3.21
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-containers.yml
  changelogs/fragments/ansible-test-remotes.yml
  test/lib/ansible_test/_data/completion/docker.txt
  test/lib/ansible_test/_data/completion/remote.txt
Labels: feature, has_issue

#84526 ansible-test - Replace RHEL 9.4 with 9.5
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-remotes.yml
  test/lib/ansible_test/_data/completion/remote.txt
Labels: feature, has_issue

#84527 ansible-test - Replace FreeBSD 14.1 with 14.2
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-remotes.yml
  test/integration/targets/setup_cron/vars/freebsd-14.yml
  test/lib/ansible_test/_data/completion/remote.txt
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: feature, has_issue

#84529 ansible-test - Fix FreeBSD instance CA certs
  changelogs/fragments/ansible-test-freebsd-nss.yml
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: bug

#84524 📝 Drop drop-down default note from issue forms
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: needs_triage

#84523 📝 Update the outdated WGs+community links in GH issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: needs_triage

#84510 constructed, let users know some limitations
  lib/ansible/plugins/doc_fragments/constructed.py
Labels: needs_triage

#84537 Use ECR Public for container test
  test/integration/targets/ansible-test-container/runme.py
Labels: test

#84545 ansible-test - Update utility containers
  changelogs/fragments/ansible-test-containers.yml
  test/lib/ansible_test/_internal/commands/integration/cloud/httptester.py
  test/lib/ansible_test/_internal/docker_util.py
  test/lib/ansible_test/_internal/pypi_proxy.py
Labels: feature, has_issue

#84547 Bump acme test container to 2.3.0
  changelogs/fragments/84547-acme-test-container.yml
  test/lib/ansible_test/_internal/commands/integration/cloud/acme.py
Labels: stale_review, feature

#84325 validate-modules: enforce FQCNs in seealso plugin/module entries
  changelogs/fragments/84325-validate-modules-seealso-fqcn.yml
  test/lib/ansible_test/_util/controller/sanity/validate-modules/validate_modules/schema.py
Labels: feature

#84536 .github: simplify PR templates
  .github/PULL_REQUEST_TEMPLATE/Bug fix.md
  .github/PULL_REQUEST_TEMPLATE/Documentation change.md
  .github/PULL_REQUEST_TEMPLATE/New feature.md
  .github/PULL_REQUEST_TEMPLATE/Tests.md
  .github/PULL_REQUEST_TEMPLATE/Unclear purpose or motivation.md
Labels: needs_triage, feature

#84473 `with_dict` type error include value in error message
  changelogs/fragments/84473-dict-lookup-type-error-message.yml
  lib/ansible/plugins/lookup/dict.py
Labels: needs_triage, stale_review, feature

#84464 fix[doc.py]: path will be undefined
  changelogs/fragments/fix-cli-doc-path_undefined.yaml
  lib/ansible/cli/doc.py
Labels: stale_ci

#84521 User: Update prompt for SSH key passphrase prompt
  changelogs/fragments/user_passphrase.yml
  lib/ansible/modules/user.py
Labels: module, bug, has_issue

#84491 Allows iptables chain creation with wait parameter
  changelogs/fragments/84490-allow-iptables-chain-creation-with-wait.yml
  lib/ansible/modules/iptables.py
  test/units/modules/test_iptables.py
Labels: module, stale_ci, bug, has_issue

#84485 get_url: add support for BSD-style digest
  changelogs/fragments/get_url_bsd_style_digest.yml
  lib/ansible/modules/get_url.py
  test/integration/targets/get_url/tasks/main.yml
  test/units/modules/test_get_url.py
Labels: module, stale_ci, bug, has_issue

#84486 ansible-vault integration test fix (fixes: #83837)
  test/integration/targets/ansible-vault/runme.sh
Labels: stale_ci, bug

#84494 fix incongruent ansible-vault cli options
  changelogs/fragments/vault_cli_fix.yml
  lib/ansible/cli/vault.py
  test/units/cli/test_vault.py
Labels: needs_triage, bug, has_issue

#84551 ansible-test - Use urllib intead of curl
  changelogs/fragments/ansible-test-curl.yml
  test/lib/ansible_test/_internal/http.py
Labels: feature, has_issue

#84554 Fix unit and integration tests
  test/integration/targets/loops/tasks/main.yml
  test/units/template/test_templar.py
Labels: test

#84482 Fix wrong homedir permissions when UMASK is unset in /etc/login.defs …
  changelogs/fragments/user_module.yml
  lib/ansible/modules/user.py
  test/integration/targets/user/tasks/test_no_home_fallback.yml
Labels: module, bug, has_issue

#84549 remove pointless cache storing os.path.join result
  lib/ansible/plugins/vars/host_group_vars.py
Labels: needs_triage, bug

#84563 fix template
  lib/ansible/module_utils/facts/ansible_collector.py
  lib/ansible/vars/manager.py
  lib/ansible/vars/reserved.py
  test/integration/targets/var_reserved/tasks/task_vars_used.yml
Labels: needs_triage, bug

#84575 reserved vars, avoid gather_subset
  lib/ansible/vars/manager.py
  lib/ansible/vars/reserved.py
Labels: needs_triage, bug

#84439 [2.18] fix reset_connection with templated connection variables (#84240)
  changelogs/fragments/84238-fix-reset_connection-ssh_executable-templated.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/plugins/connection/__init__.py
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/connection/test.sh
  test/integration/targets/connection/test_reset_connection_templated.yml
Labels: backport, needs_triage, bug

#84457 copy, prevent internal options in task (#84422)
  changelogs/fragments/copy_validate_input.yml
  lib/ansible/plugins/action/copy.py
  test/integration/targets/copy/tasks/main.yml
Labels: backport, needs_triage, bug

#84460 Added None/empty notes to regex_search (#84437)
  lib/ansible/plugins/filter/regex_search.yml
Labels: backport, needs_triage

#84542 fix warnings about reserved variable names to cover all sources (#84432)
  changelogs/fragments/reserved_module_chekc.yml
  lib/ansible/executor/task_queue_manager.py
  lib/ansible/module_utils/facts/ansible_collector.py
  lib/ansible/playbook/play.py
  lib/ansible/vars/manager.py
  lib/ansible/vars/reserved.py
  test/integration/targets/var_reserved/runme.sh
  test/integration/targets/var_reserved/tasks/block_vars.yml
  test/integration/targets/var_reserved/tasks/main.yml
  test/integration/targets/var_reserved/tasks/play_vars.yml
  test/integration/targets/var_reserved/tasks/set_fact.yml
  test/integration/targets/var_reserved/tasks/task_vars.yml
  test/integration/targets/var_reserved/tasks/task_vars_used.yml
Labels: backport, needs_triage, bug

#84543 fix warnings about reserved variable names to cover all sources (#84432)
  changelogs/fragments/reserved_module_chekc.yml
  lib/ansible/executor/task_queue_manager.py
  lib/ansible/module_utils/facts/ansible_collector.py
  lib/ansible/playbook/play.py
  lib/ansible/vars/manager.py
  lib/ansible/vars/reserved.py
  test/integration/targets/var_reserved/runme.sh
  test/integration/targets/var_reserved/tasks/block_vars.yml
  test/integration/targets/var_reserved/tasks/main.yml
  test/integration/targets/var_reserved/tasks/play_vars.yml
  test/integration/targets/var_reserved/tasks/set_fact.yml
  test/integration/targets/var_reserved/tasks/task_vars.yml
  test/integration/targets/var_reserved/tasks/task_vars_used.yml
Labels: backport, needs_triage, bug

#84458 Added None/empty notes to regex_search (#84437)
  lib/ansible/plugins/filter/regex_search.yml
Labels: backport, needs_triage

#84440 [2.17] fix reset_connection with templated connection variables (#84240)
  changelogs/fragments/84238-fix-reset_connection-ssh_executable-templated.yml
  lib/ansible/executor/task_executor.py
  lib/ansible/plugins/connection/__init__.py
  lib/ansible/plugins/strategy/__init__.py
  test/integration/targets/connection/test.sh
  test/integration/targets/connection/test_reset_connection_templated.yml
Labels: backport, needs_triage, bug

#84463 [2.17] Make sure we are always using Lock from our multiprocessing context
  changelogs/fragments/macos-correct-lock.yml
  lib/ansible/executor/action_write_locks.py
  lib/ansible/plugins/strategy/__init__.py
Labels: backport, needs_triage, bug

#84400 [stable-2.17] ansible-test - fix coverage for test modules (#84366)
  changelogs/fragments/ansible-test-coverage-test-files.yml
  test/integration/targets/ansible-test-coverage-windows/aliases
  test/integration/targets/ansible-test-coverage-windows/ansible_collections/ns/col/plugins/modules/win_collection.ps1
  test/integration/targets/ansible-test-coverage-windows/ansible_collections/ns/col/tests/integration/targets/win_collection/library/test_win_collection.ps1
  test/integration/targets/ansible-test-coverage-windows/ansible_collections/ns/col/tests/integration/targets/win_collection/tasks/main.yml
  test/integration/targets/ansible-test-coverage-windows/runme.sh
  test/integration/targets/ansible-test-coverage-windows/test-coverage.py
  test/integration/targets/collection/setup.sh
  test/lib/ansible_test/_internal/commands/coverage/__init__.py
Labels: backport, needs_triage, bug

#84569 ssh - Improve CLIXML stderr parsing
  changelogs/fragments/ssh-clixml.yml
  lib/ansible/plugins/connection/ssh.py
  lib/ansible/plugins/shell/powershell.py
  test/units/plugins/shell/test_powershell.py
Labels: needs_triage, bug

#84562 Ansible.Basic - Fix required_if check
  changelogs/fragments/Ansible.Basic-required_if-null.yml
  lib/ansible/module_utils/csharp/Ansible.Basic.cs
  test/integration/targets/module_utils_Ansible.Basic/library/ansible_basic_tests.ps1
Labels: needs_triage, bug

#84399 [stable-2.16] ansible-test - fix coverage for test modules (#84366)
  changelogs/fragments/ansible-test-coverage-test-files.yml
  test/integration/targets/ansible-test-coverage-windows/aliases
  test/integration/targets/ansible-test-coverage-windows/ansible_collections/ns/col/plugins/modules/win_collection.ps1
  test/integration/targets/ansible-test-coverage-windows/ansible_collections/ns/col/tests/integration/targets/win_collection/library/test_win_collection.ps1
  test/integration/targets/ansible-test-coverage-windows/ansible_collections/ns/col/tests/integration/targets/win_collection/tasks/main.yml
  test/integration/targets/ansible-test-coverage-windows/runme.sh
  test/integration/targets/ansible-test-coverage-windows/test-coverage.py
  test/integration/targets/collection/setup.sh
  test/lib/ansible_test/_internal/commands/coverage/__init__.py
Labels: backport, needs_triage, stale_ci, bug

#84580 [stable-2.18] ssh - Improve CLIXML stderr parsing (#84569)
  changelogs/fragments/ssh-clixml.yml
  lib/ansible/plugins/connection/ssh.py
  lib/ansible/plugins/shell/powershell.py
  test/units/plugins/shell/test_powershell.py
Labels: backport, needs_triage, bug

#84582 [stable-2.18] Ansible.Basic - Fix required_if check (#84562)
  changelogs/fragments/Ansible.Basic-required_if-null.yml
  lib/ansible/module_utils/csharp/Ansible.Basic.cs
  test/integration/targets/module_utils_Ansible.Basic/library/ansible_basic_tests.ps1
Labels: backport, needs_triage, bug

#84459 copy, prevent internal options in task (#84422)
  changelogs/fragments/copy_validate_input.yml
  lib/ansible/plugins/action/copy.py
  test/integration/targets/copy/tasks/main.yml
Labels: backport, needs_triage, bug

#84472 gather_facts, fix 'smart' handling with network os and 'setup' (#84425)
  changelogs/fragments/gather_facts_netos_fixes.yml
  lib/ansible/plugins/action/gather_facts.py
  test/integration/targets/gathering_facts/runme.sh
Labels: backport, needs_triage, bug

#84553 fix incongruent ansible-vault cli options (#84494)
  changelogs/fragments/vault_cli_fix.yml
  lib/ansible/cli/vault.py
  test/units/cli/test_vault.py
Labels: backport, needs_triage, bug

#84581 [stable-2.17] Ansible.Basic - Fix required_if check (#84562)
  changelogs/fragments/Ansible.Basic-required_if-null.yml
  lib/ansible/module_utils/csharp/Ansible.Basic.cs
  test/integration/targets/module_utils_Ansible.Basic/library/ansible_basic_tests.ps1
Labels: needs_revision, backport, needs_triage, bug

#84583 New release v2.18.2rc1
  changelogs/CHANGELOG-v2.18.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.18.2rc1_summary.yaml
  lib/ansible/release.py
  pyproject.toml
Labels: backport, needs_triage, feature

#84584 New release v2.17.8rc1
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.8rc1_summary.yaml
  lib/ansible/release.py
  pyproject.toml
Labels: backport, needs_triage, feature

#84586 Update Ansible release version to v2.18.2rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#84585 Update Ansible release version to v2.17.8rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#84567 targets/handlers: fix incorrect test cmd
  test/integration/targets/handlers/runme.sh
Labels: test

#84568 cache: remove deprecated method
  changelogs/fragments/deprecate_api.yml
  lib/ansible/vars/fact_cache.py
Labels: bug

#84587 Update win_dirname and win_basename docs
  lib/ansible/plugins/filter/win_basename.yml
  lib/ansible/plugins/filter/win_dirname.yml
Labels: needs_triage

#84555 Apt key bye
  changelogs/fragments/apt_key_bye.yml
  lib/ansible/modules/apt_key.py
  lib/ansible/modules/apt_repository.py
  test/integration/targets/apt_key/tasks/main.yml
Labels: module, has_issue

#84544 generator: add support for extra vars usage
  changelogs/fragments/generator_use_extra.yml
  lib/ansible/plugins/inventory/generator.py
  test/integration/targets/inventory_generator/aliases
  test/integration/targets/inventory_generator/extra_vars_generator.yml
  test/integration/targets/inventory_generator/generator.yml
  test/integration/targets/inventory_generator/generator_parent.yml
  test/integration/targets/inventory_generator/runme.sh
Labels: bug, has_issue

#84015 uri: Handle HTTP exception raised
  changelogs/fragments/uri_httpexception.yml
  lib/ansible/modules/uri.py
  test/integration/targets/uri/files/testserver.py
  test/integration/targets/uri/tasks/main.yml
Labels: module, stale_ci, bug, has_issue

#84588 apt_key: fix module names in docs
  lib/ansible/modules/apt_key.py
Labels: module, needs_triage

#84597 debug: hide loop variables while using var
  changelogs/fragments/hide-loop-vars-debug-vars.yml
  lib/ansible/plugins/callback/__init__.py
  test/integration/targets/callback_default/callback_default.out.result_format_yaml_lossy_verbose.stdout
  test/integration/targets/callback_default/callback_default.out.result_format_yaml_verbose.stdout
Labels: bug, has_issue

#84615 New release v2.18.2
  changelogs/CHANGELOG-v2.18.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.18.2_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#84614 New release v2.17.8
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.8_summary.yaml
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#84617 Update Ansible release version to v2.18.2.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#84616 Update Ansible release version to v2.17.8.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#84619 Revert "generator: add support for extra vars usage (#84544)"
  changelogs/fragments/generator_use_extra.yml
  lib/ansible/plugins/inventory/generator.py
  test/integration/targets/inventory_generator/aliases
  test/integration/targets/inventory_generator/extra_vars_generator.yml
  test/integration/targets/inventory_generator/generator.yml
  test/integration/targets/inventory_generator/generator_parent.yml
  test/integration/targets/inventory_generator/runme.sh
Labels: feature

#84592 connection: raise exception return by SSH
  changelogs/fragments/ssh_raise_exception.yml
  lib/ansible/plugins/connection/ssh.py
Labels: bug, has_issue

#84622 service_facts: skip unwanted lines in openrc output
  changelogs/fragments/openrc-status.yml
  lib/ansible/modules/service_facts.py
Labels: module, bug, has_issue

#84624 [fix] `warn_if_reserved` expects a list
  lib/ansible/vars/manager.py
Labels: needs_revision, needs_triage, bug, has_issue

#84645 [stable-2.17] release.py - Use changelog requirements (#83920)
  packaging/release.py
Labels: backport, feature

#84646 [stable-2.16] release.py - Use changelog requirements (#83920)
  packaging/release.py
Labels: backport, feature

#84647 [stable-2.14] release.py - Use changelog requirements (#83920)
  packaging/release.py
Labels: backport, feature

#84649 [stable-2.16] Use separate venvs for each release command (#84641)
  packaging/release.py
Labels: backport, needs_triage, bug

#84650 [stable-2.14] Use separate venvs for each release command (#84641)
  packaging/release.py
Labels: backport, needs_triage, bug

#84629 [stable-2.18] ansible-test - Use urllib intead of curl (#84551)
  changelogs/fragments/ansible-test-curl.yml
  test/lib/ansible_test/_internal/http.py
Labels: backport, feature

#84630 [stable-2.17] ansible-test - Use urllib intead of curl (#84551)
  changelogs/fragments/ansible-test-curl.yml
  test/lib/ansible_test/_internal/http.py
Labels: backport, feature

#84631 [stable-2.16] ansible-test - Use urllib intead of curl (#84551)
  changelogs/fragments/ansible-test-curl.yml
  test/lib/ansible_test/_internal/http.py
Labels: backport, feature

#84632 [stable-2.14] ansible-test - Use urllib intead of curl (#84551)
  changelogs/fragments/ansible-test-curl.yml
  test/lib/ansible_test/_internal/http.py
  test/sanity/ignore.txt
Labels: backport, feature
