Repository ansible/ansible, pull requests merged in 2025-05, with the labels that each got.

#85096 fix typo get_url.py: missing closing parenthesis
  lib/ansible/modules/get_url.py
Labels: module, needs_triage

#85092 [stable-2.16] Fix old_style_cache_plugins test failure using latest redis
  test/integration/targets/old_style_cache_plugins/setup_redis_cache.yml
Labels: backport, test, needs_triage

#85091 [stable-2.17] Fix old_style_cache_plugins test failure using latest redis
  test/integration/targets/old_style_cache_plugins/setup_redis_cache.yml
Labels: backport, test, needs_triage

#85101 New release v2.19.0b3
  changelogs/CHANGELOG-v2.19.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.19.0b3_summary.yaml
  lib/ansible/release.py
Labels: backport, feature

#85102 Update Ansible release version to v2.19.0b3.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#85111 dnf5: skip pkgs that don't satisfy bugfix/security when specified
  changelogs/fragments/dnf5-advisory-type.yml
  lib/ansible/modules/dnf5.py
Labels: module, bug

#85103 add fuzzy matching to package_data sanity
  pyproject.toml
  test/sanity/code-smell/package-data.py
Labels: bug

#85113 [stable-2.18] dnf5: skip pkgs that don't satisfy bugfix/security when specified
  changelogs/fragments/dnf5-advisory-type.yml
  lib/ansible/modules/dnf5.py
Labels: backport, module, needs_triage, bug

#85107 Fix typos
  changelogs/fragments/84490-allow-iptables-chain-creation-with-wait.yml
  lib/ansible/_internal/__init__.py
  lib/ansible/_internal/_json/__init__.py
  lib/ansible/plugins/action/__init__.py
  test/integration/targets/cache-plugins/test_inventory_cache.yml
Labels: bug

#85108 Use 4 spaces instead of 2 as indent in examples
  lib/ansible/modules/sysvinit.py
Labels: needs_revision, module

#85119 Misc config type coercion fixes
  changelogs/fragments/ensure_type.yml
  lib/ansible/config/base.yml
  lib/ansible/config/manager.py
  lib/ansible/constants.py
  lib/ansible/module_utils/parsing/convert_bool.py
  lib/ansible/plugins/loader.py
  lib/ansible/utils/display.py
  test/units/config/test_manager.py
Labels: bug, has_issue

#85121 template module - render `None` as empty string
  changelogs/fragments/template-none.yml
  lib/ansible/plugins/action/template.py
  test/integration/targets/lookup_template/tasks/main.yml
  test/integration/targets/lookup_template/templates/none.j2
  test/integration/targets/template/tasks/main.yml
  test/integration/targets/template/templates/none.j2
Labels: bug, has_issue

#85122 ansible-test - Relax some deprecation checks
  changelogs/fragments/ansible-test-pylint-deprecated-fix.yml
  test/integration/targets/ansible-test-sanity-pylint/ansible_collections/ns/col/plugins/lookup/deprecated.py
  test/lib/ansible_test/_util/controller/sanity/pylint/plugins/deprecated_calls.py
Labels: bug, has_issue

#85126 Apply trust to declarative plugin config
  changelogs/fragments/plugin-loader-trust-docs.yml
  lib/ansible/_internal/_testing.py
  lib/ansible/inventory/manager.py
  lib/ansible/plugins/loader.py
  lib/ansible/utils/plugin_docs.py
  test/integration/targets/inventory/doc_fragments/fragment_with_expression.py
  test/integration/targets/inventory/inventory_plugins/constructed_with_hostvars.py
Labels: bug, has_issue

#85127 Ensure that all config return values are Origin-tagged
  changelogs/fragments/preserve_config_origin.yml
  lib/ansible/cli/arguments/option_helpers.py
  lib/ansible/config/manager.py
Labels: needs_triage, bug

#85129 fix ensure_type to support vaulted values
  lib/ansible/config/manager.py
  lib/ansible/utils/collection_loader/__init__.py
  test/units/config/test_manager.py
  test/units/controller_only_conftest.py
  test/units/mock/vault_helper.py
  test/units/parsing/vault/test_vault.py
  test/units/parsing/yaml/test_vault.py
Labels: needs_revision, ci_verified, stale_review, bug

#85072 ensure predictable permissions on module artifacts (#84948)
  changelogs/fragments/ensure_remote_perms.yml
  lib/ansible/plugins/action/__init__.py
  test/integration/targets/ansiballz_debug/aliases
  test/integration/targets/ansiballz_debug/tasks/main.yml
  test/units/plugins/action/test_action.py
Labels: backport, needs_triage, bug

#85044 These actions do not support until (#84847)
  lib/ansible/plugins/doc_fragments/action_core.py
Labels: backport, needs_triage

#85078 [stable-2.17] - script fix become on Windows (#85077)
  changelogs/fragments/win-script-become.yml
  lib/ansible/plugins/action/script.py
  test/integration/targets/win_script/tasks/main.yml
Labels: backport, needs_triage, bug

#85073 ensure predictable permissions on module artifacts (#84948)
  changelogs/fragments/ensure_remote_perms.yml
  lib/ansible/plugins/action/__init__.py
  test/integration/targets/ansiballz_debug/aliases
  test/integration/targets/ansiballz_debug/tasks/main.yml
  test/units/plugins/action/test_action.py
Labels: backport, needs_triage, bug

#84994 [2.17] ansible-doc: fix indent and line wrapping for first line of (sub-)option and (sub-)return value descriptions
  changelogs/fragments/84690-ansible-doc-indent-wrapping.yml
  lib/ansible/cli/doc.py
  test/integration/targets/ansible-doc/randommodule-text-verbose.output
  test/integration/targets/ansible-doc/randommodule-text.output
  test/integration/targets/ansible-doc/test_docs_returns.output
  test/integration/targets/ansible-doc/test_docs_suboptions.output
  test/integration/targets/ansible-doc/test_docs_yaml_anchors.output
Labels: backport, needs_triage, bug

#85133 New release v2.19.0b4
  changelogs/CHANGELOG-v2.19.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.19.0b4_summary.yaml
  lib/ansible/release.py
  pyproject.toml
Labels: backport, feature

#85060 release.py - Remove email announcement support
  packaging/release.py
Labels: stale_ci, feature

#85135 [stable-2.17] add fuzzy matching to package_data sanity (#85103)
  pyproject.toml
  test/sanity/code-smell/package-data.py
Labels: backport, needs_triage, bug

#85136 [stable-2.18] add fuzzy matching to package_data sanity (#85103)
  pyproject.toml
  test/sanity/code-smell/package-data.py
Labels: backport, needs_triage, bug

#85138 [stable-2.16] add fuzzy matching to package_data sanity (#85103)
  pyproject.toml
  test/sanity/code-smell/package-data.py
Labels: backport, needs_triage, bug

#85139 [stable-2.18] release.py - Remove email announcement support (#85060)
  packaging/release.py
Labels: backport, feature

#85141 [stable-2.16] release.py - Remove email announcement support (#85060)
  packaging/release.py
Labels: backport, feature

#85142 [stable-2.14] release.py - Remove email announcement support (#85060)
  packaging/release.py
Labels: backport, feature

#85137 Update Ansible release version to v2.19.0b4.post0.
  lib/ansible/release.py
Labels: backport, feature

#85143 New release v2.17.12rc1
  changelogs/CHANGELOG-v2.17.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.17.12rc1_summary.yaml
  lib/ansible/release.py
  pyproject.toml
Labels: backport, feature

#85144 New release v2.18.6rc1
  changelogs/CHANGELOG-v2.18.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.18.6rc1_summary.yaml
  lib/ansible/release.py
  pyproject.toml
Labels: backport, needs_triage, feature

#85146 Update Ansible release version to v2.18.6rc1.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#85145 Update Ansible release version to v2.17.12rc1.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, feature

#85148 misc changelog and docstring cleanup
  changelogs/fragments/templates_types_datatagging.yml
  lib/ansible/_internal/_templating/_jinja_bits.py
  lib/ansible/module_utils/_internal/_datatag/__init__.py
  lib/ansible/module_utils/_internal/_json/_profiles/__init__.py
  lib/ansible/utils/listify.py
  test/units/utils/test_listify.py
Labels: stale_review, feature

#85149 ensure builtin tests always return bool
  changelogs/fragments/truthy_tests.yml
  lib/ansible/plugins/test/core.py
  lib/ansible/plugins/test/uri.py
  test/units/plugins/test/dummy_vault.txt
  test/units/plugins/test/test_all.py
Labels: bug

#85154 Add missing cache plugin test scenarios
  test/integration/targets/cache-plugins/inspect_cache.yml
  test/integration/targets/cache-plugins/inspect_inventory_cache.yml
  test/integration/targets/cache-plugins/inventory_plugins/test_inventoryconfig.py
  test/integration/targets/cache-plugins/runme.sh
  test/integration/targets/cache-plugins/test_inventory_cache.yml
Labels: test

#85160 ansible-test - Update sanity requirements
  test/lib/ansible_test/_data/requirements/sanity.ansible-doc.txt
  test/lib/ansible_test/_data/requirements/sanity.changelog.txt
  test/lib/ansible_test/_data/requirements/sanity.pep8.txt
  test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  test/lib/ansible_test/_data/requirements/sanity.yamllint.txt
  test/sanity/code-smell/black.requirements.txt
  test/sanity/code-smell/mypy.requirements.txt
  test/sanity/code-smell/package-data.requirements.txt
  test/sanity/code-smell/pymarkdown.requirements.txt
  test/sanity/code-smell/update-bundled.requirements.txt
Labels: feature

#85161 ansible-test - Update default containers
  test/lib/ansible_test/_data/completion/docker.txt
Labels: feature

#85002 Fix constructable inventory default keyed group
  changelogs/fragments/constructed-default-value.yml
  lib/ansible/plugins/doc_fragments/constructed.py
  lib/ansible/plugins/inventory/__init__.py
  test/integration/targets/inventory_constructed/keyed_group_default_value.yml
  test/integration/targets/inventory_constructed/keyed_group_list_default_value.yml
  test/integration/targets/inventory_constructed/keyed_group_str_default_value.yml
  test/integration/targets/inventory_constructed/runme.sh
  test/integration/targets/inventory_constructed/tag_inventory.yml
Labels: bug

#85165 Code formatting for test/sanity/code-smell/
  test/sanity/code-smell/deprecated-config.py
  test/sanity/code-smell/mypy.py
  test/sanity/code-smell/no-unwanted-characters.py
  test/sanity/code-smell/no-unwanted-files.py
  test/sanity/code-smell/package-data.py
  test/sanity/code-smell/pymarkdown.py
  test/sanity/code-smell/test-constraints.py
  test/sanity/code-smell/update-bundled.py
Labels: test

#85168 Code formatting for packaging/release.py
  packaging/release.py
Labels: feature

#85167 Code formatting for packaging/cli-doc/
  packaging/cli-doc/build.py
Labels: feature

#84487 Mark integration tests as needs/root
  test/integration/targets/apt/aliases
  test/integration/targets/become/aliases
  test/integration/targets/become_su/aliases
  test/integration/targets/become_sudo/aliases
  test/integration/targets/deb822_repository/aliases
  test/integration/targets/hardware_facts/aliases
  test/integration/targets/package_facts/aliases
  test/integration/targets/slurp/aliases
Labels: test, P3

#85166 Code formatting for .azure-pipelines/
  .azure-pipelines/scripts/publish-codecov.py
Labels: feature

#85169 Expand scope of `black` sanity test
  test/sanity/code-smell/black.json
Labels: test, needs_triage

#85130 Integration tests clean up
  test/integration/targets/ansible-galaxy-collection-scm/tasks/main.yml
  test/integration/targets/ansible-inventory/tasks/toml.yml
  test/integration/targets/ansible-test-container/runme.py
  test/integration/targets/ansible-test-git/collection-tests/uninstall-git.yml
  test/integration/targets/ansible-vault/single_vault_as_string.yml
  test/integration/targets/apt/vars/Ubuntu-20.yml
  test/integration/targets/become_unprivileged/cleanup_unpriv_users.yml
  test/integration/targets/become_unprivileged/setup_unpriv_users.yml
  test/integration/targets/cron/tasks/main.yml
  test/integration/targets/dnf/tasks/gpg.yml
  test/integration/targets/dnf/tasks/logging.yml
  test/integration/targets/dnf/tasks/main.yml
  test/integration/targets/git/tasks/archive.yml
  test/integration/targets/git/tasks/main.yml
  test/integration/targets/git/vars/main.yml
  test/integration/targets/group/tasks/tests.yml
  test/integration/targets/hostname/tasks/test_normal.yml
  test/integration/targets/loop-until/tasks/main.yml
  test/integration/targets/package/tasks/main.yml
  test/integration/targets/package_facts/tasks/main.yml
  test/integration/targets/pip/tasks/main.yml
  test/integration/targets/pip/tasks/pip.yml
  test/integration/targets/prepare_http_tests/tasks/default.yml
  test/integration/targets/reboot/tasks/test_invalid_test_command.yml
  test/integration/targets/reboot/vars/main.yml
  test/integration/targets/replace/tasks/main.yml
  test/integration/targets/service/files/ansible.sysv
  test/integration/targets/setup_paramiko/install-RedHat-8-python-3.yml
  test/integration/targets/setup_paramiko/uninstall-RedHat-8-python-3.yml
  test/integration/targets/setup_paramiko/uninstall-zypper-python-3.yml
  test/integration/targets/subversion/roles/subversion/templates/subversion.conf.j2
  test/integration/targets/unarchive/tasks/test_include.yml
  test/integration/targets/user/tasks/main.yml
  test/integration/targets/user/tasks/test_create_user_password.yml
  test/integration/targets/user/tasks/test_expires.yml
  test/integration/targets/user/tasks/test_expires_min_max.yml
  test/integration/targets/user/tasks/test_expires_new_account.yml
  test/integration/targets/user/tasks/test_expires_new_account_epoch_negative.yml
  test/integration/targets/user/tasks/test_expires_no_shadow.yml
  test/integration/targets/user/tasks/test_expires_warn.yml
  test/integration/targets/user/tasks/test_inactive_new_account.yml
  test/integration/targets/user/tasks/test_local.yml
  test/integration/targets/user/tasks/test_local_expires.yml
  test/integration/targets/user/tasks/test_shadow_backup.yml
  test/integration/targets/user/vars/main.yml
  test/integration/targets/yum_repository/tasks/main.yml
Labels: test, stale_review

#85177 New release v2.18.6
  changelogs/CHANGELOG-v2.18.rst
  changelogs/changelog.yaml
  changelogs/fragments/2.18.6_summary.yaml
  lib/ansible/release.py
  pyproject.toml
Labels: backport, needs_triage, feature

#85179 Update Ansible release version to v2.18.6.post0.
  lib/ansible/release.py
Labels: backport, needs_triage, feature

#85180 Update Ansible release version to v2.17.12.post0.
  lib/ansible/release.py
Labels: needs_revision, backport, needs_triage, feature

#85183 Remove unnecessary module shebang
  changelogs/fragments/unnecessary-shebang.yml
  lib/ansible/modules/hostname.py
Labels: module, needs_triage, bug

#85182 ansible-test - Fix option filtering
  changelogs/fragments/ansible-test-delegation-options.yml
  test/lib/ansible_test/_internal/util.py
  test/units/ansible_test/_internal/test_util.py
Labels: bug, has_issue

#85159 ansible-test - Improve deprecated checking type inference
  changelogs/fragments/ansible-test-pylint-fix-inference.yml
  test/integration/targets/ansible-test-sanity-pylint/ansible_collections/ns/col/plugins/lookup/deprecated.py
  test/integration/targets/ansible-test-sanity-pylint/expected.txt
  test/lib/ansible_test/_util/controller/sanity/pylint/config/ansible-test-target.cfg
  test/lib/ansible_test/_util/controller/sanity/pylint/config/ansible-test.cfg
  test/lib/ansible_test/_util/controller/sanity/pylint/config/code-smell.cfg
  test/lib/ansible_test/_util/controller/sanity/pylint/config/collection.cfg
  test/lib/ansible_test/_util/controller/sanity/pylint/config/default.cfg
  test/lib/ansible_test/_util/controller/sanity/pylint/plugins/deprecated_calls.py
Labels: feature, has_issue

#85186 csvfile lookup: remove Python 2 compat
  changelogs/fragments/lookup-csvfile-remove-py2-compat.yml
  lib/ansible/plugins/lookup/csvfile.py
  test/integration/targets/lookup_csvfile/tasks/main.yml
Labels: needs_triage, bug

#85189 ansible-test - Add RHEL 10.0 remote
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/ansible-test-rhel-10.yml
  test/integration/targets/copy/tasks/acls.yml
  test/integration/targets/iptables/tasks/main.yml
  test/integration/targets/lineinfile/tasks/acls.yml
  test/integration/targets/prepare_http_tests/tasks/default.yml
  test/integration/targets/rpm_key/aliases
  test/integration/targets/rpm_key/defaults/main.yaml
  test/integration/targets/rpm_key/tasks/main.yaml
  test/integration/targets/rpm_key/tasks/rpm_key.yaml
  test/integration/targets/rpm_key/vars/main.yml
  test/integration/targets/setup_paramiko/install-RedHat-10-python-3.yml
  test/integration/targets/setup_paramiko/uninstall-RedHat-10-python-3.yml
  test/lib/ansible_test/_data/completion/remote.txt
  test/lib/ansible_test/_util/target/setup/bootstrap.sh
Labels: stale_review, feature

#85194 display - Replace CRNL with NL
  changelogs/fragments/display-windows-newline.yml
  lib/ansible/utils/display.py
  test/integration/targets/display-newline/aliases
  test/integration/targets/display-newline/library/noisy.py
  test/integration/targets/display-newline/tasks/main.yml
Labels: feature

#85196 Include message in captured tracebacks
  lib/ansible/module_utils/_internal/_traceback.py
  lib/ansible/module_utils/basic.py
  lib/ansible/module_utils/common/warnings.py
  lib/ansible/module_utils/datatag.py
  lib/ansible/plugins/action/__init__.py
  lib/ansible/utils/display.py
Labels: feature

#85197 win coverage - Fix untrusted coverage collection
  lib/ansible/executor/powershell/coverage_wrapper.ps1
  lib/ansible/executor/powershell/module_wrapper.ps1
Labels: needs_triage, bug

#85175 dnf5 - handle all specific libdnf5 exceptions
  changelogs/fragments/84634-dnf5-all-exceptions.yml
  lib/ansible/modules/dnf5.py
  test/integration/targets/dnf/tasks/repo.yml
Labels: module, stale_ci, bug, has_issue, code_health

#85222 Added _TEMPLAR_SANDBOX_MODE config
  changelogs/fragments/sandbox_config.yml
  lib/ansible/_internal/_templating/_jinja_bits.py
  lib/ansible/_internal/_templating/_jinja_common.py
  lib/ansible/config/base.yml
  test/units/_internal/templating/test_templar.py
Labels: needs_revision, feature, has_issue

#85074 make async true again
  changelogs/fragments/async_really_true.yml
  lib/ansible/executor/powershell/async_watchdog.ps1
  lib/ansible/executor/powershell/async_wrapper.ps1
  lib/ansible/executor/task_executor.py
  lib/ansible/modules/async_status.py
  lib/ansible/modules/async_wrapper.py
  lib/ansible/plugins/action/__init__.py
  lib/ansible/plugins/action/async_status.py
  lib/ansible/plugins/action/gather_facts.py
  lib/ansible/plugins/test/core.py
  lib/ansible/plugins/test/finished.yml
  test/integration/targets/async/tasks/main.yml
  test/support/windows-integration/plugins/modules/async_status.ps1
  test/units/plugins/action/test_action.py
Labels: needs_revision, module, bug

#85235 [stable-2.17] User: Update prompt for SSH key passphrase prompt (#84521)
  changelogs/fragments/user_passphrase.yml
  lib/ansible/modules/user.py
Labels: backport, module, bug

#85236 [stable-2.16] User: Update prompt for SSH key passphrase prompt (#84521)
  changelogs/fragments/user_passphrase.yml
  lib/ansible/modules/user.py
Labels: backport, module, bug

#85238 Misc ssh agent fixes
  changelogs/fragments/ssh_agent_misc.yml
  lib/ansible/_internal/_ssh/__init__.py
  lib/ansible/_internal/_ssh/_agent_launch.py
  lib/ansible/_internal/_ssh/_ssh_agent.py
  lib/ansible/cli/__init__.py
  lib/ansible/config/base.yml
  lib/ansible/plugins/connection/ssh.py
  test/integration/targets/ssh_agent/action_plugins/ssh_agent.py
  test/integration/targets/ssh_agent/action_plugins/ssh_keygen.py
  test/integration/targets/ssh_agent/fake_agents/ssh-agent-bad-shebang
  test/integration/targets/ssh_agent/fake_agents/ssh-agent-hangs
  test/integration/targets/ssh_agent/fake_agents/ssh-agent-incompatible
  test/integration/targets/ssh_agent/fake_agents/ssh-agent-truncated-early-exit
  test/integration/targets/ssh_agent/tasks/main.yml
  test/integration/targets/ssh_agent/tasks/tests.yml
  test/sanity/ignore.txt
Labels: feature

#85239 local connection always passes str to Popen
  changelogs/fragments/local_popen_text.yml
  lib/ansible/plugins/connection/local.py
Labels: needs_triage, bug
